== Selection from the Journal of John Gratton

It has often been in my heart to write a short account
to leave behind me of the Lord`'s gracious dealings with me,
and of the great mercies, which in His infinite love, He has freely bestowed upon me,
far beyond my deserts or expectation, to my great joy and consolation.
Praises, thanks, glory, honor and renown, be given and ascribed unto Him;
for He alone is worthy, God over all, blessed forever, amen.
To the end that my children and others, who may see these lines,
may be encouraged to trust in the living God, and to cast their care upon Him,
and obey Him truly; for He never fails them that put their trust in Him,
and abide in His blessed counsel.

When it first pleased the Lord to visit me,
and to cause His light to shine in me, which is now my life, I was but a child,
and was keeping my father`'s sheep, and was addicted to sin and vanity,
for which I was reproved and smitten inwardly.
It was made manifest to me that I was not in a state of salvation,
nor had I any true peace in my mind;
but whenever I came seriously to consider my condition, I found an accuser near me.
I also found that He who reproved me for sin, and showed me the deceit of my heart,
also counseled me to embrace truth and righteousness,
and was always with me to instruct me and guide me in the way of holiness,
and advised me to sin no more in word or deed, but always to speak truth.
When I took His counsel and followed His advice, then was I easy,
and my burden seemed to lighten,
and it would give me encouragement to hold on and take heed to
that good Spirit in me which thus instructed me to godliness,
and to shun that which was evil.
I found, as it were, two spirits working in me, both striving to gain me,
the one from the other.
And I found that the good Spirit (for so it was) always counseled me to do good things,
and when I was obedient to it, then I found the evil spirit could not break my peace.
And had I stood here, and always lived in the counsel of this good Spirit of instruction,
and never rebelled against it, then my peace would have been as a river.

I was about ten or eleven years old when
the Lord visited me with the light of His Son,
and gave me to see the vain life and way I lived in,
being much given to play amongst rude boys, and took great delight in playing at cards,
and shooting at targets, and ringing of bells, for which I was reproved.
I came to see that vain sports and pleasures were displeasing to the Lord,
to which I was much inclined before I came truly
to know the Word of God in my heart and mouth,
to hear it and do it.
Indeed I was judged in myself for these things, but I knew not the Judge,
being but a child.
I did not yet know the Lord,
nor think it had been He who met me in my heart and conscience,
and told me all that ever I did, and made all things manifest that were reproved,
though I had read in the Scriptures that Christ was come to redeem
from a vain manner of life to serve the living God.
And Christ taught to pray, "`Your kingdom come; Your will be done in earth,
as it is in heaven,`" and said, "`I came not to do My own will,
but the will of Him that sent Me,`" and,
"`not My will but Your will be done,`" when He was to drink that bitter cup of the cross.
And He said, "`He that will be my disciple must deny himself,
and take up His cross daily and follow Me,`" and so the cup He was to drink,
and the baptism He was to be baptized with,
they also should drink and be baptized with the same.
Oh, it is beyond words, or the depth of man`'s wisdom to reach, and yet we must drink it,
and be baptized with His baptism!

It was He that appeared in me when I was young, though I knew Him not,
but instead followed hireling priests, Presbyterians, etc.,
yet I was uneasy among them all.
When I saw that I lived not as I ought, a fear came over me,
and I sat down upon the ground and was very serious,
and I thought to live more carefully and holy for the time to come.
And when this mind was begotten in me, I felt and saw the grace of God appear in me,
but I knew not what it was, yet I would gladly have held it,
and have kept the enjoyment of it, but did not.
For being young, my mind went out again after vain and childish sports, and sinful,
foolish pastimes, when I met with my companions, sporting myself in earthly things,
and so I fell from the counsel of the heavenly, and lost the sense, sight,
and feeling of it.
So it was that trouble and sorrow of mind came over me.

Thus I lived for five or six years, and as I grew in years,
so trouble and sorrow increased in me.
Yet I did often find the heavenly Monitor meet with me,
and sometimes did sharply reprove me, and sometimes gently instruct me.
And at last He did clearly open my heart to me, and broke my peace,
and caused His terrors to seize upon me, and I was wounded at my heart.
Great was my sorrow, and my tears were many, and I knew not what to do.

Yet in this state of sorrow I sometimes had a secret hope,
and this kept me from sinking under the great weight that lay upon me.
This gave me courage to pray to God, though I knew not how to pray.
Yet I thought that in secret, where none could hear or see me, I could pray best,
and could confess those sins that I was not willing men should know of,
and pray for forgiveness and for power over them.
But still I did not find power to forsake the sins I was so prone
to because I received not the One to whom all power is given,
nor yet knew Him.

I little thought it had been He who told me all that ever I had done,
and who searched out all my secret sins.
There was nothing hidden from Him,
but He discerned the very thoughts and intents of my heart,
and I was even laid naked before Him, and could hide nothing from Him.
Yet His appearance^
footnote:[He speaks here of Christ`'s initial inward
appearance as a convicter and reprover of sin.]
seemed such a poor, low, despised thing, that I did not believe in it,
nor did I think it possible to find Christ in me, but rather looked for Him in heaven,
above the skies.
And though He appeared to me wonderfully by His Spirit, yet I did not know Him,
but still rejected His counsel, and came not to Him to be taught by Him,
though He had long waited to be gracious to me.
Glory to His name, for indeed He made many things manifest to me.

Great was the travail of my poor soul,
and all outward things sometimes seemed of little worth to me.
I cried unto the Lord that He would tell me what He would have me to do,
and that He would show me who were His people that worshiped Him aright,
according to His will.
I read much and conferred with many about religion,
and ran to and fro to hear those that were accounted great preachers,
but I neglected the great teacher in my own heart.
I esteemed the priests that were then in place, in Oliver Cromwell`'s time,^
footnote:[Oliver Cromwell was the Lord Protector of the Commonwealth of England,
Scotland, and Ireland from 1653 to 1658.]
and went constantly to hear them, but often came home full of sorrow,
for I was not satisfied with their doctrine of election and reprobation,^
footnote:[The Protestant church at this time was almost unanimous in its assertion
that God had foreordained a specific and small number of individuals to be saved,
and had consequently predestined the rest of humanity
(the vast majority) to eternal condemnation.]
which put me into deep trouble.
Indeed I was sometimes very near concluding that I was a reprobate,
my state appearing to be a state of sin.

Yet I believed that men who were in Christ were elected,
but men who were out of Christ were out of the way to God.
For Christ is the elect and chosen of God, the heir of all things,
and all that are in Him are co-heirs with Him.
And if Christ be theirs, then all is theirs,
and Christ is all in all to them in whom He lives and reigns.
But if Christ be not in them, then they are reprobates, without God in the world,
dead in sins and trespasses, and so all they do are dead works, dead prayers,
dead preaching, dead worship and performances.
Indeed, many are seeking the living among the dead, among dead ordinances, dead faiths,
dead observations, and dead professions.

My sorrows increased, yet I strove hard to get ease.
I read much, and prayed much in secret, and went to hear sermons very eagerly.
I was now become one of the Presbyterian church, and had been much among them,
and told some of them part of my condition.
But, alas! alas!
They could not help me, no, nor themselves neither!
For they would tell me it was a good condition,
and that I must be troubled with my sins as long as I lived,
and that even the best of God`'s children all along had their failings.
All this was to persuade me to sit down contented
before I was cleansed and washed from my sins.
Oh, these were the physicians of no value!
These were they that plastered with untempered mortar, and cried, "`peace,
peace`" when there is no peace at all experienced!
So my sorrows increased upon me, and when the people sang psalms in the steeple-house^
footnote:[Because they understood the true church to be the spiritual,
corporate body of Christ,
the early Quakers were unwilling to refer to church buildings as
the "`church,`" and instead used the term "`steeple-house.`"]
when I was present, I dared not sing the same sayings of David, as they did.
It would have been a lie in my mouth.
For I clearly saw I was not in the condition David was in,
nor could I sing it truly as my own song; and if I had sung,
it would have been a false thing, as to myself.

My sorrows still increased night and day, and my tears and fears were also many.
Sometimes I secretly prayed unto the Lord, and confessed all my sins,
and begged of the Lord forgiveness, and used many words (some of which, it may be,
I had learned from the priests, and others were real according to my state).
Yet, when I was done, I was condemned and full of sorrow,
and my spirit would sometimes be more heavy laden after I was done than before I began,
being condemned in myself that I had not prayed in faith, doubting nothing,
nor had I prayed in the Spirit of prayer and supplication.

I could find no rest to my poor soul.
I mourned deeply because I was unholy and unrighteous,
though my neighbors thought better of me, for I saw my sins and trespasses were many,
and I believed the Scripture that says,
"`No unclean thing can enter the kingdom of heaven,`" and, "`without holiness,
no man shall ever see the Lord.`"

I mourned deeply,
and was ready to conclude that my heart was not right in the sight of God.
I prayed much in private, in the stable and barns, and in bed, and in the open fields.
One day, being alone on the top of a hill in the snow,
I cried aloud with strong cries to the Lord, and desired Him to show me my own heart.
The Lord was pleased to hear and answer my prayer at that time,
so that He gave me to see my own heart in such a way that
I knew it was the Lord that did show it to me,
to my satisfaction.
For I plainly saw it to be deceitful, and not a good, humble, and pure heart.
I was pleased that I saw it, and knew what it was.
But I was sorry it was so very bad.
This was the first time, to my remembrance,
that I was sure the Lord gave me an answer to my prayers.

I had deep sorrow, yes, very deep sorrow, and watered my pillow with tears.
Sometimes I was ready to say, "`Oh, that I had never been born!`"
But it pleased the Lord to put it into my mind to be content,
and to await the Lord`'s time for Him to give me further knowledge of His will.
For a while I lived in great sorrow and fear and trouble.
Oh, it was undeclarable!
So that in the morning, I was glad that the day was come, and at night,
that night was come.
Truly I was apt to think that no man`'s condition was ever like mine.

About this time, King Charles II came to the crown,
and after a while uniformity was concluded on and enacted^
footnote:[He means uniformity of religion,
mandated and enforced by the state.]--that none must have liberty
to preach in churches (so called) except such as would conform,
and read the common prayer book,
and observe those ceremonies that were set up by the Episcopalians, or else be silent.
Then the Presbyterian priests, whom I had so much esteemed and admired,
made their farewell sermons and left us;
for they desired not to conform to the common prayer book themselves,
and so would not venture to stay with their flocks, which caused me to weep bitterly.

Whereupon it came into my mind to search the Scriptures
to see whether those the Lord sent forth to preach the gospel in
the demonstration of the Spirit could be silent at a man`'s command,
even though they were men in authority who forbade them; and whether these,
who now pretend to be His ministers, could, according to Scripture,
be clear to leave their flocks and congregations for of the will of man, yes or no.
For I believed that if God had sent them and set them up,
then man ought not to pull them down.
I likewise found it plain, by the Holy Scriptures,
that they ought not to be silent at man`'s command,
if the Lord had indeed sent and commanded them to preach.
They ought rather to obey God instead of man,
when the Lord commands one thing and man another--as
with the three children and Daniel also,
who patiently bore the wrath of the king,
and were put into the fiery furnace and the lions`' den.
These trusted in God, and He delivered them.

And when the rulers of the Jews commanded the apostles
not to preach any more in the name of Jesus,
they answered with a query,
"`Whether it be right in the sight of God to obey men rather than God, you judge.
For we cannot but speak the things which we have heard and seen.`"
And they went straight away into the temple, and preached or taught.
In the next chapter, when the Lord delivered them out of prison,
they went again into the temple and taught, and one came and told the rulers,
"`Behold the men whom you put in prison are standing
in the temple and teaching the people.`"
Then they sent for them before the council, and the high priest said,
"`Did not we strictly command you that you should not teach in this name, and behold,
you have filled Jerusalem with your doctrine,
and intend to bring this man`'s blood upon us.`"
Then Peter, and the other apostles answered, and said,
"`We ought to obey God rather than men.`"
And right away, to their faces, they preached boldly, and did not keep silence,
nor flee their testimony, as the priests did in those days.

And that able minister of Christ, the Apostle Paul said,
"`Necessity is laid upon me, and woe is unto me if I preach not the gospel.`"
He and they had the gospel to preach, and knew it to be weighty and powerful,
and were filled with the Holy Spirit, so that they could not contain it, or be silent;
for if they had, they would have felt "`the woe.`"
Men could not silence them, though they used violence,
for they chose to suffer rather than to be silent; for they dared not be silent,
seeing their great Lord and Master had commanded them to preach,
nor could they be silent without bringing themselves
under that woe which man could not take off.
Though they imprisoned them, whipped and stoned them, and used great violence to them,
still they testified (even to the very faces of those kings
and rulers they were brought before) of their way of worship,
and of the truth and life that is eternal, not valuing their lives,
or counting them dear unto themselves.

Meeting with the priest who lived in the parish where I did,
I spoke my mind to him,
and told him that I believed if God was pleased to
fit and qualify men for the work of the ministry,
gift them for it, and send them to preach, they ought to obey God.
And if men forbid them to obey God,
they ought not to forbear their obedience to God in order to please men,
nor to be silent at man`'s command if God command them to preach or teach,
as He did His servants of old times.
Those He sends in these days ought to be obedient to God,
even if man be displeased and cause them to suffer for righteousness sake.
For the Lord is God, and will help them,
and recompense them into their bosoms a hundred fold in this life,
and in the world to come life everlasting.
The priest told me that he preached in his own hired house, as Paul did at Rome,
and was not silent.
But that did not satisfy me, for Paul was a prisoner, and they were not.
Had they stayed till they were pulled out and put in prison,
then they had done like men that trusted in God,
and then the question would be whether men truly had power to take them from their flocks.
But they fled and left us.

Having searched the holy Scriptures,
and found that these priests acted contrary thereto,
and that both the Old and New Testament were against them,
and that if they had been true ministers of Christ they could not be silent,
though they had laid down their lives,
"`not knowing but that after them grievous wolves might come in,`"^
footnote:[Acts 20:30]
I was fully persuaded in my mind upon the aforesaid grounds
that the Presbyterians were not the true ministers of Christ.
And I felt my mind turned against them, considering that, if God had sent them,
they should have stood in their places, but if they were not sent of God,
then they ran before they were sent, and were not the men that I had taken them to be,
and now they were manifest.
So I left them,
and saw they were like those spoken of by our Lord in the 10th chapter of John,
who were hirelings, and not true shepherds.
For when they saw the wolf coming, they left the flock and fled.
But the true Shepherd lays down His life for the sheep.

Where to go, or what to do, I knew not, and I was much grieved,
and could not tell who the people of the Lord were.
I often cried, "`Lord, show me who are Your people, and those that worship You aright!
I pray You join me unto them, and enable me to serve You,
that I may enjoy Your presence.`"
Had I then joined to the Lord, and to the gift or grace of God that appeared in my heart,
and believed in it, and obeyed the teaching of it,
I should then have been joined to the Lord in His Spirit,
and also have been brought to them who were in the Spirit before me.
For they are His true worshipers who are in the Spirit, and in it worship God aright,
who is a Spirit.

When the Presbyterians were removed out of the pulpit (and out of my heart also),
then the Episcopal priests came in with their white robes,
and read the Book of Common Prayer with long composed forms,
(of which there is nothing mentioned in all of holy Scripture).
This was as a dead, empty sound to me, and my spirit was grieved with it,
for I met with nothing at all of the life or power of God in them;
so I saw they had a form without the power.
Indeed, this was the form of godliness without the power (2 Tit 3:5),
which the Scripture exhorts all to turn away from.
For the power that Episcopal priests came in by,
was the same that the others were put to silence by;
and this power had also authorized the priest to compel all to buy his wares,^
footnote:[By "`wares`" he is referring to the "`spiritual merchandise`" (i.e. sermons,
sacraments, rites, etc.) offered by the priests in exchange for obligatory tithes.]
and if any refused, he had power given to excommunicate him out of the synagogue.
And then, if anyone would not have his wares,
yet he had power to make him pay for them still, even after he was cast out.

Hearing that all must go to this form of worship,
I also went to worship I knew not what.
When I came, who should come to carry on the work but an old Presbyterian,
who had spoken much against the Book of Common Prayer,
and against those ceremonies which were commanded by men to be used.
But rather than lose the great benefits that yearly
came in (for praying and preaching to the people),
he swallowed down that which before he had vomited up.

I observed their worship, and I searched the Scriptures again and again,
and found the power they stood in not to be the power of God, but of men.
I found that God commanded, "`Whatsoever you desire that men should do to you,
do you even so unto them,
for this is the law and the prophets;`" but these went contrary to this.
The Lord commanded His servant Paul, saying, "`Pray always,
with all prayer and supplication in the Spirit;`"
but I found the Episcopal prayers in a book.
I found the worship God required to be in Spirit and in truth,
but the Episcopal worship was in ceremony and external things without life.
I found the Lord commanded in the New Testament not to observe days and times,
and months and years, but these priests commanded days to be observed, one above another.
The Lord commanded His ministers, saying, "`Freely you have received,
freely give,`" but these gave nothing freely, but sat ready to receive,
and even compelled people to give.
Finally, I found them to be in nothing suitable to the Scriptures,
and I then concluded they were like the false prophets who were spoken of in Scripture.

So I absented myself and did not join with them,
but was separated from them by the Lord, blessed be His name forever,
who has been gracious to my soul far beyond what I can express;
living praises be given to His holy name, forevermore.
I left them, with their dead forms, dead sounds, dead works, yes, all seemed dead to me;
and to stay there, seeking the living among the dead,
would not profit my poor soul at all.
I had this saying in my mind--Whoever is right I know not, but these are wrong.
Their eyes are blinded, their ears are dulled, their hearts are proud, carnal, covetous,
and greedy after their gain, and they do not profit the people at all.
And if they leave people after ten, twenty, thirty or forty years tithing to them,
yet they are no better for all the charges they have put them to.
They are "`miserable sinners`" still, and likely to remain so.
But though this was seen by me,
I still lacked wisdom to come to the true light which made these things manifest to me.
Instead, I was considering in my own wisdom what to do, and yet could not tell,
or find the true worshipers.

I heard of a sort of people who were much commended,
who used to meet in private houses in great fear of being persecuted,
but were much commended by great professors^
footnote:[The word "`professors`" is used to refer to those who _profess_ Christianity.
Here the word has nothing to do with teachers or scholars.]
whom I looked upon to be understanding men.
I went to their meetings, some of whom were called Independents, some Presbyterians,
and some Anabaptists.
I found some of this mixed multitude believed that
God had elected a certain number to be saved,
and had reprobated all the rest.
Others of them held forth free grace, or Christ a gift freely given to all.
Some held baptizing infants in water; some said no,
that none ought to be baptized in water till they believe.
And some baptized not at all.
But the greatest thing of all that I did not find when among them was the Lord,
nor could I see the power of God upon them, or amongst them.
Instead, pride abounded, slandering one another, foolish jesting, vain talking,
fashioning themselves according to the customs of the world,
many of them conforming so far as to go one time to their own meeting,
and another time to the steeple-house,
though they had much to say against the steeple-house worship.
I saw they feared man greatly, as it appeared;
for when the law of man come forth with great penalties upon all separate meetings,^
footnote:[A law was passed by the Parliament of England imposing
fines on any person attending a religious assembly (other than
those of the Church of England) consisting of five or more people.
Attendees were fined five shillings for the first offense,
and ten shillings for the second offense.
The preacher, and the one offering their home for such meetings,
were fined twenty pounds for the first offense and forty for the second.]
they refrained from meeting and were not to be found,
and kept silent rather than hazard this world`'s goods.
So I was still in great trouble of mind, and knew not what to do.
For indeed the Lord was what I longed for, and to glorify Him was my desire;
but I knew not how.

Then I went to Chesterfield,
to seek out and meet with those people called Independents; for I liked the name,
seeing nothing at all in man to depend on.
But these depended only upon the death and sufferings of Christ in His own body,
yet did not come to see Him, nor His appearance in themselves to be their life,
and had not heard His voice, and the Word of God they did not have abiding in them.
So these were dead professors and dry trees, not bringing forth fruit.
But they preached free grace, universal love, general redemption,
and tender mercy to all.^
footnote:[The terms "`universal love`" or "`general redemption`" should not be
confused with the doctrine of universal salvation or universal reconciliation.
The word universal was used by early Quakers to refer to their belief
that God _offers_ salvation to all mankind
(and not only to a small, predestined number)
through a measure of His light
or grace that witnesses in the heart against sin,
and invites all to find salvation in Christ.
It is this gracious, inward _invitation_ that is universal.
When received, followed, and obeyed,
this light becomes the life and salvation of the soul.
If rejected, the same light becomes man`'s condemnation.
See John 3:19-21.]
This pleased me well,
far better than the Presbyterian doctrine of election and reprobation.
Yet I was not satisfied or easy, for I read Scripture very much,
and saw by reading the Scriptures (with the secret help of Almighty God,
which He afforded me in His infinite love) that as
many as were led and guided by the Spirit of God,
these were the sons of God, and that, if any man has not the Spirit of Christ,
he is none of His.
This is such a clear distinction between the children
of God and the children of the wicked one,
or the children of this world, that there is no uniting them.
This is clear from the holy Scriptures.
For light and darkness are opposites; and Christ and Belial,
believers and infidels are past uniting without a new creation, a new birth,
which the unconverted are encouraged to wait for, seek for, beg and hope for.

I saw that without the enjoyment of God in my own soul all was in vain.
It was little comfort to me to read and hear what other men had enjoyed,
while I went without it.
The wise virgins`' oil would not serve them and me too.
I saw that a little measure of the Spirit of God
was more precious than all this vain world,
and that short of this I could not rest.
I made my remarks on those Independents, and saw they were very proud,
and were afraid of men and sufferings.
When we went to meetings, we were cautioned to go as privately as might be,
so that they went several ways, one under one hedge side, and another under another,
that we might not be taken notice of.
Then, when we came to the meeting places,
scouts or watchers were set to see and to give notice, that if a magistrate came,
we might all run away and break up our meeting.
This seemed a wrong thing to me, and it displeased me,
for I saw that they were not like the disciples of Christ who were
not ashamed or afraid to acknowledge Christ before men.
Doing this did not tend to spread the gospel, if indeed they preached it.

I found no true peace with God among them,
nor enjoyment of the Lord in my poor soul.
Whereupon I left them, and all churches and people,
and continued alone like one that had no mate or companion.
Yet at times, some hope would arise beyond my expectation,
and I believed that God had a people somewhere, but I knew not who they were.
I was afraid to join with any, lest they should not worship God aright,
and then I might be guilty of idolatry,
which I had often observed in Scripture to be offensive to the Lord (among the Jews),
and I saw that He not only threatened them sorely by His prophets,
but also brought judgments upon them for their idolatry and rebellion against Him.

The sorrows of hell took hold on me and the very pangs of death encompassed me.
Which way to turn I knew not, but I could find none to comfort me,
or to lend me a hand in my tears, fears, terrors, grief, amazements, bitterness, anguish,
and deep mourning.
Yet I was forward to discourse and talk about matters
of religion with any who would talk with me,
for many had a love to me.
But the priests I saw were in deceit, and I was sharp upon them at times.
My sorrows were so great that sometimes I roared out,
and cried mightily to the Lord when I traveled upon the plains and moors
and thought none was near to hear or see me but the Lord alone,
who was the only one to whom I did look and in whom I did hope for help and deliverance.

Now it pleased the Lord to open and show me many things.
He opened holy Scriptures to me sometimes,
and I was mightily afraid of sinning against the Lord, so that I walked carefully.
It grieved me to see people live badly,
and to see that they could not believe one another
in what they said when they bought and sold;
and when I heard a man swear I trembled.
Sometimes I felt something in my inward parts that was very precious and sweet to me,
yet I did not clearly understand what it was.
But if at any time I did or said anything that was not right,
then I soon lost the sight and feeling of that.
Oh, it has been gone in a moment!
I saw that everything which offended the holy God and was reprovable would not abide,
but all defilement and whatsoever was tinctured with evil was against it,
and it let me see it, and condemned it, and me too, so far as I joined with it.
Oh, to enjoy this is a comfort beyond utterance to that heart
which loves righteousness and hungers after it!

When I have been talking with a person who
did not see that I had spoken a wrong word,
yet I have seen it, and the Lord`'s Spirit gave me to see it,
though it may have slipped from me unaware for lack of diligent heed,
and watching like a doorkeeper as I ought to have done--oh,
then my sorrows would be renewed upon me, and tears and fears in abundance!
Yet a secret desire was in me that I might die, and go out of this wicked, sinful world,
where I found it rare to find a true-hearted man or woman.

One first-day,
after I had been reading one while and weeping another under a wall in a field,
about the middle of the day I came home,
and found my father and mother had come over to see us (for
I then lived with my grandfather as an apprentice).
I thought they would hinder me from minding the exercise I was in, which was deep.
In the afternoon I fell ill of a bodily sickness,
and when I felt my illness grow upon me, I was glad,
and in some hopes I should be taken out of this world,
for I was plainly sick with trouble of mind.
Yet a secret hope was underneath, that if I did die,
the Lord (who is gracious and merciful) would forgive
the sins of my childhood and youth.

After I was pretty well again, I went to the moor to pull shrubs,
and being alone, as my manner was, I was very full of inward exercise,
and began to think that that which I had sometimes felt so sweet and precious,
and other times as a swift witness, a reprover, a just judge,
and a condemner of all unrighteousness, was the Holy Spirit of God.
I remembered that I had been often visited by it, and yet did not know it.
For I thought I was not worthy to have the Holy Spirit given to me,
and that it would be presumption in me to expect it.
Yet now it came into my mind to think much of it,
and of its operations and workings in me.
It darted into my mind that it was really the Spirit of truth,
and also that I had not felt it, or seen its appearance for some time past.
Then I was full of fears, lest I had sinned against the Holy Spirit,
and such a terror fell upon me that I dared not tarry upon the moor,
but arose (for I was lying on the ground) and got away home.
I then remembered what made me so desirous to die the day my parents came to see us,
when I had been reading and weeping much,
and such a tender frame came over me that a hope sprung
up in me that if I died in that frame of spirit,
the Lord would have mercy on me,
so that I was desirous to die while that frame and hope continued.

Yet after all this, I fell into trouble again, and sorrow took hold on me.
At this time I happened to meet with a young man that was
dissatisfied about matters of faith and worship.
We appointed to meet on the following first-day at a woman`'s house,
who was called a Quaker (but I did not know that till after,
or but little of any such people, though I had heard of them).
When the day came, we met,
and it fell out that two other men came and met with us who were both called Quakers,
but had not long been so.
This day we spent mostly in discourse.
One of the men was of small appearance and slow utterance,
and one that never used to preach in meetings,
yet that day the Lord`'s power came upon him,
and he so spoke that he reached the witness of God in me,
and I thought that that exercise came upon him in mercy to me.
But, alas!
I had entertained such hard thoughts of these people that I went homeward very sorrowful.
My cry still went up to the Lord that He would show me Zion, the city of my God,
and who they were that dwelt therein.

And that first-day, as I was alone,
and in great exercise of mind about these things,
it pleased the Lord to show me His people who served Him.
As I walked along through a dark wood, I was so exercised that I scarcely knew how I was.
And as I came out of the wood to go up a hill, I had a vision,
and I saw a people laid close one by another in a very low place,
lower than the other parts of the earth, where they lay still and quiet.
I looked upon them, and it rose in my heart that they were the Lord`'s people.
This made me look earnestly to see who they were,
that I might know (to my comfort) the ones whom the Lord acknowledged as His people,
and I saw plainly that they were the people called Quakers, a poor, despised,
low sort of people.
When I perceived this, I was as one amazed and in great trouble,
for these were a people of all others that endured the greatest sufferings,
and were by all the rest hated, reviled, and scorned.

As I walked on, the vision ended, but I was in a strange frame,
and considering the matter, I felt a change in me,
and I knew that my countenance was altered.
I drew near a little village (my way lying through it),
but I had a mind to escape being seen as much as I could,
because I concluded that they would take notice that my countenance was much altered.
But it fell out, that when I had gotten almost through the town,
there was a woman who saw me and called to me,
though I went as far from her as I well could and still keep in the road.
She asked me how I did, and what ailed me to look so?
I gave her little answer, but said, "`Not very well.`"
So I passed on, and coming to a wall that was upon the top of a high hill,
I sat down upon it,
and there it was shown me that if I would be a true follower of the Lamb,
I must forsake the world, its corrupt ways, fashions, customs, worships,
and all the vain glory, love, and friendship of it.
I saw that if I now came into obedience to the Lord,
who had thus graciously heard my cries, and answered my breathings (or rather,
the breathings which He had begotten in me), that I must part with all the repute,
friendship, love, and praise of men, which I then had lived in.
I must forsake my old companions with whom I had
wasted much precious time in vain sports and gaming,
in which we lived and delighted, with many other things I prized highly.
All of this I must now let go for the Lord if I would choose and follow Him.

At this I was much troubled, for I was very unwilling to lose either,
and would gladly have had both the love of God and the love of men too.
I would have liked to enjoy both God and the world, but could not.
My love to these vanities was so great, and I prized them so much,
that it went very hard with me to think of losing all for Christ.
Yes, this was almost as bitter as death to me in appearance because
of the love and favor of the people I valued highly,
and the cross seemed so great that I could then by
no means persuade myself to take it up.
Great was the conflict I was in, and a very sharp war there was in me,
yet I did not disclose my condition to any, but kept all secret from man.

But the all-seeing eye beheld me, and allowed me not to be overcome,
nor the enemy to destroy my poor soul, though He allowed him to try and prove me,
till the Lord was pleased to raise up His living witness in me, which I admired at.
I could not tell what this was,
and did not know that it was the grace or gift of God that brings
salvation which had appeared to me (though I had grieved it,
and disobeyed it) until it seemed to grow less and less,
and to withdraw so long that I could see but little of its appearance.
Yet it never wholly left me, though I rebelled often against it, but still it rebuked,
reproved and judged me.
Indeed, I could not be at peace, because it loved me and would not let me alone,
but waited to be gracious to me, though I was unwilling to take its counsel.

I was greatly exercised in my mind and was
dissatisfied about the things of eternity,
and my sorrows were deep, and no man knew them.
Before I got home,
the enemy came near as if he would have whispered in my ear these words,
"`Who knows but this may be a trick of the enemy,`" meaning the vision.
And presently there appeared a part in me which was seemingly pleased with this whisper,
and said, "`It is very likely it may be so.`"
Thus the old self sought to save himself.
Then I remembered that the priests of those days had preached against
all such things as not to be looked for in these days.
They said that visions, revelations, and miracles were all ceased,
and that it was presumption for any man to look for the
Spirit of God to be given to him now as formerly.

So I threw off all again as a dangerous thing,
and would take no further notice of it.
I even desired, and was ready to say in my heart, "`Oh,
that the Lord would be pleased in these perilous times to speak audibly to some man,
as He did to Moses, that we might assuredly know His mind, seeing that one cries, '`Lo,
here,`' and another cries, '`Lo, there!`' But Christ, the power of God,
is in none of them.`"
So great blindness, darkness, and woeful ignorance seized upon me,
when I had rejected the Lord`'s counsel and trampled
such an extraordinary visitation under my feet,
and turned my back on it as the work of the enemy.
I have great cause to admire the Lord`'s mercies towards me,
that I was not wholly forsaken by Him.
For indeed His eye was still over me,
though for a time I was in deep darkness and distress, and my concern was very great.
In which time I conferred with many men of several opinions,
but I found none that could help me in this matter,
because I came not to the One that is mighty, upon whom help is laid.
Thus I was like a bird alone in the woods without a mate, joined to none.

In this state I met with an unexpected exercise;
for within a few days after this (on a first-day),
there came to me a young man who was full of inquiry, and a great seeker,
who told me there was a book lately come out that
had the greatest mysteries in it that ever were,
as far as he knew.
He said that God had spoken audibly to one John Reeve
of London (or thereabouts) and had told him His mind,
and bade him go to one Lodowick Muggleton, and he should be as his mouth,
as Aaron was to Moses.
And that God had given them commission above all men,
and power to bless them that believed them, and to curse them that spoke against them;
and whomever they blessed, they said were blessed,
and whom they cursed were cursed to all eternity, with many other strange things.

I greatly desired to see the book, for if true, this was the thing I had desired,
and I thought within myself,
that no man would dare presume to say such a thing unless it were really true.
In a few days I went to Chesterfield and saw it, and as one that had my wish,
I read it eagerly.
Upon reading where he said the Lord had spoken to him,
and had given to him and Muggleton a commission,
and that they were the two witnesses spoken of in the 11th chapter of Revelation,
I was ready to believe it.
I borrowed the book then, and afterwards bought it,
and as many other of his books as cost me eight shillings,
and read them through several times.
I concurred with him in many things,
and at last I was so taken with the story that I was likely to be deceived by it,
as was also the young man who spoke to me of it.

Then it pleased the Lord in mercy to visit me again,
to open my eyes and enlighten my understanding,
and He gave me to see great errors in the book,
and that his writings were clearly opposite to the holy Scriptures in many respects.
For they that were of that opinion,
and were carried away to believe the false prophet Muggleton (for Reeve was now dead),
had no worship at all.
When we met together at one widow Carter`'s home,
we were not for either waiting upon God,
or for any other exercise at all--either of preaching, praying,
or reading holy Scriptures.
No, we had no more to do besides believe Muggleton, and be saved.
So we spent some time in discourse, and then parted.

I saw it was clear from the holy Scriptures that it pleased
the Lord that men should worship Him according to His own will,
in all ages, and that He would be sanctified in the assembly of His saints,
and be held in reverence by all that were about Him.
But there was nothing of this among the Muggletonians.
And though the Lord had said, "`Where two or three are gathered together in my name,
there am I in the midst of them,`" this neither they, nor I, knew anything of.
We were simply to trust in Muggleton`'s name and power, and if he blessed us,
we were blessed, live as we would.
But if he cursed us, we were cursed, and there was no remedy.
This doctrine I found was contrary to the doctrine of Christ, the true prophet, who said,
"`Bless, I say, and curse not.`"
And I found that Muggleton`'s spirit took more delight to curse than to bless.
So I wrote a letter to him and made twelve or fourteen objections against his doctrine,
and sent it to him at London, to which he sent me a letter, and referred me to his books,
but did not answer any of the objections.
He told me he judged that I wrote in ignorance and inquiringly,
and therefore forbore to curse me till further trial.
But I left him, and sat down satisfied that he was a false prophet.

So I was like a man in a cloud; nobody saw my case, and I hardly saw it myself.
In this time I was sorely tempted,
and yet some hope lay very deep that I should meet with Christ in Spirit,
and know His Spirit in my own soul.
For I understood by the Scriptures that this Spirit was poured forth upon all flesh,
sons and daughters, and that nothing could be done well pleasing to the Lord without it,
and that they who were led and guided by the Holy Spirit of God were the sons of God.
I saw that all worship which was not in Spirit and in truth was not acceptable to God.
For all the prophets and the apostles came in this Spirit,
they having received it according to the prophecy of Joel 2:28,
and the promise of Christ in Luke 24:49, and Acts 2.

After I had been concerned with this man`'s books, and had finished with them,
I resolved to cease reading such strange books, and to read the Scriptures of truth only,
by which I was made a little easy.
Yet how to come to Christ (of whom I stood in great need), I knew not,
and was almost out of hope.
I discoursed with many, but found no true peace, comfort, or satisfaction,
but remained under much secret sorrow,
and I was still not so wise as to mind the gift or witness of God in me.
If I heard any evil reported of the people called Quakers,
I was glad and took courage to go on slighting the
appearance of Truth in my inward parts.
Yet the love of God was so great towards me that He did not take His Holy Spirit from me.
Praises, living praises, to His holy name forever!

I removed from the place where I had lived all my time,
and came to live at Monyash, six miles from there.
I inquired what sorts of professors were there, and I found a people called Anabaptists,
of whom I knew very little, but chose rather to accompany them than the rude,
worldly ones.
I conferred much with them, and took a liking to them,
which brought me to be acquainted not only with their principles,
but also with their practices in worship, which coming to understand,
I could say little against them,
thinking they came nearest to the Scriptures of any I had yet tried.
I therefore went to their meetings,
and was almost persuaded that I ought to be dipped into the water,
for unless I was dipped, I could have no admittance into their church.
Seeing no further, I could gladly have done so,
for this was a far easier way for the flesh than to obey the gift of God in me.

But I could not get to water baptism in faith.
For I heard them preach that water baptism is a sign of death, burial, and resurrection,
and that a man ought to be dead before he be buried; for said they,
"`It is monstrous in nature to bury a man before he is dead.`"
Then finding the Holy Scripture say,
"`He that is dead is freed from sin,`" and "`How
can you that are dead to sin live any longer therein?`"
I examined myself, and found I was not free from sin, so I was not dead,
and therefore I was not fit to be buried.
And before I was dead and buried,
I could not know a rising unto holiness and righteousness.
And if I should go and be buried under water as though I were dead,
it would be as a masquerade and a lie, and I would deal falsely both with God and man.
This kept me out of the water,
but one of the chief of them came to me one day to ask me why I came not to be dipped,
and I told him as above.
Yet he said to me, "`Many do come, that I believe are more unfit than you are.`"
I said that was nothing to me, for I dared not.

After this I went to see my sister dipped in a river called the Wye,
and after her two young men.
And when they came up out of the water, I spent some time with them,
and observed them who had passed from death to life (as they signified).
But I saw no appearance of the Spirit, or newness of life, or power,
or evidence that they thereby received the Holy Spirit--their
baptism being only with water,
which can only wash away the filth of the flesh (1 Pet 3:21).

But such as are baptized into Christ,
must be baptized into His death by dying unto sin,
and be buried by His baptism into death, so that being made free from sin,
they may come to have a part in Christ, the resurrection and the life,
by whom they are made alive unto God.
For in Christ life is manifest, and we have seen it,
and have tasted and handled the good Word of life, which has been as a fire,
and as a hammer, to break our rocky hearts asunder, and indeed water has gushed out,
and we have felt our hearts made new, and our consciences clean,
being washed with pure water to answer the pure requirings of the Lord.
Our souls being baptized into Christ, and He being put on,
in Him we have a safe habitation,
and come to see that even as none were saved by the
ark of Noah but the few that were in it,
so none can know salvation but those that are in Christ,
the ark of the everlasting covenant.
For He is given to be a covenant to the people, a light to lighten the Gentiles,
to open their blind eyes, and to be God`'s salvation to the ends of the earth.
And there is no other name under heaven by which any can be saved, but by Jesus Christ.
To Him be all glory given forever.

I found that they to whom I looked should have been dead to sin,
as they professed they were, yet they lived therein,
and pleaded for it during their term of life.
Then I began to question their form,
and through mercy I found it was but a form without life or power,
and I plainly saw they were not in the power and Spirit of God.
Thus the mercy of the Lord preserved me, and His long-suffering was salvation to me.
He drove me out of all the inventions and imaginations of men,
and stripped me naked and bare.
I had no hiding place, for these fig trees bore nothing but leaves,
and it was bread I needed.
These outward things brought no inward peace, power, or life, and could not,
nor can ever sanctify or make those that come thereto perfect as pertaining to the conscience,
and therefore cannot satisfy the immortal birth.

Yet I continued with them, until one day as I sat in the meeting,
I observed that the elders and chief speakers were
putting one another to preach and to pray,
saying, "`You do it, you are more able than me.`"
Thus they were urging one another, and as I saw and heard them,
there arose a dislike in me of these doings, and I said in my heart,
"`Why do you put such things on one another?
Let God put it on whom He pleases.`"

Afterwards, there came a mighty power and weight over me,
and it was in my heart to go and speak to the meeting.
When I felt that this increased upon me,
and I knew not how to contain it if I did not yield to speak,
I gave up and went through the meeting to those who
had been treating one another as aforesaid,
and desired I might have liberty to speak a few words.
One of them told me that it was not their manner
to admit any to speak among them before he was dipped,
and had entered in by the door, and had passed through the ordinances, or to this effect.
"`But,`" said he, "`we believe you are an honest man, and so you may take your liberty.`"
So I turned to the meeting, and spoke so that tears ran down.
I admired at the condition I was then in, for I was like a bottle uncorked,
and the power of the Spirit flowed in me, and when it stopped I ceased to speak.

The next first-day I went again,
and the meeting fell in course to be at an elder`'s house, one Humphrey Chapman.
At this time a very wicked act was put in force against religious meetings held in any
manner other than according to the liturgy or practice of the Church of England,
where above the number of five persons, besides the family, were assembled.
The fine was twenty pounds for the house, twenty pounds for the preacher,
and five shillings for each hearer.
But the elder (so called) refused the meeting for fear of being fined twenty pounds.
So the meeting was tendered to another, who was not only an elder but a preacher,
who had dipped the two men aforesaid;
but he too refused it for fear of his twenty pounds.
Then it was offered to a third, who accepted it for that day,
though it fell not to be at his house by course.
But when I saw the other two refuse the meeting for fear of suffering,
one being a preacher, who had dipped two men when I stood by,
I was not a little troubled.
For I remembered the words of Christ who said, "`He that denies Me before men,
him will I deny before My Father which is in Heaven.`"

So after the meeting was ended,
they discoursed about what they must do for the time to come,
and the query was where and when they must meet.
About this they differed much.
Some were for meeting in the bottom of a valley, to save the fine of a house.
And as for the meeting time, some were for meeting early,
so to be done by the time that the priest and people
came from the steeple-house to dinner,
but some were for beginning then.
Some were of one mind and some of another.
But there was one that I loved best,
who desired they might meet as they had done formerly.
As I sat and beheld them,
I felt the same power arise in me (in which I had preached
amongst them the week before) with these words,
"`These people are not the people of God, for they do not stand in the power of God.`"
This I believed, and went away satisfied that it was so.
So I left them, and went no more to join with them in worship.

I was once more singled out, and dared join with none of those formalists.
I was like a lost sheep, strayed from my Shepherd, whom, after a long time,
I now came again to remember.
At last I was persuaded that it was the gift of God, or the Spirit of Truth,
that had come to me to lead and guide me in the way of truth.
This wrought in me a great fear and dread,
lest I should have sinned out my day of visitation,
and I greatly questioned whether it would ever appear to me again.
Yet I had a secret hope, which kept me from being entirely hopeless.
I came again to be much exercised in mind,
and the travail of my soul was to truly enjoy the Lord,
and to be an instrument for His glory.
I longed to know His will and worship, and to perform the same,
and be joined to those who were joined unto Him.
I was like a speckled bird, with none like me,
for as yet I had not been at a Quaker`'s meeting.
But I sought to live as holy and righteous as I could among men,
and to join with none in worship,
for fear of being deceived by joining in false or will-worship and idolatry.

Afterwards, I went home and kept myself from all people, and joined with none,
having tried almost all persuasions among Protestants.
I had much sorrow in secret,
and was deeply baptized with the "`spirit of judgment and burning,`"
and I saw the baptism with the Holy Spirit and fire,
for my pride and empty knowledge, notions and opinions, yes,
my faith that I had gotten by the wisdom of man, was burned up.
Oh, the cup that I drank deeply from at that time is unspeakable!
When the Holy Spirit appeared in me, Jordan overflowed her banks.
Indeed it was deep at that moment of time, but in the midst of judgment,
the Lord showed mercy.

It began to be much in my mind, and I was ready to conclude,
that what I had felt in me was really the Spirit of the Lord who had long waited on me,
and striven with me.
I once said to two professors, "`Something appeared in me,
as one that had a mind to be received and entertained;
but for lack of my being open-hearted, nor inclined to embrace, receive, and mind it,
I often lost the sight and feeling of it.`"
Those to whom I told how it was with me said nothing to me at all,
nor could they tell me what it was, though I requested that they should inform me.
The appearance of it was mild, meek, low and gentle, and full of good counsel,
yet it stood firm always, and condemned evil, reproving,
rebuking and judging it righteously.
So at last I was much persuaded, in the secret of my heart, that it was the pure,
Holy Spirit of God; and then I thought if it did not come again, my state was dreadful,
sad, and deplorable.
I mourned and lamented greatly, but none knew my sorrows but the Lord alone.

Now I knew not what to do, for my former resolution to live a holy life,
and to be as righteous as ever I could, I found did not help me to peace with God.
Indeed I had no true rest for my poor soul day or night,
for I found I had no power to live as I desired to do.
No man could condemn me for any evil things,
yet I saw in myself that which others could not see.
I lacked the Lord`'s presence,
and without that my soul could not be satisfied or find true rest,
even though my life and conduct was such that most loved me who knew me.

About this time I entered into a married state, and went to keeping house.
After some time, my wife grew earnest to have me go with her to hear a priest,
but I dared not, for I saw they were as wrong as any.
Great sorrow fell on us, and we disputed often until we both wept.
In this condition I met with great temptation, and the enemy sought my ruin,
both of soul and body--all which I kept secret.
None knew the deep sorrow I was under night and day,
for I had none to whom I could open my mind, except my wife, but I dared not tell her,
lest I should trouble her, and put her in fear concerning me.
Yet sometimes, upon close search, I found a little hope,
but it was very low and very small.

After a time a cry arose in me to the Lord: "`Oh, that I knew His will,
and what He would have me to do!
Oh, that I knew His people, and His true worship with which He is well pleased,
that I might be joined unto those that were joined unto Him!
Oh, that I understood aright the things that belong to my peace!`"
When I awoke in the morning, a secret cry arose in my heart: "`Oh,
that this day may be my birthday!`"
For I saw that I needed to be born again, and to be made a new creature,
and my exercise was very great.
No comfort could I find in anything that this world
afforded without the enjoyment of His presence.
For this I travailed in spirit before the Lord,
and had some hopes He would show mercy to me, which, blessed be His name,
I do now witness.
For in His own time He caused the Spirit of His Son
to arise in my heart with true power and efficacy,
and I clearly saw it was the Spirit of God indeed which I had so long grieved.
This begat a godly sorrow in me, and then I came to it to ask counsel,
and it showed me the way of life, and gave me power to become a child of God.
Blessed be the Lord forever!

One day, in corn harvest,
as I was riding on the road to Sheldon in a deep exercise,
and taking a view of my condition, being in deep tribulation and anguish,
condemning and judging myself, it pleased the Lord suddenly, unexpectedly,
and unlooked for, to cause the Day Star to arise in my heart,
and the Sun of Righteousness to appear with healing in His wings,
even when the sorrows of hell seemed to take hold on me.
It pleased the Lord to appear in me, and to visit me with the Dayspring from on high,
in a very powerful and wonderful manner, in great mercy, goodness, goodwill,
and infinite lovingkindness.
I was, in my inward man, full of the power and presence of Almighty God.
Indeed His heavenly, glorious light shone in me so mightily,
that I may truly say it far exceeded the brightness of the outward day.
The eye of my understanding was opened,
and I saw that it was the Lord`'s Holy Spirit that appeared in me, and I believed,
and could do no otherwise.

Oh, then I was glad, and my soul was filled with joy,
because I had met with the Lord, who I knew was sufficient to teach me all things!
And He gave me to see that my sins would be remitted and forgiven,
in and through Jesus Christ.
Christ Jesus was now become my light and my salvation, and living faith sprang in me,
for I felt power and strength to believe.
I then saw and felt what true faith was,
and I knew that I had never before had this true living faith.
This faith was the free gift of God, for it sprung up in His power, and stands in it.
I also saw life eternal made manifest through Christ Jesus,
and I tasted the good Word of God, and was made a partaker of the Holy Spirit,
and was enlightened.
For the life was manifested, and I saw it, and I saw that the Son of God was come,
and He gave me an understanding to know Him that is true; for He revealed Himself,
or made Himself known in me and to me.

Now my soul was quickened and enlivened in Him and by Him, in whom is life,
and I also heard Him as the Shepherd and Bishop of my soul, who had come near,
even to my own soul.
And the holy Scriptures were opened to me, to my admiration and joy,
and I understood them far beyond what I had done before.
These became more sweet, comfortable, and precious to me,
so that I wondered how I had never seen them so before,
having read them so much night and day.
But now the Lord gave me in measure to understand them, for they were very plain.
And I saw that no man knows the Scriptures but those to whom it
is given by the Holy Spirit of Him who has the key of David,
and who opens and shuts as He pleases.

I kept what I had found that day, and it was to me as the Pearl of great price,
hidden in my own field (though I had sought for it in many forms and professions).
And I now understood the parables of the lost piece of silver in my own house,
and of the little leaven that lay hidden in my three measures of meal,
which I saw to be my body, soul, and spirit.
I saw that this had long been working in me, even while I knew it not,
in order to leaven my whole lump with its own divine nature,
which was capable of being leavened into good by the working
of that good and perfect gift which had come down from above,
and was freely given to me of God.

For truly the sons of God were led and guided
into all truth by the Holy Spirit of Truth.
And it was He that made David wiser than all his teachers,
and did attend him from his youth, and enabled him to go against the lion, the bear,
and great Goliath in the name of the Lord.
And I saw that no man could be a child of God without His Holy Spirit,
and it was this which I had lacked the knowledge of all my days.
And I was glad when I felt and knew that I had it freely given to me.
Now my great concern was to mind it, and be obedient to it,
for this was my Master and Witness that would either excuse or accuse,
according to my deeds.
It was my Reprover and Instructor, which showed me all that ever I did, and no thought,
word, or action was hidden from Him.
I was glad that I had found such a Comforter,
and that it was poured forth upon all flesh,
according to the promise in Joel 2 and Acts 2.

Great had been the work of this measure of grace in me,
which had come by Jesus Christ in order to make me a new creature in Christ (my life,
light, and salvation), or to leaven me into a new lump, and work a thorough change in me.
For indeed, I had great need of it, being a child of wrath in the corrupt nature,
as well as others.
Yet I still had not a clear knowledge of this measure of grace,
for great had been my ignorance.
And though light had shone in my dark, ignorant heart,
and made all things manifest that were reproved,
yet my dark heart had not comprehended it,
or understood that it was the light of Christ which so wrought in me.
For we lived in darkness, and in the night of blindness, and sowed to the flesh,
and took pleasure in unrighteousness, and lived in pleasure,
having our affections set on things below, and not on things above.
Yes, we loved the world and the praise of men more than that of God,
for the love of God was not yet known to us,
nor shed abroad in our hearts so as to see or feel that it was His love.
I was in a profession of religion without life, until the Lord appeared to me,
and caused the light of His Son to arise in my heart,
to my exceeding joy and satisfaction.
But when I was brought to the knowledge of this (which was the Lord`'s doing,
and it was marvelous in my eyes), my sorrow was turned into joy,
and greatly did I feel the love of God.
And great love arose in my heart unto the Lord,
and I was deeply sorry that ever I had sinned against Him.
I felt true repentance given to me,
and saw that I never knew what true repentance was before.

Now I had such a sense and assurance of the love, mercy,
and goodness of God to me in Christ Jesus,
and for His sake (who had now become precious to me), that if I had died in that hour,
I was satisfied of my soul`'s eternal happiness and peace.
Oh, then all fear of death and hell was taken away!
For I plainly felt my soul so affected with the love of God,
that I was troubled that I had ever grieved His Holy Spirit,
and great was my desire that I might do so no more.
I went on rejoicing with praises and thanksgiving, which arose in my heart unto the Lord,
my joy being great in Him, and I was ready to think that my sorrows were ended,
and my tears wiped away.
A new song was given me that none could sing, but only he that had it,
and I was glad to feel the precious Truth in my inward parts, which God loved;
and truly He loves those that love it, live in it, and obey it.
O happy day it was to my soul!
I loved the holy Scriptures,
which were never so sweet and precious to me before as they were now!
I loved all people,
and greatly desired that they might be brought to the knowledge of the Truth as I was,
for I knew that it was the will of God that all should be saved.

Thus, having met with the Lord to my joy and comfort,
I felt that His Holy Spirit was rightly called the Comforter,
which leads and guides into all Truth, which I now rejoiced to know, feel, taste,
and handle.
Then I turned my mind in to the Lord, to commune with Him,
desiring to know who were His people, so that I might join with them,
and worship Him aright, according to His own will.
And the Lord in mercy answered me as I prayed to Him,
and the word of the Lord was so powerful in my heart
that I could do no other than believe it.
And the Lord made known to me that the people called
Quakers were His people above all other people.
When I understood that this was the Lord`'s people, I felt a part in me that was sorry,
for if it had been any other people,
I might have been more at liberty to please the world, and to keep the friendship of it,
and not be so hated by it.
For this people were despised, persecuted, and suffered deeply beyond all others.
Others could flee from sufferings, and conform a little at times,
but this people stood and abode,
though the winds blew and the rains fell and the floods beat upon them.
For the Lord enabled them to stand and withstand it.
All praises forever be given to Him!

Seeing that I had such a clear manifestation of Truth,
I was desirous to do the will of God, and was afraid of losing the sense, sight,
and feeling of that which the Lord had in mercy given me the precious enjoyment of.
He was pleased to let me see that no man could take that from me, nor hurt my soul,
if I did not do it myself.
Oh, it was precious to my soul!
And so, though I had been offended with the people called Quakers,
I now called them Friends, as Christ did those of old who obeyed Him.
I went on to my journey`'s end with my mind exercised in serious consideration.

But, as I came back, the world was set before me, and all I had in it,
and I saw I must give up all, and let all go.
And this was not all, but I was likely to go to prison,
and my wife and children might be brought to poverty.
But I put my trust in the Lord alone, who is all-sufficient,
and is the portion of His people, and the rock of their safety, forever, amen.

Though the enemy was busy with me,
I was concerned to feel the Lord remain with me,
to keep and help me to abide in Him and with Him.
And blessed and praised be His name forever, He did not leave me, nor forsake me,
though sometimes He hid (as it were) His face from me.
And when I trespassed or offended for lack of a diligent watch,
or allowed my mind to wander, yet He has not been angry forever.
Though His Word has been to me as a sword and as a hammer,
yet in judgment the Lord remembered mercy,
and the good Samaritan has come and poured in oil and wine, and healed me wonderfully.
Praise, glory, and renown be given to Him!

My satisfaction was great, and my heart was turned to the Lord,
and my very countenance was so altered that my wife
and neighbors took notice and spoke of it.
But I kept my mind inward and said little, except as I had it given to me,
and I kept my exercises to myself for some time, and neither told my wife,
nor anyone else.
For as yet I had not been at any Friends`' meetings,^
footnote:[i.e. the Society of Friends, who were in scorn called Quakers.]
neither was there any about Peak country, where I then lived.

I met with some Friends at the market, and conferred with them,
but told them not of my condition.
The greatest part of the town was stirred; some said well of me, and had a love for me,
and some said ill of me, and hated me without a cause,
and they differed one with another.
But after some time, many were convinced and came to meetings.
The Lord having showed me again His poor, despised people,
it made me glad when I found those with whom I was to wait upon Him.

After some time, I heard of a meeting at Exton, at one widow Farnay`'s house,
whose husband had been an honest Friend.
I went to it, and found various Friends who had come many miles.
And when I came,
I was confirmed that these were in that Truth whereof I had been convinced,
though they were so much derided by the world.
There was little said in that meeting, but I sat still in it,
and was bowed in spirit before the Lord.
I felt Him with me, and with Friends,
and saw they had their minds retired and waited to feel
His presence and power to operate in their hearts,
and that they were spiritual worshipers who worshiped God in spirit and truth.
I was sensible that they felt and tasted the Lord`'s goodness,
as I did as well at that time; and though few words were spoken,
yet I was well satisfied with the meeting.
For there arose a sweet melody that went through the meeting,
and the presence of the Lord was in the midst of us.
And I met with more true comfort, refreshment,
and satisfaction from the Lord in that meeting than ever I had in any meeting,
in all my life before.
Praises be to the Lord forever.

I was assured that these were His people and were guided by His Spirit,
by which they came to understand His will,
and were brought in their measure into true obedience to His commands,
being made willing to bear His cross, deny themselves, and become fools,
that they might know true wisdom.
For this they wait in silence,
to feel the inspiration of the Almighty to give them
an understanding of the things of God,
which the natural man cannot understand,
because he does not wait in the Spirit for the manifestation.
I also felt such a love in my heart to them as I had never felt to any people.
Oh, it was true love, such a love as none knows but they that have it!
And I also felt the same love in them towards me,
and some of them got me in their arms and were glad of me, though I knew but few of them,
nor they me.

So I came home,
and my poor wife was sorely grieved that I had gone
among Friends (the people called Quakers).
The people of our town began to rage.
Some disputed with me; some cursed me (as I heard); some pleaded for me;
some derided and mocked me, calling after me, "`Quaker, Quaker.`"
When I heard them thus call after me,
my heart was glad and filled with joy that I was reproached for Christ`'s sake,
and was thought worthy to take part with Friends in the sufferings of Christ
"`that were yet behind in His body`" (Col 1:24). And the thought arose in me,
"`Now I have got the name;
oh that I may be truly brought into the nature of God`'s people!`"

But there were several things that as yet I did not discern clearly.
Though I felt the Lord with me and was sure it was the truth, yet I intended,
in the secret of my mind, not to imitate the Quakers.
I continued to put off my hat to men, and to use the same language that I had done before.
For I did not like their plain language and behavior to people,
and I was not willing to come into the practice of
these things merely in imitation of Friends.
I thought I should please people better if I said "`you`" to a single person,
and put off my hat to them (for many love to be worshiped,
though there is no worship due to any creature upon earth).
So my coming among Friends was hidden for a time, few knowing what I was,
nor what I had seen, heard, and felt.
Yet I knew it was the Lord that met with me on the road,
and it was with such power that I willingly received
it to my great satisfaction and comfort,
and believed that the Lord (when He saw fit) would open
my understanding and give me to understand the holy Scriptures,
which, in His great mercy, He has since wonderfully done.

I was careful to hold fast that which was freely given unto me,
and it came into my mind to wait on the Lord to know what He would have me to do.
So I waited in my mind to hear what the Lord my God would say to me.
After some time, as I was riding on the road and waiting,
the word of the Lord arose in great power in my heart, saying,
"`Speak truth to your neighbor.
Be not double-tongued; respect no man`'s person.`"
This fully satisfied me; and I saw I was to enter the kingdom of heaven as a little child.
I was to learn to speak and walk anew,
and I stood in need to be helped and held up by the secret hand of the almighty,
omnipresent God, and to mind Him in all I said, and in all my walkings and doings.
I saw that God changes not, and that as men truly turn to Him, they come to be true men.

But this language and manner of life was hard to flesh and blood,
which desired both to please men and to receive praise.
I had grown accustomed to such things when I was young,
and so it went hard with me to lose it all.
But I knew I must, though men took offense at me for my obedience to the Lord.
So I gave up in obedience to the will of God, in which I found life and peace to my soul,
and great encouragement and joy in the Lord.
Nevertheless, this way of speaking and carriage went very hard with me,
and was a great cross to my natural part,
and helped to lay me very low and to mortify the old man in me,
and made me willing to be a fool in the eyes of the world, and to be despised of men.

Now, blessed forever and praised be the Lord God Almighty!
He has made my soul glad, and satisfied the breathings of my spirit.
He has opened to me the mysteries of His kingdom, and given me a measure of His grace.
He has caused His light to arise in me and caused the darkness to flee away.
He has given to me the true bread of life,
and made my heart glad with the wine of His kingdom.
He Himself has become my teacher, and has gathered me into His power,
and covered me with the banner of His love.
He has become my hiding place, my rock, strength and refuge;
I need not fear what man can do unto me.
He is my portion, I shall not want, and therefore I trust in Him alone,
my helper in the needful time.
He has wrought all my works in me and for me,
both to will and to do of His own good pleasure.
He is a sufficient reward to all those who wait upon Him.
He is all in all; I have none beside Him.
He is all-sufficient; I am nothing but what I am in Him,
therefore He alone is to be praised.
Glory is wholly due unto Him, for it is He alone that has redeemed my soul from death,
and has opened to me the way of life.
He has taken my fetters from my legs, and has set my feet upon a sure foundation.
He has brought me out of the prison house, and has set my soul in a pleasant place.
He has plucked me like a brand out of the fire,
and has given me strength above my enemies.
He has redeemed my soul from death, and caused me to walk in the path of life.
He has heard my sighing, and my groanings were not unknown to Him.
Indeed, the breathings of my soul He has regarded,
and my heaviness He has turned into joy.
Yes, He has tenderly waited to be gracious to me,
and His long-suffering has led me to repentance.

Oh, what shall I render to the Lord my Savior,
who has dealt so bountifully with me?
My soul, bless the Lord forever, and all that is within me praise His holy name,
for He has caused mercy to surround me.
Oh the lovingkindness of the Lord!
All you that know Him praise His name, for His mercies endure forever!
He has caused light to shine out of darkness,
and manifested thereby those things which are reproved.
To this light my heart is turned,
and I am resolved to turn away from my iniquities and serve
the Lord with reverence and holy fear.

Now I know it was He, by His Word,
who showed me my thoughts and the intents of my heart.
Though I was once ignorant of it,
yet now am I assured that it was His Word which often called behind me, saying,
"`This is the way, walk in it!`" (Isa.
30:21) He was still seeking to save me out of the enemy`'s power,
though I then regarded Him not.
Nevertheless He pursued me, till at last my heart opened to receive Him,
who is now my beloved, and has given me to taste that God is good,
whose goodness far exceeds all that this world can afford.
Praised be the name of the Lord!

I have found the Pearl of great price, the one thing needful for my soul to know,
and this is Christ within, the hope of glory, the true way to the Father,
who promised to be with His disciples to the end of the world.
This is He whom we are to hear and obey in all things,
lest we be cut off from among His people.
This is the anointing which I have received of the Lord, that teaches all things,
which is truth, and is no lie.
Oh that the children of men would open their hearts,
that the king of glory might enter in,
to drive out that den of thieves who rob them of
that treasure and peace which passes their understanding.
Then they would come to witness the Comforter, the Spirit of Truth,
to lead them into all truth; for it is He who works all our works in us and for us.
This is the Lord`'s doing, and it is marvelous in our eyes;
to whom be praise and glory forever!

[.asterism]
'''

[.emphasized]
After at last finding what he had so long sought after,
John Gratton continued in faithful submission to His Master and
became an eminent minister in the early Society of Friends.
He traveled often in the service of the gospel, declaring all over England, Scotland,
Ireland, and Wales what the Lord had done for him, and what he had
"`heard, seen, and handled concerning the Word of life.`"
Among other trials and afflictions that fell to his lot,
he was arrested in 1860 for noncompliance with the Church of England
and imprisoned for the space of five and a half years,
during which time he wrote many edifying treatises
and epistles for the strengthening of his brethren.
When at last he was released by a proclamation of
King James in favor of liberty of conscience,
he resumed his travels in the work of the ministry,
and remained a faithful laborer and elder in the church until his death in 1712,
at the age of sixty-nine years.
Some of his very last words were, "`May the Lord bless His people,
prosper His Truth amongst them, and enable them to live in love one with another.`"
Not long after, weakening very fast, he said,
"`Lord, I freely commit my soul and spirit unto you.`"
