== Chapter III

The Baptists were displeased with me when they saw
there was no hope of my return to them,
and often disputed with me; for great disputes were at Monyash between them and Friends.
But the Lord had opened my understanding, and also the holy Scriptures to me.
I wrote a little book concerning baptism, and therein showed,
that no man had commission from Christ to baptize with water since John`'s race was run,
and his ministry fulfilled,
making it appear that the Baptists baptized without any command from Christ.

At this time Truth prospered in the Peak country, in Derbyshire,
and the word of God grew, and was multiplied,
the word which God sent unto the children of Israel, preaching peace by Jesus Christ,
who is Lord of all.
"`That word,`" said Peter, "`which was published throughout all Judea,
and began from Galilee, after the baptism which John preached;`" which word,
Peter preached to the Gentiles, namely, Christ Jesus, the Lord of all,
who is the only way to come unto God by:
"`For no man can come unto the Father,`" said Christ,
"`but by me;`" and there is no other name given under heaven by which any can be saved,
but by Jesus Christ; for he is the Fountain of eternal life,
which is opened for all to wash in and be cleansed,
and for that end he has poured out of his Spirit upon all flesh,
that they may have a part in him; and the cleaner we are washed,
although it be in great tribulation, the whiter will our robes be.

Now I was come to know what the city of God is, which I had read of in the Revelations,
that is, to be the true church,
which has no need of the sun or of the moon to shine in it;
for the glory of God does lighten it, and the Lamb is the light thereof, in which light,
the nations of them that are saved must walk.
There the kings of the earth shall bring their glory and honour;
the gates of this city shall not be shut at all by day, and there is no night there;
here none are to enter which are defiled, neither whatsoever works abomination,
nor makes a lie, but they who are written in the Lamb`'s book of life.

After this I went to Oxston again, where the informers were very busy,
and the officers came, and one charged me in the king`'s name to come down and be silent,
as I was speaking in the power of God.
But I charged him in the name of the King of kings to be silent, and also asked him,
if he did come in the king`'s name; he said yes: Then said I, Did he send you?
Does he know of our meeting?
He answered no: then said I, how can you come in the king`'s name, if he did not send you?
And the man turned from me and got away, taking those away who came with him.
We had a precious meeting that day.
After this, I went to Great Markham, where they stoned us as we rode through the streets,
and brought a man to the meeting, furnished with rotten eggs, as I supposed;
for he came and stood just before my face, and flung them towards me,
but did not hit me with any of them.

Another time I went to Markham again, and the priest came and brought the town officers,
and sent them in to break up the meeting, while he stayed at the door.
The officers came in, and Friends making way for them,
they sat down and heard very quietly;
for I was declaring in the Lord`'s heavenly power before they came in,
and they stayed till the meeting was done, and gave no disturbance,
but to the priest who stayed at the door outside, to see the meeting broken up,
but when they did not do that, lie raged, and said,
he brought them to break up the meeting, in which they stayed: but he went away angry,
and afterwards we departed, sweetly refreshed and comforted.

I ran to and fro, and had many meetings both in the High Peak, Scarsdale, Staffordshire,
Cheshire, Lancashire and Yorkshire; and Truth prospered gloriously.
I also had meetings in fresh places; as Ashford, Longson, Tideswell, Bradow, Grinlowe,
Baslow, Matlock.

And there was a convincement at Bradow, and thereabouts in the Peak;
and one Jonathan Fisher and his wife, with others were convinced.
We appointed meetings there, and such a multitude came,
that the house could not contain them.
Therefore I went into the street under a great tree, in the market place,
that was walled about, and I got upon the top of the wall and spoke to the people,
but a company of rude fellows set on to stone us, and the stones flew about my head,
and rattled in the trees, yet hit me not:
but a great stone struck and wounded a woman that happened to sit near me,
and the people came and carried her into a house, but she recovered after some time.
At last a man came, blaming them who threw stones at us, and got into the crowd,
but after he had stood awhile, he stooped to take up a stone to fling at me,
as was supposed, and one of his neighbours standing by, who,
for some time had been very attentive, seeing the man that had blamed others,
going to throw a stone, struck him on the ear,
that he let the stone fall and did not fling it at me:
this man who struck the other was convinced that day, and became an honest man,
and so continued till his death, for aught I know.

At last Henry Jackson, and Henry Roebuck came to the meeting,
and got on the top of the wall also; and as Henry Jackson was declaring,
a parcel of young men came and thrust Friends violently off the wall.
Henry Jackson was heavy, and they were very hard set to get him down, but they did.
I went down and spoke to one of them, asking him why he was so uncivil; he answered,
if they let us alone all the town would be Quakers.

I went to a part of the wall that was just before the greatest part of the crowd,
and getting up, kneeled down on the top of the wall before their faces,
and all fear of stones or men was gone,
and I prayed to the Lord by the help of his holy Spirit, with a loud voice,
and the Lord`'s power came over all, and the people fell in their minds, and were still,
and became like another people.
Henry Jackson had good service among them after,
and our meeting ended in great sweetness, and as we rode out of town some blessed us,
and seemed very friendly and loving, and never disturbed me after,
though I have since been at many meetings there, at Jonathan Fisher`'s house,
who lived and died an honest Friend, and left a good savour behind him,
and his memory is sweet: many were convinced there, and at Slackhall also.

We went sometimes over the East Moor, and had meetings at Totly and Dore,
where some were convinced, and near Beechief, where Justice Pegg lived,
but he never concerned himself to disturb us.
Most of our meetings were out of doors, but one we had in the hall,
and several in a large barn; but one first-day we had one near Beechief,
which was at the back side of a house in a lane, and many came to it.

There came a high constable, whose name was John Stone, and brought officers,
and a company with him on horse-back, white I was preaching,
and the constable charged me in the king`'s name to keep the king`'s peace.
But the Lord`'s power and presence being with us,
I held on speaking boldly in the name of the Lord,
but he sent one of his company and bade him go fetch me out.
The man came and laid his hand on me and trembled, but had not power to take me away;
he stood by me a while, I continuing my testimony;
he then left me and went through the meeting without me.
When, he came to his master, he said, "`Why have you not brought him?`"
What answer he made I heard not.
Then he took out his pen, ink, and a little book, and called to a Friend to assist him;
the Friend went to him to see what he wrote,
and he said his hand trembled so that he could not write.
After I had eased my spirit a little, I was silent, and gave way to Henry Jackson,
my elder brother, who had good service that day.
The officers were very uneasy, and John Stone rode away angry,
as though he would go to the justice for more power, and the meeting continued finely.
He stayed, I suppose, above an hour; when he came again,
he had as little authority over us as before,
for the people were so affected and strengthened,
that they ventured to talk boldly to him, and told him,
it was fitter for him to go and search the ale-houses,
and to take notice of drunkards and bad people, than to come there after that manner,
to disturb such honest people as we were.
He fumed about awhile, and at last put spurs to his horse and rode away,
and took all his company with him, so we had a precious time,
and he had no power to stir us.
Soon after that the high constable died:
there were some went away soon after the officers came,
but they have been poor ever since: but the Lord has blessed the faithful every way,
thanks be given to him forever!
He was with us from day to day, and from place to place,
and permitted no weapon or wicked instrument to hurt me wherever I came.
Blessed be his holy name forevermore.

Another time I went to a meeting at an old house near Whitwell common,
and there the officers came, but I declared the holy truth among them.
After a while they went out, as I thought, to consult what to do,
and I heard that one said to the other,
"`He speaks almost nothing but Scripture;`" and they were not willing to disturb us,
but after a while they went away.
The Lord was with us, and gave us a good meeting, praises be given to him forever.

I was invited to a meeting not far from Newcastle-Underline, where I went;,
but when I came there the house was too little, for many came to it,
and William Yardley was at it.
So William and I sat down in the house,
but the parlour and other rooms were filled with people,
and there came a man from Newcastle on purpose to be an informer against that meeting.
He went into a byroom that had many people in it.
The meeting being gathered, I felt the Lord with us, and he enabled me to speak,
and my voice was shrill, and they that were in the other rooms heard plainly.
This informer took offence at some words which I spoke,
but he was a dark ignorant fellow, as all informers are,
else they would not be informers to hurt the Lord`'s people for their obedience to him.
His offence was so great, that he was restless,
and disturbed the people that were in the room with him;
yet he stayed while William Yardley was declaring to the meeting.
I sat silently waiting upon the Lord,
and it pleased him to manifest to me that there was a man in another
room that had taken offence at some words which I had spoken:
and showed me the words, and I remembered them, though no creature had told me a tittle,
nor had I seen the man; but I was so plainly showed it from the Lord,
that when William Yardley had done, I stood up again, and called out to the man, saying.
Whosoever you are that are offended at these words, which I repeated,
and then spoke fully to, and opened them,
making it appear plain and easy to be understood,
that the words which I spoke were words of truth and righteousness:
and the man heard me and was satisfied and got up and went quietly away.

Soon after the meeting ended,
the people that were in that room with the man before mentioned,
came to me and asked me who told me; I answered them.
No man told me; at which they wondered how I should know so fully,
and tell it so plainly; and God had the glory, and the man had not power to hurt us,
but went his way, and I saw him no more.
Thus were we delivered from the wicked,
that they did not gain their prey upon the righteous who trusted in God;
and for this end I write these things,
that they that fear and love God may put their trust in him, and be obedient to him,
and valiant for his name and Truth, and fear not man whose breath is in his nostrils,
who is here today and gone tomorrow.

After this I went to a meeting at Blyth again, and we met on the highway side,
for the meetinghouse doors were locked up, and we kept out;
but the officers watched lest the informers had come,
and when our meeting was done and all silent, and about to part,
the officers stepped to us, and went away with us as though they had broken us up;
but they took some before a justice, and told him the meeting was silent,
so Friends were not fined, nor the officers blamed:
for they took that way on purpose to save themselves and Friends also.

We had many good meetings at Baslow,
till at last they cast Hugh Masland into prison at Derby,
and George Ellis and Hugh Masland`'s wife died; but one day two men came to be informers,
and stayed the meeting quietly, but after it went to Justice Ayre of Highlow, to inform,
and wanted a warrant to distrain our goods.
But he was displeased and sharp upon them, and bid them look to themselves;
for if he found that they did forswear themselves, and he ever caught them in a lie,
or to that effect, he would have their ears;
by which they were so daunted that they went away and let it fall,
and troubled us no more.

After this the priest of that town grew angry,
and gave a challenge in writing to dispute with me on three points.
First; he said there was no revelation in these days.
Second; that no man had the Spirit of God in him in these days.
Thirdly; that if I had the Spirit of God I might read in a book he had, which was Greek.
He set a day and place to meet on; and when the day came,
I met him in a close of Humphrey Chapman`'s, in Baslow, a civil man,
and many people of diverse sorts were there;
and when I had showed the priest`'s blindness about revelation,
he put his book into my hand, and said, "`If you have the Spirit of God in you,
read in this book;`" so I took it and held it till
he had vaunted and made an oration to the people,
and then he would have taken the book from me.
No, said I, you gave it me to read; first see whether I shall read or no.
So I took my Bible and read the Scriptures to the people,
and showed them how they spoke quite contrary to the priest,
and the priest quite contrary to the holy Scriptures,
which says the Spirit of God is given to all, but not to all alike;
to one was given the gift of tongues, to another the interpretation;
some were gifted for miracles, but not all; some do prophesy, and preach the gospel;
but the manifestation of the Spirit is given to every man to profit with.
I read the plain Scripture, but he knew not that it was Scripture, but talked against it,
till one that stood by, told him, "`It is Scripture, man,`" so he was sorely despised;
and when he saw that he had plunged himself into a great deal of error, he was silent,
and was so manifest that one Benjamin Ashton, the justice`'s son,
came to him and took him by the sleeve and led him quite away,
and left me with the people.
There were many Baptists, to whom I spoke awhile, so the people stayed,
all but the man who went away with the priest; and we had good service for God that day,
and were comforted.
Truth prevailed and the people were edified, and the Lord`'s power was over all.
Many talked of this dispute,
and the priests of the country were offended with this priest, for challenging me,
and envied me the more for it.

Our meeting at Monyash increasing,
several priests up and down the country were angry and very envious,
and I and others were served with sessions and assize processes.
One Wilson, the chief priest of our parish,
was to come on a first-day to our town to give or sell to the people bread and wine.
Those that will not buy it of him, he uses to make pay for it;
whether they will have it or no, pay they must;
for he has sent officers and distrained my goods for it,
though neither I nor my wife ever had any from him.

The meeting was to be at our town that day,
and the priest ordered one of the church wardens to go early that morning,
and call at Ashford, and take the constable with him to Justice Ashton, a moderate,
peaceable man, one who did much good in his place.
The constable had some private notice and slipped out of the way,
but the officer of Monyash went as the priest had ordered him,
and desired the justice to grant him a warrant,
to break up a meeting that was to be that day.
"`How!`" said the justice, "`a meeting that is to be?
I will grant him no warrant for a meeting that is to be.
How do you know it is to be?
Had you seen the meeting, I would have granted you a warrant;
but none will I give you on such account,`" said he, or to this effect,
as I was informed.
So the officer came back without a warrant, yet the priest Wilson came,
after he had done his forenoon`'s work, and sent for all the officers in the town,
and came to our meeting, and brought his clerk to be informer,
for they would have broken up our meeting by pulling and hauling us out by force.
But when they had us out, and went to fetch more, we followed them in again;
and as some were forced out others went in.
Thus they wearied themselves a while, and then the priest was going away;
but I being got in again after they had hauled me out, my mouth was opened;
and when the priest heard that I had begun to preach, he turned again and stood quiet,
and all was still till I had done.
I spoke to the priest before the people, and told him,
if he took himself to be our shepherd, and that we were strayed from the flock of Christ,
let him make it appear that we were in an error, and I would take it friendly;
but he said he came not to take the sheep, but wolves, and went away,
but left the informer at a back window, looking in at a casement,
and confessed that the Lord was among us.

We had a precious meeting after they were gone, and a Friend went to prayer,
and praised the Lord, that his presence was with us.
Yet this informer went after this to the monthly meeting of justices,
to inform against this meeting.
We had then the high constable living in our town, who was a loving, friendly,
moderate man;
he was setting in the room when the priest`'s clerk came to inform against Friends,
and asked him what he came there for: and the clerk told him;
but when the high constable understood his business,
he got up and put him out of the room, and kept him out,
that he could not inform that day.
It happened soon after, that this informer went to let off his musket,
he being a trained soldier, and it burst in pieces, by which he was wounded,
and narrowly escaped being killed.
He confessed that he thought it fell to his lot to be so hurt,
for what he had done to the Quakers, and that he would be done if he could;
so he troubled us no more.

After this I heard that Wilson, the priest of our parish, went to the justices himself,
and wanted some course to be taken with the Quakers, to put down their meeting;
for he was hot against us, but against me above all; but the justices held him off,
telling him that they were not willing to have any hand in ruining their neighbours,
and desired him to take some other way than by informers.

Before these things happened, I was in great exercise of mind,
notwithstanding which I was willingly given up to serve the Lord,
whatever I suffered for it.
In this exercise I was brought very low, being deeply plunged in my spirit,
until at a meeting in my house,
it pleased the Lord in mercy mightily to break in upon me, greatly tendering my spirit,
to the gladdening of my soul.
Then were my tears, tears of joy, for I rejoiced in the Lord,
for his mercy endures forever; thanksgiving be given to him,
who failed me not in this needful time,
but supported and bore me up in these days of great tribulation.

At this time Friends suffered deeply in many places, both by fines and imprisonments;
also the priests in their pulpits raged against Truth and us.
In these perilous days I went up to London, to the yearly meeting,
where I was glad to see such brave meetings.
The first I was at was in Gracious street,
which was so large that the court was almost tilled.
In this meeting the Lord`'s power was with me,
and I had more mind to hear others than to be heard myself;
for there were many brave men there, who are since gone to their rest.
But the power of the Lord came upon me,
and at length my mouth was opened in the demonstration of the holy Spirit,
to my great joy.

In the afternoon I went to the meeting at the Bull and Mouth, which was also large;
but before I got there, a woman Friend was declaring;
her name was Theophila Townsend--she had a living, powerful testimony,
yet notwithstanding that, the rude people about the door despised her,
and spoke unhandsomely of her.
I pressed through them and got into the gallery, and after she had done, I spoke,
and first directed my speech to those unruly men,
showing whom the Scripture said should not enter into the kingdom of God; but said,
It is likely you think God will be better than his word; and they were still and silent,
for the Lord`'s power came over all; then I turned to the meeting,
and Oh! the streams of life that ran through the living that day.

The next day I went to another meeting, and to several meetings following in that week,
and it was a precious time to Friends.

On the seventh-day I met with three Friends who were going to see Lodowick Muggleton,
namely, Robert Barclay, Patrick Livingston, and William Haglie,
and I went along with them, only I desired they would conceal my name from him,
for he had had my letter but a little before.
When we came there, his wife civilly conducted us into a room,
after which he came down and looked on us, saying, "`Is any of you John Gratton?`"
But Robert Barclay answered, "`Are you a prophet, and you need to ask?`"
At this Muggleton stopped, saying, "`You are Scotchmen,
and I will have nothing to do with you; for I was lately cheated by a Scotchman,
one John Swinton.`"

This J. Swinton had been to see this false prophet, and in discoursing with him,
he supposing him to be a poor man, gave him half a guinea,
upon which Muggleton blessed him;
but before J. S. went away he told him he believed that he was a false prophet:
upon which Muggleton cursed him; so he would not meddle with Scotchmen.

Robert Barclay asked him then, why he did not give the man his gold again?
to which he made no reply.
Then I spoke to him, saying, I am an Englishman, talk with me;
and I put some questions to him, as,
whether all Scotchmen must suffer for one man`'s offence,
if it was so that he was offended?
He said he mattered not:
I told him it seemed to be contrary to the nature of Christ Jesus,
who came to seek and to save that which was lost.
Then I asked him how he came by his authority?
Had he seen anything, or heard any voice?
He answered no; then said I, You have nothing for what you do,
but what you had from John Reeve; he said no, he had not.
Then said I, I perceive that all you have for what you do,
is only the bare word of a man; he answered, it was.
Then said I,
Do you not think it would be a credulous thing for me to
venture my eternal salvation upon the bare word of a man?
To this he answered, "`You must, if ever you be saved.`"
That is strange, said I; for I knew he lied, and was a false prophet;
praised be the Lord, who gave me to see him fully.
Then I asked him if he had power to bless a man after he had cursed him; he answered no.
Said I, What! have you power to curse a man after you have blessed him,
and have not power to bless him after you have cursed him, provided the man repent?
He answered no.
Robert Barclay then replied, that it was strange,
if he had power to curse men after he had blessed them, for then, by the same rule,
he should have power to bless men after he had cursed them.
But still he knew not me.
Then spoke Patrick Livingston, saying, "`I was with a disciple of yours at Chesterfield,
and she told me I should never have any more openings or fresh springs again;
but,`" said he, "`I have found her a liar every day.`"
Then said he, "`Did she curse you?`"
"`Yes,`" replied Patrick.
"`Well,`" said Muggleton, "`in confirmation of her curse, I pronounce you cursed.`"
Then another said something to him, and he cursed him also;
and when he had done he was so pleased,
that he said it did him more good than if a man had given him forty shillings:
upon which I asked him what he thought of me, and what would become of me?
He answered, if I was careful I might do well; saying several times, "`If you be careful,
it will be well with you in the end.`"

Then I desired Friends to bear witness,
that this false prophet says he has not power to bless a man after he has cursed him;
and yet, having cursed me before ever he saw me, he tells me now, if I be careful,
I may do well, and it will be well with me in the end.
O, what a false prophet, said I, are you!
And then I told him my name; but when he heard that, he was sadly confounded,
and made no further reply to me.
So we left him, and went away.

This I write in the memory I have of it, and have been large in the account,
that it may be seen how plainly he was made manifest to be a deceiver,
that others may beware of him; desiring that it may please the Lord,
to deliver every honest-hearted soul from the baits, snares,
cunning wiles and devices of the enemy of all mankind.

Soon after this, as I was riding through Islington, I looked upon the city,
remembering thankfully the good time I had had there,
and it was manifest to me that I should meet with some trial before I got home,
for the gospel`'s sake; yet, nevertheless, we went forward, and came to Ware.
There we called to see Thomas Burr: from there we went to Huntington,
where I had some relations.
At this place great spoil had been made on Friends, it being a time of great persecution;
we called to see a Friend at Godmanchester,
whose house was sadly plundered for meeting together.
We passed on to Ives, where we stayed their first-day meeting, which was very large,
and Friends ordered it to be in an outhouse, which belonged to Tobias Hardmeat,
though it fell by course to be elsewhere that day.
Here the informers missed of us, though they intended to have caught us,
but they being misinformed of the meeting, we were preserved out of their hands.
From here we went to Stamford, in Lincolnshire, to William Collingworth`'s,
where once I had a meeting, and at Oakham,
at Joseph Holt`'s. From here we passed on till we came to Long Clawson,
in the vale of Beaver, and as we walked down the hill it came into my mind,
that at this place I should meet with the exercise which I had a foresight of before,
notwithstanding which, I was given up to the service I was called unto.

We came a Friend`'s house named Edward Hallam, where we lodged that night,
and Friends came to see us, and desired us to stay a meeting with them next day;
but I inquired of them, how things were with them, whether they were quiet?
for I was sure we should be disturbed, yet I dared not deny a meeting with them,
yet I kept all to myself.
They told me as yet they had met with no trouble,
but said the priest had threatened of late.
However we agreed to have a meeting the next day, and I told them it might so fall out,
that they might be fined twenty pounds for me; they answered, "`If you will venture,
we will:`" so it was resolved on.
That night in my sleep, the Lord showed me the meeting in the meetinghouse,
and let me see a company of great dogs come in and fall on us,
and rear up at us with their forefeet upon our shoulders, as if they would worry us;
one seemed to be upon me, and had got my left arm in his mouth,
but I lifted up my right hand and knocked him down, and down they all came,
and went away, and we had a good meeting after,
and looked one upon another to see if any were hurt,
and no man had so much as his skin broken, so we parted.

Next day before the meeting was gathered,
as soon as I came within sight of the meetinghouse door,
I saw the priest and officers of the town with two
informers in soldiers coats going there;
and I saw they were pressing to get into the meetinghouse,
insomuch that I was afraid they would get in before me and keep me out,
but I hasted all I could, and pressed through the crowd,
and got in before the priest and officers.

Soon after they came in, and went to taking names, but were so confounded,
that it was observed they asked their own town`'s people their names,
though they knew them well enough.
After some time the power of the Lord arose in me, and I kneeling down, went to prayer,
so my right hand was lifted up, and they fell and got away out of the meeting.
The priest and constable took horse and went about four miles to fetch a justice,
whom they brought back with them to the meeting, though it was ended before.
The informers, by the help they had got, kept us in till the justice and priest came;
so we all sat silent.
Then the justice asked, "`What is here to do?`"
And after some pause I stood up, and went before him and told him,
that we were there in obedience to the Lord,
to wait upon and worship him according to his own will, in spirit and in truth,
and not in any contempt of authority; and though some of us had wives and children,
and some estates in the world to lose, if it pleased the Lord to allow it so to be,
yet we dared do no otherwise than we did, or to this effect.
He asked me my name, and where I dwelt, which I told him;
so he went on and took names through all the meeting,
and fined me twenty pounds for preaching,
and the rest five shillings a piece for hearers.

This was about the time called mid-summer,
and about the time called Michaelmas after he sent up a warrant by the informer,
to Justice Gilbert of Locka,
and he gave his warrant to the constable to distrain of me for twenty pounds.
The night before they came, I being laid down in my bed, a great exercise fell upon me.
I waited to see what it would come to, and it increasing upon me,
I thought I was walking upon a very fine green place, and saw a storm coming,
with a very strong wind, upon which I resolved to stand it,
and set myself so as I thought to stand fast, and not be moved;
but the storm came upon me, and took me up, but I was filled with the power of God.
When it was over, I considered of this exercise, and it came into my mind,
that it did not come to me for nothing,
for I thought the Lord had something for me to do, and I felt him very sweetly with me;
and I said in my heart, Lord, what would you have me to do?
Then the word of the Lord arose in my heart, saying, Sell all that you have.
After this I fell to rest, and next morning I went to the quarterly meeting at Tupton;
when I came there,
I heard that two red coats were gone up to Monyash to distrain my goods,
and the rumour was,
all that I had must be taken from me for preaching the everlasting gospel,
for that was my crime, and nothing else; praised be the Almighty forever!

I acquainted the meeting with the exercise I had in my bed the night before,
and how the word of the Lord came to me, bidding me sell all,
and I desired the sense of the meeting, whether I should sell all actually,
or give up all, and let all go patiently and freely for the truth`'s sake,
if the Lord was pleased to allow me to be so tried with the loss of all?
And it was the sense of the meeting, that I should give up all into the Lord`'s hand.
At that time I owed monies both to Friends and others,
which would have set me hard to pay on a sudden,
without selling what I had in my own possession, for I had much owing me,
but could not get it in suddenly, whatsoever came on me.
But I owed most to Friends, and they were at the quarterly meeting, and came to me,
and were very tender to me, and encouraged me to give up all freely, and if all went,
they would be content to take things as they were, or as it did fall.
A precious day it was, and the Lord`'s power was over all the powers of the earth,
and I was strengthened; praises to our God forever!

I came home that night,
and the two informers were come to town with a warrant from Justice Gilbert,
it being certified to him concerning that meeting at Clawson, by the said Lister,
called a justice, who never prospered since, but is wasted and gone into a low condition,
and become poor.
The informers sent for the constable, who heard that I was not at home over night,
upon which he refused to come till the next morning.
But on the next morning early, I sent for a man of the Church of England,
to whom I owed ten pounds;
he came and I delivered goods into his hand to sell and pay himself,
and give me the overplus;
so he took them and was well pleased to see my honest care of him.
To another man I owed three pounds, but it happened he had a cow of mine in his grounds;
so I sent to him to keep her for his money, or sell her, and pay himself,
and give me the overplus.
Then what I owed to Friends I was easy about, seeing they had been so kind and tender,
and gave up theirs freely.

Soon after this was done, I saw the constable go into a neighbour`'s house,
to whom I went and spoke; but, poor man! he was full of trouble, and lacked counsel;
when he saw me, he said to me, You have brought yourself into trouble, and me too,
and was very passionate.
Man, said I, I have done no man any wrong, I would not have you be troubled,
for if you will distrain you may, but if you will take my counsel,
I will tell you what I would have you to do.
He asked, What would you have me to do?
Said I, Send these men away, and tell them, if you need assistance,
you can call to your neighbours.
He was pleased with my advice, and went up to the inn; but before he left me,
the informers came, and they knew me, and said I was the man: Yes, said I,
how does Justice Lister?
I thought he had been more moderate,
than to have prosecuted the law against me to this height.
One of them said.
You are a people that will be obedient to no law.
I felt the Lord`'s power to arise in me, and I said unto him.
What do you think, are we children of God, or children of the devil?
If the latter, you may take courage to do as you do; (though I knew he ought not,
if it was so) but if you think we be children of God, how dare you?
But one thing let me tell you, the Scripture says, that he that is born after the flesh,
persecutes him that is born after the spirit.
Now, said I, there is your mark; and further, it says,
that is an evident sign to them of perdition, but to you of salvation, and that of God.

The Lord`'s power appearing with these words, they both were silent,
and went away to the inn, and the constable also followed them.
I stayed a little and weighed in my mind, what to do:
whereupon I felt freedom to go to the inn also, and found the informers at their meal,
and talked with them, enquiring of Friends at Clawson, how they stood?
And whether any shrunk?
And they told me, indeed Friends suffered deeply.

The constable and some neighbours were in another room, and called me to come to them,
but when I came they said to me, Are you so mad as to stay with your enemies?
Ah, said I, we must love our enemies, and do good to them that hate us,
and pray for them that persecute and despitefully use us.
Ah, said they.
It is well for you if you can do so, for we cannot.

The informers came to take leave of the constable, and told him,
they did believe I was an honest man,
and they would have him be as favourable to me as he could, saying, It would not be much,
if the town`'s men would pay it for him; for, said they,
we heard as we came up the country, that he was an honest man.
Then they begged of the constable, to give them some money to help them home,
for they had above thirty miles to go, upon which he gave them sixpence.

When they were gone, the constable came down,
and I thought he would have followed me into my house, but he stayed in the street,
hanging down his head very sorrowfully.

Some of the town offered to pay the money, and take it up again as I could pay it,
but I could not with freedom do it; but while I was at the inn,
some of the chief women of the town came to my house,
and finding no body in it but my wife, they, against her mind,
violently took all the best of the goods away,
and carried them--on purpose to save them for us--to a neighbour`'s house.
When I came home and saw the goods gone, I was sorry, and asked my wife, how it was?
She told me she could not help it, and where they had carried them she could not tell,
for they would do it, whether she would or no.

I went out and invited the constable to come in,
but he desired me to shut the door on him; I answered him, No, for I had done no wrong,
nor was I afraid of any man, and besides, I was not free to shut my doors;
then he came in, and sat down in much trouble, hanging down his head.

After some time, we had some warm food ready for dinner, and we invited him to dine,
he roused up himself and eat with us, and after dinner,
he went and sat down again as before in much trouble.

At last I began to think, what to do with him, for no way opened to him how to do,
and it went hard with him to distrain, for he seemed confounded.
Then I spoke and told him, he might write down what goods there were,
he saw how things were, and I could not help it, and that he might leave them with me,
for I would net make them away, if he did not;
and he also might proclaim them at the market-cross, and in the steeple-house,
and if anybody would buy them, let them come to buy them at my house.

This proposal he liked, and did accordingly, but when people heard them proclaimed,
they wished sad things to such as bought any of them: so that none were sold.

Soon after this the sessions came, where the constable went,
and meeting with Justice Gilbert, of Locka, who granted the warrant, and another,
called Sir Henry Every, he went to them, and offered to deliver them his warrant,
and his bill of goods that he had distrained, and told them that he could not sell them;
but said Justice Gilbert to him.
If you cannot sell them in Derbyshire, you must carry them into Yorkshire.
No, replied Justice Every, what need of that, you granted your warrant,
and you have done your office; and good fellow, said he to the constable,
you have executed your warrant, and have done your office, if you can not sell them,
you can but go your ways home, and let it be as it is.
He was Chief Justice in that county, and loved honest Friends, but hated hypocrites,
and was much against proud priests:
also the Earl of Devonshire and his lady had spoken to him before to be tender of me,
as he was ever after.

After this, when I was a prisoner,
he laid hold of every twig of encouragement till he got me out again.
When King James put out his proclamation,--which some would
have hindered me the benefit of--he spoke to the judge,
and got me discharged.

The constable came home, and with great joy told me what had passed,
that he came off so finely, and that my goods were saved.

Thus the Lord delivered me, defended and pleaded my cause in the time of need.
Oh! his mercies were great to me at this time,
he filled me with the Holy Spirit that day the informers were with me;
so that sometimes I was ready to say, that if I had had a house full of goods to lose,
I could freely part with them for the sake of truth.
For to us it is given in the behalf of Christ, not only to believe in him,
but also to suffer for his sake;
and all that will live godly in Christ Jesus must suffer persecution.
It is cause of great joy, when we are counted worthy to suffer for him;
and he that loses anything for his sake, shall receive a hundred fold in this life,
and in the world to come life everlasting.
If we suffer with him, we shall reign with him; but if we deny him, he also will deny us.
They are counted happy that endure; for he that endures to the end shall be saved:
therefore we are exhorted, to Lay hold on eternal life, and hold it fast,
lest any take our crown, which he freely gives to all them that love his appearing.

After this sessions I was lined several times, twenty pounds a time,
and the constables took the same way as the first did, and always went to Justice Every,
and returned their warrants to him, which he took,
and discharged the officers and sent them home;
so the Lord preserved me from the spoilers, blessed be his name!
He allowed the enemies of Truth to go no further,
nor to do any more than he was pleased to give his people strength to bear,
with comfort and rejoicing; for he has been my rock and stay, yes,
my portion both for soul and body; he has helped me in all my necessities,
and stood by me to hold up my head above all the waters and tempests;
he is my salvation and treasure which will never decay,
praise forevermore be given to him!

After this I went to a meeting at a town called Whittington,
to which meeting came the mayor of Chesterfield, where two men waited on him;
but the priest of the town, as they told us, sent two informers,
who followed the mayor into the meeting, though he knew not what or who they were,
that I could hear of.

The mayor came simply and innocently to hear truth declared.
I was preaching when he came in and stood up close by me:
I was opening to the people the parable of the supper,
(Luke 14.) and how those who were bidden made excuses,
but the servant was sent out again into the streets and lanes of the city,
to bring in the poor, the maimed, the halt and the blind to the supper;
and I was showing who these poor, lame, blind and halt were,
and how those that were wounded and lay lame and sick came to the supper.
The mayor asked me how they were wounded?
and without stopping,
I told him that they were the poor in spirit who received the kingdom,
and the wounded in spirit, saying, The spirit of a man would sustain his infirmities;
but a wounded spirit, who can bear! and so went on:
and the power of God broke mightily through the meeting, that the mayor cried out,
It is true!
When I had done, he went out and wept bitterly, and desired Francis Davenport,
the Friend of the house where the meeting was,
to show him where he might lie down a while; he had him into a chamber,
where he lay down, weeping sorely, and he was very loving to me all his days after,
though, poor soul, he was very rich in worldly riches,
and it was too hard for him to stand in a public profession of the truth with us;
but he was under a concern in his mind to his dying day.

But though the mayor, I believe, neither thought to do, nor did us any harm,
yet the laws were such that I was fined twenty pounds again for preaching,
and the Friend of the house was fined twenty pounds also;
for the two men that the priest of the town sent to our meeting, as aforesaid,
went and informed against it for a conventicle.

Justice Barton, of Dranfield,
without calling me before him to hear my accusers face to face,
according to the ancient laws of the nation, sent out his warrants to distrain our goods,
and they took Francis Davenport`'s cattle and horses,
and went to Fleshly fair and sold most of them, before Francis and I could get there;
but after we came and told it in the fair how they came by those goods,
nobody would buy any more of them: and one man,
who had ignorantly bought some of the cattle, was sorely troubled, and said,
had he known it, he would not have bought them.

The officers of our town had got a precedent,
and took the same method as the former constable had done:
they took some goods away from me, but could sell none,
upon which the constable acquainted Justice Every, who bid him go his way home,
and let it be as it was.
Thus this justice stood in the gap,
and stopped my goods in favour to me from being sold time after time,
by which means I was preserved wonderfully from being plundered;
and the goods they took out of my house were brought again after the sessions.

Indeed my neighbours showed much love to me,
and were reluctant to have me hurt at any time,
so that the Lord was wonderfully good both to me and my family,
and was pleased to work for me from time to time;
glory to his great and honourable name forever! so that I never lacked a bed to lie on,
or beds for my friends, nor food to eat, nor raiment to put on.
