== Chapter IV

About this time I went into Cheshire, and had a meeting at Chester,
where I met Roger Haydock, Eleanor Loe, and Mary Warrel, of whose company I was glad.

In this place there were several men who had received the truth,
and yet through unfaithfulness fell away, but when I understood this I was sorry,
and went again to Chester; for I had no ease in my spirit for two days and nights.
I came there on the sixth-day of the week, and at night I had a few words before eating,
where an apothecary and his wife were at supper.

The next day I walked to and fro through the market, with a great concern upon my mind,
but had not an opportunity in the street to speak to the people.
The apothecary got me to his house, where both he and his wife were very friendly;
he also told me, that the unfaithfulness of some in that city had hindered them, else,
said they, we had been among you before this day.
I talked with them and then we parted friendly.

On first-day I went to Richard Smith`'s house to the meeting,
and sat down and stayed an hour or more before the meeting was fully gathered;
then I stood up and went nearer to Friends, for it was a very large room,
and the Lord in mercy was pleased to give us a precious meeting,
and there was great brokenness of heart with many tears.
At the latter end of this meeting, Richard Smith spoke very tenderly,
and desired that they who were unfaithful might amend their ways,
and for the time to come do better; yet poor man, notwithstanding this exhortation,
he himself, after some time, did worse than he had done before,
for he wrote against Friends and the blessed Truth; however, he,
with some others who opposed the Truth, were soon after taken away.

King Charles II. gave liberty to such Presbyterians as would,
to license places to meet in, and they got a great barn at Ashford in-the-water.
I happened to be in the town one day, and saw their meeting break up,
and there appeared in the street abundance of people,
and it troubled my spirit to see so many poor people led away,
with such as I had tried and found to be false apostles.
Within three days the word of the Lord came to me, to go to that meeting next fifth-day,
but it was very hard with me to give up to go,
for there were many that I loved very well, and that I believed loved me;
but the Lord was good and encouraged me,
upon which I acquainted an ancient Friend with the concern which was upon me,
and he also encouraged me.

On fifth-day morning a friend came to me, and to the meeting we went,
where the priest was preaching, and preached false doctrine.
My message to the meeting was, That that meeting should fall and come down before long,
with more I had to say, as it did in a few weeks after,
and there was never a meeting since in that barn, though they had set up a pulpit in it,
and fine seats.
When the priest had done, I desired the privilege of the gospel, which was.
If anything was revealed to him that sat by, let him speak,
and the rest hold their peace; but before I had said what I had to say,
they came violently upon me, and abused me, hauling me out;
the priest looked pale and went away, though I charged him with false doctrine.
When I was out I declared to the people in the power of God,
against their priests and worship, but none answered me in defence of their way.
When I had done I went away, and soon after saw the word of the Lord fulfilled,
for their meeting was not to be found in all the country,
because they fled and got into holes in those suffering times.

Another day I was at Wirksworth market, and the people swore dreadfully,
at which my spirit was sorely grieved, and the word of the Lord came unto me, saying.
Go to the market cross and declare against the wickedness of the people.
I was reluctant to go, for I knew many of them to be rude, wicked, drunken,
swearing people; besides, I did not know but they might pull me to pieces,
and therefore I took my horse and went home.
But I was followed with sharp reproofs and righteous judgments from the Lord,
with which I was in deep sorrow, and I looked for the renewing of that concern no more.

But the next time I went, when I was in the market again,
an exercise fell heavy upon me to go and warn the people.
Now I went, not standing to consult any more,
and in the heavenly power of God declared the Truth,
and bore my testimony against their great wickedness,
insomuch that the people were much reached, and wept aloud,
and no man had power to hurt me.
I stopped twice and sat down, and waited still for the fresh motion of life,
and the Lord enabled me to stand up again.
When I had eased my spirit I came away in peace and great joy,
and after I came to my inn, some followed me, but it rose in my heart to go out of town,
which I did.
After I was gone, I heard one Justice Loe came to the town,
and sent to my inn to fetch me before him, intending to send me to prison,
but the Lord delivered and saved me out of the hands of wicked men;
for this justice was a great persecutor of Friends.
Thus the Lord was with me, and kept me wherever I went.
Oh! let my soul livingly praise his holy Name.

About this time I went much to meetings, and ran to and fro, the Lord helping me,
without whom I could do nothing, for in him all fullness dwells; and many were convinced,
and our meetings were greater and greater, and many proved faithful;
but the priests raged sorely, for I went abroad as much as I could,
and kept my trade going too.
My family also grew larger, and my care was great to pay all I owed to every body,
so that I was often constrained to ride many miles after meetings,
to gain my markets on the second-day of the week, and the Lord blessed me every way.

Many Friends came to visit me at my house,
for the more I travelled and laboured in the work and service of the Lord,
the more I gained acquaintance with Friends abroad.
And I went often to the yearly meeting at London,
and there inquired how Truth spread abroad from nation to nation; and I was glad,
and Friends came in love to see me, who went in the love of God to visit them.
Our town`'s people thought that they would eat me up, as I heard,
and waited to see me fail in the world; but when it did not prove so,
but rather the contrary, then they changed their minds, and said, that the Quakers,
as they called them, gave me money for preaching;
and many such false accusations and slanders I patiently bore in those days.

Thus the subtle serpent, by his wicked and false reports,
laboured to hinder the prosperity of the pure Truth;
yet I saw no way but to give up my cause, and the cause of Truth, into the Lord`'s hand,
for him to plead it as he saw fitting.

The priests seeing the magistrates did not like to persecute us,
laid their heads together, and got out a writ against me and two other Friends.
It so happened that I was gone to York, and those parts thereabouts, in Truth`'s service,
and came not home till the writ was near being out of date,
but the other two Friends were taken and sent to prison at Derby,
and were long kept prisoners there.

After this, they cited me to the bishops`' court, to which I went, and when I was called,
went up towards the high priest and the others; one of them was called the Register,
whose name was Nichols, of Litchfield.
When I came near him, he looked on me with an envious countenance, saying to me,
"`Are you there?
I thought to have had you in jail before now;`" but said he, "`I will have you in jail.`"

Then said I, I have read, that the devil shall cast some of you into prison;
but I never read, that any prophet, apostle,
or servant of Jesus Christ laid any man in prison for conscience sake.
But Nichols answered again, "`I will lay you in prison.`"
Then said I, You will join with the devil.

"`Pray, Mr. Wilson,`" said he to the high priest,
the same who came before to our meeting to persecute us,
after he had been at that called his sacrament, "`do you admonish him.`"
Upon which I looked for some information and counsel; but all he said was,
"`I admonish you to come to church: I admonish, I admonish you to come to church.`"
I admired at their folly and blindness;
for I expected they would have laboured to show me that it was my duty to come to church,
or that I was in error; but seeing nothing came but, I admonish, I admonish,
I admonish you, three times, to make way for their wicked court to go on to persecute me,
and get money; I said to him, Prithee,
whether do you admonish me for the good of my soul, or for the love of my money?
Nichols said, "`I for the love of your money, and he for the good of your soul.`"
With that the people made a noise with laughing;
for they saw it was money more than the good of souls,
that they aimed at in that wicked court.
Then the Lord`'s power arose in my heart, and I was going to declare against them;
for I saw their wickedness in their high places was very great, and from an evil, cruel,
persecuting, selfish spirit; but they cried out,
"`Have him away;`" upon which I was violently hurried out of their court.

At the next court I was cited again,
and in the mean time summoned to appear at the court sessions at Derby.
The bailiff of our hundred told me, we must go to the clerk of the court sessions.
I told him we would not, for it was in vain to go to him, except we would give him money.
Then said he, "`You must appear before the judge.`"
I seemed willing to that, and told him,
it might do well to let him know how we were abused by him, and his men the bailiffs;
for we are hurried to the court sessions, because we cannot give you money,
and people of other opinions, who can give you money, you leave at home; yes, said I,
to my own knowledge, you left one at home for one groat.
We were many Friends together,
and when he heard me so free to appear before the judge and discover
how they made their ends of the people in the country,
he bid me get me away home, if I would.
I said, then I would have all my friends along with me.
He bade me take them, and away we came home, and these greedy men got no prey from us.

The next day being cited to appear again before the Spiritual court, so called,
but rather wicked court, at Bakewell; three of us went.
I came from the Temporal court one day, and went to the Spiritual court another,
but they all missed of their chief ends of me; for they were of Felix`'s mind,
they troubled me the oftener, thinking to get money of me.
When we came there, the court was removed into the inn, to go to dinner;
after which they held their court in a chamber, where we appeared;
but Nichols said he would not take mine for an appearance.
I asked him why, saying any time that day, while the court lasted would do.
The priest answered, saying,
"`You are a people that will not be obedient to the king`'s laws.`"
I then asked him.
Is the king your ruler?
To this he was silent, and bid an apparitor take me away,
but I stayed till the other Friends had done, and then went away.

After this I travelled hard, and went to meetings in many places;
and one day as I was drawing homeward, having been in Leicestershire,
and Nottinghamshire, coming by Derby, William Fallowfield being with me,
a letter from Abraham Morris, of Lincoln, met me, desiring me to speak to a great woman,
who was about to put some Friends in prison, who were her tenants, for tithes.
I went to her, and after some talk with her, she grew very cool and moderate,
and ordered me to go to her steward, about eight miles from Derby;
so William Fallowfield left me: I went home from Derby,
and on the next day I went to the steward`'s, but he was gone to Brasson.
I went there, and he was gone to the hall.
I sent for him to my inn, but he would not come; so I went to him to the hall,
where were two priests and the master of the house, and some of Derby, who all knew me.
I got the steward from them into the hall, where I discoursed him,
telling him his mistress`'s mind, and left him very friendly;
after which I heard no more of the Friends going to Lincoln prison.

I pressed on then to go home to my family, though it snowed and blew hard;
but when I was on Brasson Moor, the word of the Lord came to me,
bidding me go to Auldwark and help them out.
There I went, not daring to deny.
There was no priest or priest`'s shop in that town,
and many were under trouble about religion.
I had some acquaintance with one John Buzston, to whose house I went,
and he bid me welcome.
I acquainted him I had a desire to have a meeting, and they acquainted the town,
and about the hour appointed the house was full.
I was enabled to speak as in the ability of God`'s holy Spirit,
and was powerfully carried on for about four hours.
The meeting ended before twelve, but some stayed till two,
and the man and his wife were convinced, and both their parents; also the servant man,
who has since a fine testimony among Friends, and twenty more of the town.
John Buzston said he believed all the town was convinced.
Many came to meetings, some till they died, some till they married;
some went into America, and did well, as I hear.
I had also meetings about the same time at Newman-Lays-Millen,
and a brave convincement there was in those days; some of whom are alive to this day,
and faithful to the truth;
and also in many other places where the Lord ordered me and went with me,
and by his own right arm did unutterable things.
Many were convinced, yes, hundreds, I believe, and came to meetings,
at which the devil was angry, and I was cast into prison.

Soon after this, a writ _de Excommunicato Capiendo_ came out.
While I was abroad among Friends,
I had a great sense of a deep suffering falling upon me,
insomuch that I said to a friend, it was so deep I could not see to the bottom of it;
and I desired in my heart of the Lord, that I might be enabled to stand it.
Before I got home out of Yorkshire, I had a dream one night, in which I saw,
as I thought, a great mastiff dog look hold on me,
and held me by my clothes just by Derby jail.
I saw it was to no purpose to strive,
and therefore after I had called to his master to take him off,
but could not see he was inclined to it, I gave up to let him hold me.
The day before I got home I felt the suffering more and more;
and the next day I went to Bakewell fair,
and the apparitor arrested me before I could get into my inn,
or put up my horse in the stable, being the 16th of the sixth month, 1680.
So to Derby I must go, but we stayed that night at Bakewell,
where my wife came next morning, and wept.
I bid her not weep,
but rather rejoice that we were counted worthy to suffer for Christ`'s sake,
who had suffered so much for us.
Then she bore it very well, when she saw me bear it so cheerfully.

Now when we came to the jail I demanded a free prison, but the jailer was unwilling,
and offered me kindness if I would stay in his house and pay for my table,
but I had a wife and family,
and therefore could not afford to lie at seven shillings per week in his house;
but I insisted to have a free prison, as I knew the law allowed.
It happened that a little before,
there were several Friends in that prison whom he put in the dungeon among thieves,
and would scarcely allow them clean straw; so I got a statute book,
which said that no sheriff, nor under-sheriff, nor jailer, nor under-jailer,
should keep and lodge debtors and felons together, upon the penalty of five pounds.
I took it and went to the sheriff, whose wife and mine claimed some kindred;
they were very friendly to me, and desired me to leave my book with him,
and meet him at the court session, where he would speak to the judge, which he did,
and the judge ordered my friends to be put from the felons,
and to have rooms to themselves.
The next that came to prison was myself, so I demanded one of those rooms.
He said he had corn in it.
Take it out then, said I, which he did in great vexation, and put me there,
it being an old prison chamber.
I borrowed a bed, with some other things, and went in.
He came up to see how I fared.
I had a fire, and though I could see the stars at night through the holes in the tiles,
yet I lay warm enough: I had my health, and was well content,
and thought in my mind that this was but small suffering
to what I might go through before I died.
I gave up all into the Lord`'s hand, soul, body and spirit, wife, children,
and all I had, saying in my heart, sickness or health, life or death,
the will of the Lord be done.
Oh! how good the Lord was to me, and I lay quiet and slept sweetly.

But when the jailer saw that I settled to abide there, and framed to housekeeping,
he was angry and went his way, and locked me up close, and I remained so some time.
I did not so much as desire to look out at the door.
My heart was glad that I was accounted worthy of those bonds;
and though I could get nothing except I had drawn it in at the window with a cord,
yet it happened that I lacked nothing all the time it was thus with me,
for indeed I resolved to abide it patiently.

At length a Friend, one Robert Meek, came to see me,
and the turnkey came to tell me there was one come to see me, saying,
I must come down into the house to him.
By this I saw that the jailer was willing to have me come
to my friends that they might spend money in the house;
whereupon I told the turnkey that I was not willing to go down.
If my friends, said I, must not come to me, I am not willing to come to them.
He went down, and in a short time brought up the Friend to me, leaving us together,
and the door unlocked, and when the Friend had stayed his time,
I went down with him to see him take horse.
When he was gone, I spoke to the jailer, and asked him,
why he carried it so severely to me?
I told him, if he was civil, he should have civility from me, and if he would not,
he might do as he would.
He said that we were a people that would do nothing but what we wished;
so when we had talked a while, he said.
There hangs the key, take it, and do as you please.

Ever after I went in and out as I had occasion into the jailer`'s house and gardens,
but home he would not let me go, though my wife was taken so ill,
that it was feared she would have died.
I gave up wife and children, and all I had into the Lord`'s hand, and was contented,
saying in my heart, after this manner: Life or death, poverty or riches,
come what will come, the will of the Lord be done.
But it pleased the Lord that my wife mended again; and.
Oh! how easy I was after I had given up all, and my jail was made a pleasant place to me,
for the Lord in mercy was with me, so that I even sang a living song of praise;
for to him praise is due forever more!

Friends at London, in brotherly love,
sent down an habeas corpus to have me up to appear in London,
where I went to please them; for Nichols had not hit the law right,
but the court at London would not let me have law for my money at that time.
I was very uneasy until I came to the temple and heard what
tricks the priest`'s party and Nichols had done;
then I threw it up, and resolved to wait the Lord`'s time to bring me out,
as he had been pleased to appear to me.
The word of the Lord came to me.
Be content, and I will bring you out with honour.
Upon which I came back to prison, and lay quietly till king James set me at liberty.

After this that jailer went out, and another came in, who was very civil and kind to me,
and also his wife.
Towards the spring my eldest son John, died.
I obtained liberty to go to see him, but he died that night after he had seen me.
Some of his last words were,
that he hoped we should meet where they-- meaning bad men--should not part us anymore.
The day after he was buried, I left my wife and went to prison again.

The priests were pleased that I was in prison;
and two of them meeting in my inn at Tideswell, priest Wilson said to Fern,
with whom I had the dispute at Baslow,
Sir, I can tell you news:
What news? said Fern;
Why, said Wilson, Gratton is in prison.
I am glad of it, said Fern.
These are the hirelings that show their envious spirit, who spare not the flock of Christ!

This year I wrote an epistle to the yearly meeting in London, which is as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear friends and brethren,

In the pure unchangeable truth do I dearly salute you all;
who are truly kept faithful in and by the power of God to his glory:
who has in his endless mercy called and chosen us
to bear testimony to his eternal power and godhead,
who is God over all the gods of the earth, which are but as grass,
which soon wither and come to an end.

You, dear friends, who dwell in the power of God, the mountain of true holiness,
and in the unchangeable light,
that is the same at this day which it was at the first of its breaking forth in us,
is my love at this time freshly unto.
And I feel you near and dear to me as ever.
You whom God has made pillars in his house, honourable vessels in his hand,
fitted for his service, my soul honours and highly esteems in the Lord;
knowing right well,
that it is your food and drink to do the will of your Father which is in heaven;
and your hearts are gladly carried on in your Father`'s business.
You can truly say that they, and they only, are your brethren and sisters,
who are knowers and doers of the will of your Father which is in heaven: for God,
even our God and Father everlasting,
has raised us up by his own arm and brought us forth in his own light, life and power,
not to do our own wills, but his.
Blessed be his name! his own people delight to live under his government,
and love his reign, and are not a little glad to feel the increase of his kingdom,
in their own particulars, and to behold it in others.
For this, dear Friends, is a travail known in every upright heart,
and a weighty concern upon the honest-minded in all the churches of the saints,
that nothing may be allowed or permitted that hinders the increase
of the kingdom and government of Christ Jesus our Lord.

For this cause, with others I might mention,
I know it is a thing well pleasing unto the Lord, that you meet together,
who have cheerfully a weighty care upon your spirits,
for the prosperity of the eternal Truth, which is truly precious unto you;
that you may in the wisdom and love of God, through his eternal power,
and in the spring of life be truly carried forth
as one man to stand up for the cause of God,
and enabled to discharge your spirits of that weighty service which lies upon you.
Oh! how largely has the Lord our God made it manifest,
that this your meeting is well pleasing unto him,
by giving you his presence in such a powerful and glorious manner,
as is beyond my ability to declare, and has sealed it in my heart,
and I am sure in your hearts, that it is a right good and honourable thing;
and declares to all the world, that though we be of several counties of this nation,
and of several nations, yet are we one body, in one spirit and mind; and our unity,
love and concord remain fresh in that life and light which never alters,
and is the same at this day that ever it was.
Therefore the enemy rages and envies our prosperity in the blessed Truth,
and seeks every way to hinder the increase of the kingdom
and government of our Lord and Saviour Jesus Christ,
to whom be glory forever!
The Lord rebuke him and chain him down and tread him under our feet.

I earnestly breathe unto the Lord our God,
to give you a good soul-satisfying opportunity, according to his customary manner,
and I believe he will do it, and fill your cups full, yes,
and make them overflow abundantly,
to the joy and consolation of every sincere heart among you;
and the Lord fill you with the spirit of judgment,
that you may be as helps in government.
Judge for God, and set true judgment on the head of transgression and transgressors,
wherever they are found, and so clear Truth,
which is clear from scandals and scandalous professors of it, that God may be glorified,
and all his enemies who will not that he should reign over them,
be brought down and slain before him, that he over all may be exalted,
who alone is worthy--God blessed forever: amen.
Dear brethren, I can truly say I am with you in spirit;
and my love springs freshly to you, and I should be glad to be with you personally,
but could not get leave;
so as a token of my dear love and true unity unto you and with you,
it was in my heart thus to write: and in this I remain your dear friend and brother.
Everlasting praises be given to our God forever.
Amen.

Written in Derby jail, where I am a prisoner for the Truth`'s sake.

[.signed-section-signature]
John Gratton.

[.signed-section-context-close]
22nd of the Third month, 1683.

--

After some years the jailer gave me leave to go home sometimes, and stay some weeks,
but it displeased the priests and apparitors.
And one time, I being at home, a Friend who was to be married came to me,
and was earnest with me to come to his marriage, saying,
he believed there would be a great service, for many people of the town of Chesterfield,
where he had been an apprentice, would be at it.
Therefore I thought to go, but that night after he was gone, as I sat in my own house,
an exercise fell upon me, so I turned in my mind, and waited to know the cause,
and the word of the Lord came unto me, saying.
You must not go to this marriage, for the apparitor will be there;
but you must go to Derby to the jail tomorrow.
I went to bed very sorry that I must go to Derby so soon,
because I had leave to stay at home some weeks longer.
I told my wife of it, and questioned whether I should sleep, yet through mercy I did,
but when I awaked the next morning, it remained with me till I went.

When I came to Derby, the jailer was at the Bowling-green;
I told him I was come to see them, at which he was glad, and bade me go down,
and he would follow me.
When I had been a little time at the jail, there came two high priests,
and one called a gentleman with them, to see me, and asked for me; so I came to them,
but when they saw me, they had nothing to say to me, only the man who came with them,
whose name was Ouldershaw, and knew me well, to cover the matter, for they called for me,
as I suppose, as if they were sure that I was not there,
put himself to talk a little with me, and framed some discourse about religion;
but he was soon silent, and was not able to withstand the Truth,
but the priests said nothing, but paid their shot and went away.

When they were gone, the jailer rejoiced that it was so ordered,
that I was there so ready to be seen by them, and said,
he would not for forty pounds but that I had been there that day,
for one of the priests was the chief priest of Derby town, and the other one very high;
and he was so pleased, that he let me go home again the same day.

Thus the wicked plotted against the just;
for we perceived their design was to have advantage
against the jailer for giving me liberty,
and so have got me to be kept close prisoner,
and then they hoped some relation of mine would have given them money for my release.
I suppose they had some information that I was expected to be at the marriage aforesaid;
and they laid the design so, that the apparitor went to the marriage to catch me there,
expecting to find me preaching, for he brought a justice with him to the meeting,
called Gladman, one who knew better than he practised, who asked for me;
and the justice took hold of R. C. to pull him out of the meeting, but slipped his hold,
and fell upon a form, and from there to the floor,
and there lay till Friends helped him up.
Those priests were to have evidenced that they came
that day to the prison and called for me,
and that I was not there.
But the good God disappointed them, and ordered me to be at the jail,
and not at the marriage: but the apparitor informed against the meeting,
and Friends were fined; one Friend twenty pounds for preaching,
which must have been my lot had they found me preaching there,
and the rest five shillings a piece for hearers.
So they distrained on G. H. for twenty pounds, and Friends for five shillings,
but the Lord saw all their plots against me, and in mercy delivered me that day;
neither did my jailer suffer for his kindness to me.
Oh! what a manifestation of the Lord`'s great love was this,
for which I was not able to the full to return the praise
and humble acknowledgments that are due to him,
for his mercy and fatherly care, who knew the designs of our enemies, and prevented them.

Though we were ignorant and knew nothing of this plot,
yet the Lord in mercy revealed it to me by his good Spirit,
that I should go to the prison.
Oh! what a tender Father and wonderful Counsellor have we;
heaven and earth are full of his majesty, and his power is over all.
Let the whole creation, and my soul, with all that is within me praise the Lord,
for his mercy endures from generation to generation.
He is God and changes not--the same today, yesterday and forever.
Therefore his people are not consumed, though the sea rage,
and the beasts of the field roar,
yet the sheep and lambs of the flock of Christ Jesus are saved,
and the lions and bears slain by him, who has all power in heaven and earth,
and will deliver all that truly trust in him.
David said, "`Why do the heathen rage, and the people imagine a vain thing?
The rulers take counsel together against the Lord,
and against his anointed;`" whom the apostle remembered with joy: Acts 4,
18 to 34. Read it and take courage, you that love our Lord Jesus Christ in sincerity,
and fear not man; for, if God be for us, who can be against us?
Neither men nor devils can hurt us, though they may tempt and try us;
yet if we follow the Lord, he will help us in time of need.
My chief end in writing these remarkable things is,
that others may take courage to trust in God, and be obedient to him in all things,
without fearing man, who is but as grass.

While I lay in prison, I sometimes spoke out of the window to the people,
and many of them were loving and friendly to me, and some young men were convinced,
among whom the jailer`'s eldest son was one,
who came finely forth in obedience to the Lord, for which his father was angry,
and turned him out of doors.
He was likewise offended with me,
and said he would put me in the dungeon and lock me to the wall.
But he never did; for he would sometimes seem worse than he really was,
for he loved me more than he made a show of, and the liberty he gave me declared it.

One day I was concerned in mind for his son, for he got little trade in Derby,
for the town was envious, and many of them seemed to turn from him,
and would not trade with him, because he was turned to the Truth.
His father was uneasy,
for some would have had the high sheriff to put him out from being jailer;
but it came into my heart to make the jailer a motion,
that if he pleased to give me and his son leave, I would go with him to London,
and place him there.
I went down and told his wife, and she told her husband, to which he consented;
upon which I helped his son what I could off with his goods,
then I took him with me to London, and placed him with an honest Friend, George Watts,
where he did well, for the Lord gave him favour in the sight of Friends,
and he grew in the Truth;
and after some time he found his mind engaged in affection toward a sober young woman,
of an honest family, a Friend;
upon which he came down to have the consent of his parents, to proceed in marriage:
and now I must go up again, which I did, and liked the young woman well; so they married,
and he went into partnership with a Friend in trade, and grew rich every way,
and the Lord blessed him; and after some time his father went up to London,
and saw how his son lived,
and confessed that I had done more for him than he could have done.

One time, having leave to go home for some time, to see my wife and family,
it fell out so that Robert Meller, of Whitehough in Staffordshire, died,
who had been an honest Friend in his day, and a noble standard in suffering times;
his wife was also a sincere-hearted woman, and his son John a very honest Friend.
They hearing of my being at home, sent and invited me to come to his burial;
and though I was sorry for the loss of so faithful a Friend,
yet was I desirous to go to his burial, thinking there would be many people,
for he was beloved both by rich and poor, and of good report among men of all sorts.
But I being a prisoner, was careful the jailer might not be blamed,
or turned out of his place on my account,
for both he and his wife and children loved me well, and were very kind to me;
upon which I waited upon the Lord, desiring to know his mind, whether I should go, or no.
Then I felt I might go;
though I had a sense there would be danger of meeting with some trouble,
but how or which way it would come I did not know.

When the day came I went, and many people were there,
many of them people of note and figure in the world,
and the high constable of our hundred, to whom Robert was uncle.
I was not easy in my spirit to stay at the house,
but it was in my mind to go to the graveyard,
and not to stay till the corpse was carried from the house;
upon which I left the people at dinner, and went away,
and when I came at Basford town`'s end, I overtook two men In black raiment,
who opened the gate for me, but as I went on,
it rose in my heart that they were informers; they went on also past the graveyard,
as though they had been going further,
though I knew there was no road that way which they went.
Then I slipped off my horse and went to a style to watch them,
and saw they went through a village into the Friend`'s ground who lived there,
and lay down under a hedge till the corpse came near;
when they arose and put themselves into the, crowd,
all which I saw and was exercised what to do,
whether I should go into the graveyard or no; for if I should go,
I knew not but my keeper might be turned out of his place,
and there were three public Friends besides, namely, W. F., J. H.,
and J. J. So I humbly waited on the Lord for counsel,
if in mercy he would please to teach and help me to do his will at that time;
and as I waited and walked about, the people came with the corpse,
and it pleased the Lord to encourage me to go to the grave and all should be well;
whereupon I went, where my mouth was opened to speak to the people,
and the Lord`'s power was with me, and after I had done I went into the Friend`'s house,
and sat down and kept my coat about me;
but some strangers came in under pretence of lighting their tobacco,
and asked the Friend`'s maid who I was; saying, what a brave man they had heard:
wishing they could do as he had said.
I sat by, and they did not know me again, but asked my name and where I dwelt;
and she told them, by which they got their end.

Now the two men in black proved informers, the one of them was a priest,
and the other a schoolmaster, as I heard afterwards.
They informed against me to the magistrates, and they fined me twenty pounds,
and the three Friends who spoke at the grave twenty pounds each, and Thomas Hammersley,
the Friend of the house, for the graveyard twenty pounds, in all a hundred pounds,
besides other Friends five shillings a piece for hearers.
Yet these informers got nothing of that hundred pounds of any of us five,
for Friends went to the magistrates, and they moderated it,
also the justices of our county refused to grant their warrants to distrain my goods,
because I was a prisoner.
The deceased Friend was a rich man, and so were his relations,
both in that county and in Derbyshire;
upon which they sent out a warrant to distrain upon the widow`'s goods,
from whom they took a mare, and few else lost much by these informers,
for the hearts of many people rose against them.

I being in another county, a warrant was sent after me to sir William Boothly,
to distrain my goods for twenty pounds, but he said, I was out of his hundred,
and he would not meddle; by this he put them off, and all was well,
though they employed a sorry attorney of Staffordshire, to go to Simon Degg,
a justice of Derby, for a warrant to distrain my goods,
but the justice told them I was a prisoner.
"`No,`" said the attorney, "`he is at liberty.`"
"`No,`" said the justice, "`he is in prison.`"
It happened that there was a prisoner by at that time, and the justice asked him,
and he bore witness that I was in jail, for I came in over night, for he both saw me,
and was with me some time in the jailer`'s house; upon which the justice said,
"`What would you have?
he is a prisoner; therefore I will not grant any warrant against him.`"

The prisoner came home in the evening, and told me,
before the jailer and his wife and many others,
what a tug he had about me at Justice Degg`'s, saying, "`One Sutton, an attorney,
craved a warrant against you,
for preaching at Robert Meller`'s burial;`" but the prisoner aforesaid, by name Porter,
affirmed that I was in prison, and so Sutton got no warrant.
When my jailer perceived that while I had been about home upon leave,
I did venture to go to this burial, he cried out, saying,
"`You will undo yourself and me too.`"
But I looked on him, and said boldly as it arose in my heart, Man, never fear,
for you will suffer nothing for any kindness you show to me.

This was the assize time at Derby, and the high constable aforesaid,
who was Robert Meller`'s nephew, and was at the burial, told counsellor Leming,
that he could find in his heart to complain to the judge of my jailer,
for letting me have liberty to go to meetings.
Counsellor Leming told it to a friend of mine, an attorney in the town,
who wished me well, and he told me what he had heard, and who told him.
I said to him, Pray ask the counsellor, if it was not Robert Dale;
for he was at the burial as well as me: and said I, it is hard,
if we may not have liberty to bury one another, or to this effect.
But when he knew that I had marked him out, he said no more,
nor made any complaint to the judge;
for it would have been a shame for him to complain
against me for being at his uncle`'s burial.
My kind jailer had no blame, but all was well,
according to what was said in my heart when I went to the grave-side,
that all should be well.
The devil was not permitted to do so much mischief as he would have done;
and the Lord comforted my soul through all these exercises; glory,
honour and praise be given to him, who never fails those who truly trust in him.

After some time I went to London again, and was there when king Charles died,
and his brother came to the crown, who, after some time,
set all that were in prison for conscience sake, at liberty.

While I remained in prison, I had some discourse with the Papists,
who were in prison with me, about several things.
The first time the popish priest began with me thus;
the jailer being ill I went down to see him,
and when the priest heard I was with the jailer, he came also, with about eight debtors,
who were civil men, being well brought up, and they came to see the jailer,
and being pretty cheerful with the old man, the popish priest broke out, and said,
"`Well may I be cheerful, who suffer for the Truth,
when I see how cheerfully some men suffer for error.`"

There were none but he and another Papist, and I,
who suffered for our profession of religion, so that I saw he struck at me, and told him,
there were none at that time who suffered for their religion
but him and another of his own mind and me,
therefore said I, it must needs be me you mean, that suffers for error.
Either prove your charge, or own your fault, for I am not willing to sit down with it;
telling him, that if he could make it appear that I suffered for an error,
I would take him for my friend, for I was not willing either to live or die in error,
if I knew it.

Then he would have heard no more of it,
but I was not willing to pass it by and let him go so; for the charge was great.
Prove it, said I, or confess your error.

So he asked what we must be tried by; it was answered, By the rule of the church.
He acquiesced with that, and so did I. Then I asked him what that rule was;
but he seemed to evade and would not answer; but one that sat by,
said it was the Scriptures.
He said no: then I asked him again, what he said the rule was; to which he made no answer.
Is it the pope?
said I; "`No,`" said he.
Is it the church?
said I; he answered no: and so did I too; for the church was to be ruled by the rule,
therefore could not be the rule.
But said I, What do you say is the true church`'s rule?
But he seemed unwilling to answer; but being urged, he said tradition was the rule.
Tradition! said I, but what was the rule before there was tradition?
for there must needs be the elders, before there was the tradition of the elders.
And said I, The rule is a firm, stable, standing rule,
from the beginning of the world to the end, that alters not or changes,
which cannot be added to nor taken from.
All this he seemed to have but little or nothing to say against.

The company desired me to tell them what I believed this rule was.
And in answer to their request, I told them; "`It was the Holy Spirit,
the Spirit of Truth, which was in the beginning, and was God, and is God,
and changes not; and since our Lord Jesus Christ suffered death for us, and rose again,
this Spirit is poured forth upon all flesh: see Acts 2. This is that which guided Enoch,
so that he obtained testimony that he pleased God.
This has been the guide, rule and leader of all the patriarchs,
prophets and the holy men of God, who spoke as they were moved by the Holy Spirit,
or Spirit of Truth, which leads and guides the true church into all truth,
and all true worship is in it.
And as many as are led and guided by the Spirit of God,
they are the sons and daughters of God.
This was and is the true church`'s rule; and if any man have not the Spirit of Christ,
he is none of his; so this that is the guide of the church, must be the rule;
he that works by a rule is guided by it and ruled by it.
This is that which baptizes men into the church or body of Christ;
of which the children of God are born, and are nourished by, so that it gives them life,
and inspires them, and gives them understanding,
manifesting to every man that which is for his profit and welfare, and is freely given.
The apostles were ministers or servants of it; this brings men into the adoption,
and enables them to call God Father, and to say truly, that Jesus is the Lord.
It directs men to obey, and enables them to do the will of God;
this is grace and a free gift to all, and if they will,
they may come and drink abundantly of it, for it is a fountain of living water.
Since men have turned from it, and run after blind guides,
they oppose it and one another, and are confounded!
Having lost the rule, the true guide, they cry, Lo here, and lo there,
and are out of love and charity one with another, and one is for one head and ruler,
and another for another head; so every head would rule,
and there being many heads and horns, even to admiration,
they are pushing at one another,
and in Babylon is found all the blood of the saints and martyrs of Jesus;
but the true church is full of love and good will to all mankind:
with much more to that purpose.`"

Upon this discourse the company believed that the Spirit of Truth was the rule and guide;
whereupon the popish priest desired that he and I might be at peace,
and would have no more discourse.
