== Chapter VI

I was a prisoner for the gospel`'s sake here above
five years and a half before I was set at liberty,
by king James 2. I was discharged in open court, the 23rd of the first month,
1685-6. Then I went home to my wife, but after I had stayed a while,
I was concerned to visit friends, and travelled through most parts of this nation,
except Cornwall, and was also in some parts of Wales.
I had also many meetings in and about Eastwood, Nottinghamshire, and many were convinced,
and became obedient to the blessed truth.

But the priest of Eastwood hearing a great rumour about Friends,
as also that many of his hearers left him, bade his son who was a priest also,
and sometimes preached in his father`'s stead, to preach the same doctrine which I did;
but when he went about what his father advised him, he was so confounded in his matter,
that he could not go on.
It happened one day, that I had a very large meeting at the house of Luke Hanks,
where I heard that this priest of Eastwood should say I stole his sheep from him,
meaning some of those who had been his hearers.
After meeting I went to a friend`'s house, but that night the priest sent his clerk,
desiring me to go to his house, where I went, and several friends along with me.

When we came there, we were invited to sit down, which we did,
and sat a while in silence; until the priest of Heynor, who had followed us there,
spoke to the priest of Eastwood, saying, he perceived that I was sent for to him,
that he might speak with me; upon which the young priest asked me,
how I was called to be a preacher.
But before I answered his question, he added, I grant that a man may be rightly called,
though not of God; for, said he, the king`'s call is sufficient.
At which a friend, who was present, said, I suppose this king has called none of you.
No, replied the priest, I believe he will call you before any of us.
I then spoke, saying, I deny that any man can be rightly called,
if he be not called of God, as was Aaron; and this I was willing to prove by Scripture.
The priest of the house laboured to help his son out,
but he run himself into the same snare,
for they were not able to prove that any man was rightly called to preach,
unless he was called of God.
We talked further till they were both silent and confounded;
in this silence a concern came upon me,
on which I stood up and preached truth among them, and when I had done,
the priests gave me their hands, and we parted friendly; when we were gone,
the priest`'s wife was angry with them, saying, they sent for me like fools,
and let me go like fools; but if ever I came again, she threatened,
that she would either burn or scald me.
After this I heard that the priest of Heynor fell into great trouble of mind,
and was confounded in his pulpit.

I visited Friends in Lancashire, +++[+++and several other parts]
and the Lord was with me in his great love and mercy,
else my travels had been tiresome and unpleasant, but the Lord helped me many a time;
yes, the living know it, and met with him to their comfort,
else meeting with me could have done little, tor the work was the Lord`'s,
and he wrought in us and for us, of his own good pleasure; glory,
honour and praise are wholly due to him.

After this I went into Cheshire, and to Chester again, where I had been exercised,
and where there was now more openness than formerly.

I went to Chester several times after, and had good meetings there,
through the Lord`'s goodness and mercy, who made them so with his precious presence,
according to his blessed testimony;
that wheresoever two or three are met together in his name,
there is he in the midst of them.
This I have witnessed many a time; for if the Lord had not been with us,
we could have done nothing without him.
He was mouth and wisdom to us, and gave us to understand Scripture,
and also the motion of his holy Spirit, inspiring us by it; for we spoke as it moved us,
and gave us utterance.
Renowned and exalted over all, be our gracious God;
for we came not with words of our own wisdom,
or with words which man`'s wisdom teaches or taught us,
but with words which the Holy Spirit gave us, comparing spiritual things with spiritual.

I went to most meetings in the county of Cheshire; and a fine people there were,
and much love, unity, peace and concord were among Friends.

After this I travelled in several counties in England, both east, west and south;
and through other counties northward;
as Worcestershire and Staffordshire in my return home,
and found Friends in great love and unity, and many were convinced.
Truth prospered, and we were sweetly refreshed and comforted together;
for we were a help and a strength one to another, and the body edified itself in love;
blessed and praised be the name of our God forever.

I went much abroad to meetings, and ran to and fro to the utmost of my ability,
in most parts of the nation, preaching the gospel freely, and also travelled into Wales,
and through great part of it; and had many good meetings there.
We were in great danger in passing over the water at Aust into Gloucestershire,
but through mercy, got safe to John Bolton`'s, at Ouldstone,
and visited most meetings in that county.
I was at Frenchay, and from there to Bristol,
and was at many good meetings in Somersetshire, and in Devonshire, as far as Exeter,
where were a fine meeting and a house newly built;
and I travelled through several counties to London.
The Lord in great mercy favoured me with his power and presence,
to my great comfort and joy.
After the yearly meeting at London, I went into Hertfordshire and Essex,
and to and fro in Suffolk, Norfolk, as far as Yarmouth, and back to Norwich,
and up and down in that county to Downham and Lynn, and into the Isle of Ely,
Cambridgeshire, Huntingtonshire, Northamptonshire, Leicestershire and Rutland,
into Lincolnshire, to Boston and Lincoln city, and through most of that great county.
So into Nottinghamshire, and then into Derbyshire home.
Having travelled in great love, many in this journey were turned to the Lord,
from the evil of their ways, as at many other times and places, where I travelled,
and though I often came home much spent, weak and weary, yet I had my reward with me,
my sheaves in my bosom, and usually was soon better when I had rested a while.

I had it upon me to go and visit Friends in Scotland; and accordingly I went by Halifax,
Leeds and York, where I met Thomas Aldam, who accompanied me.
We went to North Allerton, Yarm, Stockton, Bishop Aukland and Durham;
from there to Newcastle upon Tyne, where we had great meetings; was at Sunderland,
and many places in Northumberland, which I cannot name.
We came to Berwick, where the rude people disturbed the meeting, breaking the windows,
but a lady who dwelt in Northumberland, being there, went to the magistrates of the town,
upon which the rabble were rebuked.
Next day we went to Kelso, and had a quiet meeting.
James Holliday went with us to Edinburgh,
where we were at their yearly meeting for that nation,
and it was a comfortable opportunity; the next meeting we had was at Montrose;
we had also another meeting before we came to Ury,
where the widow of Robert Barclay dwelt.
There we stayed several days, in which time I observed,
that when her children were up in the morning and dressed,
she sat down with them before breakfast, and in a religious manner waited upon the Lord;
which pious care and the motherly instruction of her children, when young,
doubtless had its desired effect upon them; for as they grew in years,
they also grew in the knowledge of the blessed Truth,
and since that time some of them are become public preachers thereof.

From there we went to Aberdeen, and found a fine meeting of Friends,
and stayed there some time; from there to John Forbes`'s, and to Cashore, Kingswells,
and back to Aberdeen, Ury and Montrose, Dundee, Leith and Edinburgh,
at which place they stoned us, when we were quietly in the meeting.
From there to Lithgow, and so to Charles Hambleton`'s, the duke`'s servant;
from there we came to Durand, and a town where there was a meetinghouse,
in which we had a meeting.
From there to Glasgow, where the people were wicked, and from there to Hambleton,
where we had a good meeting; so to Argyle and Douglass, and to one James Wood`'s house,
where we had a meeting; and he came with us by Dumfries into England.
The Lord in mercy helped me mightily with his heavenly power,
and gave us many precious meetings up and down in that nation,
though I felt the Scotch people in a bitter, envious spirit in several places,
and we were in perils twice, both at Edinburgh and Glasgow, where they stoned us.
At Edinburgh a stone hit me as I was declaring in the meeting, but did not hurt me.

After our return out of Scotland, we had many good meetings in Cumberland,
which were comfortable seasons to us; for the Comforter was with us,
and mightily helped us from meeting to meeting.
From there we travelled to Kendal, the Height, and Swarthmore,
where we had a fine meeting; we were also at Lancaster,
from which place we returned back again to Kendal,
and passed from there to Thomas Camm`'s, and into Yorkshire,
to John Blakling`'s near Sedbergh, and by William Ellis`'s to Skipton,
from which place we went to Leeds and Warnsworth, where I left my companion, T. Aldam,
and returned home, and there found my wife and family well, to my great comfort;
praised be the Lord forever.

Friends in Scotland and elsewhere were very loving to us,
and fine living meetings there were in that nation.
I felt them in the life near to my spirit,
in which the living know one another beyond words,
and I hope and believe the Lord will have a great people there in time to come,
though the enemy be angry, and would hinder the spreading of the holy Truth,
by the enemies thereof; yet his weapons are but carnal, silly and weak.
I desire many Friends may think of that nation,
and in the will of God give up to visit it; for there is a zealous professing people,
and were they but brought to the knowledge of the Truth,
I believe very many would be zealous for it.

I found that those two worthy men, Robert Barclay and Patrick Livingston,
had left a sweet savour behind them, and the removing of them, especially the former,
was a great loss to that nation, and cause of great mourning to Friends there,
and also to others elsewhere; but blessed be God, he, Robert Barclay,
has left a hopeful family behind him; praises be given to the Lord forever.

In this year I had a concern to visit Friends with the following lines:

An Epistle to Friends in Scotland, Written at Monyash, the 22nd of the Eleventh Month,
1694.

Truly beloved friends and brethren,

With pure love unfeigned, which springs from the Fountain thereof,
do I tenderly salute you, and all true Friends with you,
feeling you near and dear to me at all times when I remember you;
and am glad that the God and Fountain of all our mercies,
has reached forth so plentifully to your immortal souls,
and made you so largely to partake with us of his free grace and gift of eternal life,
so that your portions and measures hereof are very large, to the mutual joy of you, me,
and many more, for which we are deeply obliged to be truly thankful unto our God,
from whom every good and perfect gift comes.
Unto him alone we ought still to look, that as men in need of continual supply,
we may experience his bountiful hand to minister freely to every one of
us for it is he alone that both makes and keeps us and all his,
truly living, faithful, fruitful and serviceable in this blessed day of his mighty power,
wherein as we abide we have fellowship both with him and one with another.
The travail and earnest desire of my soul to the Lord is,
that we may all be preserved to the end in true self-denial, humbly,
meekly and innocently walking in this glorious day of gospel light, life and power,
so as we may help one another`'s joy;
and the blessed unity of his holy Spirit being lived in, no man can take our joy from us,
which is only possessed by us as we abide in him, who is life eternal,
to whom be praise given by us and all that partake with us, forever, Amen.

Many are the exercises, temptations, sufferings and tribulations which attend us here,
both within and without.
Well may we say, our God is God and changes not,
else before this we might have been destroyed, for we are poor, and weak,
and insufficient of ourselves, to think a good thought.
The enemy knows this, and labours to deceive us with his subtle wiles;
for if we keep not in him who is our wisdom, righteousness,
sanctification and redemption, we have no wisdom of our own, or righteousness,
or power to save ourselves at all.
Oh, the goodness of God to us is undeclarable!
And we see as much need as ever to keep looking unto him for help every moment,
for all our time is a time of need,
and if the Lord was not with us we could not bear up against the enemy`'s floods,
tempests and raging violence and storms, that attend us in this perilous pilgrimage.
But glory, honour, praises, and high returns of humble and sincere thanks,
be given to our great and merciful God.
He is with us, and is the same he was in ancient days,
when he carried Israel through the Red sea on dry ground,
and gave them to behold his miraculous deliverance,
and saved them out of the hands of their many enemies, who sought to destroy them.
The sense of his love, and the experience which I have of his goodness,
tenders my poor heart, and bows my spirit before him; and I hope you partake with me,
and will also feel with me beyond words or writings.

Dear friends, I desire we may all be mindful of Him who is our rock and refuge,
keeping near him always, not forgetting the Lord.
Here is divine light, for he dwells in it, and in him is no darkness at all;
here we see our states as they are, and that what we are, we are by his grace.
Here it is we meet with fresh pastures of life, and feed together,
where the enemy cannot come, nor the lofty, unclean Edomite approach.
My heart is glad, to feel love run so freely towards you at this time.
I do not write these things as though I looked upon you not to know them; no, if I did,
I could not be so free and open to you, but a little to remind you,
and in these few lines to confer with you in love; for it is the fruits of dear,
unfeigned love, I here salute you with, as men that I can say are of my flesh and bones,
and members with me, of that sweet, harmonious body, of which Christ Jesus is Head,
Lord and King: worthy is he to reign, it is his right;
and he that would be great among you, must be least of all;
and this is the Lord`'s doing, and it is marvellous in our eyes.
Oh! that we may see this low state experimentally,
for in that place many have met with him, and been met with by him,
who despises not the low state of his servants and handmaids.
Surely it behooves us to be low, for our teacher is meek and lowly in heart.

My dear and truly beloved, the meek are most filled with love,
even that love which is not puffed up, seeks not its own in that sense the apostle means,
but leads us to seek the good of all,
and the things that are Jesus Christ`'s. I pray that we may always dwell in this love,
and then we shall be sure to love one another.
I was glad in heart, when I felt your love to me in the Lord, when present with you,
and to my companion also;
and also when I felt your love kept fresh to us after our departure from you in person,
not in spirit, and that you remembered me in your prayers;
I desire you would still remember me, and I hope I shall not forget you.

I desire you as a brother, to keep up the good order of the blessed Truth among you,
and let not your monthly and quarterly meetings be neglected,
and take care of the whole church of God, in your nation,
and delay not to help one another.
For God Almighty has set up his standard,
and his controversy is proclaimed against all unrighteousness.
I know help was lacking in some places when I was with you;
the Lord has gifted some to be helps, and to rule well in the church:
and we know the apostles in their travels left the brethren decrees to keep,
and took care of the churches as they travelled, and went to see how they did.
I hope you will take it well that I make thus bold with you,
and will feel my tender love to you.

I was glad when I saw a copy of your letter to G. K.,
yet sorry to see the answer to you from him, or his wife, or both; he must, it seems,
be made manifest.
I desire you may grow in the heavenly root,
and multiply to the glory of him that has grafted you into it.

My dear friends, in every respect be truly obedient unto the Lord,
and may he by his own power strengthen,
establish and root you deeply in his blessed Truth.
To him I tenderly commit you all.
He is God Almighty even now as in Abraham`'s days; to him be praise, worship, honour,
glory and renown forever more.
Amen.

Read this to all as you see a service, and send honest Bartholomew Gibson a copy of it,
and let him know my dear love is to him and his wife, Francis Soneman,
and Friends in Edinburgh.
Let copies of it be sent to all in Scotland.
I thank God I am pretty healthy, but not strong in body.
So with my true love to you all, I am your sincere friend in pure love,

John Gratton.

I stayed about home some time, where I had many meetings,
and there was a fine increase in the number of Friends.
But many of them went into America, about forty from our monthly meeting,
and some others, which lessened our meeting pretty much.

After some time it came upon me to go and visit Friends in Ireland;
several of whom had been in England, and a love lived in me to them.
I gave up to go, and went to Westchester in order to it,
but found there was an embargo laid upon ships, that they must not go out.
When we could not go for Ireland, we went to Shrewsbury, and so down into Herefordshire,
R+++.+++ Needham being with me, and to the yearly meeting in Wales, at Ponty Moyle,
in Monmouthshire.
A fine meeting it was, and after at the Pont,
and so over the passage into Gloucestershire, to Bristol, and into Somersetshire,
to Richard Vickris`'s, at Chew, John Whiting`'s at Wrington,
and William Laurence`'s at Axbridge, and back to Bristol to the yearly meeting there,
and from there to the yearly meeting at London.
After that I returned home with my wife, and stayed about seven days,
and then set forward again for Ireland with Godfrey Newhall, a Friend of Yorkshire,
and went to Whitehaven in Cumberland for George Rook`'s company, and so to sea;
the winds were somewhat contrary, and we were in some danger of our lives;
but we put into the Isle of Man, and at last arrived safe at Dublin in the fifth month.

We had many precious meetings in that nation, especially their province meetings,
and Friends were generally in sweet love, unity, peace, concord and order,
and good government among them, and great love and care of one another`'s families,
the poor and youth in all respects.
When we had been at all the meetings of Friends that we knew of in the nation,
or seen some Friends of all the meetings, and were clear to come away,
we left them in true love, being well satisfied in visiting them;
and took shipping at Dublin, and came to Holyhead, and through Wales to Westchester,
and so home.

Many Friends in Ireland had a great care upon them in the over-sight of the flock,
watching over them, that Friends be careful in all respects,
to keep their profession without blame, and that none run inordinately after the world,
or break in other men`'s debt;
to prevent which they are advised to labour lawfully for the maintenance of their families,
providing things honest in the sight of men; by thus watching over one another,
doubtless some things are prevented,
which otherwise might prove a disreputation to our holy profession.

[.asterism]
'''

After his return from Ireland, he kept no exact account of the residue of his travels,
though he visited Friends in various counties, labouring in the work of the gospel,
as he found drawings thereto, though in his latter days he was afflicted with disease,
which much abated his natural strength; nevertheless he came several times to London,
and particularly in the winter, 1699.

He also came to the yearly meeting in 1700;
and in his return home had many good meetings in the way,
being accompanied by John Cade to Blyth, where his wife met him.

The next year he travelled as far as Bristol, and was at their yearly meeting.
From there he went to Bath, and travelled up to London to the yearly meeting,
which fell in the fourth month, 1701.
It was a large and precious meeting: after which he returned home.

He also came up to the next yearly meeting London, 1702.
At this time he brought up his Treatise relating to Tithes,
which was an answer to a letter, entitled, The Clergy`'s Legal Right to Tithes, etc.

In the year 1703, he came again to the yearly meeting,
visiting Friends in many places as he came.

The 26th of the second month, 1704, he set out again for London,
visiting Friends in many places as he came, as in Nottinghamshire, Huntingtonshire,
the Isle of Ely, and a great part of Norfolk, and had several meetings in Suffolk,
the last of which was at Ipswich, from which place he came to Colchester,
and was at their meeting on first-day; after which he visited several meetings in Essex,
and then came to London to the yearly meeting;
having travelled in this journey three hundred and thirty-four miles,
according to his own account.

After his return home at this time,
there is no account of his travelling for two or three years:
greater weakness growing upon him, it is probable he continued about home,
visiting Friends as he was able.

In 1707, he disposed of his estate at Monyash, and dwelt with his son Joseph some time;
then he went to visit some Friends in several adjacent places, his wife accompanying him,
though both of them were aged and weakly.
But after they returned home, his wife growing weaker and weaker,
departed this life the 4th of the tenth month, 1707; dying in peace with the Lord,
leaving a good report behind her, among those who knew her.
The account of her death he gave himself, saying,
a very comfortable wife she had been to him nearly thirty-eight years: adding,
that she had never hindered him from going abroad to visit Friends.

In the year 1708, he took a journey to London again, and went into some parts of Essex,
Surry and Kent; after which he returned to London again, where staying some time,
he was taken ill, and weakness increasing upon him, he removed out of the city,
for the benefit of the air, to Richard Richardson`'s, near Uxbridge,
where he was carefully attended for three weeks, in which time,
several Friends of London went to visit him.
From this place Daniel Wharley took him to his house; from there he went to Ailsbury,
and by small journeys he got home, Richard Needham accompanying him.
He continued living with his daughter above three years, being weakly until his decease,
which was in the ninth month, 1711, aged about seventy years; dying,
no doubt in peace with the Lord, and unity with all the faithful,
and is entered into his everlasting rest, among the faithful followers of Jesus.
