[short="Treatise Concerning the Light of Christ"]
== A Small Treatise Concerning the Light of Christ; to Which is Added, Something Concerning the Death and Sufferings of Christ.

Some time ago I was discoursing with a person, whom I wish very well,
about matters of the greatest weight and importance;
and he told me they heard that we preached up a new light.
This made me sorry,
and I thought it strange that we were no better known
to a person of that note and so near a neighbour;
therefore, to clear us of that scandal, and to inform sober,
moderate and friendly inquirers, and to satisfy our enemies that falsely accuse us;
and above all, for the propagating the holy Light and Truth,
which the good man prayed to God of old to send forth, Ps. 43:3,
are these few lines written; with desires,
that God in his great mercy may make them serviceable to all honest,
sincere-hearted readers thereof, to his glory forever.

I testify to all, that we believe in and preach no other light,
but that true Light that John preached and bore testimony of;
and we know his testimony is true.
"`In the beginning was the Word, and the Word was with God, and the Word was God.
The same was in the beginning with God.
All things were made by him; and without him was not anything made that was made.
In him was life, and the life was the light of men.
And the light shines in darkness, and the darkness comprehended it not.`"
This is that very light we bear witness of,
the light of eternal life that was in the beginning, and therefore is no new doctrine,
or new light.
The apostle John goes on and tells us what God sent John the Baptist to bear witness of:
"`There was a man sent from God, whose name was John.
The same came for a witness, to bear witness of the Light,
that all men through him might believe.
He was not that Light, but was sent to bear witness of that Light.
That was the true Light, which gives light to every man that comes into the world.
He was in the world, and the world was made by him, and the world knew him not.`"
Here are two Johns, one the beloved disciple, the other John Baptist, a prophet;
and both declare of the very same Light,
of which the despised and falsely accused Quakers, do now in these days bear testimony.
Well may we be bold to bear witness of it, for we know it is the true Light,
the same that these men preached in their day;
and that it has enlightened us and showed us all that ever we have done,
and that it is the Lord`'s mercy that we see this day; which Abraham rejoiced to see,
and saw it, and was glad.
Many of the prophets testified of it,
as may hereafter be showed and Christ himself does very fully and plainly speak of it,
in several places.

But first we will take notice of the prophets; David says,
"`The Lord is my light and my salvation, the strength of my life;`" and,
"`With you is the fountain of light; in your light shall we see light.`"
What plain evidence is here: he tells what the light is; it is the Lord, his salvation,
his life and strength, in whose light we see light,
and know it to come from the Fountain of Life; and Ps. 43:3, he prays,
"`O send out your light and your truth: let them lead me:
let them bring me unto your holy hill.`"
What is more desirable or more profitable than that which leads
and brings the soul into God`'s holy hill and tabernacle!
David did not despise the light, but prayed that God would send it out,
to lead him and guide him to his holy hill; he loved it,
and so do all the upright in heart.
The Lord is God, and changes not; the same today, yesterday and forever;
and they that are enlightened with the enlightenings of the Lord at this day,
do know their earthly nature has been made to tremble;
yet has the sincere soul rejoiced with trembling, and has kissed the Son,
and been glad to see the light, that is sown for the righteous;
and gladness for the upright in heart.
As Abraham did, so do all his children, rejoice to see the light of the Lord.
But some say, How do we know that David speaks of the light within?
Answer, his words are full and plain, and agree with John`'s. John says,
"`that Christ is the true Light that enlightens every man, and that in him is life,
and the life is the light of men.`"
David said, "`The Lord is my light,
and my salvation;`" so David`'s Lord is his light and salvation.

And John says,
"`It enlightens every man that comes into the world;`" so herein
is manifested God`'s universal love and good will to all men.
As it is said elsewhere, "`God so loved the world, that he gave his only begotten Son,
that whosoever believed in him should not perish,
but have everlasting life;`" even that life that is the light of men.
So the Lord in mercy causes his sun to shine upon all,
and to give light to the whole world.

There are some parts of the earth that have seen the true light of life,
and trembled too, that are not called Quakers, because, though they have seen and felt,
tasted and handled of the Light or Word of God, yet they have rebelled against it.
They are of those that rebel against the light, they know not the ways thereof,
nor abide in the paths thereof.
And there are some of this sort who walk in the form, but deny the power,
and cause the way of Truth to be evilly spoken of.
There are some that, though the light shines in them, and lets them see their evil ways,
and reproves them, yet they are so in love with the world, and the evils thereof,
that they turn away from the Lord, and from his light, grace and holy Spirit,
that strives with them; so these lie under guilt and condemnation.
Their own hearts condemn them, their heart and conscience is defiled; these see it,
and confess it, but will not forsake sin, and therefore they lie under condemnation;
as in John 3:19-20; This is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
For every one that does evil, hates the light, neither comes to the light,
lest his deeds should be reproved.
These refuse to come to the light, because they love not to be reproved, troubled,
or disquieted in their minds.
They take pleasure in sin, and to live at ease in iniquity,
and love not to be parted from the world, or its evil ways;
therefore they love darkness rather than light.

Now it is clear, that if a day of visitation had not come,
and the Sun of Righteousness had not risen and shined upon the world,
and made all things manifest that are reproved;
then there might have been some excuse made.
But upon whom has not his light shined?
Who does not know?
The Lord calls for holiness, and lets all men see what is evil, and what is good,
that they may love the good and cleave to it, and turn from the evil,
and flee all appearance of it.
Therefore cease to do evil, and learn to do well, and find mercy with the Lord.

Christ said, "`If I had not come, they had not had sin;
but now they have no cloak for their sin.`"
And again, "`If you were blind, you should have no sin: but now, you say, we see;
therefore your sin remains.`"
If it was not day, then it might be more excusable to the world; but seeing it is day,
and that the true light now shines,
therefore that man that runs in the mire and dirt of sin, and sees it,
and yet will do it, it is his own doing, and he must bear his own burden;
for he does what he knows he ought not, and leaves undone what he knows he ought to do.
Light shines, and with the light he sees it is so,
and therefore is condemned in himself justly, because he knows the will of God,
but does it not.
God is righteous in all his judgments, and just in all his ways.

Our Lord further says, "`He that does truth comes to the light,
that his deeds may be made manifest, that they are wrought in God.`"
This is the man that loves the light,
and is not willing to rest short of being approved by the Lord,
and is thankful to God that has showed him light, who has made us able to say,
his Word is a lamp unto our feet, and a light unto our path.
O says this man, "`Truly the light is sweet,
and a pleasant thing it is for the eyes to behold the sun.`"
"`O house of Jacob! come and let us walk in the light of the Lord.`"
For the mountain of the Lord`'s house shall be established in the top of the mountains,
and shall be exalted above the hills, and all nations shall flow unto it,
therefore let us trust in the Lord, that will yet choose Jacob; "`Cry out and shout,
inhabitant of Zion, for great is the holy One of Israel in the midst of you.
But woe unto them that call evil good, and good evil; and put darkness for light,
and light for darkness.`"
This evangelical prophet Isaiah, ably declares of the glorious fight, Christ Jesus, chap.
ix. 2; "`The people that walked in darkness have seen a great light;
they that dwelt in the region of the shadow of death, upon them has the light shined.`"
Was not this our state who are Gentiles; and now the light of Zion is come,
why should she not bear witness of it?
For the Light of Israel "`shall be for a fire, and his holy One for a flame,
and it shall burn;`" and, "`I the Lord will give you for a covenant of the people;
for a light of the Gentiles: to open the blind eyes,
to bring out the prisoners from the prison,
and them that sit in darkness out of the prison house.
I will also give you for a light unto the Gentiles,
that you may be my salvation unto the ends of the earth.`"
"`Arise and shine, for your light has come, and the glory of the Lord is risen upon you.
And the Gentiles shall come to your light, and kings to the brightness of your rising.`"
"`The sun shall be no more your light by day,
neither for brightness shall the moon give light unto you,
but the Lord shall be unto you an everlasting light, and your God your glory.
Your sun shall no more go down, nor your moon withdraw herself;
for the Lord shall be your everlasting light,
and the days of your mourning shall be ended.`"
Here is a testimony to the light of the Gentiles, the light of Zion, the light of Israel.
This is that true light we now desire all may come to, both high and low, rich and poor;
for it is come, blessed be the Lord our God forever more.

I proceed to the Saviour`'s testimony in John 8:12; Then spoke Jesus unto them, saying,
"`I am the light of the world; he that follows me shall not walk in darkness,
but shall have the light of life.`"
Oh! that people would follow him, and not the traditions of men,
the rudiments of the world, the commandments and doctrines of men; for all that do so,
are living in darkness, and hating the light, speaking evil of it,
because their deeds are reproved by it, and made manifest to be sinful and unrighteous,
are enemies to Christ.
He says again, "`As long as I am in the world,
I am the light of the world;`" and he has promised
to be with his people to the end of the world,
read Matt. 28.

Then said Jesus unto them, "`Yet a little while is the light with you:
walk while you have the light, lest darkness come upon you;
for he that walks in darkness, knows not where he goes.
While you have light, believe in the light, that you may be the children of light.`"
And, "`I am come a light into the world,
that whosoever believes on me should not abide in darkness.`"
Is it not cause of great admiration, that men who own the Scriptures,
should blame us for preaching Christ the Light of the world, the true Light,
that now shines in the hearts of men, and tell us that the light is conscience?
Some say, it is the light of nature, and some call it the Quaker`'s idol.

But now reader, you may see what Christ says it is: he says,
"`I am the Light of the world.`"
John says,
"`He is the true light that enlightens every man
that comes into the world:`" and the prophet says,
"`The Lord is my light and my salvation; he is given for a light unto the Gentiles,
and for God`'s salvation to the ends of the earth.`"
And Zacharias said, speaking of his son,
"`You child shall be called the prophet of the highest,
for you shall go before the face of the Lord, to prepare his ways;
to give knowledge of salvation unto his people, by the remission of their sins,
through the tender mercy of our God, whereby the dayspring from on high has visited us;
to give light to them that sit in darkness, and in the shadow of death,
and to guide our feet into the way of peace.`"
Good old Simeon praised God; "`For my eyes have seen your salvation,
which you have prepared before the face of all people; a light to lighten the Gentiles,
and the glory of your people Israel.`"
So these all preached Christ, the true light; and therefore it is no new doctrine,
nor new light, as some say that we preach,
but the very same that the Scriptures so largely and plainly testify of.

Our Lord said to Paul--"`I am Jesus whom you persecute;
I have appeared unto you for this purpose, to make you a minister and a witness,
both of these things which you have seen,
and of those things in the which I will appear unto you; delivering you from the people,
and from the Gentiles, unto whom now I send you, to open their eyes,
and to turn them from darkness to light, and from the power of Satan unto God.`"
Now here it is plain, Paul was sent to turn them from darkness to light.
Could he do it and not preach it?
No, he obeyed the Lord`'s command; and was Paul a Quaker,
or are we who are called Quakers to be blamed for preaching this primitive,
ancient doctrine?
Surely no; for God has called us so to do, and we fear not man that opposes God,
his truth and people; nor did Paul,
at whom the high priests and rulers were sorely offended;
yet he "`witnessed both to small and great,
saying none other things than those which the prophets and Moses did say should come:
that Christ should suffer, and should be the first that should rise from the dead,
and should show light unto the people, and to the Gentiles.`"
But still some may say, Is this light any where preached to be within men?
Yes; this apostle says, "`For God, who commanded the light to shine out of darkness,
has shined in our hearts, to give the light of the knowledge of the glory of God,
in the face of Jesus Christ.
But we have this treasure in earthen vessels,
that the excellency of the power may be of God, and not of us.`"

Here the apostle preaches the light shining in our hearts.
This then is the light within, and God in mercy causes it to be so,
and he that does not turn in to behold the shining of it,
but is gazing at things without him, is yet in darkness.
Though the light shines in his dark heart, yet he knows it not,
nor believes in the light, nor follows it; and therefore abides in darkness,
and loves so to do.
These love the world, and the friendship of it, but the love of God is not in them;
but the children of the light are said to be a chosen generation, a royal priesthood,
a holy nation, a peculiar people, that they should show forth the praises of him,
who has called them out of darkness into his marvellous light.
Which, in time past, were not a people, but now are the people of God;
which had not obtained mercy, but now have obtained mercy; 1 Pet. 2:10-9.

John, the beloved disciple of Christ, in his first epistle, says:
"`This then is the message which we have heard of him, and declare unto you,
that God is light, and in him is no darkness at all.
If we say that we have fellowship with him, and walk in darkness,
we lie and do not the truth.
But if we walk in the light, as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.`"
Again, "`A new commandment I write unto you, which thing is true in him, and in you;
because the darkness is past, and the true light now shines.
He that says he is in the light, and hates his brother, is in darkness even until now.
He that loves his brother, abides in the light,
and there is none occasion of stumbling in him.
But he that hates his brother, is in darkness,`" etc.
Come try all the churches, and see where this love is to be found,
and let that church be manifest that abides in the light.

In the Revelation the same apostle says;
"`And there came unto me one of the seven angels, and talked with me, saying, Come here,
and I will show you the bride, the Lamb`'s wife.
And he carried me away in the spirit to a great and high mountain,
and showed me that great city, the holy Jerusalem, descending out of heaven from God,
having the glory of God; and her light was like unto a stone most precious,
even like a jasper stone, clear as crystal.`"
And he goes on to speak of her, till he says, "`I saw no temple therein:
for the Lord God Almighty and the Lamb are the temple of it.
And the city had no need of the sun, neither of the moon to shine in it:
for the glory of God did lighten it, and the Lamb is the light thereof.
And the nations of them which are saved shall walk in the light of it:
and the kings of the earth do bring their glory and honour into it.
And the gates of it shall not be shut at all by day: for there shall be no night there.
And they shall bring the glory and honour of the nations into it.
And there shall in no way enter into it anything that defiles,
neither whatsoever causes an abomination or a lie;
but they which are written in the Lamb`'s book of life.`"

Is not here a clear declaration of the state of the true church of Christ,
and of her light, that the Lord God gives her,
and that this is wholly what the Lord God Almighty and the Lamb does freely bring her to,
and is to her; so that here is nothing of man, nor of man`'s wisdom, art or skill,
strength or power, or of any creature whatsoever.
It is not anything of that kind that can give the soul acceptance with the Lord.
He is fitting his church and people, and making her ready for himself,
as he gathers her up into his own, and places her in his holy habitation,
where no unclean thing can enter.
This is the city of God, the new Jerusalem, the free woman, the mother of us all,
who are new born babes, born of incorruptible seed by the Word of God,
that lives and abides forever.

Now it is clear, this true church of Christ being called the bride, the Lamb`'s wife,
denotes that she is really espoused or joined unto the Lord in his own love, life, light,
power and spirit, and loves and enjoys his presence, hears his voice,
is truly sensible of his love; knows his name to be as ointment poured forth,
and also a strong tower; meets in it, is saved in it, and goes to God in it;
and as she is refreshed in it, and in true rest and peace with the Lord in him,
who has reconciled her unto God by the death of his Son, and saved her by his life.
So here it is plain, the Lord is unto his people a husband, a father, a fountain of life,
light and love; of wisdom, knowledge, understanding, and all good things.
And the tabernacle of God is with men, and he will dwell with them,
and they shall be his people, and God himself shall be with them, and be their God,
and they shall live in his life, and walk in his light,
even all the nations that are saved,
or the saved of all nations shall walk in the light of the Lord God, and of the Lamb.
This is the just man`'s path; "`A shining light,
that shines more and more unto the perfect day.`"

But some may say, this is the state of the church in heaven, not on earth: answer,
it is clear,
the Lord showed unto John things that must shortly come to pass here on earth,
and that this true church came down from God out of heaven,
prepared as a bride adorned for her husband; and then it follows:
"`And I heard a great voice out of heaven, saying, Behold,
the tabernacle of God is with men.`"
So the true church is born of God, born of the Spirit, and is in God the Father,
and the Lord Jesus Christ, and has heavenly places in Christ to sit down in,
and is redeemed from the earth, and is baptized into Christ, has put him on,
and lives in the Spirit, and walks in it, is led, guided and preserved, comforted,
and enabled by it and in it, to worship God aright, and to pray aright, preach aright,
and praise aright.
So all that she has is come down from God out of heaven, every good and perfect gift.
All her fresh springs, all her strength, power, and ability; all her faith, hope, life,
light, wisdom, knowledge, joy, great comfort and consolation; all her love and beauty,
fairness, comeliness, yes, all that she has is freely given of God,
and comes down from God out of heaven.
She is the Lord`'s, and is nothing but what she is in him,
nor can do anything without him, who is her light and salvation, her portion,
her treasure, her beloved, and she is his.
Her glorying is in the Lord, her rejoicing in the God of her salvation,
on whom she leans, depends and trusts in the Lord alone, who is her helper, deliverer,
redeemer, sanctifier, Saviour and preserver, and all that she has and needs,
and is also her rock, fortress, shield, buckler, strong tower, armour, defender,
and habitation of safety.
In a word, God is all in all to his true children and people,
and is over all worthy of praise, honour, glory, worship,
thanksgiving and everlasting renown; for it is only due unto him, who is Lord of lords,
and King of kings over all, to him that sits upon the throne forever and ever more, amen.

I hope it is very clear from plain Scripture in a plentiful manner,
that it is no new light, or new doctrine to preach Christ the light of the world,
the light of men, the light within, that enlightens the soul,
and gives it to see all things that are reproved, and makes all things manifest,
as the apostle affirms; "`All things that are reproved are made manifest by the light;
for whatsoever does make manifest is light:`" then follows this advice,
"`Awake you that sleep, and arise from the dead, and Christ shall give you light.
See then that you walk circumspectly, not as fools, but as wise, redeeming the time,
because the days are evil.
Be not unwise, but understanding what the will of the Lord is.`"

When men by the light come to see all things that are reproved,
and do turn from those things, and give up to obey the will of God,
though they have long lain dead in sin and dead works;
yet now they awake out of a sleepy, secure, dead state,
arising and fleeing from it to Christ.
Then he gives more light, and gives them to know of his doctrine,
and the mysteries of his kingdom, when they are given up to do his will.
Then, to them that were some time in darkness and very ignorant,
it is given to know the things that belong to their peace, and they become light,
or lightened in the Lord, and then walk as children of light,
and bring forth the fruits of the Spirit, in all righteousness, goodness and truth,
"`proving what is acceptable unto the Lord;
having no fellowship with the unfruitful works of darkness,
but rather reproving them;`" so are become one with
him that reproved them when they were in darkness.

Therefore, dearly beloved friends and brethren,
who make profession of this holy light and day of the Lord, be careful to walk in it,
so as to give no occasion of stumbling; for the enemy watches for occasion,
and though he can find none in the Lord our light and head, law-giver, and all in all,
yet he endeavours to reproach him through us, and by any spot or shortness in us.
Those that depart from the Lord and become wicked,
"`The light of the wicked shall be put out, and the spark of his fire shall not shine.
The light shall be dark in his tabernacle; for his candle shall be put out.`"

It is sadly experienced even in these days,
that men may be enlightened and taste of the heavenly gift,
and be made partakers of the Holy Spirit, and taste the good word of God,
and the powers of the world to come,
and yet fall away and crucify unto themselves the Son of God afresh,
and put him to an open shame, or to be openly reproached by wicked men.

And as Peter says, "`There shall be false teachers among you,
who privily shall bring in damnable heresies, even denying the Lord that bought them,
and bring upon themselves swift destruction.
And many shall follow their pernicious ways,
by reason of whom the way of truth shall be evil spoken of.
And through covetousness shall they with feigned words make merchandise of you.`"
"`A heart they have exercised with covetous practices; cursed children,
which have forsaken the right way, and are gone astray, following the way of Balaam,
who loved the wages of unrighteousness,`" but,
"`it had been better for them not to have known the way of righteousness,
than after they have known it, to turn from the holy commandment delivered unto them;
but it is happened unto them according to the true proverb,
The dog is turned to his own vomit again; and the sow that was washed,
to her wallowing in the mire.`"
Jude also speaks of these: and my dearly beloved friends,
let it be our care to abide in the vine, partaking of its sap, virtue, and fatness,
that we may bring forth much fruit to the glory of him that
has called us out of darkness into his marvellous light.

Let us walk in the light, that we may have fellowship with God and one with another,
and know the blood of Christ to cleanse us from all sin.
Then shall we, in the light, love as brethren; yes, love all men, even enemies,
and be concerned for the prosperity of the holy light and truth of God,
that many may come to the knowledge of it, and be saved.

And all sober people of all sorts that may see these lines,
unto you does the love of God reach, and in my heart at this time is it felt;
let me entreat you to turn in your minds to this pure light that shines in your hearts,
to give you to discern all things, and to divide between the precious and the vile,
between him that serves God, and him that serves him not.
Let it be your choice, for it is of God, and will outlive all its opposers;
and let not the loud clamours and false accusers of God`'s truth and people,
cause you to reject the light, and embrace darkness, to choose evil and refuse good;
but mind this grace or gift that appears in you, for there is no guile in it,
nor can you say it ever consented to evil, but reproved it.
This is He that none charges justly with any evil, therefore hear him,
for God speaks by him; his love is great to all, he died for all,
tasted death for every man, and enlightens every man that comes into the world;
come and walk in him forever more, amen.
