[short="A Few Words in True Love"]
== A Few Words in True Love to all Who Believe that Christ Jesus, the Lamb of God, that Takes Away the Sins of the World, is Come the Second Time, Without Sin unto Salvation.

[quote.scripture, , Heb. 9:28]
____
So Christ was once offered to bear the sins of many;
and unto them that look for him shall he appear the second time, without sin,
unto salvation.
____

It is needful for all who believe the holy Scriptures, which testify of Christ,
to look for him as he appears the second time without sin unto salvation;
that they may know him so to appear in them, as to take away all their sins,
that being washed by him, and made clean, they may have a part in him,
a part in his life, in his Spirit, in his love, in his light, in his wisdom,
and in his power; that they may know experimentally he is in them, and they in him,
and be truly made new creatures; for if any man be in Christ, he is a new creature;
and thus by Christ be made heirs of the covenant made with Abraham.

God is faithful who has promised;
and many are made partakers of his great and precious promises, in Christ Jesus the Seed,
in whom all the promises of God are yes and amen, forever,
and are and will be fulfilled to them that receive Christ,
in his appearance the second time, without sin unto salvation;
which is in spirit by the Holy Spirit, as he promised.
It was to as many as received him, that power was given to become the sons of God,
even to them that believe in his name.
To such he said,
"`He that is with you shall be in you,`" and without him we can do nothing;
we have no strength of our own, nothing at all that is good,
but are by nature children of wrath, while we live in the lust of the flesh,
and so have need to be delivered.
But there is no deliverer besides Christ; no way, no truth, no life:
no man can come unto the Father but by him;
"`He that has him (as Scripture says) has life, but he that has him not, has not life.`"
The law did not give life, nor does the Scripture, by the letter or reading of it,
give life; for though it is a testimony of him who is life, light, wisdom, power,
God over all, blessed forever, yet it cannot give life; the life is in Him.
For as in the beginning all things were made by him,
and without him was not anything made, that was made;
so no man is sanctified or made new but by him, and they that are sanctified by him,
are joined to him; "`For both he that sanctifies,
and they who are sanctified are all of one,
for which cause he is not ashamed to call them brethren.`"

He is the true vine, the root of life; "`By him kings reign,
and princes decree justice;`" but without him men are dead in trespasses and sins,
miserable offenders, in whom there is no health, but wounds, bruises and putrified sores,
from the head to the foot, until he heals us, and quickens us by his Spirit in us,
which is the Comforter, whom he sends to guide into all truth,
and as many as are led by it are the sons of God, By him we can call God Father,
for he is all in all to the children of God: and says the Apostle, "`All is yours,
and you are Christ`'s, and Christ is God`'s:`" and again, "`You are not your own,
you are bought with a price, not with corruptible things, as silver and gold,
but with the precious blood of Christ, as of a Lamb without spot or blemish.`"

"`Behold,`" says John, "`the Lamb of God that takes away the sin of the world.`"
And John`'s disciples beheld him and left John, and followed Jesus Christ,
who asked them whom they sought.
They said unto him, "`Rabbi, where are you staying?`"
he said, "`Come and see;`" and they came and saw where he dwelt,
and abode with him that day.
This is very precious; to see him and know his dwelling place,
and to abide with him during the time which is given us to live.

Let it be your joy to abide with him all your time, and see where he dwells;
this is more than to hear of him with the hearing of the ear,
to see and hear him yourself, and be taught by him.
Oh! he is well pleased with those that sell all, or leave all to follow him,
who is the Lamb of God, that is greater than John.
"`This is he,`" says John, "`that comes after me, but is preferred before me,
for he was before me, and I knew him not; but he that sent me to baptize, said unto me.
Upon whom you shall see the Holy Spirit descending, and lighting on him like a dove,
the same is he that baptizes with the Holy Spirit: and I saw, and bear record,
that this is the Son of God.`"

John was not offended that his disciples left him, and followed Christ,
but rejoiced to hear his voice, and to have him made manifest to Israel.
"`Therefore,`" said he, "`I come baptizing with water; but I must decrease,
he must increase:`" of the increase of his kingdom and government there shall be no end.
For the kingdoms of this world shall become the kingdoms of God, and of his Christ,
and he shall reign forever and ever; even so, come Lord Jesus! come quickly!

This is He that John saw, "`Clothed in a vesture dipped in blood,
and his name was called the Word of God.`"
"`And the armies which were in heaven followed him.`"

Oh! that all who are upon the earth would follow him, hear him, and obey him;
for God speaks in and to men by him, "`Whom he appointed heir of all things;
by whom also he made the worlds, who being the brightness of his glory,
and the express image of his substance,
and upholding all things by the word of his power;
when he had by himself purged our sins,
sat down on the right hand of the Majesty on high.`"

This is Christ the Son of God; the Word that was in the beginning with God, and was God;
the Alpha and Omega, the beginning and the end, the first and the last; who was dead,
but is alive again.
But all flesh is as grass, and the glory of man as the flower of the field;
the grass withers, and the flower thereof fades away,
but the word of the Lord endures forever.
Cease therefore from man, whose breath is in his nostrils;
for wherein is he to be accounted of?
And again it is said, "`In vain is the help of man.`"
O then remember, God now speaks by his Son, who laid down his life for us, and suffered,
the just for the unjust, that he might bring us unto God.
And if ever you come unto God, it must be by Jesus Christ, the new and living way.
He is the Rock of Ages, the foundation of many generations, the offspring of David,
and also his Lord.

This is the Foundation of God to men, that stands sure,
and the Lord knows them who are his.
The whole house or church of God, and every member of it,
is built upon this Rock and Foundation; "`For other foundation can no man lay,
than that which is already laid, which is Christ.`"

This is the foundation of Christianity, this makes true Christians,
which weak and beggarly elements cannot do; for they cannot sanctify men,
or make them new creatures: there are none true Christians who are not in Christ,
and he in them spiritually; for he is the Lord from heaven, a quickening Spirit:
and where the Spirit of the Lord is, there is liberty.

O that men would live and walk in the spirit of Christ!
for all the children of God are chosen in him,
and blessed with all spiritual blessings in him,
through whom they obtain the adoption of children.
He is our peace, the Prince of peace, and until I knew him in spirit,
I never knew true peace with God, nor peace of conscience.

We cannot be heirs with Christ, and members of the church which is in God,
but as we come to sit together in heavenly places in Christ, and fitly framed together,
become a holy temple to the Lord,
in whom men are built together for a habitation of God through the Spirit.
God is in the midst of that house, church or assembly, wherever it is,
it being gathered in the name of Christ, to whom all power in heaven and earth is given;
and those that receive him now into their hearts,
receive power to become the sons of God, being born again.
"`For that which is born of the Spirit is spirit,
but that which is born of the flesh is flesh.
He that is in the flesh cannot please God.`"
For such do those things they ought not, leaving undone those things they ought to do,
and are miserable offenders, in whom there is no health:
but in vain do these worship God, teaching for doctrine the commandments of men,
following the rudiments, traditions and ordinances of men,
which afford no life to their souls, and being beggarly elements,
cannot nourish the soul immortal.
Therefore touch not, taste not, handle not, for they all perish with the using,
being not after Christ; for in him is life, and he gives life to them that receive him,
but nothing which is earthly can give life.
"`He that is of the earth is earthly, and speaks of the earth;
but he that comes from above, is above all.`"
Earthly men are in the wisdom that is from below, that is earthly, sensual, and devilish;
not pure, peaceable, gentle, easy to be entreated, full of righteousness, goodness,
truth and love.

"`Thus says the Lord, the Redeemer of Israel, to him whom man despises,
to him whom the nation abhors, to a servant of rulers, kings shall see and arise,
princes also shall worship; because of the Lord that is faithful,
and the holy One of Israel, and he shall choose you.`"
And Isaiah 49:22-23; Thus says the Lord, Behold I lift up my hand to the Gentiles,
and set up my standard to the people; and kings shall be your nursing fathers,
and their queens your nursing mothers, and you shall know that I am the Lord;
for they shall not be ashamed that wait for me.
And chap.
1, verse 10; Who is among you that fears the Lord, that obeys the voice of his servant,
that walks in darkness and has no light?
Let him trust in the name of the Lord, and stay upon his God.
And chap.
lii.; Oh captive daughter of Zion!
You have sold yourselves for naught, and you shall be redeemed without money.
Read chap.
liii.
and see who is given for a witness to the people, a leader and commander to the people:
and seek the Lord while he may be found, and call upon him while he is near;
let the wicked forsake his way, and the unrighteous man his thoughts,
and let him return unto the Lord, and he will have mercy upon him, and to our God,
and he will abundantly pardon.

The Lord God, which gathers the outcasts of Israel, says.
Yet will I gather others to him, besides those that are gathered unto him; Isaiah Ivi.
6, 7, 8.

What +++[+++Him]
is this?

This is Shiloh; the peaceable Saviour, of whom Jacob prophesied, on his death bed,
when he was near his end; Gen. 49:10.
This is He that the holy prophet Isaiah speaks of, in the 53rd chapter:
and to him the same prophet invites men to come, saying.
Ho every one that thirsts, come, etc., chap.
Iv. Those therefore who embrace this invitation, and dwell with him,
are of that church which God will make an eternal excellency, a joy of many generations; Isaiah 9.

These are redeemed out of the fall; these have received the spirit of adoption,
and know grace to reign in righteousness;
these are come into the mountain of the Lord`'s house, into Christ,
in whom none hurls or destroys.
These know that Jesus is the Lord, the King of kings, the Ruler of princes;
these are his sheep, hear his voice and follow him;
these will not set up such as know nothing, but what they know naturally as brute beasts,
and therein corrupt themselves, and neither know the Scriptures nor the power of God,
but are such as the prophet complains of, saying, "`His watchmen are blind,
they are all ignorant, they are all dumb dogs, they cannot bark; yes,
they are greedy dogs, which can never have enough;
and they are shepherds that cannot understand, they all look to their own way,
every one for his gain from his quarter.`"

"`The Word of God is quick and powerful, and sharper than any two edged sword,
piercing even to the dividing asunder the soul and spirit, and of the joints and marrow;
and is a discerner of the thoughts and intents of the heart,
neither is there any creature that is not manifest in his sight,
but all things are naked and open to the eyes of him with whom we have to do.`"
Those that have not this Word of God to preach, they are neither quick nor powerful.
Those that put into their mouths please them, but against them that do not,
they prepare war.
These receive honour one of another, and like the Pharisees of old, walk in long robes,
and have the chief places in the synagogues, and the uppermost rooms at feasts,
love greeting in the markets, and to be called master;
they come with good words and fair speeches,
by which they deceive the hearts of the simple; they run when God never sends them.
Christ speaking to such says.
The Father himself, which has sent me, has borne witness of me.
You have neither heard his voice at any time, nor seen his shape;
and you have not his Word abiding in you; for whom he has sent, him you believe not.
Search the Scriptures, for in them you think you have eternal life,
and they are they which testify of me,
and you will not come to me that you may have life; John 5:37-39. Read on,
and see how like these are to those, who had not the love of God in them,
but loved the praise of men, and received honour one of another,
but sought not the honour that comes from God only.

But Christ, who is the way, the truth, and the life, is come the second time, in spirit;
and tells us all that ever we did, as he did the woman at Jacob`'s well; who,
when she heard him, and believed in him, went into the city and bade them,
"`Come see a man that told me all that ever I did!
Is not this the Christ?`"
Many of the Samaritans of the city believed on him, and besought him to tarry with them,
and he abode with them two days; and many heard and believed because of his own words,
saying, "`We have heard him ourselves, and know that this is indeed the Christ,
the Saviour of the world.`"
He gave them to see, hear, believe and have everlasting life.
Oh that men would look unto him, come unto him, and learn of him;
blessed are they that hear the Word of God, and keep it.
"`Your Word have I hid in my heart,`" says David; "`the Lord is my light,
and my salvation.`"
And he prayed, saying, "`O send out your light and your truth!`"
O, that all our kings and rulers were of king David`'s mind, and of the same spirit,
who said, "`Why do the heathen rage, and the people imagine a vain thing?
The kings of the earth set themselves,
and the rulers took counsel together against the Lord, and against his anointed.
Be wise now, O you kings!
Be instructed you judges of the earth; serve the Lord with fear,
and rejoice with trembling; kiss the Son, lest he be angry, and you perish from the way,
when his wrath is kindled but a little.
Blessed are all they that put their trust in him.`"

Oh! that the kings and rulers, and great men, would hearken and hear the King of kings,
and Lord of lords, and remember that it is the meek that shall inherit the earth,
and that God gives more grace to the humble; but the proud he beholds afar off:
humble yourselves, therefore, under the mighty hand of God.

Seeing you are all enlightened, turn your minds to the light;
"`For there is a spirit in man,
and the inspiration of the Almighty gives it understanding.`"
It is said, "`Great men are not always wise, neither do the aged understand judgment.`"
It is hard for rich men to enter into the kingdom of heaven;
for they have great possessions on the earth, and stately palaces,
and are worshipped and honoured like gods, and the women sow pillows to their arm-holes,
and kerchiefs upon their heads.
The prophet said, "`Woe to the women that sow pillows to all arm-holes,
and make kerchiefs upon the head of every stature to hunt souls!
Will you hunt the souls of my people,
and will you save the souls alive that come unto you?
And will you pollute me among my people, for handfuls of barley, and for pieces of bread,
to slay the souls that should not die, and to save the souls alive that should not live,
by your lying to my people that hear your lies?`"

These are such as tell people, they must live in sin term of life; and teach them to say,
"`They stray from the ways of God like lost sheep,
and follow the devices of their own hearts, and are miserable offenders.`"
Yet if they put into their mouths, they will speak peace; but if not,
they will prepare war against them.

These are the hirelings of the blind people; blind guides that lead the blind,
and despise the true prophet, quench the Spirit,
and speak evil of the light that shines in the hearts of men,
to give the light of the knowledge of the glory of God and his Truth,
that is the sanctifier of men, and the way to God, and the life of every living soul;
"`For he that has the Son has life, and he that has not the Son has not life.`"
He is the anchor of the soul, both sure and steadfast,
the author and finisher of our faith, who for the joy that was set before him,
endured the cross, and despised the shame,
and is set down at the right hand of the throne of God.
These things has God made known to the weak of this world,
whom he has chosen to confound the strong,
and foolish things has God chosen to confound the wise; unlearned men,
like Peter and John; but they had been with Jesus, and learned of him,
and received the things which were freely given them of God: the manifestations,
revelations and operations of the Spirit, and the comfort of it,
were freely given them from above.
They received not faith, wisdom and power from man, or by man, but from Christ,
in whom all fulness dwells, and of his fulness, they, with others received,
and grace for grace.
The law was given by Moses, but grace and truth came by Jesus Christ.
By grace they were made what they were, they believed in the light, and walked in it;
and did not call it a natural light, as the merchants of Babylon do.
Christ said, "`This is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.`"

Christ appears the second time to them that look for him, Heb. 9:28;
see that you refuse not him that speaks, +++[+++mark, he speaks now in you.]
It does not say here, he did speak, he had spoken, or he would speak, but speaks;
now hear him, for he speaks from heaven.
While it is called today, hear him; for the night comes,
and utter darkness will be the portion of all those who reject so great salvation,
so great love, mercy and good will; for Christ speaks very plainly in men,
and to men`'s weak capacities and understanding; so that it need not be said.
Who shall ascend, etc., to bring him to us.
But the anointing, which they receive, teaches all things that are needful;
so that they need not that any man teach them,
but as the same anointing teaches them all things;
see 1 John 2:27. This anointing is in them.
O that men would hear the words of this teacher!
How often has he called by his prophets and apostles,
and the Scriptures have in them many calls, to come and hear what the Spirit says;
and none can be saved but they in all nations who walk in the light of the Lamb.
O that men would consider, and turn from evil, and cease from man, and gather to Christ,
the Word that abides forever, who never failed the prophets or apostles,
nor any man that ever believed in him.
He is the Rock of Ages, the tried stone, elect and precious,
he that believes in him shall never be confounded.
This is the foundation of all the righteous generations,
which bore them up in all their sufferings;
see Heb. 11. All power is his in heaven and earth; "`And to as many as receive him,
he gives power to become the sons of God.`"

This short testimony I have had in my mind some time, to leave behind me,
as an invitation of love, to come to him that is freely given of God to all mankind,
and is calling to all to come to him.
"`Ho, every one that thirsts, come to the waters, and he that has no money; come,
buy and eat; yes, come, buy wine and milk, without money and without price.
Why do you spend money for that which is not bread?
and your labour for that which satisfies not?
hearken diligently unto me, and eat that which is good,
and let your soul delight itself in fatness.`"
And again, "`Behold, I stand at the door, and knock: if any man hear my voice,
and open the door, I will come in to him, and will sup with him, and he with me.`"
And John 4:14; "`Whosoever drinks of the water that I shall give him,
shall never thirst;
but the water that I shall give him shall be in him
a well of water springing up into everlasting life.`"

All you that read these lines, I desire you to take the counsel of God,
and come out of Babylon, and partake not of her sins.
She is in that wisdom that is from below, that is earthly, sensual and devilish;
she is full of blood, and is the abomination of the whole earth,
and her plagues will assuredly be poured out upon her,
and her great and rich merchants shall partake of her plagues,
and her golden cup by which she has made them drunk,
shall be seen to be no profit to any soul.

But the wisdom that is from above, is first pure, then peaceable,
gentle and easy to be entreated, full of mercy and good fruits.
This is the true and heavenly wisdom,
hear her voice you sons of men! and take her counsel;
"`Her ways are ways of pleasantness, and all her paths are peace.`"

[.signed-section-signature]
John Gratton.
