[short="Letter to a Magistrate"]
== A Copy of a Letter Sent to a Great Person, After I Had Been in Discourse With Him at His Own House, in the Tenth Month, 1694.

Beloved friend.

In true love I write these lines.
It is cause of grief to me, that you being a magistrate,
and knowing how men have been harmed in these days by swearing,
and it has grieved you that you could not ease your quiet and peaceable neighbours,
and yet you plead for swearing, though it is so plainly and fully forbidden,
both by our Lord Christ and the apostle James, and yes and no set up instead of an oath,
saying, "`What is more comes of evil.`"

The law said, "`You shall not forswear yourself;`" so the law forbids false swearing,
but Christ Jesus forbids all swearing; and we are commanded to hear him.
Is not Christ greater than Moses, and above angels and men?
Yes; then surely his commands we ought to obey.
Is not all power his, in heaven and in earth?
Then ought not the powers of the earth to obey him?
Ought not he to rule whose right it is?

Is there any command in all the holy Scriptures for swearing, since Christ said,
"`Swear not at all?`"
It is plain, Christ was before the law, or sin and transgression were;
because of which the law was added, till Christ the Seed came; but he is come,
and as many as receive him, receive power to become the sons of God.
Must not the children of God be believed without swearing?
In the beginning it was not so.
Sons of God are true men, their yes is yes; they speak truth to their neighbour;
but the sons of Belial are false men, whose oaths cannot be believed.

Christ says, swear not; but you magistrates say, swear: but whether we ought to obey,
you judge.
Again, Christ says, "`I am the light of the world.`"
If so, then this light is divine, and ought to be believed and walked in.

Again, Christ says, "`Be therefore perfect,
as your Father which is in heaven is perfect.`"
Does Christ command impossibilities?
Read Eph. 4. from verse 3 to 14,
where the apostle speaks for what service some men were gifted, namely: Some apostles,
some prophets, some evangelists, some pastors and teachers,
for the perfecting of the saints, for the work of the ministry,
till we all come in the unity of the faith, and of the knowledge of the Son of God,
unto a perfect man.

"`There is therefore now no condemnation to them that are in Christ,
who walk not after the flesh, but after the Spirit;`" these have but one Lord,
and do not serve two masters; these are clean, for no unclean thing is in Christ.
These are bidden to abide in him; and says he,
"`Every branch in me that brings forth good fruit, my Father purges,
that it may bring forth more fruit.`"
So it is plain, men may be really, perfectly, sincerely, children or branches,
yet may grow from strength to strength, faith to faith, in and by the spirit of the Lord,
yet be perfect children, and grow to be young men, and overcome the wicked one,
and still grow to be fathers,
and still press toward the mark for the prize of the high calling of God in Christ Jesus.

Let us therefore, as many as be perfect, be thus minded.
This is the perfection we mean;
we do not mean such a perfection as that nothing can be added unto it.

It would be in vain for us to press after and labour
to attain unto a heavenly place in Christ Jesus,
if it be not attainable; and if it be a heavenly place, it is perfectly so,
for heaven admits of no mixture.
If we be children of God, we are perfectly so,
for we cannot be both children of God and of the devil too,
neither can a good tree bring forth bad fruit, nor a corrupt tree good fruit.
Yet good trees grow as they are ministered unto from the root, and the root bears them,
and not they the root.
So children are real, perfect children,
partakers of the same nature with young men and elders, but the root, Christ,
is all in all.

I ascribe nothing to man in all this, for God is the great Husbandman, who works in us,
and for us; for he sows his seed in all grounds, and gives of his talents to all.
No man has anything that is good, but what he receives from above,
for every good and perfect gift comes from there,
and the glory of all belongs to him who is God over all, blessed forever more, amen.

This is written in true love, with desire to be better understood;
for our principles are Christian, sound, and agree with holy Writ:
but the world hates us, wrongs us, and misrepresents us and our principles too.
I wish we and our principles were better known to all men,
for we are hated without just cause.
I pray God forgive them that do it, and am your true friend in sincerity.

John Gratton.
