== Christ is All, and in All

Or a True Testimony Concerning Jesus Christ, the Unsearchable Gift of God,
Who so loved the world, that He gave His only begotten Son,
that whosoever believed in Him should not perish, but have everlasting life.

Christ came into the world in the form of a servant, and went about doing good,
and healing all manner of diseases; yet the world knew him not,
though the world was made by him.
He preached the gospel, after he had been baptized by John in Jordan,
and the Holy Spirit came down from heaven like a dove upon him, and the Lord,
by a voice from heaven, said, "`This is my beloved Son, in whom I am well pleased,
hear him.`"
He was led into the wilderness and tempted of Satan, but he overcame him,
so that he departed from him, and angels came and ministered unto him.
Having thus bruised the serpent`'s head, he went on conquering and to conquer,
and preached the gospel of the kingdom of God, saying, "`The time is fulfilled,
and the kingdom of God is at hand; repent and believe the gospel.`"
He went about in their synagogues, preaching the gospel of the kingdom,
and healed all manner of sicknesses and diseases among the people;
they brought unto him sick people, that were taken with various diseases,
and those that were possessed with devils, and those that were lunatic,
and he healed them.

He preached wonderful, good and holy doctrine, as appears by his sermon in the mount,
where his counsel was sweet, precious and profitable for all to put in practice.
He taught them how to live, how to pray, and to please God in all things;
so that the people were astonished at his doctrine.
He showed infinite love both to body and soul; the blind he made to see,
the deaf to hear, the dumb to speak, the lame to walk; he cleansed the lepers,
he healed the palsy, he cast out devils, he raised the dead,
and had mercy on the very worst of men,
turning publicans and harlots from their evil ways.
He turned water into wine, and fed several thousands with a few loaves and fishes;
he spoke wonderful parables,
his doctrine was more excellent than man by all his own wisdom can understand.
He showed great love and pity to all sorts of people, and great dislike of all evil,
hypocrisy and sin; yet encouraged such as repented and turned therefrom,
and came to him to be healed, and obeyed him; not one of these was rejected by him.

But what shall I say?
Who can declare the good he did!
It is undeclarable, his goodness surpasses the understanding of all mankind;
he fulfilled the law of Moses to a jot or little, and was so holy, harmless, righteous,
just and good, that no man could convince him of sin.
He was and is the end of the law for righteousness to every one that believes.
He suffered for us, the just for the unjust, that he might bring us to God;
he laid down his life a ransom for all, and tasted death for every man.
He offered up himself a Lamb without spot unto God.
He poured out his soul unto death, and became an offering for sin,
and was a propitiatory sacrifice, our passover, sacrificed for us,
offered up himself once for all,
and by one offering has perfected forever them that are sanctified.
Those who receive him in the love of God, he works in them and for them,
makes them new creatures, and quickens them who were dead in trespasses and sins.
He is the resurrection and the life; "`He that believes in me,`" says he,
"`though he were dead, yet shall he live; and he that lives and believes in me,
shall never die.`"

He is our peace-maker, the Prince of peace, our reconciler to God,
the word of reconciliation;
he is the true light that gives light to every man that comes into the world;
he that believes in him shall not abide in darkness,
but shall have the light of life--he is our wisdom, righteousness,
sanctification and redemption, our life, strength and way to God, our all in all.

Oh! the benefits, advantages, favours,
blessings and mercies accruing by the coming of Christ into the world,
by his living and dying in it and for it, perfecting the work of our salvation,
without any merit of mankind; for all had sinned and fallen short of the glory of God.
There were none in that state righteous, no, not one; there were none that did good,
they were altogether become unprofitable, the way of peace they did not know,
there was no fear of God before their eyes; yet when we were without strength,
in due time Christ died for the ungodly.
God commends his love towards us, in that while we were yet sinners, Christ died for us.
Here is the love, not that we loved him, but God so loved us,
that he gave his only begotten Son,
that he by the grace of God should taste death for every man.
The love of Christ constrains us, because we thus judge, that if one died for all men,
then were all dead, and that he died for all, that they who live,
should not henceforth live unto themselves, but unto him that died for them,
and rose again.
So all things are of God, and nothing of man in this great work of salvation,
but all of God, "`Who has reconciled us to himself by Jesus Christ,
and has given to us the ministry of reconciliation; that is,
that God was in Christ reconciling the world unto himself,
not imputing their trespasses unto them,
and has committed unto us the word of reconciliation.
Now then we are ambassadors for Christ, as though God did beseech you by us,
we pray you in Christ`'s stead, be reconciled to God;
for he has made him to be sin for us, who knew no sin;
that we might be made the righteousness of God in him.`"

It appears very fully by the holy Scriptures,
that after Christ had abundantly benefited the world while he lived in it,
he also by his death has done much good to all mankind beyond utterance, yes,
beyond the understanding of man.
What, to all mankind?
Yes, to enemies, to sinners, to ungodly men, as is clear from Rom. 5:6;
For if when we were enemies we were reconciled to God, by the death of his Son;
much more being reconciled we shall be saved by his life.
So now we joy in God through our Lord Jesus Christ,
by whom we have received the atonement.
Here is good will to men, even to enemies.

Here is great advantage by the coming, suffering and death of Jesus Christ to all men.
First; The sacrifice is offered, and acceptably too,
a propitiatory sacrifice once for all.
Secondly; The atonement is made, and a peace offering, and that freely by Jesus Christ.
Thirdly; The law and prophets, and John`'s baptism are fulfilled;
so that Christ is the end of the law for righteousness to all them that believe.
So that where Christ reigns, the kingdom is come, the divine will done in earth,
and grace reigns through righteousness unto life eternal.
Fourthly; The middle wall of partition is broken down between Jew and Gentile,
and those who sometime were afar off, are made nigh by the blood of Christ,
"`For He is our peace, who has made both one; having abolished in his flesh the enmity,
even the law of commandments contained in ordinances, for to make in himself, of twain,
one new man, so making peace: and that he might reconcile both unto God in one body,
by his cross,`" that is, both Jew and Greek, having slain the enmity thereby.
And came and preached peace,
so that "`in Christ Jesus neither circumcision avails anything, nor uncircumcision,
but a new creature.
And as many as walk according to this rule, peace be on them, and mercy,
and upon the Israel of God.`"
In him "`we have redemption, through his blood, even the remission of sins.
Being justified freely by his grace, through the redemption that is in Jesus Christ.
Whom God has set forth to be a propitiation, through faith in his blood,
to declare his righteousness for the remission of sins that are past,
through the forbearance of God; to declare, I say, at this time his righteousness;
that he might be just, and the justifier of him which believes in Jesus.
Who was delivered for our offences, and raised again for our justification,`"

Fifthly; When he ascended up on high, he led captivity captive, and gave gifts unto men;
yes, to the rebellious also, according to the measure of the gift of Christ,
and they that keep the unity of the Spirit, in the bond of peace, are one body,
and one spirit.
They have one Lord, one faith, and one baptism; one God and Father of all,
who is above all, through all, and in you all; to him be glory.
"`There are diversity of gifts,`" says the apostle, "`but the same spirit.
There are differences of administrations, but the same Lord.
There are diversities of operations, but it is the same God, which works all in all.
But the manifestation of the Spirit, is given to every man to profit withal.`"
The same apostle tells us for what these gifts were given:
"`For the perfecting of the saints, for the work of the ministry,
for the edifying of the body of Christ; till we all come in the unity of the faith,
and of the knowledge of the Son of God unto a perfect man,
unto the measure of the stature of the fulness of Christ, the Head,
from whom the whole body, fitly joined together,
and compacted by that which every joint supplies,
according to the effectual working in the measure of every part,
makes increase of the body, unto the edifying of itself in love.`"

From all which, it is clear that the Holy Spirit or Spirit,
is poured forth or given to all, to every man, to all flesh, according to Joel,
Christ is given to all, the Sun of righteousness is risen, and shines upon all,
enlightens "`every man that comes into the world.
For in him is life, and the life is the light of men;`" who is the same today,
yesterday and forever.
Yes, he shines in darkness, though the darkness comprehends it not.
The grace of God that brings salvation, appears to all men;
and they who receive this grace, and learn of it,
"`It teaches them to deny ungodliness and worldly lusts, and to live soberly,
righteously and godly in this present world; looking for that blessed hope,
and the glorious appearing of the great God, and our Saviour Jesus Christ,
who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people, zealous of good works.`"
He is God`'s salvation to the ends of the earth;
which he has prepared before the face of all people, as Simeon said,
a light to lighten the Gentiles, and the glory of his people Israel.

"`God so loved the world, that he gave his only begotten Son,
that whosoever believed in him, should not perish, but have everlasting life.`"
Here salvation is offered to all, whether Jew or Gentile.
"`God is no respecter of persons; but in every nation, he that fears him,
and works righteousness, is accepted with him.`"
This is good news, glad tidings to all people.
Shall it be told abroad?
Yes, Christ said, "`Go into all the world, and preach the gospel to every creature.`"
Here Christ the Lamb of God, who tasted death for every man, shows his universal love,
and came that they might have life, and preached himself, the light of the world.
God would have all men to be saved, and come to the knowledge of the truth.
There is good will in him to all men, and mercy for all men with him;
he is not willing that any should perish, but that all should come to repentance.
For all are his, both by creation and purchase,
and he has laid help upon one that is mighty,
who is able to save them to the utmost that come unto God by him; and those that come,
he will in no way cast off: so that it is man`'s fault if he will not come to Christ,
who is come to give life.

The Lord calls, saying, "`Incline your ear, and come unto me; hear,
and your soul shall live.`"
And in the "`great day of the feast, Jesus stood up and cried, saying.
If any man thirst, let him come unto me and drink.
He that believes on me, as the Scripture has said,
out of his belly shall flow rivers of living water; but this spoke he of the Spirit,
which they that believed on him should receive.`"
Here is great encouragement, in much love and mercy, good will and fatherly kindness.
None are excluded here; seeing they that have no money are invited.
This is surely glad tidings to the poor, to whom the gospel is preached;
and without respect of persons, to all people.
And whosoever will, may come, for the gift is given to all, not only offered,
but freely given.
For "`the Spirit and the bride say, come, and let him that hears, say, come;
and let him that is athirst come; and whosoever will,
let him take the water of life freely.`"
The water of life is the flowing of the Spirit of God; for God is the Fountain,
and has poured out his Spirit upon all flesh, and given his Son to the world,
who invites all to come to him and drink.
None need fear any deficiency in this Fountain;
for it is a Fountain that can never be drawn dry: it is now unsealed,
and the thirsty are invited to come and drink freely,
and his beloved to drink abundantly.
"`Eat, O friends, drink, yes, drink abundantly, O beloved.`"
And Christ invites such as are weary and heavy laden, to come unto him,
and take his yoke upon them, for it is easy, and his burden, for it is light, and says,
"`You shall find rest unto your souls.`"

It is clear from holy writ, that man`'s destruction is of himself.
"`But you will not come unto me,`" said Christ, "`that you may have life.`"
He was despised and rejected of men; a man of sorrows, and acquainted with grief:
men hid their faces from him, and saw no beauty or comeliness in him.
They who follow him must deny themselves, take up the daily cross, and suffer with him,
if they ever reign with him; but he that denies him before men,
him will he also deny before his Father which is in heaven.

Oh! that all who read the holy Scriptures, which testify of Christ, would come to him,
believe in him, hear and learn of him, and obey him, who is Lord and King over all,
and Judge of quick and dead, that they might have life.
When Christ comes and works by his spirit in men, and they feel it, then,
and not till then, they know the mystery hid from ages, but now made manifest,
which is Christ in us, the hope of glory; the riches of the Gentiles, the Star of Jacob,
the bright and Morning Star.
He is the Sun of righteousness, the tree of Life,
the true Vine that enables every branch to bring forth fruit, as it abides in him.
And they who partake of his life, power and spirit, he is in them, and they in him;
and they do not walk as other Gentiles in the vanity of their minds.

Come, friends, have you heard him, and been taught by him, or are you past feeling?
If you do not feel, taste and handle these things, and hear Christ in you, as he said,
"`My sheep hear my voice, and they follow me,`" you know not the Truth,
nor are you sanctified, or made free by it, and then it is no matter what you profess.
For he that is in Christ is a new creature, and in covenant with God, abides in Christ,
and he in him.
Oh! therefore, lay hold of, and hold fast eternal life, and if Christ be in you,
you will find ability to come to God by him; for he is the way, the truth and the life:
no man comes unto the Father but by him.
He is the one thing needful; the pearl of price: if ever you find him, it must be in you,
giving life to your soul, love in your heart, wisdom beyond man`'s,
and power over all your enemies, yes, over death, hell and the grave, the world,
the flesh and the devil; all power in heaven and earth is in him,
none else can give you any.

Therefore be persuaded to look unto him, and wait for his appearing in you,
or else your faith is dead, and you feel no life in anything.

"`Come taste and see,`" said David, "`that the Lord is good:`" find him and you find all.
How glad were those that found Christ.
Simon said, "`We have found the Messiah:`" and Philip said to Nathaniel,
"`We have found him, of whom Moses and the prophets did write.`"
Nathaniel said unto him, "`Can any good thing come out of Nazareth?`"
"`Philip said unto him, Come and see:`" so say I unto you, who are apt to say,
Can any good thing be found in me?
Turn in and see; there is that which reproves you for evil, is not that good?

Oh! then seek the Lord while he may be found, call upon him while he is near.
Let the wicked forsake his ways, and the unrighteous man his thoughts,
and turn unto the Lord, and he will have mercy on him, and to our God,
for he will abundantly pardon.

Christ prayed for his, to his Father, saying, "`Sanctify them through your truth,
your word is truth.`"
Truth in the inward parts changes the heart, and enlivens the soul;
for it is a quickening Spirit.
Christ is the way, the truth, and the life: no man comes unto the Father but by him.
This is he that brings to God: this is the bridegroom of the soul,
the beloved of the church, and the church is his: this is the glory of the living;
the living glory in the Lord;
all things else are to them as dross and dung in comparison of Christ.

The apostle speaking to the church, said, "`All is yours, and you are Christ`'s,
and Christ is God`'s:`" so the Lord is the portion of his people,
and the Lord`'s portion is his people; Jacob is the lot of his inheritance,
to whom he said, "`Fear not, for I am with you;
when you pass through the waters I will be with you, and through the rivers,
they shall not overflow you.`"

Oh! that men would trust in God, obey and follow him as dear children,
keeping their minds stayed upon the Lord, that they may be kept in perfect peace,
and walking in him, they walk in the light; for "`God is light,
and in him is no darkness at all; and they that walk in the light,
have fellowship one with another,
and the blood of Jesus Christ his Son cleanses them from all sin,`" and sets them free;
"`and if the Son make you free, you shall be free indeed.`"

It is clear from what has been said, that Christ is all, in all his people: their wisdom,
strength, power, righteousness, light, life, peace, sanctification, justification,
consolation, and salvation; with him we have all things, without him we can do nothing.
In him all fulness dwells.
Though he was rich, yet for our sakes he became poor,
that we through his poverty might be rich.
And He who is heir of all things, was once offered to bear the sins of many;
and unto them that look for him shall he appear the second time,
without sin unto salvation.
Blessed are they who love his appearance.
They are ready to say, "`Come Lord Jesus, Come quickly.
Arise, O Lord, and let your enemies be scattered;`" make haste and come away.
"`Your kingdom come, your will be done.`"

To the Lord I leave all, and in true love am a friend to all men,
and servant for the Truth`'s sake.

John Gratton.
