[quote.epigraph, , Acts 10:34-35]
____
For God is no respecter of persons;
but in every nation he that fears him, and works
righteousness, is accepted with him.
____

== Forward by Editor

John Gratton (1641-1711) was one of several early Quakers who
were convinced of the Truth directly by the Lord,
apart from the preaching or writings of others in the Society.
His desperate and agonizing pursuit for true Christianity (amongst the many
sects and denominations of the day) at last brought him to dramatically
experience the truth of Christ`'s promise--"`Everyone who asks receives,
and he who seeks finds, and to him who knocks it will be opened.`"
Having found Christ, John Gratton denied himself, picked up his cross, and followed Him,
thus becoming an eminent minister and a faithful sufferer for
the Truth among the early Society of Friends.

My goal in preparing this edition of Gratton`'s journal
was to make the English somewhat more readable without
changing the meaning or over-modernizing the language.
As with all publications in our Early Quakers Series, this proved to be difficult task,
and it was approached with great care, and in a measure of the fear of the Lord,
believing that the Spirit of God was the true Author
behind much of what John Gratton has left us.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
February, 2016
