== Chapter 4. Prison Years

Soon after this, a writ __de Excommunicato Capiendo__^
footnote:[A writ ordering the imprisonment of an excommunicated
person until he or she submitted to the church.]
came out.
While I was abroad visiting Friends,
I had a great sense of a deep suffering coming upon me, insomuch that I said to a friend,
"`It appears so deep I cannot see to the bottom of it.`"
I desired in my heart that the Lord might enable to stand it.
Before I got home from Yorkshire, I had a dream one night in which I saw, as I thought,
a great mastiff dog take hold of me, and hold me by my clothes just by Derby jail.
I called to his master to take him off, but could see that he was not inclined to do it.
I then saw it was to no purpose to strive, and therefore gave up to let him hold me.
The day before I got home I felt the suffering more and more.
The next day, the 16th of the sixth month, 1680, I went to Bakewell fair,
and the magistrate arrested me before I could get into my inn,
or put up my horse in the stable.
So to Derby jail I must go, but we stayed that night at Bakewell,
where my wife came the next morning and wept.
I bid her not to weep,
but rather rejoice that we were counted worthy to suffer for Christ`'s sake,
who had suffered so much for us.
Then she bore it very well, seeing me bear it so cheerfully.

Now when we came to the jail I demanded a free prison,
but the jailer was unwilling,
and offered me kindness if I would but stay in his house and pay for my table.
But I had a wife and family to support,
and could not afford to lie in jail at seven shillings per week in his house,
so I insisted to have a free prison, as I knew the law allowed.
Now it had happened a little time before this,
that there were several Friends in that prison whom
this jailer put in the dungeon among thieves,
and would scarcely allow them clean straw to lie upon.
So I got hold of a statute book which said that no sheriff, under-sheriff, jailer,
or under-jailer, should keep and lodge debtors and felons together,
upon the penalty of five pounds.
At this time,
I took the book and went to the sheriff (whose wife and mine claimed some kindred).
They were very friendly to me, and desired me to leave my book with him,
and meet him at the court where he would speak to the judge.
This being done, the judge ordered my Friends to be put separate from the felons,
and to have rooms to themselves.

I was the next one to come to this prison, so I demanded one of those rooms.
He said he had already filled the room with corn.
"`Take it out then,`" said I, which he did in great vexation, and put me there,
it being an old prison chamber.
I borrowed a bed, with some other things, and went in.
He came up to see how I fared.
I had a fire,
and though I could see the stars at night through the holes in the roof tiles,
yet I lay warm enough.
I had my health, and was well content,
and thought in my mind that this was but small suffering
compared to what I might go through before I died.
I gave up all into the Lord`'s hand--soul, body, spirit, wife, children, and all I had,
saying in my heart, "`Sickness or health, life or death, the will of the Lord be done.`"
Oh, how good the Lord was to me, and I lay quiet and slept sweetly.

But when the jailer saw that I planned to abide there in the free prison,
he was angry and went his way, and locked me up close,^
footnote:[Those who were committed to jail for debt, or for other lesser offenses,
were often kept as "`open`" prisoners.
These had a measure of liberty granted them to leave the jail for lawful employment,
or to buy necessities from nearby towns, or even to visit families.
A "`close`" prisoner was one who was forbidden to leave the jail premises.]
and I remained so for some time.
I did not so much as desire to look out the door.
My heart was glad that I was accounted worthy of those bonds.
And though I could get nothing unless I drew it in at the window with a cord,
yet it happened that I lacked nothing all the time I was there,
for indeed I resolved to abide it patiently.

At length a Friend, one Robert Meek, came to see me.
The turnkey came to tell me there was one come to visit me,
saying I must come down into the jailor`'s house^
footnote:[At this time, in addition to housing prisoners,
jailers often kept ale houses where prisoners were encouraged to buy food and drink.]
to see him.
By this I saw the jailer desired my Friends and I to spend money in his house,
whereupon I told the turnkey that I was not willing to go down.
"`If my Friends,`" said I, "`cannot come to me, I am not willing to come to them.`"
He went down, and in a short time brought up the Friend to me,
leaving us together with the door unlocked.
When the Friend had stayed his time, I went down with him to see him take horse.
And when he was gone, I spoke to the jailer, and asked him,
"`Why do you carry yourself so severely with me?
If you are civil, you will have civility from me.
But if you are not willing, you may do as you please.`"
He said that we were a people that would do nothing but what we wished.
But when we had talked awhile, he said,
"`There hangs the key, take it, and do as you please.`"

After this,
I went in and out as I had occasion into the jailer`'s house and the gardens,
but home he would not let me go,
though my wife was taken so ill that it was feared she would die.
I gave up my wife and children, and all I had into the Lord`'s hand, and was contented,
saying in my heart after this manner,
"`Life or death, poverty or riches, come what will come, the will of the Lord be done.`"
But it pleased the Lord that my wife mended again.
And oh how easy it was after I had given up all!
My jail was made a pleasant place to me, for the Lord in mercy was with me,
so that I even sang a living song of praise; for truly,
to him praise is due forever more!

In brotherly love to me, Friends in London sent down a habeas corpus^
footnote:[A _habeas corpus_ is a legal action or writ by means
of which prisoners can seek relief from unlawful imprisonment.]
to have me appear in London.
I went to please them,
for it seemed that Justice Nichols had not managed the law rightly in my case,
but the court at London would not let me have the benefit of the law at that time.
I was very uneasy until I came to hear what
tricks the priest`'s party and Nichols had done.
Then I gave all up to the Lord, and resolved to wait his time to bring me out,
as he had been pleased to appear to me.
The word of the Lord came to me--"`Be content and I will bring you out with honor.`"
Upon which I came back to prison,
and lay quietly till King James set me at liberty +++[+++in March 1686].

After this my jailer went out, and another came in,
who was very civil and kind to me, as was his wife.
Towards the spring, my eldest son John died.
I obtained liberty to go see him, but he died that same night after he had seen me.
Some of his last words were that he hoped we should meet again
where they (meaning evil men) should not separate us anymore.
The next day he was buried, and I left my wife and returned to prison again.

The priests were pleased that I was in prison,
for two of them met in my inn at Tideswell,
and priest Wilson said to Fern (with whom I had the dispute at Baslow),
"`Sir, I can tell you news.`"
"`What news?`"
said Fern.
"`Why,`" said Wilson, "`Gratton is in prison.`"
"`I am glad of it,`" said Fern.
These are the hirelings that show their envious spirit,
who spare not the flock of Christ!

This year I wrote an epistle to the yearly meeting in London,
which is as follows:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends and brethren,

In the pure unchangeable truth do I dearly salute you all,
who are truly kept faithful in and by the power of God unto his glory.
In his endless mercy he has called and chosen us to
bear a testimony to his eternal power and godhead,
who is God over all the gods of the earth,
which are but as grass that soon withers and comes to an end.

My love at this time is freshly unto you, my dear friends,
who dwell in the power of God, in the mountain of true holiness,
and in the unchangeable light that is the same
at this day as when it first broke forth in us,
and I feel you as near and dear to me as ever.
Yes, my soul honors and highly esteems you in the Lord,
you whom God has made pillars in his house, honorable vessels in his hand,
fitted for his service.
For I know right well that it is your food and drink to
do the will of your Father who is in heaven,
and that your hearts are gladly carried on in your Father`'s business.
You can truly say that they (and they only) are your brethren and sisters
who are knowers and doers of the will of your Father who is in heaven.
For God, even our everlasting God and Father, has raised us up by his own arm,
and brought us forth in his own light, life, and power, not to do our own wills, but his.
Blessed be his name!

His own people delight to live under his government, and they love his reign,
and are exceedingly glad to feel the increase of his kingdom in their own particulars,
and also to behold it in others.
For this, dear Friends, a travail is known in every upright heart,
and a weighty concern is upon the honest-minded in all the churches of the saints,
that nothing may be allowed which hinders the increase
of the kingdom and government of Christ Jesus our Lord.

For this cause, with others I might mention,
I know it is well-pleasing unto the Lord that you meet together,
and cheerfully bear the weighty concern upon your
spirits for the prosperity of the eternal Truth,
which is truly precious to you.
Oh, how clearly has the Lord our God made it manifest that
your meeting is well-pleasing unto him,
by giving you his presence in such a powerful and glorious manner,
as is beyond my ability to declare.
Indeed, he has sealed it in my heart
(and I am sure in your hearts as well) that it is a right,
good, and honorable thing to meet as you do,
and it declares to all the world that,
though we be of several counties of this nation, yes, and of several nations,
yet we are one body, in one spirit and mind.
And truly our unity, love,
and concord remain fresh in that life and light which never alters,
and is the same at this day that ever it was.
For this reason the enemy rages and envies our prosperity in the blessed Truth,
and seeks every way to hinder the increase of the kingdom and
government of our Lord and Savior Jesus Christ,
to whom be glory forever!
May the Lord rebuke him and chain him down and tread him under our feet.

I earnestly breathe unto the Lord our God to give you
a good soul-satisfying opportunity,
according to his manner, and I believe he will do it and fill your cups full, yes,
and make them overflow abundantly,
to the joy and consolation of every sincere heart among you.
And may the Lord fill you with the Spirit of judgment,
that you may be as helps in his government.
Judge for God, and set true judgment on the head of transgression and transgressors,
wherever they are found, and so clear the Truth,
which is clear from scandals and scandalous professors of it.
May God be glorified, and all his enemies who desire not that he should reign over them,
be brought down and slain before him, that he may be exalted over all,
who alone is worthy--God blessed forever, amen.

My dear brethren, I can truly say I am with you in spirit,
and my love springs freshly to you, and I would be glad to be with you personally,
but could not get leave.
So as a token of my dear love and true unity unto you and with you,
it was in my heart thus to write.
I remain your dear friend and brother.
Everlasting praises be given to our God forever.
Amen.
Written in Derby jail, where I am a prisoner for the Truth`'s sake.

[.signed-section-signature]
John Gratton

[.signed-section-context-close]
22nd of the Third month, 1683

--

After some years the jailer gave me leave to go
home sometimes and stay some weeks,
but it displeased the priests and magistrates.
One time when I was at home,
a Friend who was to be married came to me and
earnestly desired me to come to his marriage,
saying he believed there would be a large service because many people of the
town of Chesterfield (where he had been an apprentice) would be at it.
Accordingly I planned to go.
But that night after he was gone, as I sat in my own house, an exercise fell upon me,
so I turned in my mind and waited to know the cause.
Then the word of the Lord came unto me, saying, "`You must not go to this marriage,
for the magistrate will be there;
but you must go to Derby and return to the jail tomorrow.`"
I went to bed very sorry that I must go to Derby so soon,
for I had leave to stay at home some weeks longer.
I told my wife of it, and questioned whether I would be able to sleep,
yet through mercy I did.
But when I awoke the next morning, the concern remained with me until I went.

When I came to Derby, the jailer was at the bowling green.
I told him I had come to see them, at which he was glad,
and bade me go down and he would follow me.
When I had been just a little time at the jail,
two high priests and one called a gentleman came to see me.
They asked for me, and I came to them, but when they saw me,
they had nothing to say to me.
They called for me, it seemed, as though they were sure I would not be there.
But finding me present,
one whose name was Ouldershaw (who knew me well) put himself to talk
a little with me and framed some discourse about religion.
He was soon silent, not being able to withstand the Truth, and the priests said nothing,
but paid for their drink and went away.

When they were gone, the jailer rejoiced that I happened to be there,
and that I was so ready to be seen by them.
For one of the priests was the chief priest of Derby town,
and the other was also very influential,
and we perceived their design was to make complaint
against the jailer for giving me liberty,
and thereby to require me to be kept a close prisoner with the hope
that some relation of mine would give them money for my release.
Indeed, the jailor was so pleased, that he let me go home again the very same day.

Thus the wicked plotted against the just;
for it seems they had some information that I
was expected to be at the aforesaid marriage,
and so designed their snare accordingly.
For the magistrate went to the marriage to catch me there,
expecting to find me preaching,
and he brought one justice Gladman with him to the
meeting (one who knew better than he practiced),
who asked for me there.
At the same time,
the two priests were to have secured evidence that they
came that day to the prison and called for me,
and that I was not there.
But the good God disappointed them,
and ordered me to be at the jail and not at the marriage.
Truly, the Lord saw all their plots against me, and in mercy delivered me that day;
neither did my jailer suffer for his kindness to me.
Oh, what a manifestation of the Lord`'s great love was this,
for which I was not able to fully return the praise and humble
acknowledgments that are due to him for his mercy and fatherly care,
who knew the designs of our enemies and prevented them!

Though we were ignorant and knew nothing of this plot,
yet the Lord in mercy revealed it to me by his
good Spirit that I should return to the prison.
Oh, what a tender Father and wonderful Counselor we have!
Heaven and earth are full of his majesty, and his power is over all.
Let the whole creation, and my soul, with all that is within me praise the Lord,
for his mercy endures from generation to generation!
He is God and changes not; He is the same today, yesterday and forever,
therefore his people are not consumed.
Though the sea rage, and the beasts of the field roar,
yet the sheep and lambs of the flock of Christ Jesus are saved,
and the lions and bears are slain by him who has all power in heaven and earth,
and will deliver all who truly trust in him.
David said, "`Why do the heathen rage, and the people imagine a vain thing?
The rulers take counsel together against the Lord,
and against his anointed;`" which the apostle remembered with joy: Acts 4:18-34.
Read it and take courage,
you that love our Lord Jesus Christ in sincerity, and do not fear man;
for if God is for us, who can be against us?
Neither men nor devils can hurt us, though they may tempt and try us;
yet if we follow the Lord, he will help us in time of need.
My chief end in writing these remarkable things
is that others may take courage to trust in God,
and be obedient to him in all things, without fearing man, who is but as grass.

Nevertheless the magistrate informed against the
meeting and Friends at the marriage were fined.
One Friend was fined twenty pounds for preaching (which would
have been my lot had they found me preaching there),
and the rest were fined five shillings a piece for hearing.
The justice also went to take hold of R. C. to pull him out of the meeting,
but slipped and fell to the floor, where he lay till Friends helped him up.

While I lay in prison, I sometimes spoke out the window to the people,
and many of them were loving and friendly to me.
Some young men were convinced, amongst whom was the jailer`'s eldest son,
who came forth in obedience to the Lord, for which his father was angry,
and turned him out of doors.
He was likewise offended with me,
and said he would put me in the dungeon and lock me to the wall.
But this he never did, for he would sometimes appear worse than he really was.
Indeed, he loved me more than he made out, and the liberty he gave me declared it.

One day I was concerned in my mind for his son
because he got very little business in Derby,
for the town was envious and turned from him,
and would not trade with him because he had turned to the Truth.
His father also became uneasy,
for some in the town desired to have the high sheriff put him out from being jailer.
But it came into my heart to make the jailer a proposition,
that if he was pleased to give me and his son leave,
I would go with him to London and place him there.
I went and told the jailor`'s wife, and she told her husband, to which he consented.
So I helped his son gather his goods,
and then took him with me to London and placed him with an honest Friend, George Watts,
where he did very well, for the Lord gave him favor in the sight of Friends,
and he grew in the Truth.
After some time he found his mind engaged in affection
toward a sober young woman of an honest family,
a Friend,
upon which he came back to obtain the consent of his parents to proceed in marriage.
I then returned with him again to London, and liked the young woman well.
They married, and he went into partnership with a Friend in trade,
and grew rich every way, for the Lord blessed him.
After some time his father went up to London and saw how his son lived,
and he confessed that I had done more for his son than he ever could have done.

One time, having leave to go home for some time to see my wife and family,
it fell out that Robert Meller of Whitehough in Staffordshire died,
who had been an honest Friend in his day and a noble standard in suffering times.
His wife was also a sincere-hearted woman, and his son John was a very honest Friend.
Hearing of my being at home, they sent and invited me to come to his burial.
Although I was sorry for the loss of so faithful a Friend,
yet was I desirous to go to his burial, thinking there would be many people,
for he was beloved both by rich and poor,
and was of good report amongst men of all sorts.
But I being a prisoner was careful that the jailer might not
be blamed or turned out of his place on my account,
for both he and his wife and children loved me well and were very kind to me.
So I waited upon the Lord, desiring to know his mind, whether I should go or no.
Then I felt I might go,
though I had a sense there would be danger of meeting with some trouble,
but how or which way it would come I did not know.

When the day came I went, and many people were there,
several of whom were people of note and figure in the world, and also the high constable,
to whom Robert was uncle.
I was not easy in my spirit to stay at the house,
but it was in my mind to go to the graveyard,
and not to stay till the corpse was carried from the house.
So I left the people at dinner and went away, and when I came to Basford town`'s end,
I overtook two men in black clothes who opened the gate for me, and as I went on,
it rose in my heart that they were informers.
They also went on past the graveyard, as though they had been going further,
but I knew there was no road the way which they went.
So I slipped off my horse and went to a fence to watch them,
and saw they went through a village into the Friend`'s ground who lived there,
and lay down under a hedge till the corpse came near.
Then they arose and put themselves into the crowd.
I did not know what to do, whether I should go to the graveyard or no.
For if I should go, I knew not whether my jailer would be turned out of his place,
and there were three other ministering Friends besides me: W. F., J. H.,
and J. J. So I humbly waited on the Lord for counsel,
if in mercy he would be pleased to teach and help me to do his will at that time.
As I waited and walked about, the people came with the corpse,
and it pleased the Lord to encourage me to go to the grave and all should be well.
So there I went, and my mouth was opened to speak to the people,
and the Lord`'s power was with me.

After I was done, I went into the Friend`'s house, sat down,
and kept my coat about me.
Then the two strangers came in under pretense of lighting their tobacco,
and asked the Friend`'s maid who I was, saying,
what an excellent man they had heard preach,
and that they wished they could do as he had said.
I sat by, and they did not recognize me,
but they asked the maid my name and where I dwelt.
She told them, and so they achieved their end, and left.

Now these two men in black proved to be informers,
one a priest and the other a schoolmaster, as I heard afterwards.
They informed against me to the magistrates and they fined me twenty pounds.
They also fined the other three Friends who spoke at the grave twenty pounds each,
and Thomas Hammersley (the Friend who owned the house) twenty pounds,
all in all a hundred pounds,
besides the Friends who were fined five shillings a piece for hearers.
Yet these informers got nothing of that hundred pounds from any of us,
for Friends went to the magistrates and they moderated it.
Also the justices of our county refused to grant their
warrants to restrain my goods because I was a prisoner.
Now the deceased Friend was a rich man, and so were his relations,
both in that county and in Derbyshire.
So they sent out a warrant to restrain the widow`'s goods, from whom they took a mare.
But no one else lost by these informers,
for the hearts of many people rose up against them.

Since I resided in another county,
a warrant was sent after me to Sir William
Boothly to restrain my goods for twenty pounds.
But he said that since the wedding took place outside of his county, he would not meddle.
By this means he put them off, and all was well.
Then they employed an attorney to go to Simon Degg
(a justice of Derby) for a warrant to restrain my goods,
but the justice told them I was a prisoner.
"`No,`" said the attorney, "`he is at liberty.`"
"`No,`" said the justice, "`he is in prison.`"
It just so happened that there was a prisoner standing by at that time,
and the justice asked him, and he bore witness that I was indeed in jail,
for I came in overnight and he saw me and was with me some time in the jailer`'s house.
Upon this the justice said, "`What would you have me do?
He is a prisoner; therefore I will not grant any warrant against him.`"

This prisoner, named Porter,
returned in the evening and told me (in the presence of the jailer and his
wife and many others) what a struggle he had about me at Justice Degg`'s,
saying, "`An attorney named Sutton craved a warrant against you
for preaching at Robert Meller`'s burial,
but I affirmed you were in prison, and so Sutton got no warrant.`"
When my jailer perceived that I ventured to go
to this burial while I had been home upon leave,
he cried out, saying, "`You will undo yourself and me too!`"
But I looked on him, and said boldly as it arose in my heart, "`Man, never fear,
for you will suffer nothing for any kindness you show to me.`"

This was the time of the court sessions at Derby,
and the high constable Robert Dale (who was Robert Meller`'s
nephew and was at the burial) privately told counselor Leming
that he desired to complain to the judge about my jailer,
for letting me have liberty to go to meetings.
Counselor Leming told it to a friend of mine (an attorney in the town
who wished me well) and he then told me what he had heard.
I said to him,
"`Please ask the counselor if it was not Robert Dale who desired to make this complaint,
for he was at the burial as well as I; and it is sad,
if we cannot have liberty to bury one another`", or to this effect.
But when Robert Dale knew that I had marked him out,
he said no more nor made any complaint to the judge;
for it would have been a shame to him to complain
against me for being at his uncle`'s burial.
My kind jailer received no blame, but all was well,
according to what arose in my heart after I went to the graveside,
that all should be well.
The devil was not permitted to do as much mischief as he would have done,
and the Lord comforted my soul through all these exercises.
Glory, honor and praise be given to him, who never fails those who truly trust in him.

After some time I went to London again,
and I was there when King Charles died and his brother came to the crown, who,
after some time, set all at liberty that were in prison for conscience sake.

While I remained in prison,
I had discourse with some Roman Catholics (who
were in prison with me) about several things.
The first time was as follows: The jailer being ill, I went down to see him,
and when a Catholic priest heard I was with the jailer, he came also,
along with about eight debtors, who were civil men and well brought up.
They came to see the jailer, and being pretty cheerful with the old man,
the Catholic priest broke out, and said, "`It is good that I be cheerful,
who suffer for the truth, when I see how cheerfully other men suffer for error.`"
There were none but he, another Catholic,
and I who suffered for our profession of religion, so that I saw clearly he struck at me.
I told him,
"`There are none here who suffer for their religion but
you and another of your own mind and me,
therefore,`" said I, "`it must be me you mean that suffers for error.
Either prove your charge or own your fault, for I am not willing to accept it.`"
Then I said, "`If you can make it appear that I suffer for an error,
I will take you for my friend, for I am not willing either to live or die in error,
if I know it.`"
Then the priest would dropped it, but I was not willing to pass it by and let him go,
for his charge was great.
"`Prove it,`" said I, "`or confess your error.`"

So he asked by what our discourse must be tried,
and one answered "`By the rule of the church.`"
He acquiesced to that, and so did I.
Then I asked him what that rule was,
but he seemed to evade the question and would not answer.
One that sat by said it was the Scriptures, and he said,
"`No.`" Then I asked him again what the rule was, to which he made no answer.
"`Is it the pope?`"
said I; "`No,`" said he.
"`Is it the church?`"
said I. He answered "`No,`" and I did too,
for indeed the church is to be ruled by the rule, and therefore cannot be the rule.
"`But,`" said I, "`What do you say is the true church`'s rule?`"
But he seemed unwilling to answer.
Finally, being urged, he said, "`Tradition is the rule.`"
"`Tradition!`" said I, "`But what was the rule before there were traditions?
For there must have been elders before there was the tradition of the elders.`"
"`And,`" said I, "`The rule is a firm, stable, standing rule,
from the beginning of the world to the end, which does not alter or change,
and which cannot be added to nor taken from.`"
He seemed to have but little or nothing to say against all this.

The company then desired me to tell them what I believed this rule was.
In answer to their request, I told them; "`It is the Holy Spirit, the Spirit of Truth,
which was in the beginning and was God, and is God, and changes not;
and since our Lord Jesus Christ suffered death for us and rose again,
this Spirit is poured forth upon all flesh,`" see Acts 2.
"`This is the rule which guided Enoch,
so that he obtained a testimony that he pleased God.
This has been the guide, rule, and leader of all the patriarchs, prophets,
and the holy men of God, who spoke as they were moved by the Holy Spirit,
or Spirit of Truth.
This Spirit leads and guides the true church into all truth,
and all true worship is in it.
And as many as are led and guided by the Spirit of God,
they are the sons and daughters of God.
This was and is the true church`'s rule; and if any man have not the Spirit of Christ,
he is none of his.
So then, that which is the guide of the church must be the rule,
and he that works by a rule is guided by it and ruled by it.
This is that which baptizes men into the church or body of Christ.
This is that by which the children of God are born and are nourished,
so that it gives them life and inspires them, and gives them understanding,
freely manifesting to every man that which is for his profit and welfare.
The apostles were ministers or servants of this Spirit.
It is the Spirit that brings men into the adoption and enables them
to call God "`Father,`" and to say truly that Jesus is the Lord.
It directs men to obey, and enables them to do the will of God.
This is the grace and the free gift of God to all, and if they will,
they may come and drink abundantly of it, for it is a fountain of living water.
Since men have turned from it and run after blind guides,
they oppose it and one another and are confounded!
Having lost the rule, the true guide, they cry,
"`Lo here,`" and "`Lo there,`" and have no love and charity one for another.
One is for one head and ruler, and another for another head,
so that every head seeks to rule.
And now, there being so many heads and horns (even to admiration),
they are pushing at one another.
Truly in Babylon is found all the blood of the saints and martyrs of Jesus,
but the true church is full of love and good will to all mankind.`"
And I spoke much more to this purpose.
After this discourse the company believed that
the Spirit of Truth was the true rule and guide,
whereupon the Catholic priest desired that he and I might be at peace,
and desired to have no more discourse.

After this,
two men of the Church of England (who wished me well) came to
see me and sent for me to come to the jailer`'s hall.
But before I came,
another Catholic (who had been imprisoned for clipping coins)
got into discourse with them and sadly vilified their church.
Then I asked a question, "`If,`" said I,
"`it can be made to appear that the Pope of Rome is not in the apostle Peter`'s spirit,
will you not then grant that he cannot be Peter`'s successor?`"
The Catholic answered, "`Yes.`"
Then I asked, "`Was not Simon Magus out of Peter`'s spirit,
who thought that the gift of God could be bought and sold for money?`"
He replied "`Yes.`"
"`Then,`" said I, "`the Pope is in Simon Magus`'s spirit, and not in Peter`'s,
for he thinks so still.`"
But he said, "`No, the Pope does not think so.`"
"`Then,`" said I, "`he is worse than Simon Magus,
because he makes other people believe so, otherwise,
why does he take their money for his bulls, pardons, and indulgences?`"
To this neither he nor the priest that stood by said a word more, but went away;
and the churchmen were glad.

After this there came in a Jesuit and another priest and two more Catholics.
One day the Jesuit showed me a place in a book speaking
of a man being born of the Spirit and of water.
I asked him why he showed it to me, and he answered,
"`To let you see that a man must be born of water as well as of the Spirit.`"
I asked him, "`What water?`"
He said, "`Baptismal water.`"
"`What!`" said I, "`Elementary water?`"
He said "`Yes.`"
"`Then,`" said I,
"`Do you believe that elementary water has that virtue
in it which can make a man a new creature?`"
He said "`Yes.`"
Then I denied their baptism,
and told him he could not prove that ever our Savior Christ baptized any with water,
or commanded any man to baptize with water; and I bade him either prove or yield.
But he could not prove their baptism, nor was he willing to yield.

After this he fell on me sharply about the Eucharist
(or sacrament, as they call it) of bread and wine.
He told me that after the words of consecration (so called) by the priest,
(we read of no such words in Scripture) the bread was really, corporeally,
and substantially the very flesh of Christ, and the wine was his very blood,
urging Christ`'s words, "`Take, eat, this is my body.`"

I told him that Christ also said, "`The flesh profits nothing,
it is the Spirit that gives life; the words that I speak unto you,
they are spirit and they are life,`" and,
"`He that has the Son, has life; but he that has not the Son, has not life.`"
But the apostle speaking of the children of Israel (1 Cor. 10) says,
"`They were all baptized into Moses, in the cloud and in the sea;
and they did all eat the same spiritual food, and did all drink the same spiritual drink;
for they drank of that spiritual Rock which followed them, and that Rock was Christ.`"
"`Now,`" said I, "`if it be the same food and drink, then it is spiritual,
and not corporeal, as you say.
And if it be not the same, then what apostle says is not true.`"
This put him to silence, for he dared not say the apostle lied.
And indeed, if the apostle spoke the truth then it was the same, and if the same,
then not the flesh of Christ corporeally.
So he was silent awhile, and at last he said,
"`Well, for my part, I know nothing of spiritual eating or drinking.`"
"`Then,`" said I, "`There is no reason to talk more with you.`"

Another time he began to discourse with me,
asking me if I did believe in a purgatory where all go before they can go to heaven.
He asserted there was a place of purging after this life,
and there were three sorts of people who went into purgatory: one sort were holy,
and so went straight through it into heaven,
for their works did abide and they had reward for the same;
another sort was so unholy that they went straight through purgatory into hell;
and still there was a third sort, the most numerous,
who were neither so holy as to go straight to heaven,
nor so very unholy as to go straight to hell,
and these stayed in purgatory fire till they were made clean and suffered loss,
because their works did not abide when they were tried by fire.
Yet these, he said, were saved but so as by fire, alluding to the apostle`'s words,
"`that every man`'s work should be tried by fire, of what sort it is, wood, hay,
or stubble,`" 1 Cor. 3:12-14.
Then he asked,
"`Can any man`'s work be tried before it be done?`"
"`I said "`No.`" "`Then,`" said he,
"`Can a man`'s work be said to be done before he be dead?`"
I said "`No.`" "`Well then,`" said he,
"`if a man`'s work cannot be tried before it be done, as it cannot,
nor done before he be dead, it must need to be tried after he is dead,
and it must be tried by fire, therefore it must need purgatory fire.`"
I asked him what sort of fire it was, whether like the one before us,
(which was a coal fire) elementary fire?
He said, "`Yes.`"
"`I never heard before,`" said I, "`that a coal fire could try men`'s works,
or that it could burn to all eternity.`"

Now the Lord was pleased to appear, for I felt him near me,
and he opened my understanding.
I labored to show him from the holy Scriptures that men were
to be baptized into Christ`'s death and to become dead to sin
and be buried with him by baptism into death,
and that as Christ was raised from the dead by the glory of the Father,
even so we also should walk in newness of life.
"`For if we have been planted together,`" said the apostle,
"`in the likeness of his death, we shall be also in the likeness of his resurrection;
knowing this, that our old man is crucified with him,
that the body of sin might be destroyed,
that henceforth we should not serve sin,`" Rom. 6.
The apostle says, "`How can you that are dead to sin, live any longer therein?`"
So the old man being crucified, death has no more dominion over you;
and he that enters into Christ (the true rest)
ceases from his own works as God did from his.
Indeed Christ works in him, for he is all in all.
The baptism of Christ is with the Holy Spirit and fire,
and he will purge away the filth of the daughter
of Zion with the spirit of judgment and burning;
and the day of the Lord shall burn as an oven; and Jacob shall become a flame,
and the house of Esau stubble.
The Lord shall sit as a refiner`'s fire and like a fuller with soap,
and take away the filth of the daughter of Zion,
and purely purge away her dross and take away her tin.
The Lord said by his prophet,
"`I will make a man more precious than gold, than the golden wedge of Ophir;`"
and that he would purify the sons of Levi.
The word of the Lord is as a fire and a hammer to break the rocks asunder;
and our God is a consuming fire to all the workers of iniquity,
and reveals himself in flames of fire to render vengeance upon all that know not God,
and that obey not the gospel of our Lord Jesus Christ.
The Lord makes all things new, and if any man be in Christ he is a new creature;
old things are done away, and they become as dross and dung in comparison of Christ,
so that man loses all his own works, for they cannot abide the trial.
But Christ is, of God, made unto us wisdom, righteousness, sanctification and redemption;
and if any man glory, he must glory in the Lord, for apart from him there is none.
Truly this must be done or known in this life, in the day time,
for the day shall declare it, and the fire try every man`'s work, of what sort it is.
"`Therefore,`" said Christ,
"`Work while it is day, for the night comes wherein no man can work.`"
There are twelve hours in the day in which a man may work, but there is neither work,
nor device, nor knowledge, nor wisdom in the grave.
Therefore, whatsoever your hand finds to do, do it with all your might,
for as the tree falls so it shall lie, and as death leaves, judgment finds,
and in the grave there is no repentance.
The grave cannot praise the Lord, death cannot celebrate him.
They that go down into the pit cannot hope for his Truth,
but they that die in the Lord are blessed.
And they that are in Christ need no purgatory after death,
having washed their garments and made them white in his own blood.
Nothing else can cleanse people or save them from their sins,
for there is no other way to God but by him,
neither is there any that can save from death and give life eternal, but Jesus Christ.

Much more was said than I can now remember,
but he was ignorant and not acquainted with these things, so he did not oppose,
nor did he deny what I said.
So his purgatory was all thrown aside as an invention of men,
and their pretending to pray men out of purgatory was shown to be a cheat to get money,
and all their pardons nothing but deceit, for the Lord only has power to forgive sin.
Much opened in my mind, and all he could say came to nothing, so we parted friendly.

Oh, blessed be the Lord, who has discovered the great deceiver,
and all her abominations, and has exposed the false prophet (with all his transformings),
and both are thrown down to the earth together.
She is full of the blood of the saints and martyrs of Jesus, and she thirsts for more.
But the Lord has a remnant that have come out from her
and refuse to partake with her of her sins,
lest they should partake with her of her plagues.
Indeed, strong is the Lord God Almighty that judges her.

I also had good service with many other people,
and sometimes got to some meetings at Little-Eaton and other places,
but I did not write down what passed in all places, only some things of note.

I wrote to the priests of Derby about the rude,
wicked practices which the people of that town lived in; for they made bonfires,
and one year they carried around a thing that they called the Pope,
and then burnt it in the fire.
The next year they carried around a thing they called Presbyter John,
and then burnt that also.
These things, along with many others I beheld in the town, grieved me very much.

About this time the priests in their pulpits preached aloud that
active obedience must be practiced by all the king`'s subjects.
Henry Ward, having spent a day with the mayor,
came to me in the evening and told me that the
mayor also said we must obey the king actively,
so that if the king commanded us to worship Mahomet, we ought to do it;
and if the command was amiss, it would be the king`'s fault and not ours.
At this time an act was put in execution requiring twenty
pounds per month against non-conformists who were rich,
or against whomever else the prosecutors had a mind to afflict.
Then Derby (in order to avoid suffering) conformed,
and there was scarcely a man in that town who was willing to be reputed a Presbyterian,
for they had no meeting in or about that town unless it was in secret.

Such is the cowardice of men whose religion is
built upon the tradition and inventions of men,
and not upon Christ.
Indeed, how needful it is for men to lay their building upon
that Rock which neither the windy doctrines of men,
nor the swelling waves of persecution are able to move.

In this time of my confinement,
several people came to me in prison on first-days, and we had good meetings there.
For though the ministers of the gospel may be
shut up in jails for the sake of their testimony,
yet the Word of God cannot be bound, and indeed, it had free course and was glorified.
This prison was made easy to me,
and things were well at home with my dear wife and family.
Though my wife was a tender woman, yet she was enabled, through mercy,
to keep markets and to carry on our business for their livelihood.
She also came sometimes to see me in prison, though it was a journey of sixteen miles,
which was hard for her in the winter season.

While I was a prisoner I wrote a little book which I entitled
"`The Prisoner`'s Vindication,`" as well as some epistles and letters to Friends,
and meditations in verse for my children.
The reason why I wrote the remarkable occurrences in my sufferings for Truth,
along with the great things which the Lord has wrought for me (both in
supporting me in trials and delivering me from further sufferings),
is that my children and others may be encouraged to be
faithful to the Lord and valiant for the Truth upon the earth.
For this cause it came into my mind to tell to others how good the Lord has been to me,
for which I am deeply engaged to praise his great name.
