== Chapter 5. Return to Ministry

I was a prisoner for the gospel`'s sake here above five and a
half years before I was set at liberty by King James II. I was
discharged in open court the 23rd of the first month, 1686.
I then went home to my wife,
but after I had stayed awhile I was concerned to visit friends,
and so traveled through most parts of this nation, except Cornwall,
and was also in some parts of Wales.
I also had many meetings in and about Eastwood, Nottinghamshire,
and many were convinced and became obedient to the blessed truth.
But the priest of Eastwood hearing a great rumor about Friends,
as also seeing that many of his hearers left him, bade his son (who was also a priest,
and sometimes preached in his father`'s stead) to preach the same doctrine that I did.
But when his son sought to do what his father advised him,
he was so confounded that he could not go on.

It happened one day that I had a very large meeting at the house of Luke Hanks,
where I heard that this priest of Eastwood would
often say that I stole his sheep from him,
meaning some of those who had been his hearers.
After meeting I went to a friend`'s house,
but that very night the priest sent his clerk and requested that I go to his house.
So there I went, and several friends along with me.
When we arrived we were invited to sit down, which we did, and we sat awhile in silence.
Then the young priest (who had followed us there) spoke to the priest of Eastwood,
saying he perceived that I was sent for that he might speak with me.
Upon this he asked me, "`How were you called to be a preacher?`"
But before I answered his question, he added,
"`I grant that a man may be rightly called, though not of God. For,`"
said he, "`the king`'s call is sufficient.`"
I then spoke saying,
"`I deny that any man can be rightly called if he is not called of God, as was Aaron,`"
and this I was willing to prove by Scripture.
The priest of the house labored to help his son out,
but he ran himself into the same snare,
for they were not able to prove that any man was
rightly called to preach unless he was called of God.
We talked further till they were both silent and confounded,
and in the silence a concern came upon me,
upon which I stood up and preached truth among them.
When I had finished, the priests gave me their hands, and we parted friendly.
But when we were gone, the priest`'s wife was angry with them, saying,
"`You sent for him like fools, and let him go like fools; but if ever he comes again,
I will burn or scald him!`"
After this I heard that the young priest of fell into great trouble of mind,
and was confounded in his pulpit.

I visited Friends in Lancashire
(and several other parts)
and the Lord was with me in his great love and mercy,
otherwise my travels had been tiresome and unpleasant.
But indeed Lord helped me many a time, and truly the living know it,
and have met with him to their great comfort,
otherwise meeting with me could have done little for them.
The work was the Lord`'s, and he has wrought in us and for us of his own good pleasure.
Glory, honor and praise are wholly due to him.

After this I went into Cheshire, and to Chester again,
where I had formerly been exercised, but where there was now more openness than before.
I went to Chester several times after and had good
meetings there through the Lord`'s goodness and mercy,
who made them good by his precious presence, according to his blessed testimony that,
"`wheresoever two or three are met together in his name, there is he in the midst of them.`"
This I have witnessed many a time, for truly if the Lord had not been with us,
we could have done nothing without him.
He was mouth and wisdom to us, and gave us to understand Scripture.
He also gave to us the motion of his Holy Spirit, inspiring us by it;
for we spoke as it moved and gave us utterance.
Renowned and exalted over all be our gracious God,
for we came not with words of our own wisdom,
or with words which man`'s wisdom teaches or had taught us,
but with words which the Holy Spirit gave us, comparing spiritual things with spiritual.

I went to most meetings in the county of Cheshire, and a fine people there were,
and there was much love, unity, peace and concord amongst Friends.
After this I traveled in several counties in England, both east, west and south,
and through other counties northward,
such as Worcestershire and Staffordshire on my return home.
I found Friends in great love and unity, and many were convinced.
Truth prospered, and we were sweetly refreshed and comforted together;
for we were a help and a strength one to another, and the body edified itself in love.
Blessed and praised be the name of our God forever.

I went much abroad to meetings, and ran to and fro in most parts of the nation,
to the utmost of my ability, preaching the gospel freely.
I also traveled into Wales and through a great part of it,
and had many good meetings there.
We were in great danger in passing over the water at Aust into Gloucestershire,
but through mercy got safely to John Bolton`'s at Ouldstone,
and visited most meetings in that county.
I was at Frenchay, and from there to Bristol,
and then was at many good meetings in Somersetshire, and in Devonshire, as far as Exeter,
where a fine meeting house had newly been built.
I then traveled through several counties on my way to London.
The Lord in great mercy favored me with his power and presence,
to my great comfort and joy.

After the yearly meeting at London, I went into Hertfordshire and Essex,
and to and fro in Suffolk, Norfolk, as far as Yarmouth, and back to Norwich,
and up and down in that county to Downham and Lynn, and into the Isle of Ely,
Cambridgeshire, Huntingtonshire, Northamptonshire, Leicestershire and Rutland,
into Lincolnshire, to Boston and Lincoln city, and through most of that great county.
Then I visited Nottinghamshire and Derbyshire on my way home.
Having traveled in great love,
many in this journey were turned to the Lord from the evil of their ways,
as at many other times and places where I traveled.
Though I often came home much spent, weak, and weary, yet I had my reward with me,
"`my sheaves in my bosom,`" and was usually soon better after I had rested awhile.

I had it upon me to go and visit Friends in Scotland,
and accordingly I went by Halifax, Leeds and York, where I met Thomas Aldam,
who accompanied me.
We went to North Allerton, Yarm, Stockton, Bishop Aukland and Durham,
and from there to Newcastle upon Tyne, where we had large meetings.
I was at Sunderland, and many places in Northumberland, which I cannot name.
We came to Berwick, where rude people disturbed our meeting, breaking the windows,
but a lady from Northumberland being present went to the magistrates of the town,
and the rabble were rebuked.

The next day we went to Kelso and had a quiet meeting.
James Holliday went with us to Edinburgh,
where we were at their yearly meeting for that nation,
and it was a comfortable opportunity.
The next meeting we had was at Montrose, and then another meeting before we came to Ury,
where the widow of Robert Barclay^
footnote:[Robert Barclay (1648-1690) was a Scottish Quaker,
and one of the most eminent writers in the Society of Friends.
His most celebrated work, the _Apology for the True Christian Divinity,_
is still in print today and can be purchased
from Quaker Heritage Press (www.qhpress.org).]
dwelt.
There we stayed several days,
in which time I observed that when her children were up in the morning and dressed,
she sat down with them before breakfast, and in a religious manner waited upon the Lord.
Her pious care and motherly instruction of her children when young,
doubtless had its desired effect upon them, for as they grew in years,
they also grew in the knowledge of the blessed Truth,
and since that time some of them have become public preachers of it.

From there we went to Aberdeen and found a fine meeting of Friends,
and stayed there some time.
From there we journeyed to John Forbes`'s, and to Cashore, Kingswells,
and back to Aberdeen, Ury and Montrose, Dundee, Leith and then Edinburgh,
at which place they stoned us when we were quietly together in the meeting.
From there we went to Lithgow, and so to Charles Hambleton`'s (the duke`'s servant),
and then to Durand, and a town where there was a meeting house in which we had a meeting.
From there we traveled on to Glasgow where the people were wicked,
and then to Hambleton where we had a good meeting, and then to Argyle and Douglass,
and to one James Wood`'s house where we had a meeting,
and then James Wood came with us by Dumfries into England.
The Lord in mercy helped me mightily with his heavenly power,
and gave us many precious meetings up and down in that nation.
However, I felt the Scottish people to be in a bitter, envious spirit in several places,
and we were in perils twice, both at Edinburgh and Glasgow, where they stoned us.
At Edinburgh a stone hit me as I was declaring in the meeting, but it did not hurt me.

After our return out of Scotland, we had many good meetings in Cumberland,
which were comfortable seasons to us, for indeed the Comforter was with us,
and mightily helped us from meeting to meeting.
From there we traveled to Kendal, the Height, and Swarthmore, where we had a fine meeting.
We were also at Lancaster, from which place we returned back again to Kendal,
and passed from there to Thomas Camm`'s,
and into Yorkshire to John Blakling`'s near Sedberg.
Then we passed by William Ellis`'s to Skipton, and from there to Leeds and Warnsworth,
where I left my companion T. Aldam, and returned home to find my wife and family well,
to my great comfort.
Praised be the Lord forever!

Friends in Scotland and elsewhere were very loving to us, and we had fine,
living meetings in that nation.
I felt them in the Life near to my spirit,
in which the living ones know one another beyond words,
and I hope and believe the Lord will have a great people there in time to come.
Though the enemy be angry and desire to hinder the
spreading of the holy Truth through its enemies,
yet his weapons are but carnal, silly, and weak.
I desire that many Friends think of that nation,
and in the will of God give up to visit it,
for there is a zealous professing people there,
and were they brought to the knowledge of the Truth,
I believe very many would be zealous for it.
I found that those two worthy men, Robert Barclay and Patrick Livingston,
had left a sweet savor behind them.
The loss of them, especially the former,
was a great loss to that nation and a cause of
great mourning to Friends there and elsewhere.
But blessed be God, for Robert Barclay has left a hopeful family behind him.
Praises be given to the Lord forever!

In this year I had a concern to visit Friends with the following lines:

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle to Friends in Scotland

[.salutation]
Truly beloved friends and brethren,

With pure and unfeigned love, which springs from the Fountain,
I do tenderly salute you, and all true Friends with you,
feeling you near and dear to me at all times when I remember you.
Truly I am glad that the God and Fountain of all our mercies
has reached forth so plentifully to your immortal souls,
and made you to so largely partake with us of his free grace and gift of eternal life,
so that your portions and measures of it are very large, to the mutual joy of you, me,
and many more.
For this we are deeply obliged to be truly thankful unto our God,
from whom every good and perfect gift comes.
Unto him alone we ought to continually look, that as men in need of continual supply,
we may experience his bountiful hand to minister freely to every one of us.
Indeed, it is he alone that both makes and keeps us truly living, faithful, fruitful,
and serviceable in this blessed day of his mighty power, and as we abide therein,
we have fellowship both with him and one with another.

The travail and earnest desire of my soul to the Lord is that
we may all be preserved to the end in true self-denial,
humbly, meekly and innocently walking in this glorious Day of gospel light,
life and power, so that we may help one another`'s joy.
And as the blessed unity of his Holy Spirit is lived in, no man can take our joy from us,
for this joy is possessed by us only as we abide in him who is life eternal,
to whom be praise given by us and all that partake with us forever, amen.

Many are the exercises, temptations,
sufferings and tribulations which attend us here, both within and without.
Well may we say that our God is God and he changes not,
or else we might have been destroyed; for truly we are poor, and weak,
and insufficient in ourselves even to think a good thought.
The enemy knows this, and labors to deceive us with his subtle wiles;
for if we keep not in him who is our wisdom, righteousness, sanctification,
and redemption, we have no wisdom of our own, or righteousness,
or power to save ourselves at all.

Oh, the goodness of God to us is undeclarable!
And we see as much a need as ever to keep looking unto him for help every moment;
for all our time is a time of need,
and if the Lord was not with us we could not bear up against the enemy`'s floods, tempest,
raging violence and storms that attend us in this perilous pilgrimage.
But glory, honor, praises,
and high returns of humble and sincere thanks be given to our great and merciful God!
He is with us,
and is the same he was in ancient days when he
carried Israel through the Red Sea on dry ground,
and gave them to behold his miraculous deliverance,
and saved them out of the hands of their many enemies who sought to destroy them.
The sense of his love, and the experience which I have of his goodness,
tenderizes my poor heart, and bows my spirit before him.
Indeed I hope you partake of this with me,
and also feel with me beyond words or writings.

Dear friends, I desire we may all be mindful of him who is our rock and refuge,
keeping near him always, not forgetting the Lord.
Here there is divine light, for he dwells in it, and in him is no darkness at all.
Here we see our states as they are, and that what we are, we are by his grace.
Here it is we meet with fresh pastures of life, and feed together,
where the enemy cannot come, nor can the lofty, unclean Edomite approach.
My heart is glad to feel love run so freely towards you at this time.
I do not write these things as though I looked upon you not to know them.
No, for if I did, I could not be so free and open with you.
I write only to remind you, and with these few lines to confer with you in love;
for it is with the fruits of dear, unfeigned love that I now salute you,
as those that I can say are of my flesh and bones, and members with me of that sweet,
harmonious body, of which Christ Jesus is Head, Lord, and King.
Worthy is he to reign; indeed, it is his right.
And he that would be great among you, must be least of all.
This is the Lord`'s doing, and it is marvelous in our eyes.

Oh, that we may know this low estate experientially!
For in this place many have met with him,
and been met by him who despises not the low estate of his servants and handmaids.
Surely it behooves us to be low, for our teacher is meek and lowly in heart.
My dear and truly beloved, the meek are most filled with love,
even that love which is not puffed up, nor seeks its own,
but leads us to seek the good of all, and the things that are of Jesus Christ.
I pray that we may always dwell in this love,
and then we shall be sure to love one another.
I was truly glad in heart when I felt your love to me in the Lord while present with you,
and to my companion also.
I also felt your love still fresh unto us after our
departure from you in person (though not in spirit),
how you remembered me in your prayers.
I desire you still remember me in prayer, and I hope I shall not forget you.

As your brother,
I desire you to keep up the good order of the blessed Truth amongst you,
and let not your monthly and quarterly meetings be neglected.
Take care of the whole church of God in your nation, and delay not to help one another.
For God Almighty has set up his standard,
and his controversy is proclaimed against all unrighteousness.
I know help was needed in some places when I was with you,
and the Lord has gifted some to be of help and to rule well in the church.
We know that the apostles in their travels left the brethren decrees to keep,
and took care of the churches as they traveled, and also went to see how they did.
I hope you will take it well that I am this bold with you,
and I hope you will feel my tender love to you.

I was glad when I saw a copy of your letter to G.K.,^
footnote:[George Keith was a prominent Scottish member of the Society of Friends,
who spoke and wrote much in defense of Quaker principles and doctrines,
and even suffered imprisonment for his testimony with them.
Sadly, later in life,
because of a restless and ambitious spirit that aspired to
preeminence in the society (George Fox having died in 1690),
Keith eventually broke out into open opposition, first against specific individuals,
and eventually against the entire Society of Friends.]
yet sorry to see the answer from him, or from his wife, or both.
He must, it seems, be made manifest.
I desire that you may grow in the heavenly root,
and multiply to the glory of him that has grafted you into it.
My dear friends, in every respect be truly obedient unto the Lord, and may he,
by his own power, strengthen, establish, and root you deeply in his blessed Truth.
To him I tenderly commit you all.
He is God Almighty, even now as he was in Abraham`'s days.
To him be praise, worship, honor, glory, and renown forever more.
Amen.

Read this to all as you see a service for it,
and send honest Bartholomew Gibson a copy of it,
and let him know my dear love is to him and his wife, Francis Soneman,
and to Friends in Edinburgh.
Let copies of it be sent to all in Scotland.
I thank God I am pretty healthy, but not strong in body.
So with my true love to you all, I am your sincere friend in pure love.

[.signed-section-signature]
John Gratton

[.signed-section-context-close]
Written at Monyash the 22nd of the eleventh month, 1694

--

I stayed around home for some time and had many meetings,
and there was a fine increase in the number of Friends.
But many of them left for America (about forty from our monthly meeting,
and some others) which lessened our meeting significantly.

After some time it came upon me to go and visit Friends in Ireland,
several of whom had been in England, and a love towards them lived in me.
I gave up to go, and went to Westchester, but there we found an embargo laid upon ships,
and we could not go out.
When we could not sail for Ireland, we went to Shrewsbury,
and then down into Herefordshire (R. Needham being with me),
and to the yearly meeting in Wales, at Ponty Moyle in Monmouthshire.
This was a fine meeting, from which we passed over into Gloucestershire, to Bristol,
and into Somersetshire, to Richard Vickris`'s, at Chew, John Whiting`'s at Wrington,
and William Laurence`'s at Axbridge, and then back to Bristol to the yearly meeting there,
and then to the yearly meeting at London.

After this I returned home with my wife and stayed about seven days,
and then set out again for Ireland with Godfrey Newhall, a Friend of Yorkshire.
We went to Whitehaven in Cumberland for George Rook`'s company, and then to sea.
The winds were somewhat contrary, and for a time we were in some danger of our lives,
but at last we arrived safe at Dublin in the fifth month.
We had many precious meetings in that nation, especially in their province meetings,
and Friends were generally in sweet love, unity, peace, concord, and order.
There was good government among them, and great love and care of one another`'s families,
and for the poor and the young in all respects.
We had been at all the meetings of Friends that we knew of in the nation,
or had seen some Friends of all the meetings, and so we were clear to come away.
We left them in true love, being well satisfied in visiting them,
and so took shipping at Dublin, and came to Holyhead, and through Wales to Westchester,
and so home.
Many Friends in Ireland had a great care upon them in the oversight of the flock,
watching over them that Friends be careful in all
respects to keep their profession without blame,
and that none run inordinately after the world or break in other men`'s debt.
To prevent this they were advised to labor
lawfully for the maintenance of their families,
providing things which are honest in the sight of men.
By watching in this way over one another,
doubtless some things are prevented which otherwise
might prove a dishonor to our holy profession.

[.asterism]
'''

+++[+++After his return from Ireland,
John Gratton kept no exact account of the remainder of his travels,
though he visited Friends in diverse counties,
laboring in the work of the gospel as he found drawings thereto.
In his latter days he was afflicted with disease, which much abated his natural strength;
nevertheless he came several times to London, and particularly in the winter, 1699.
He also came to the yearly meeting in 1700,
and on his return home had many good meetings in the way,
being accompanied by John Cade to Blyth, where his wife met him.

The next year he traveled as far as Bristol, and was at their yearly meeting.
From there he went to Bath, and travelled up to London to the yearly meeting,
which fell in the fourth month, 1701.
It was a large and precious meeting, after which he returned home.
He also came up to the next yearly meeting in London, 1702.
At this time he brought up his Treatise relating to Tithes,
which was an answer to a letter, entitled, The Clergy`'s Legal Right to Tithes, etc.
In the year 1703, he came again to the yearly meeting,
visiting Friends in many places as he came.
The 26th of the second month, 1704, he set out again for London,
visiting Friends in many places as he came, as in Nottinghamshire, Huntingtonshire,
the Isle of Ely, and a great part of Norfolk, and had several meetings in Suffolk,
the last of which was at Ipswich, from which place he came to Colchester,
and was at their meeting on first-day; after which he visited several meetings in Essex,
and then came to London to the yearly meeting;
having traveled in this journey three hundred and thirty-four miles,
according to his own account.

After his return home at this time,
there is no account of his traveling for two or three years.
Due to greater weakness growing upon him, it is probable he continued close to home,
visiting Friends as he was able.
In 1707, he disposed of his estate at Monyash, and dwelt with his son Joseph some time.
He then went to visit some Friends in several adjacent places, his wife accompanying him,
though both of them were aged and weakly.
After they returned home, his wife grew weaker and weaker,
and departed this life the 4th of the tenth month, 1707,
dying in peace with the Lord and leaving a good
report behind her among those who knew her.
The account of her death he gave himself,
saying she had been a very comfortable wife to him for nearly thirty-eight years,
adding that she had never hindered him from going abroad to visit Friends.

In the year 1708, he took a journey to London again,
and went into some parts of Essex, Surry and Kent;
after which he returned to London again.
While he stayed at home he was taken ill,
and his weakness increased upon him until he removed
out of the city for the benefit of the air,
to Richard Richardson`'s, near Uxbridge, where he was carefully attended for three weeks.
During this time, several Friends of London went to visit him.
From this place Daniel Wharley took him to his house; and from there he went to Ailsbury,
and by small journeys he got home (Richard Needham accompanying him).
He continued living with his daughter above three years, being weak until his decease,
which was in the ninth month, 1711, aged about seventy years; dying,
no doubt in peace with the Lord, and unity with all the faithful,
and is entered into his everlasting rest among the faithful followers of Jesus.]

[.embedded-content-document.testimony]
--

[.blurb]
=== Phebe Bateman`'s +++[+++John Gratton`'s daughter] Testimony Concerning her Dear Father and Mother.

"`It has been much in my mind to give a short account
of the latter end of my dear and tender parents,
it pleasing the Lord so to order it that they
both finished their days with me at Farnsfield,
in Nottinghamshire.
They stopped keeping house at Monyash, in the fourth month, 1707,
and went from there to my brother Joseph`'s, and after a short stay there, came here.
My dear mother had been weakly about half-a-year before, but then was a bit better,
and took a journey with my dear father.
She had a tender care for us all, being a very affectionate, loving, tender mother;
and in our bringing up, she had an eye to the Lord,
that we might be trained up in his fear,
and she was not slow in reproving us for any appearance of evil.
My father being about five and half years in prison when we were but young,
the tuition of the children fell mostly upon her; and as we grew up,
she would often advise us to diligence and carefulness, not only to the Lord,
but in the outward affairs of the world, that we might not be a burden to any.

Her weakness of body increased fast upon her,
so that she much desired her time here might not be long, if the Lord saw it good,
yet she was freely given up to his holy will, and would say to me,
"`Do not desire my life, but give me up freely.
I know I might have been helpful to you if the Lord had been pleased to order it,
but my desires are more to be gone, if he see it good, than to live any longer here.`"
She had a tender regard in her mind for dear father, that he might not be neglected,
and I being pretty much taken up in attending her, she would often say,
"`Do you take care of your father?`"
For as their love and sympathy had been great in all times of trial,
so it continued to the last.
I believe she never hindered or discouraged him once
from going out in the service of the blessed Truth,
but was an encourager of him,
and in his absence was very diligent and careful that
nothing might go amiss to make him uneasy at his return,
so that he was much at liberty to serve the Lord
for many years before he gave up keeping house.
Towards her end,
she was preserved in much patience and resignation to the will of the Lord,
often saying she had hope in him.
She was very sensible to the last,
and departed this life in much quietness and stillness,
as if she had been going to sleep, without either sigh or groan,
the 4th of the tenth month, 1707.
I believe she is entered into the rest which is prepared for the righteous,
in the sixty-fifth year of her age,
my parents having lived together nearly thirty-nine years.
She was buried the 7th of the tenth month, in the burying place of Friends,
by the meeting-house in Farnsfield,
with many Friends accompanying her body to the grave.

My dear father was then very weakly,
and the loss of my dear mother was a near trial and exercise to him;
for indeed she had been, as he himself said, a sweet help to him in the Lord.
He was deeply bowed in spirit for the loss of her, yet freely gave her up to the Lord.
He was now brought so low and weak,
that few who saw him thought he would continue long after her,
but it pleased the Lord in his great love and infinite goodness,
to raise him up in some measure.
Though he continued weak all along,
he was enabled to go up to London the following summer to see and visit Friends,
being out near half a year, in which time he had several fits of illness,
but the sorest time was at the house of R. Richardson (he and his wife being
very tender of him.) Yet his desire was great to get to my house,
if the Lord saw it good; and he was pleased to raise him up again,
so that he was enabled to get home the 29th of the seventh month, 1708.
He continued weakly, being attended with various exercises,
which often brought him very low,
though sometimes he was enabled to take a little journey to visit Friends.
The last winter he sensibly decayed, so that he would often say to me,
he could not continue long, his stomach being so weak,
he could take little food for several months before he died.
His desires were great to go from here, if the Lord saw it good;
and as his weakness increased,
his desires grew stronger and more earnest with the
Lord to remove him out of this troublesome world,
being well satisfied his day`'s work was over; yet he desired to wait the Lord`'s time.

My eldest daughter being then very ill,
he often gave good advice and counsel to her, to fear the Lord,
and be obedient to her parents, with more to that effect to all my children.
About a month before his decease,
I was called on so suddenly that it was thought he could not live till I came to him.
I found my children and the maid weeping, thinking he would not have spoken again,
but when I came to him, he broke out into tears, saying,
he thought he should never have seen me more.
Soon he got a little strength to sit up in his chair, and called all the children to him,
one by one, and kissed them, giving them good advice,
saying it was a great comfort to him to see we should
part in so much love and unity one with another.
Then, calling for the maid, he spoke very tenderly and lovingly to her.
Being attended with sore sickness and pain, he said, "`Lord, I pray you give me ease,
if it be your holy will, and remove me soon out of this body.
You know it is through your great mercy that we have hope in you.
Lord, I pray you, be with my children that I leave behind,
and with all friends and neighbors, whatever their profession.
It is through Christ Jesus our Advocate, who is gone before us,
that we are enabled to come to you.`"
His pain and exercise of body continuing, he said again, "`Lord, if it be your holy will,
remove me out of this troublesome body.`"

Another time, I told him some Friends had come to see him,
to which he said they might see he was a weak man,
and then looking on them as they sat by him, he said, "`The Lord bless his people,
and prosper his Truth amongst them, and enable them to live in love one with another.`"
Not long after, weakening very fast, he said,
"`Lord, I freely commit my soul and spirit unto you,`"
desiring to have his dear love given to Friends,
naming several in particular.
A little before he died he told me he thought he should be gone in half an hour,
being very sensible to the last.
He departed this life on the 9th of the first month, 1712, and is, I hope,
at rest with the Lord, where the wicked cease from troubling,
and where the weary are at rest.
He was buried beside my dear mother the 11th of the same,
in the sixty-ninth year of his age,
having been convinced of the Truth about forty years.`"

[.signed-section-signature]
Phebe Bateman.

[.signed-section-context-close]
Farnsfieid, 1712.

--
