[quote.epigraph, , Dan. 12:3-4]
____
Many shall run to and fro, and knowledge shall be increased.
And they that be wise shall shine as the brightness of the firmament;
and they that turn many to righteousness, as the stars forever and ever.
____

[quote.epigraph, , Acts 10:34-35]
____
For God is no respecter of persons: but in every nation he that feareth him,
and worketh righteousness, is accepted with him.
____

== Chapter I

It hath often been in my heart to write a short account, to leave behind me,
of the Lord`'s gracious dealings with me, and of the great mercies,
which in his infinite love, he hath freely bestowed upon me,
far beyond my deserts or expectation, to my great joy and consolation; praises, thanks,
glory, honour and renown, be given and ascribed unto him; for he alone is worthy,
God over all, blessed forever, amen.
To the end that my children and others, who may see these lines,
may be encouraged to trust in the living God, and to cast their care upon him,
and obey him truly; for he never fails them that put their trust in him,
and abide in his blessed counsel.

When it first pleased the Lord to visit me, and to cause his light to shine in me,
which is now my life, I was but a child, and was keeping my father`'s sheep,
and was addicted to sin and vanity, for which I was reproved and smitten inwardly;
and it was made manifest to me that I was not in a state of salvation,
nor had I any true peace in my mind;
but whenever I came seriously to consider my condition, I found an accuser near me.
I also found, that He who reproved me for sin, and showed me the deceit of my heart,
also counselled me to embrace truth and righteousness, and was always with me,
to instruct me, and guide me in the way of holiness,
and advised me to sin no more in word or deed, but always to speak truth.
When I took his counsel and followed his advice, then was I easy,
and my burden seemed to lighten, and it would give me encouragement to hold on,
and take heed to that good Spirit in me, which thus instructed me to Godliness,
and to shun that which was evil.
I found, as it were, two spirits working in me, both striving to gain me,
the one from the other; but I found the good Spirit, for so it was,
always counselled me to do good things, and when I was obedient to it,
then I found the evil spirit could not break my peace: and had I stood here,
and always lived in the counsel of this good Spirit of instruction,
and never rebelled against it, then had my peace been as a river.

I was about ten or eleven years old, when the Lord visited me with the light of his Son,
and gave me to see the vain life and way I lived in,
being much given to play amongst rude boys, and took great delight in playing at cards,
and shooting at butts, and ringing of bells, for which I was reproved.
I came to see that vain sports and pleasures were displeasing to the Lord,
which I was inclined to,
before I came truly to know the Word of God in my heart and mouth, to hear it and do it,
and was judged in myself for the same, but knew not the Judge, being but a child.
I did not yet know the Lord,
nor think it had been he who met me in my heart and conscience,
and told me all that ever I did, and made all things manifest that were reproved;
though I had read in the Scriptures,
that Christ was come to redeem from a vain conversation, to serve the living God;
and Christ taught to pray, "`Thy kingdom come: thy will be done in earth,
as it is in heaven;`" and said, "`I came not to do my own will,
but the will of him that sent me;`" and,
"`not my will but thy will be done,`" when he was to drink that bitter cup, of the cross;
and, "`he that will be my disciple, must deny himself,
and take up his cross daily and follow me:`" and so the cup he was to drink of,
and the baptism he was to be baptized with,
they should +++[+++also drink of and be baptized with.]
Oh! it is beyond words, or the depth of man`'s wisdom to reach,
and yet we must drink of it, and be baptized with his baptism.
It was he that appeared in me, when I was young, though I knew him not,
but followed hireling priests, Presbyterians, etc., yet was uneasy among them all.

When I saw that I lived not as I ought, a fear came over me,
and I sat down upon the ground, and was very serious;
and thought to live more carefully and holily for the time to come.
And when this mind was begotten in me, I felt and saw the grace of God appear in me,
but I knew not what it was, yet I would gladly have held it,
and have kept the enjoyment of it, but did not; for being young,
my mind got out again after vain and childish sports, and sinful, foolish pastimes,
when I met with my companions, sporting myself in earthly things,
and so fell from the counsel of the heavenly, and lost the sense,
sight and feeling of it; so that trouble and sorrow of mind came over me.

Thus I lived for five or six years; and as I grew in years, so it increased in me:
yet did I often find the heavenly Monitor meet with me,
and sometimes did sharply reprove me, and sometimes gently instruct me;
and at last clearly opened my heart to me, and did break my peace,
and caused his terrors to seize upon me, and I was wounded at my heart,
and great was my sorrow, and my tears were many, and I knew not what to do.
Yet in this state of sorrow, I sometimes had a secret hope,
and this kept me from sinking under the great weight that lay upon me.
This gave me courage to pray to God, though I knew not how to pray; but yet I thought,
that in secret, where none could hear or see me, I could pray best,
and could confess those sins, and pray for forgiveness and for power over them,
that I was not willing men should know of.
But still I found not power to forsake the sins I was so prone to,
because I received not him, to whom all power is given, nor yet knew him.
I little thought it had been He who told me all that ever I had done,
and searched out all my secret sins; there was nothing hid from him,
but he discerned the very thoughts and intents of my heart,
and I was even laid naked before him, and could hide nothing from him;
yet his appearance seemed such a poor, low, despised thing, that I believed not in it,
nor thought to have found Christ in me, but looked for him,
or concluded him to be in heaven, above the skies.
And though he appeared to me wonderfully by his Spirit, yet I did not know him,
but still rejected his counsel, and came not to him, to be taught by him,
though he had long waited to be gracious to me; glory to his Name forever,
for he made many things manifest to me.
Great was the travail of my poor soul;
and all outward things sometimes seemed little worth to me, and I cried unto the Lord,
that he would tell me what he would have me to do, and that he would show me,
who were his people, that worshipped him aright, according to his will.

I read much, and conferred with many about religion, and ran to and fro,
to hear those that were accounted great preachers,
but neglected the great Teacher in my own heart.
I esteemed the priests that were then in place, in Oliver Cromwell`'s time,
and went constantly to hear them, but often came home full of sorrow;
for I was not satisfied with their doctrine of election and reprobation,
which put me into deep trouble,
and I was sometimes very near concluding that I was a reprobate;
my state appearing to be a state of sin.
Yet I believed, that men who were in Christ, were elected, but men out of Christ,
are out of the way to God; for Christ is the elect and chosen of God,
the heir of all things, and all that are in him, are co-heirs with him.
If Christ be theirs, then all is theirs;
and Christ is all in all to them in whom he lives and reigns.
But if Christ be not in them, they are reprobates, without God in the world,
dead in sins and trespasses, and all they do are dead works, dead prayers,
dead preaching, dead worship and performances;
and many are seeking the living amongst the dead, and among dead ordinances, dead faiths,
dead observations, and dead professions.

My sorrows increased; yet I strove hard to get ease, and read much,
and prayed much in secret, and went to hear sermons very eagerly.
I was now become one of the Presbyterian church, and had been much among them,
and told some of them part of my condition.
But, alas! alas! they could not help me; no, nor themselves neither; but would tell me,
it was a good condition, and I must be troubled with my sins as long as I lived,
and the best of God`'s children had all along their failings.
All this was to persuade me to sit down contented,
before I was cleansed and washed from my sins.
Oh! these were the physicians of no value;
these were they that daubed with untempered mortar, and cried, peace, peace,
when there is no peace at all experienced.
So that my sorrows increased upon me,
and when the people sang psalms in the steeple-house, and I have been there,
I durst not sing the same sayings of David, as they did:
it would have been a lie in my mouth; for I saw I was not in the condition David was in,
nor could I sing it truly, as my song;
and if I had I should have said or sung a false thing as to myself.

My sorrows still increased night and day, and my tears and fears also were many:
and sometimes, when I secretly prayed unto the Lord, and confessed all my sins,
and begged of the Lord forgiveness, and used many words, some of which, it may be,
I had learned of the priests, and some that were real, according to my state; yet,
when I had done, I was condemned, and full of sorrow,
and my spirit would sometimes be more heavy laden after I had done, than before I began,
being condemned in myself, that I had not prayed in faith, nothing doubting;
nor in the spirit of prayer and supplication, and I could find no rest to my poor soul.
I mourned deeply be`' cause I was unholy, and unrighteous,
though my neighbours thought better of me, for I saw my sins and trespasses were many,
and believed the Scripture that saith,
"`No unclean thing can enter the kingdom of Heaven,`" and without "`holiness,
no man shall ever see the Lord.`"
I mourned deeply, and was ready to think, that my heart was not right in the sight of God.
I prayed much in private in the stable and barns, and in bed, and on the high-moor.
One day, being alone on the top of a hill, in the snow,
I cried aloud with strong cries to the Lord, and desired him to show me my own heart,
and the Lord was pleased to hear and answer my prayer, at that time;
so that he gave me to see my own heart,
that I knew it was the Lord that did show it to me, to my satisfaction;
for I plainly saw it to be deceitful, and not a good, humble, pure heart.
I was pleased that I saw it, and knew what it was; but sorry it was so very bad.

This was the first time, to my remembrance,
that I was sure the Lord gave me an answer to my prayers.
But I had deep sorrow, yea, very deep, and sometimes I was ready to say, Oh,
that I had never been born! watering my pillow with tears;
but it pleased the Lord to put it into my mind to be content, and wait the Lord`'s time,
for him to give me further knowledge of his will.

For a while I lived in great sorrow and fear, and trouble.
Oh! it was undeclarable; so that in the morning, I was glad that the day was come,
and at night, that night was come; and I was apt to think,
that no man`'s condition was ever like mine.

About this time, king Charles the second came to the crown;
and after a while uniformity was concluded on, and enacted,
that none must have liberty to preach in churches, so called, but such as would conform,
and read the common prayer,
and observe those ceremonies that were set up by the Episcopalians, or else be silent.
Then the Presbyterian priests, whom I had so much esteemed and admired,
made their farewell sermons, and left us;
for they liked not to conform to the common prayer themselves,
and so would not venture to stay with their flocks; which caused me to weep bitterly.

Whereupon it came into my mind to search the Scriptures,
to see whether those the Lord sent forth to preach the gospel,
in the demonstration of the Spirit, could be silent at man`'s command,
though they were men in authority that forbade them.
And whether these, who now pretend to be his ministers, could, according to Scripture,
be clear to leave their flocks and congregations, in the will of man, yea, or nay.
For I believed that if God had sent them, and set them up,
then man ought not to pull them down.
I likewise found it clear, by the Holy Scriptures,
that they ought not to be silent at man`'s command,
if the Lord had sent and commanded them to preach; but to obey God rather than man,
when the Lord commands one thing and man another; as the three children and Daniel also,
who patiently bore the wrath of the king,
and were put into the fiery furnace and lions`' den; they trusted in God,
and he delivered them.

I found in Isaiah Ixii.
that, in plain words, the Lord commanded those that make mention of the Lord,
not to keep silence.
And when the rulers of the Jews commanded the apostles
not to preach any more in the name of Jesus,
they answered with a query, "`Whether it be right in the sight of God,
to obey men rather than God, judge ye.
For we cannot but speak the things which we have heard and seen;
and they went straitway into the temple, and preached or taught.`"
In the next chapter, when the Lord delivered them out of prison,
they went again into the temple and taught, and one came and told the rulers,
"`Behold the men whom ye put in prison,
are standing in the temple and teaching the people.`"
Then they sent for them before the council, and the high priest said,
"`Did not we strictly command you, that you should not teach in this Name, and behold,
you have filled Jerusalem with your doctrine,
and intend to bring this man`'s blood upon us,`" Then Peter,
and the other apostles answered, and said,
"`We ought to obey God rather than men:`" and forthwith, to their faces,
they preached boldly, and did not keep silence, nor flee their testimony,
as these priests did in those days.

And that able minister of Christ, the Apostle Paul, said, "`Necessity is laid upon me,
and woe is unto me, if I preach not the gospel.`"
He and they had the gospel to preach, and knew it to be weighty and powerful,
and were filled with the Holy Ghost, so that they could not contain, or be silent,
for if they had, they had felt the woe.
Men could not silence them, though they used violence to them;
for they chose to suffer rather than to be silent; for to be silent they durst not,
seeing their great Lord and Master had commanded them to preach;
nor silent could they be, unless they would bring themselves under that woe,
which man could not take off.
Though they imprisoned them, whipped and stoned them, and used great violence to them,
yet they testified,
even to the very faces of those kings and rulers they were brought before,
of their way of worship, and of the Truth and Life that is eternal;
not valuing their lives, or counting them dear unto themselves.

Meeting with the priest, who had lived in the parish where I did, I spoke my mind to him,
and told him,
that I believed if God was pleased to fit and qualify men for the work of the ministry,
gift them for it, and send them to preach, they ought to obey God;
and if men forbid them to obey God,
they ought not to forbear their obedience to God to please men;
nor to be silent at man`'s command, if God command them to preach or teach,
as he did his servants of old time.
Those he sends in these days ought to be obedient to God, though man be displeased,
and cause them to sutler for righteousness sake; the Lord is God, and will help them,
and recompense them into their bosoms an hundred fold in this life,
and in the world to come life everlasting.

He told me that he preached in his own hired house, as Paul did at Rome,
and was not silent; but that did not satisfy me, for Paul was a prisoner,
and they were not.
Had they stayed till they were pulled out and put in prison,
then they had done like men that trusted in God,
and it was a question whether men would have had power to take them from their flocks;
but they fled and left us.
I having searched the holy Scriptures, and found that they were contrary thereto,
and that both the Old and New Testament were against them;
and that if they had been true ministers of Christ, they could not be silent,
though they had laid down their lives,
not knowing but after them grievous wolves might come in,
I was fully persuaded in my mind upon the aforesaid grounds,
that the Presbyterians were not the true ministers of Christ;
and I felt my mind turned against them, considering, if God had sent them,
they should have stood in their places; but if they were not sent of God,
then they run before they were sent, and were not the men that I had taken them to be;
and now they were manifest.
So I left them, and saw they were like those spoken of by our Lord in the 10th of John,
who were hirelings, and not true shepherds; for when they saw the wolf come,
they left the flock and fled; but the true Shepherd lays down his life for the sheep.

Whither to go, or what to do, I knew not; therefore I was much grieved,
and could not tell who the people of the Lord were, but often cried.
Lord! show me who are thy people, and they that worship thee aright.
I pray thee join me unto them, and enable me to serve thee, that I may enjoy thy presence.
Had I then joined to the Lord, and to the gift or grace of God that appeared in my heart,
and believed in it, and obeyed the teaching of it,
I should then have been joined to the Lord in his spirit,
and also have been brought to them who were in the Spirit before me;
for they are his true worshippers who are in the Spirit, and in that, worship God aright,
who is a Spirit.

The Presbyterians being removed out of the pulpit, and out of my heart also,
then the Episcopal priests came in their white surplices, and read common prayer,
with long composed forms, that we had nothing of in the holy Scriptures;
which was as a dead, empty sound to me, and my spirit was grieved with it,
for I met with nothing at all of the life or power of God in them;
so that I saw they had a form without the power.
If this had been the form of Godliness, yet being without the power,
the Scripture exhorts from such to turn away; and the power that they came in by,
was the same that the others were put to silence by;
and this power had authorized the priest to compel all to buy his wares,
and if any refused, he had power given to excommunicate him out of their synagogue;
and then, though he would not have his ware,
yet he had power to make him pay for it when he was cast out.

Hearing that all must go to this form of worship, I also went to worship I knew not what.
When I came, who should come to carry on the work but an old Presbyterian,
who had spoken much against the common prayer,
and those ceremonies then commanded by men to be used.
But rather than lose those great benefits that yearly came in,
for praying and preaching to the people,
he swallowed down that which before he had vomited up.
I observed their worship, and I searched the Scriptures again and again,
and found the power they stood in not to be the power of God, but of men.
I found that God commanded, "`Whatsoever ye would that men should do to you,
do ye even so unto them, for this is the law and the prophets;`" but they went contrary.

The Lord commanded his servant Paul, saying, "`Pray always,
with all prayer and supplication,
in the spirit;`" but I found the Episcopal prayers in a book.
I found the worship God required, to be in spirit and in truth;
but the Episcopal worship was in ceremony and outward external things without life.
I found the Lord commanded in the New Testament, not to observe days and times,
and months and years; but these priests commanded days to be observed, one above another.
The Lord commanded his ministers, saying, "`Freely ye have received,
freely give;`" but these gave nothing freely, but sat ready to receive,
and compelled people to give them.
Finally, I found them in nothing suitable to the Scriptures, and as I then concluded,
none else were, but like the false prophets who were spoken of in Scripture.
Then I absented myself and did not join with them,
but was separated from them by the Lord, blessed be his name forever,
who hath been gracious to my soul, far beyond what I can express;
living praises be given to his holy Name, forevermore.

I left them, with their dead forms, dead sounds, dead works, yea, all seemed dead to me;
and to slay there, seeking the living among the dead,
would not profit my poor soul at all.
I had this saying in my mind; Whoever is right I know not; but these are wrong,
their eyes are blinded, their ears are dulled, their hearts are proud, carnal, covetous;
greedy after their gain, and they do not profit the people at all;
and if they leave people, after ten, twenty, thirty or forty years tithing them,
yet they are no better for all the charges they have put them to;
they are "`miserable sinners`" still, and likely to be so.

Though this was seen by me, I still had not that wisdom to come to the true light,
which made them manifest to me; but was considering, in my own wisdom, what to do,
and yet could not tell, or find out the true worshippers.
I heard of a sort of people much commended, who used to meet in private houses,
in great fear of being persecuted, but were much commended by great professors,
whom I looked upon to be understanding men.
I went to their meetings, some of whom were called Independents, some Presbyterians,
and some Anabaptists.
I found some of this mixed multitude believed that
God had elected a certain number to be saved,
and had reprobated all the rest: others of them held forth free grace,
or Christ a gift freely given to all.
Some held baptizing infants in water; some said nay,
none ought to be baptized in water till they believe: some baptized not at all.

But the great thing of all I met not with among them, viz: the Lord to my comfort,
nor could I see the power of God upon them, or amongst them; but pride abounded,
slandering one another, foolish jesting, vain talking,
fashioning themselves according to the customs of the world,
many of them conforming so far as to go one while to their own meeting,
and another while to the steeple house,
though they had much to say against the steeple-house worship.
I saw they feared man greatly, as it appeared; for the law of man coming forth,
with great penalties upon all separate meetings, they refrained,
and were not to be found, and kept silent, rather than hazard this world`'s goods.
So I was still in great trouble of mind, and knew not what to do;
for the Lord was what I longed for, and to glorify him was my desire;
but I found not wherewith.

Then I went to Chesterfield, to seek out and meet with those people called Independents;
for I liked the name, seeing nothing at all in man to depend on;
but they depended only upon the death and sufferings of Christ in his own body,
yet did not come to see him nor his appearance in themselves to be their life,
and had not heard his voice, and the Word of God they had not abiding in them;
so were dead professors, and dry trees, not bringing forth fruit.
But they preached free grace, universal love, general redemption,
and tendered mercy to all.
This pleased me well,
far better than the Presbyterian doctrine of election and reprobation;
yet I was not satisfied nor easy, for I read Scripture very much,
and saw by reading the Scriptures, with the secret help of Almighty God,
which he afforded me in his infinite love,
that as many as were led and guided by the Spirit of God, they were sons of God;
and that, if any man has not the Spirit of Christ, he is none of his.
This is such a clear distinction between the children
of God and the children of the wicked one,
or the children of this world, that there is no uniting them.
This is clear from the holy Scriptures.
For light and darkness are opposites; and Christ and Belial,
believers and infidels are past uniting, without a new creation, a new birth,
which the unconverted are encouraged to wait for, seek for, beg and hope for.

I saw, that without the enjoyment of God in my own soul all was in vain;
it was little comfort to me to read and hear what other men had enjoyed,
while I wanted it.
The wise virgins`' oil would not serve them and me too.
I saw that a little measure of the Spirit of God
was more precious than all this vain world;
and that short of this I could not rest.
I made my remarks on those Independents, and saw they were very proud,
and afraid of men and sufferings; and when we went to meetings,
we were cautioned to go as privately as might be; so that they went several ways,
one under one hedge side, and another under another,
that we might not be taken notice of.
Then, when we came to the meeting places,
scouts or watchers were set to see and to give notice, that if a magistrate came,
we might all run away and break up our meeting.
This seemed a wrong thing to me, and it displeased me;
for I saw that they were not like the disciples of Christ,
who were not ashamed or afraid to own Christ before men.
This doing did not tend to spread the gospel, if they preached it.

I got no true peace with God among them, nor enjoyment of the Lord in my poor soul.
Whereupon I left them, and all churches and people,
and continued alone like one that had no mate or companion;
yet at times some hope would arise beyond my expectation,
and I believed God had a people somewhere.
But I knew not who they were, and was now afraid to join with any,
lest they should not worship God aright; and then I might be guilty of idolatry,
which I had often observed the Lord had been much offended at among the Jews,
and not only threatened them sorely by his prophets,
but also brought judgments upon them, for their idolatry and rebellion against him.

The sorrows of hell took hold on me and the very pangs of death beset me round;
which way to turn I knew not, but I could find none to comfort me,
or lend me a hand in my tears, fears, terrors, grief, amazements, bitterness,
anguish and deep mourning.
Yet was I forward to discourse and talk with many about matters of religion,
who would talk with me, for many had a love to me, but the priests I saw were in deceit,
and I was sharp upon them at times;
and my sorrows were so great that sometimes I roared out,
and cried mightily to the Lord when I travelled upon the plains and moors,
and thought none was near to hear or see me but the Lord alone,
who was the only one to whom I did look and hope in for help and deliverance.

Now it pleased the Lord to open and show me many things;
and he opened holy Scriptures to me sometimes,
and I was mightily afraid of sinning against the Lord, so that I walked carefully.
It grieved me to see people live badly, and that they could not believe one another,
what they said when they bought and sold; and when I heard a man swear I trembled.
Sometimes I felt something in my inward parts that was very precious and sweet to me,
yet I did not clearly understand what it was;
but if at any time I did or said any thing that was not right,
then I soon lost the sight and feeling of that.
Oh! it hath been gone in a moment:
I saw that everything which offended the holy God and was reprovable, would not abide,
but all defilement, and whatsoever was tinctured with evil was against it,
and it let me see it and condemned it, and me too so far as I joined with it.
Oh! this to enjoy is a comfort beyond utterance,
to that heart which loves righteousness and hungers after it.
When I have been talking with a person who saw not that I spoke a wrong word,
yet I have seen it, and the Lord`'s spirit gave me to see it, though it may be,
it slipped from me at unawares for want of diligent heed, and watching like a doorkeeper,
as I ought to have done; and then my sorrows would be renewed upon me,
and tears and fears in abundance.
Yet a secret desire was in me, that I might die, and go out of this wicked, sinful world,
where I found it rare to find a true-hearted man or woman.

One first-day, after I had been reading one while and weeping another,
under a wall in a field, about the middle of the day I came home,
and found my father and mother were come over to see us,
for I then lived with my grandfather an apprentice,
and I thought they would hinder me from minding the exercise I was in, which was deep.
In the afternoon I fell ill of bodily sickness; and when I felt my illness grow upon me,
I was glad, and in some hopes I should be taken out of this world;
for I was plainly sick with trouble of mind; yet a secret hope was underneath,
that if I did die, the Lord, who is gracious and merciful,
would forgive the sins of my childhood and youth.
After I was pretty well again, I went to the moor to pull heath, and being alone,
as my manner was, I was very full of exercise,
and began to think that that which I had sometimes felt so sweet and precious,
and sometimes as a swift witness, a reprover, a just judge,
and a condemner of all unrighteousness, was the holy Spirit of God;
and remembered that I had been often visited by it, and yet did not know it.
For I thought I was not worthy to have the holy Spirit given me,
and that it would be presumption in me to expect it; yet now it came into my mind,
to think much of it, and of its operations and workings in me.
It darted into my mind, that it was really the Spirit of truth, and I had not felt it,
nor seen its appearance for some time past; and then I was full of fears,
lest I had sinned against the Holy Ghost;
and such terror fell upon me that I durst not tarry upon the moor,
but arose,--for I was lying on the ground,--and got away home.
I remembered what made me so desirous to die the day my parents came to see us,
when I had been reading and weeping much, and such a tender frame came over me,
that a hope sprung up in me, that if I died in that frame of spirit,
the Lord would have mercy on me,
so that I was desirous to die while that frame and hope continued.
Yet after all this, I fell into trouble again, and sorrow took hold on me:
in this time I happened to meet with a young man that was
dissatisfied about matters of faith and worship;
and we appointed to meet on the first-day after at a woman`'s house,
who was called a Quaker; but I did not know that till after,
or but little of any such people, though I had heard of them.

When the day came, we met, and it fell out that two other men came and met with us;
they were both called Quakers, but had not been long so.
This day we spent mostly in discourse:
one of the men was of small appearance and slow utterance,
and one that never used to preach in meetings;
yet that day the Lord`'s power came upon him,
and he so spake that he reached the witness of God in me;
and I thought that that exercise came upon him in mercy to me.
But, alas!
I had entertained such hard thoughts of these people, that I went homeward very sorrowful.
My cry still went up to the Lord, that he would show me Zion, the city of my God,
and who they were that dwelt therein.
And that first-day, as I was alone, and in great exercise of mind about these things,
it pleased the Lord to show me his people who served him.
As I walked along through a dark wood, I was so exercised that I scarcely knew how I was;
and as I came out of the wood to go up a hill, I had a vision,
and I saw a people laid close one by another in a very low place,
lower than the other parts of the earth, where they lay still and quiet,
I looked upon them; for it rose in my heart, that they were the Lord`'s people.
This made me look earnestly, to see who they were, that I might know them to my comfort,
whom the Lord owned for his people;
and I saw plainly that they were the people called Quakers, a poor, despised,
low sort of people.
When I perceived this, I was as one amazed and in great trouble;
for these were a people of all others that endured the greatest sufferings,
and were by all the rest hated, reviled and scorned.
As I walked on, the vision ended; but I was in a strange frame,
and considering the matter, I felt a change in me,
and I knew that my countenance was altered.
I drew near a little village, my way lying through it;
but I had a mind to escape being seen as much as I could,
because I concluded that they would take notice that my countenance was much altered.

But it fell out, that when I had got almost through the town,
there was a woman saw me and called to me, though I went as far from her as I well could,
to keep in the road.
She asked me how I did, and what ailed me to look so?
I gave her little answer, but said, Not very well; so passed on,
and coming to a style that was upon the top of a high hill, I sat down upon it;
and there it was showed me, that if I would be a true follower of the Lamb,
I must forsake the world, its corrupt ways, fashions, customs, worships,
and all the vain glory, love and friendship of it.
I saw, if I now came into obedience to the Lord, who had thus graciously heard my cries,
and answered my breathings, or rather, the breathings which he had begotten in me,
that I must part with all the repute, friendship, love and praise of men,
which I then had, and lived in; and must forsake my old companions,
with whom I had wasted much precious time in vain sports and gaming,
which we lived and delighted in, with many other things I prized highly;
all which I must now let go for the Lord, if I would choose and follow him.

At this I was much troubled, for I was very loath to lose either,
and would gladly have had both the love of God and the love of men too:
I would have enjoyed both God and the world; but could not.
My love to these vanities was so great, and I prized them so much,
that it went very hard with me, to think of losing all for Christ, yea,
even as bitter as death almost to me in appearance;
for the love and favour of the people I valued highly, and the cross seemed so great,
that I could then by no means persuade myself to take it up.
Great was the conflict I was in, and a very sharp war there was in me:
yet I did not disclose my condition to any, but kept all in secret from man.
But the All-seeing eye beheld me, and suffered me not to be overcome,
nor the enemy to destroy my poor soul, though he suffered him to try and prove me,
till the Lord was pleased to raise up his living witness in me, which I admired at,
and could not tell what it should be,
and did not know that it was the grace or gift of God that brings salvation,
which appeared to me, though I had grieved it, and disobeyed it,
till it seemed to grow less and less,
and to withdraw so long that I could see but little of its appearance.
Yet it never wholly left me, though I rebelled often against it; but still it rebuked,
reproved and judged me, that I could not be at peace, because it loved me,
and would not let me alone, but waited to be gracious to me;
but I was loath to take the counsel of it.
I was greatly exercised in my mind, and was dissatisfied about the things of eternity,
and my sorrows were deep, and no man knew them.

Before I got home,
the enemy came near as if he would have whispered in my ear these words,
"`Who knows but this may be a trick of the enemy,`" meaning the vision;
and presently there appeared a part in me which was seemingly pleased with this whisper,
and said, It is very likely it may be so.
Thus old self sought to save himself.
Then I remembered that the priests of those days had preached down all such things,
as not to be looked for in these days, but said, visions,
revelations and miracles were all ceased,
and that it was presumption for any man to look for
the Spirit of God to be given him now as formerly.
So I threw off all again, as a dangerous thing, and would take no further notice of it.
I even desired, and was ready to say in my heart, Oh! that the Lord would please,
in these perilous times, to speak audibly to some man, as he did to Moses,
that we might assuredly know his mind; seeing one cries, Lo, here! and another, Lo,
there!
But Christ, the power of God is in none of them.
So great blindness and darkness seized upon me, and woeful ignorance,
when I had rejected the Lord`'s counsel,
and trampled such an extraordinary visitation under my feet, and turned my back on it,
as the work of the enemy.

I have great cause to admire the Lord`'s mercies towards me,
that I was not wholly forsaken by him, for his eye was still over me,
though for a time I was in deep darkness and distress, and my concern was very great.
In which time I conferred with many men of several opinions,
but I found none that could help me in this matter,
because I came not to Him that is mighty, on whom help is laid.
Thus was I like a bird alone in the wood, without a mate, joined to none.

In this state I met with an unexpected exercise; for within a few days after this,
one first-day, there came to me a young man who was full of inquiry, and a great seeker,
who told me there was a book lately come out,
that had the greatest mysteries in it that ever were, as far as he knew;
and that God had spoken audibly to one John Reeve of London, or thereabouts,
and had told him his mind, and bade him go to one Lodowick Muggleton,
and he should be as his mouth, as Aaron was to Moses,
and had given them commission above all men, and power to bless them that believed them,
and to curse them that spoke against them; and whom they blessed, they said were blessed,
and whom they cursed were cursed to all eternity; with many other strange things.
I greatly desired to see the book; for this, if true, was the thing I had desired,
and I thought with myself, that no man durst presume to say such a thing,
except it was really true.
In a few days I went to Chesterfield and saw it, and as one that had my wish,
I read it eagerly; and upon reading where he saith the Lord had spoken to him,
and given to him and Muggleton a commission;
and that they were the two witnesses spoken of in the 11th
chapter of the Revelation 1 was ready to believe it.

I borrowed the book then, and afterwards bought it, and as many other of his books,
as cost me eight shillings, and read them through several times,
and concurred with him in many things,
and at last I was so taken with the story that I was likely to be deceived by it,
and also the young man.
Then it pleased the Lord in mercy to visit me again,
to open mine eyes and enlighten my understanding,
and he gave me to see great errors in the book;
that his writings were clearly opposite to the holy Scriptures in many respects;
for they that were of that opinion,
and carried away to believe the false prophet Muggleton, for Reeve was dead,
had no worship at all.
When we met together--those few that were at one widow Carter`'s--we
were not for either waiting upon God,
or for any other exercise at all of either preaching, praying,
or reading holy Scriptures: no, we had no more to do, but to believe Muggleton,
and be saved.
So we spent some time in discourse, and then parted.
I saw it was clear from the holy Scriptures,
that the Lord was pleased men should worship him, according to his own will, in all ages,
and would be sanctified in the assembly of his saints,
and had in reverence of all that were about him:
but there was nothing of this among the Muggletonians.
And though the Lord had said that, "`Where two or three are gathered together in my name,
there am I in the midst of them,`" this neither they nor I knew any thing of,
but were to trust in Muggleton`'s name and power; and if he blessed us, we were blessed,
live as we would: But if he cursed us, we were cursed; there was no remedy.

This doctrine I found was contrary to the doctrine of Christ, the true prophet, who said,
Bless, I say, and curse not.
But I found that Muggleton`'s spirit took more delight to curse than to bless.
I wrote a letter to him and made twelve or fourteen objections against his doctrine,
and sent it to him at London: to which he sent me a letter, and referred me to his books,
but did not answer any of the objections;
but told me he judged I wrote in ignorance and inquiringly,
and therefore forbore to curse me till further trial.
But I left him, and sat down satisfied that he was a false prophet.

But I was like a man in a cloud, no body saw my case,
and I hardly saw it myself as I would.
In this time I was sorely tempted, and yet some hope lay very deep,
that I should meet with Christ in spirit, and know his spirit in my own soul;
for I understood by the Scriptures, that it was poured forth upon all flesh,
sons and daughters, and that nothing could be done well pleasing to the Lord out of it,
and that they who were led and guided by the holy Spirit of God were the sons of God.
I saw that all worship which was not in spirit and in truth, was not acceptable to God;
for all the prophets and the apostles came in it,
they having received it according to the prophecy of Joel, chap.
ii. verse 28, and the promise of Christ, Luke 24:49, as in Acts 2.

After I had been concerned with this man`'s books, and had done with them,
I resolved to cease reading such strange books, and to read the Scriptures of truth only,
by which I was made a little easy; but how to come to Christ,
of whom I stood in great need, I knew not, and was almost out of hope,
and discoursed with many; but found not true peace, comfort or satisfaction,
but still was under much secret sorrow,
and was not so wise as to mind the gift or witness of God in me.
If I heard any evil reported of the people called Quakers,
I was glad and took courage to go on,
slighting the appearance of Truth in my inward parts;
yet was the love of God so great towards me,
that he did not take his holy Spirit from me; praises, living praises,
to his holy Name forever.

I removed from the place where I had lived all my time; and came to live at Monyash,
six miles from thence.
I inquired what sorts of professors were there?
And I found a people called Anabaptists, of whom I knew very little,
but chose rather to accompany with them, than with the rude worldly ones.
I conferred much with them, and look a liking to them,
which brought me acquainted not only with their principles,
but also with their practices in worship, which when I saw,
I could say little against them,
but thought they came nearest the Scriptures of any I had yet tried;
upon which I went to their meetings, and was almost persuaded,
that I ought to be dipped into the water,
for unless I was I must have no admittance into their church.
Seeing no further, I could gladly have been so,
it being a far more easy way to the flesh than to obey the gift of God in me.
But I could not get to water baptism in faith;
for finding them preach that water baptism is a sign of death, burial and resurrection,
and that a man ought to be dead before he be buried; for said they,
"`It is monstrous in nature to bury a man before he is dead;`"
and then finding the Holy Scripture saith,
"`That he that is dead is freed from sin;
and how can you that are dead to sin live any longer therein?`"
I examined myself, and found I was not free from sin, so I was not dead,
therefore I was not fit to be buried, and before I was dead and buried,
I could not know a rising unto holiness and righteousness;
and if I should go and be buried under water as though I were dead,
I should dissemble and lie, or deal falsely both with God and man.

This kept me out of the water,
but one of the chief of them came to me one day to ask me why I came not to be dipped?
and I told him as above: he said to me, "`Many do come,
that I believe are more unfit than you are.`"
I said, that was nothing to me, I durst not.

After this I went to see my sister dipped in a river called the Wye;
and after that two young men;
and when they came up out of the water I spent some time with them, and observed them,
who were passed from death to life, as they signified;
but I saw no appearance of the Spirit, or newness of life, or power,
or that they thereby received the Holy Ghost; their baptism being only with water,
which can only wash away the filth of the flesh.
But such as are baptized into Christ, must be baptized into his death, by dying unto sin,
and be buried by his baptism into death, that being made free from sin,
they may come to have a part in Christ, the resurrection and the life,
by whom they are made alive unto God; for in Christ life is manifest,
and we have seen it, and have tasted and handled of the good Word of life,
that hath been as a fire, and as a hammer to break our rocky hearts asunder,
and water hath gushed out, and we have felt our hearts made new,
and our consciences clean, being washed with pure water,
and to answer the pure requirings of the Lord.
Our souls being baptized into Christ, and he being put on,
in him we have a safe habitation, and come to see,
that as none were saved by the ark of Noah but a few that were in it,
so none can know salvation but those that are in Christ,
the ark of the everlasting covenant; for he is given to be a covenant to the people,
a light to lighten the Gentiles, to open their blind eyes,
and to be God`'s salvation to the ends of the earth:
and there is no other name under heaven, by which any can be saved but by Jesus Christ:
to him be all glory given forever.

I found that they to whom I looked should have been dead to sin,
as they professed they were, yet lived therein, and pleaded for it during term of life.
Then I began to question their form,
and through mercy I found it was but a form without life or power,
and I plainly saw they were not in the power and spirit of God.

Thus the mercy of the Lord preserved me, and his long suffering was salvation to me.
He drove me out of all the inventions and imaginations of men,
and stripped me naked and bare; I had no hiding place,
for these fig trees bear nothing but leaves, and it was bread I wanted,
for these outward things brought no inward peace, power, or life, and could not,
nor can ever sanctify or make the comers thereunto perfect as pertaining to the conscience,
and therefore cannot satisfy the birth immortal.

Yet I continued with them, till one day as I sat in the meeting,
I observed that the elders and chief speakers were
putting one another to preach and pray,
saying, "`Pray do you, you are abler than me.`"
Thus they were urging one another, and as I saw and heard them,
there arose a dislike in me of these doings, and I said in my heart,
Why do ye put on one another?
Let God put on whom he pleaseth.

Afterwards there came a mighty power and weight over me,
and it was in my heart to go and speak to the meeting.
When I felt that it increased upon me,
and I knew not how to contain if I did not yield to speak,
I gave up and went through the meeting to them,
who had been treating one another as aforesaid,
and desired I might have liberty to speak a few words;
and one of them told me that it was not their manner,
to admit of any to speak among them before he was dipped, and entered in by the door,
and had passed through the ordinances, or to this effect.
"`But,`" said he, "`we believe you are an honest man, and will come,
and so you may take your liberty.`"
So I turned me to the meeting, and spake so that tears ran down.
I admired at the condition I was then in, for I was like a bottle uncorked,
and the power of the spirit flowed in me, and when it stopped I ceased to speak.

The next first-day I went again,
and the meeting fell in course to be at an elder`'s house, one Humphrey Chapman.
At this time a very wicked Act was put in force against religious meetings held
in other manner than according to the liturgy or practice of the church of England,
where above the number of five besides the family were assembled.

The fine was twenty pounds the house, and twenty pounds the preacher,
and five shillings a hearer.
But the elder, so called, refused the meeting, for fear of being fined twenty pounds;
then it was tendered to another, who was not only an elder but a preacher,
who had dipped the two men aforesaid; but he refused it for fear of his twenty pounds.
Then it was offered to a third, who accepted it for that day,
though it fell not to be at his house by course.
But when I saw the other two refuse the meeting for fear of suffering, one a preacher,
who had dipped two men when I stood by, I was not a little troubled;
for I remembered the words of Christ, who said, "`He that denieth me before men,
him will I deny before my Father which is in Heaven.`"
So after the meeting was ended, they discoursed about what they must do for time to come;
for they must not be at that pass; and the query was, where and when they must meet.
About which they differed much; some were for meeting in the bottom of a valley,
to save the fine of a house; and as for the time, some were for meeting early,
to have done by the time that the priest and people came from the steeple-house to dinner;
but some were for beginning then, some were of one mind and some of another;
but there was one that I loved best, desired they might meet as they had done formerly.

As I sat and beheld them,
I felt the same power arise in me in which I had
preached amongst them that day week before,
with these words, These people are not the people of God,
they do not stand in the power of God.

This I believed, and went away satisfied that it was so;
and left them and went no more to join with them in worship.

I was once more singled out, and durst join to none of those formalists,
but was like a lost sheep, strayed from my Shepherd, whom, after a long time,
I now came again to remember, and was persuaded that it was the gift of God,
or the Spirit of Truth, that came to me to lead and guide me in the way of Truth.
This wrought in me a great fear and dread,
lest I should have sinned out my day of visitation;
and I greatly questioned whether it would ever appear to me again or no.
Yet I had a secret hope, which kept me from being quite hopeless;
and I came again to be much exercised in mind,
and the travail of my soul was truly to enjoy the Lord,
and to be an instrument for his glory, and that I might know his will and worship,
and perform the same, and be joined to those who were joined unto him.

I was like a speckled bird, none like me,
for as yet I had not been at a Quaker`'s meeting,
but thought to live as holy and righteous as I could among men,
and join with none in worship, for fear of being deceived,
by joining in false or will-worship and idolatry.
Sometimes I went two miles to see a woman at Overhaddon,
who pretended to live without meat; where I met with professors, I think I may say,
of all sorts.
One day, a man of London came, called an Independent, and there was a meeting;
and he having heard of me, desired me to pray before he began to preach.
But I felt a zeal to rise in me against putting men upon that service,
which only belonged to God to require and move men to.
I refused, and he went on, who could do what he had a mind to do, as far as I saw,
in his own will.
Then he prayed and preached;
but before he had done preaching I was so pressed in my spirit to pray,
that it was a great exercise to forbear till he had done.
Then I prayed; but with such a power, that the people were amazed,
and truly so was I too; for I had never prayed so before, for I had both wisdom, faith,
and utterance given me.

Afterwards I went home and kept from all people, and joined with none,
having tried almost all persuasions among Protestants, and much sorrow I had in secret,
and was deeply baptized with the spirit of judgment and burning;
and I saw the baptism with the Holy Ghost and fire; and my pride and empty knowledge,
notions and opinions, yea, my faith that I had got by the wisdom of man was burned up.
Oh! the cup that I drank deeply of at that time, is unspeakable.
When the holy Spirit appeared in me, Jordan overflowed her banks;
it was deep at that moment of time, but m the midst of judgment the Lord showed mercy.
It began to be much in my mind, and I was ready to conclude that what I had felt in me,
was really the Spirit of the Lord that had waited on me long, and striven with me.
As I once said to two professors, that something appeared in me,
as one that had much mind to be received and entertained;
but for want of my being open-hearted, and inclined to embrace, receive, and mind it,
I often lost the sight and feeling of it.
Those to whom I told how it was with me, said nothing to me at all,
nor could they tell me what it was, though I told them that they should inform me.
The appearance of it was mild, meek, low and gentle, and full of good counsel,
but stood firm always, and condemned evil, reproving,
rebuking and judging it righteously; so that I was much persuaded,
in the secret of my heart, that it was the pure, holy Spirit of God;
and then I thought if it came not again, my state was dreadful, sad and deplorable.
I mourned and lamented; but none knew my sorrows but the Lord alone.

Now I knew not what to do; for my former resolution to live a holy life,
and to be as righteous as ever I could, I found did not help me to peace with God;
nor had I any true rest for my poor soul day or night;
for I had no power to live as I desired to do,
though no man could condemn me for any ill things;
yet I saw that in myself which others could not.
I wanted the Lord`'s presence,
for without that my soul could not be satisfied nor find true rest;
though my life and conversation was such, that most loved me who knew me.
