== Chapter II

About this time I entered into a married state, and went to house-keeping.
After some time, my wife grew earnest to have me go with her to hear a priest,
but I durst not; for I saw they were wrong as much as any, except Papists,
and great sorrow fell on us; and we disputed often till we both wept.

In this condition I met with great temptation, and the enemy sought my ruin,
both of soul and body; all which I kept secret.
None knew the deep sorrow I was under, night and day; for I had none to open my mind to,
except my wife, and I durst not tell her, lest I should trouble her,
and put her in fear concerning me; but yet sometimes, upon close search,
I found a little hope, but it was very low and very small.

After a time a cry arose in me to the Lord.
Oh, that I knew his will, and what he would have me to do! that I knew his people,
and his true worship, which he is well pleased with,
that I might be joined unto those that were joined unto him.
Oh, that I understood aright the things that belong to my peace!
When I awoke in the morning, a secret cry arose in my heart;
Oh! that this day may be my birth day: for I saw that I wanted to be born again,
and to be made a new creature, and my exercise was very great:
no comfort could I meet with in any thing that this world afforded,
without the enjoyment of his presence.
For this I travailed in spirit before the Lord,
and had some hopes he would show mercy to me, which, blessed be his name, I witness.
In his own time he caused the Spirit of his Son to arise in my heart,
with that power and efficacy, that I clearly saw it was the Spirit of God indeed,
which I had so long grieved, which begat a godly sorrow in me;
and then I came to it to ask counsel, and it showed me the way of life,
and gave me power to become a child of God.
Blessed be the Lord forever!

One day, in corn harvest, as I was riding on the road to Sheldon, in deep exercise,
and taking a view of my condition, being in deep tribulation and anguish,
condemning and judging myself, it pleased the Lord, on a sudden,
unexpectedly and unlocked for, to cause the Day Star to arise in my heart,
and the Sun of Righteousness with healing in his wings,
even when the sorrows of hell seemed to take hold on me.
Then it pleased the Lord to appear in me,
and to visit me with the dayspring from on high, in a very powerful and wonderful manner,
in great mercy, goodness, good-will and infinite lovingkindness.
I was, in my inward man, full of the power and presence of Almighty God,
and his heavenly, glorious light shone in me mightily; so that I may truly say,
it far exceeded the brightness of the outward day;
and the eye of my understanding was opened,
and I saw that it was the Lord`'s holy Spirit that appeared in me, and I believed,
and could do no otherwise.

Oh! then I was glad, and my soul was filled with joy, because I had met with the Lord,
who I knew was sufficient to teach me all things;
and gave me to see that my sins would be remitted and forgiven,
in and through Jesus Christ.
Christ Jesus was now become my light and my salvation, and living faith sprang in me;
for I felt power and strength to believe, and I then saw and felt what true faith was,
and also that I never had had true, living faith before then;
this was the free gift of God, for it sprung up in his power, and stands in it.

I also saw life eternal manifested through Christ Jesus;
so I tasted of the good word of God, and was made a partaker of the Holy Ghost,
and was enlightened: for the life was manifested, and I saw it,
and that the Son of God was come, and gave me an understanding to know him that is true;
for he revealed himself, or made himself known in me and to me.

Now my soul was quickened and enlivened in Him and by Him, in whom is life;
and I also heard him as the Shepherd and Bishop of my soul, who was come near,
even to my own soul; and the holy Scriptures were opened to me to my admiration and joy,
and I understood them far beyond what I had done before; and they became more sweet,
comfortable and precious to me, that I wondered I had never seen them so before,
having read them so much night and day.
But now the Lord gave me in measure to understand them, for they were very plain,
and that no man knows them but those to whom it is given,
by the holy Spirit of him who hath the Key of David, and opens and shuts as he pleaseth.

I kept what I had found that day, and it was to me as the Pearl of great price,
hid in my own field, that I had sought in divers forms and professions.
And I now understood the parables of the lost piece of silver in my own house,
and of the little leaven that lay hid in my three measures of meal,
which I saw was my body, soul and spirit; and that it had long been working in me,
whilst I knew it not, in order to leaven my whole lump, with its own divine nature,
that was capable of being leavened into good,
by the working of that good and perfect gift which was come down from above,
and was freely given me of God; for the sons of God were led and guided into all truth,
by the holy Spirit of Truth.

It was he that made David wiser than all his teachers, and did attend him from his youth,
and enabled him to go against the lion, the bear, and great Goliath,
in the name of the Lord;
and I saw no man could be a child of God without his holy Spirit;
and it was that I had wanted the knowledge of, all my days;
and I was glad when I felt and knew that I had it freely given me.

Now my great concern was to mind it, and be obedient to it;
for this was my Master and Witness, that would either excuse or accuse,
according to my deeds; and my Reprover and Instructor,
which showed me all that ever I did, and no thought, word or action was hid from him.
I was glad that I had found such a comforter,
and that it was poured forth upon all flesh, according to his promise,
in Joel 2. and Acts 2. The Apostle said, "`He that sanctifieth,
and they that are sanctified, are all of one.`"
Great had been the work of this measure of grace in me, that was come by Jesus Christ,
in order to make me a new creature in Christ, my life, light and salvation;
or to leaven me into a new lump, and work a thorough change in me,
who had great need of it, being in the corrupt nature a child of wrath,
as well as others.
Yet I had not a clear knowledge of it, for great had been my ignorance;
and though light shone in my dark, ignorant heart,
and made all things manifest that were reproved,
yet my dark heart had not comprehended it,
that it was the light of Christ which so wrought in me.
For we lived in darkness, and in the night of blindness, and sowed to the flesh,
and took pleasure in unrighteousness, and lived in pleasure,
having our affections set on things below, and not on things above;
loving the world and the praise of men more than that of God;
for the love of God was not yet known to us, nor shed abroad in our hearts,
so as to see or feel that it was his love.
I was in a profession of religion without life, till the Lord appeared to me,
and caused the light of his Son to arise in my heart to my exceeding joy and satisfaction.

But when I was brought to the knowledge of it, which was the Lord`'s doing,
and it was marvellous in my eyes, my sorrow was turned into joy,
and greatly was the love of God felt in me.
Great love was raised in my heart unto the Lord;
and I was deeply sorry that ever I had sinned against him;
and felt true repentance given me,
and saw that I never knew what true repentance was before.
Now I had such a sense and assurance of the love,
mercy and goodness of God to me in Christ Jesus, and for his sake,
who now was become precious to me, that if I had died in that hour,
I was satisfied of my soul`'s eternal happiness and peace.
Oh I then all fear of death and hell was taken away;
for I plainly felt my soul so affected with the love of God,
that I was troubled that I had grieved his holy Spirit;
and great was my desire that I might do so no more.

I went on rejoicing with praises and thanks, which arose in my heart unto the Lord,
my joy being great in him; and I was ready to think that my sorrows were ended,
and my tears wiped away.
A new song was given me that none could sing, but he that had it:
and I was glad that I felt the precious Truth in my inward parts, which God loved;
and he loves those that love it, live in it, and obey it.

O happy day it was to my soul!
I loved the holy Scriptures,
which were never so sweet and precious to me before as they were now;
and I loved all people,
and greatly desired that they might be brought to the knowledge of the Truth as I was;
for I knew that it was the will of God that all should be saved.

Thus having met with the Lord to my joy and comfort,
I felt that his holy Spirit was rightly called the Comforter,
which leads and guides into all Truth, which I rejoiced to know, feel,
taste and handle of; then I turned my mind in to the Lord, to commune with him,
desiring to know who were his people, that I might join with them,
and worship him aright, according to his own will.
And the Lord in mercy answered me, as I prayed to him;
and the word of the Lord was so powerful in my heart
that I could do no other than believe it.
And the Lord made known to me,
that the people called Quakers are his people above all other people.

When I understood that this was the Lord`'s people, I felt a part in me that was sorry;
for if it had been any other people I might have
been more at liberty to please the world,
and to keep the friendship of it, and not be so hated by it.
For this people were despised, persecuted, and suffered deeply beyond others;
for others could flee from sufferings, and conform a little sometimes;
but these abode and stood, though the winds blew, and the rains fell,
and the floods beat upon them; for the Lord enabled them to stand and out-stand it;
all praises forever be given to him!

I felt the Spirit of the Lord,
and could not question the truth of what he had manifested to me;
only I observed in my mind that the Lord said,
The people called Quakers are my people above all other people;
not that they were his people +++[+++only]
and no other, but above all other.
So that I concluded that there were many more who were not yet called Quakers,
that would be brought to know him, as I did then; and feel that he is good,
and have his love shed abroad in their hearts, and love him therewith,
and one another for his sake.
I felt love to all, agreeable to that holy song, Peace on earth,
and good will towards men; praise,
glory and humble thanks to God! for with him is joy unspeakable and glorious,
far beyond what I thought I should ever have known.

There was a young man walking a little way off from me, and I felt a love to him,
though I knew not that he was of any society at that time;
but he was afterwards convinced of the Truth, and was a very honest man, and his wife,
and three sons,
and two daughters were also in time brought to the knowledge of the precious Truth,
and some of them remain to this day;
and one of them had his mouth opened to preach the Truth.
Seeing that I had such a clear manifestation of Truth,
I was desirous to do the will of God, and was afraid of losing the sense, and sight,
and feeling of that which the Lord had in mercy given me the precious enjoyment of,
and was pleased to let me see that no man could take that from me, nor hurt my soul,
if I did it not myself.
Oh! it was precious to my soul; and then,
though I had been offended with the people called Quakers, I now called them Friends,
as Christ did those of old that obeyed him.

I went on to my journey`'s end with my mind exercised in serious consideration.
But, as I came back, the world was set before me, and all I had in it,
and I saw I must give up all, and let all go; and this was not all,
but to prison I was likely to go, and my wife and children might be brought to poverty:
but in the Lord alone I put my trust, who is all-sufficient,
and is the portion of his people, and the Rock of their safety, forever, amen.

Though the enemy was busy with me, I was concerned to feel the Lord with me,
to keep and help me still to abide in him, and with him;
and blessed and praised be his Name forever, he did not leave me, nor forsake me,
though sometimes he hid, as it were, his face from me;
and when I trespassed or offended for want of a diligent watch,
or suffered my mind to wander, yet he hath not been angry forever;
though his Word hath been as a sword, and as an hammer,
yet in judgment the Lord remembered mercy:
and the good Samaritan hath come and poured in oil and wine, and healed wonderfully;
praise, glory and renown be given to him!

My satisfaction was great, and my heart was turned to the Lord,
and my very countenance was so altered,
that my wife and neighbours took notice and spoke of it.
But I kept my mind inward and said little, but as I had it given me,
and kept my exercise to myself for some time, and neither told my wife, nor any body;
for as yet I had not been at Friends`' meetings,
neither was there any about our Peak country, where I then lived.
I met with some Friends at the market, and conferred with them,
but told them not of my condition; and the greatest part of the town was stirred;
some said well, and had a, love for me, and some said ill, and hated me without a cause;
and they differed one with another: but after some time,
many were convinced and came to meetings.

The Lord having showed me again his poor, despised people,
it made me glad when I found with whom to wait upon him.
After some time I heard of a meeting at Exton, at one widow Farnay`'s house,
whose husband had been an honest Friend.
I went to it, and found divers Friends were come many miles; and when I came,
I was confirmed that they were in that Truth whereof I had been convinced,
though they were so much derided by the world.
There was little said in that meeting, but I sat still in it,
and was bowed in spirit before the Lord, and felt him with me, and with Friends,
and saw they had their minds retired,
and waited to feel his presence and power to operate in their hearts,
and that they were spiritual worshippers, who worshipped God in spirit and truth.
I was sensible that they felt and tasted of the Lord`'s goodness, as at that time I did;
and though few words were spoken, yet I was well satisfied with the meeting.
And there arose a sweet melody, that went through the meeting,
and the presence of the Lord was in the midst of us, and more true comfort,
refreshment and satisfaction did I meet with from the Lord, in that meeting,
than ever I had in any meeting, in all my life before, praises be to the Lord forever.
I was assured that they were his people, and guided by his Spirit,
by which they came to understand his will,
and were brought in their measure into true obedience to his commands,
being made willing to bear his cross, deny themselves, and become fools,
that they might know true wisdom, for which they wait in silence,
and to feel the inspiration of the Almighty,
to give them an understanding of the things of God,
which the natural man cannot understand,
because he comes not to wait in the Spirit for the manifestation thereof.

I also felt such a love in my heart to them as I had never felt to any people.
Oh! it was true love, such a love as none knows, but they that have it:
and I also felt the same love in them to me, and some of them got me in their arms,
and were glad of me, though I knew but few of them, nor they me.
So I came home, and my poor wife was sorely grieved that I went among friends, viz:
the people called Quakers, and the people of our town began to rage;
some disputed with me, some cursed me, as I heard, some pleaded for me,
some derided and mocked me, calling after me, Quaker, Quaker.
When I heard them thus call after me, my heart was glad and filled with joy,
that I was reproached for Christ`'s sake,
and thought worthy to take part with Friends in the sufferings of Christ,
that were yet behind in his body; and it arose in me, Now I have got the name.
Oh! that I maybe truly brought into the nature of God`'s people.

But there were several things that as yet I saw not clearly through;
though I felt the Lord with me, and was sure it was the Truth, yet I intended,
in the secret of my mind, not to imitate the Quakers, but I would put off my hat to men,
and use the same language that I had done;
for I did not like their plain language and behaviour to people.
I was not willing to come into the practice thereof in imitation of Friends,
thinking I should please people better if I said you to a single person,
and put off my hat to them; for many love to be worshipped,
though there is no worship due to any creature upon earth.

So I was hid for a time, few knowing what I was, nor what I had seen, heard and felt;
yet I knew it was the Lord that met with me on the road, and it was with such power,
that I willingly received it to my great satisfaction and comfort,
and believed that the Lord, when he saw meet,
would open my understanding and give me to understand the holy Scriptures,
which he hath since in mercy wonderfully done.

I was careful to hold that fast which was freely given unto me:
and it came into my mind to wait on the Lord, to know what he would have me to do;
so I waited in my mind to hear what the Lord my God would say to me.

And after some time, as I was riding on the road, and waiting,
the word of the Lord arose in great power in my heart, saying,
Speak truth to thy neighbour, be not double-tongued--respect no man`'s person.

This fully satisfied me;
and I saw I was to enter the kingdom of heaven as a little child,
and was to learn anew to speak and walk,
and stood in need to be helped and held up by the
secret hand of the Almighty Omnipresent God,
and to mind him in all I said, and in all my walkings and doings.
I came to see that this had been the language of God from the beginning,
and the language of all the righteous people in all ages, and that no prophet,
apostle or servant of God did ever use any other language to him, either in prayer,
praises, or in their writings in any age.
I saw that God changeth not, and that as men truly turn to him, they come to be true men.
But this language and conversation was hard to flesh and blood,
that would have pleased men, and had their praise, which I got when I was young,
and it went hard with me to lose it all, which I knew I must,
though they took offence at me for my obedience to the Lord.
So I gave up in obedience to the will of God, in which I found life and peace to my soul,
and great encouragement and joy in the Lord,
though this way of speaking and carriage went very hard with me,
and was a great cross to my natural part, and helped to lay me very low,
and to mortify the old man in me,
and made me willing to be a fool in the eyes of the world, and to be despised of men.

Now, blessed and forever praised be the Lord God Almighty!
He hath made glad my soul, and satisfied the breathings of my spirit;
he hath opened to me the mysteries of his kingdom, and given me a measure of his grace,
and caused his light to arise in me, and the darkness to flee away.
He hath given to me the true bread of life,
and made my heart glad with the wine of his kingdom; he is become my teacher himself,
and hath gathered me into his power, and covered me with the banner of his love;
he is become my hiding place, my rock, strength and refuge,
I need not fear what man can do unto me.
He is my portion, I shall not want, and therefore I trust in him alone,
my helper in the needful time; he hath wrought all my works in me and for me,
both to will and to do of his own good pleasure;
he is a sufficient reward to all them that wait upon him.
He is all in all; I have none beside him, he is all-sufficient,
I am nothing but what I am in him, therefore he alone is to be praised;
glory is wholly due unto him, for it is he alone that hath redeemed my soul from death,
and hath opened to me the way of life; he hath taken my fetters from my legs,
and hath set my feet upon a sure foundation; he hath brought me out of the prison house,
and hath set my soul in a pleasant place;
he hath plucked me like a brand out of the fire,
and hath given me strength above my enemies.
He hath redeemed my soul from death, and caused me to walk in the path of life.
He hath heard my sighing, and my groanings were not unknown to him;
the breathings of my soul hath he regarded, and my heaviness hath he turned into joy;
yea, he hath tenderly waited to be gracious to me,
and his long-suffering hath led to repentance.
Oh! what shall I render to the Lord my Saviour, who hath dealt so bountifully with me!
My soul, bless thou the Lord forever, and all that is within me praise his holy Name;
for he hath caused mercy to surround me.
Oh the lovingkindness of the Lord! all ye that know
him praise his Name! for his mercies endure forever.
He hath caused light to shine out of darkness,
and manifested thereby those things which are reproved,
to which light my heart is turned, resolving to turn away from my iniquities,
and serve the Lord with reverence and holy fear.

Now I know it was he, by his Word, that showed me my thoughts and the intent of my heart;
although I was once ignorant of it, yet now am I assured it was his Word,
which often called behind me, saying, This is the way, walk in it!
He was still seeking to save me out of the enemy`'s power,
though I then regarded him not; nevertheless he pursued me,
till at last my heart opened to receive him, who is now my beloved,
and has given me to taste that God is good,
whose goodness far exceeds all that this world can afford,
praised be the name of the Lord!
I have found the Pearl of great price, the one thing needful for my soul to know,
and this is Christ within the hope of glory, the true way to the Father,
who promised to be with his disciples to the end of the world.
This is he whom we are to hear and obey in all things,
lest we be cut off from among his people.
This is the unction which I have received of the Lord, that teacheth all things,
which is truth, and is no lie.
Oh that the children of men would open their hearts,
that the king of glory might enter in, to drive out that den of thieves,
who rob them of that treasure and peace which passeth their understanding,
whereby they would come to witness the Comforter, the Spirit of Truth,
to lead them into all truth; for it is he who worketh all our works in us and for us.
This is the Lord`'s doing, and it is marvellous in our eyes;
to whom be praise and glory forever!

My understanding being thus opened,
I came clearly to perceive the word of God in my heart,
which had wrought powerfully to my full convincement,
and by it I knew I must be faithful to its requiring, if I would have peace;
it giving me a true sight of my state, and how I should wait for salvation.
Then did I see, to my great satisfaction, which caused joy to arise,
that the despised Quakers were the people who worshipped God in the way he required,
in Spirit and in Truth.

Being come to see, in the light of the Lord, through all things to my satisfaction,
I went cheerfully to Friends`' meetings, and was edified and comforted.
The third meeting I was at, the power of the Lord came upon me,
and I was pressed in spirit to declare of his goodness, but it was hard to give up;
yet I durst not disobey,
so I stood up and spoke to the congregation--abundance of
Friends and others being met--what was given me to understand,
concerning the creation of man, his dominion, work, state of innocency, fall,
and restoration by the promised seed, Christ Jesus the Saviour of mankind:
all which was to the great joy of Friends, and reaching of the people.

At this meeting a woman was convinced, who with her parents dwelt at Tides-wall;
they much desired I would have a meeting at their house; accordingly I went,
much people being gathered in the garden.
This was a town in which I was formerly well known.
After the meeting had been some time in silence, I was moved to stand up and speak,
which I continued for about four hours; but my very countenance was so much changed,
that there arose a reasoning among the people, whether I was John Gratton or no.
In the time of my declaring, a woman who was a Baptist, put a question to me,
which I answered so much to her satisfaction, that she was convinced.

This woman`'s husband was a Muggletonian;
and when he came to understand she was turned Quaker,
he told her he would write to his prophet to curse me; which he did accordingly:
upon which Muggleton, by letter, sent me his curse,
the words of which were not worth mentioning; but in answer I gave him to understand,
I mattered it not.

The next first-day I went to a meeting at Matlock,
where the informers and officers had made very sad spoil, by taking away Friends`' goods;
yet many others as well as Friends came to the meeting.
As soon as I came within sight of the house, I felt the Lord with me; I went in,
and it was very full of people,
and after some time I was moved to declare the testimony of Truth:
and the presence of God was so gloriously manifest, that the people gave good attention,
and were so affected, that the fear of man was much taken away.

At this meeting the people looked earnestly upon me, at which I marvelled,
but perceived it was at a laced band which I had upon my collar;
at this I was smitten and sorry, for until now I had not minded it since my convincement.
Friends in those days showed no appearance of pride in their apparel,
neither was I pleased with myself;
for I saw that the holy Spirit did not allow of any superfluity,
either in apparel or any thing else, from a sense of which I took it off,
and wore it no more; neither did my dear wife ever offer to put it on again,
but when she understood that I was troubled for wearing lace,
she took it off all the rest of my bands,
although she was not then convinced of the Truth, though some time after she was.

My being convinced was noised much abroad, many people disputed and conferred with me,
and my kindred were sorely troubled,
and would have had me forbear the carriage and language that Truth had led me into,
saying, "`We ought not to offend.`"
I told them,
it was the little ones that believe in Christ which ought not to be offended:
"`But woe to the world!`" said Christ our Lord, for the world took offence at him,
without just cause: and so they do at his followers, who are given up to do his will,
and to follow the leadings and guidings of his holy Spirit.
If righteousness offend the wicked, whose fault is it?
Abel could not help it when Cain hated him because his works were righteous;
and he pleased God, though Cain was offended.
Even so,
he that is born after the flesh hates and takes offence
at them who are born after the spirit to this day,
and thinks it strange because they run not with them in their carnal ways,
to the same excess of riot, speaking evil of them.

But when Christ said, "`Woe be to the world, because of offences,`" He said also,
"`that offences should come; but woe be to that man by whom they come!`"
Now why come offences?
That those that are tried, living stones, may be made manifest;
and that those that will not take up the cross and deny themselves,
may also be made manifest.
For the "`Friendship of this world is enmity against God;`" and,
"`if any man love the world, the love of the Father is not in him.`"
But the cause lies here,--that unregenerate men are known by their fruits.
Woe be to the false prophets, false priests, false professors, and hypocrites;
though they walked in long robes, and sounded a trumpet when they gave alms,
and prayed in the corners of the streets, to be seen of men,
and made long prayers for a pretence.
For all this they were proud, and loved the chief place in the synagogue;
the highest rooms at feasts, and greetings in the markets, and to be called of men,
master.
They were covetous, and devoured widows`' houses; tithing mint, annise and cummin,
but omitted mercy, judgment and truth; for they were not what they pretended to be.

The Sodomites offended Lot,
and vexed the righteous soul of him that entertained the angels of the Lord;
for which they were offended at him: but woe and misery came upon the wicked Sodomites,
but Lot was delivered.
Jerusalem took offence at Jesus Christ, who came to save his people from their sins,
and to finish transgression, and to bring in everlasting righteousness.
The Jews hated him without a cause; Him that would have gathered them,
as a hen gathereth her chickens under her wings,
to save them from the devouring fowls of the air, that would destroy them utterly.
Even so Christ spreads the wing of his power over those that are gathered unto him,
to save them from the prince`' of the power of the air,
the spirit that now works in the hearts of the children of disobedience;
that roaring lion, that goes about seeking whom he may devour.

But the church is safe under the shadow of the Lord, saying,
"`I sat under his shadow with great delight,
and his fruit was sweet unto my taste;`" for it is all good;
but the fruit of the evil one is all bad, bitter as death, wormwood and gall;
and so it will be forever.

Woe and misery came upon Jerusalem also, that would not be gathered or saved;
but rejected the holy One, and the Just, and chose a thief and a murderer before him,
as those do that chose to serve the devil before Christ Jesus the Lord of life and glory.

I went abroad much, and had meetings in several counties, as Yorkshire, Lincolnshire,
Nottinghamshire, Staffordshire, Cheshire and Derbyshire.
And many were convinced; and great joy and gladness, love,
unity and concord flowed among us.

My wife was not yet convinced.
I was in much sorrow for her, and so was she for me, and disputed with me often,
till we both wept; but still we loved dearly.
And before the second meeting at my house, as I was upon the road one evening,
in great heaviness for my wife, the word of the Lord came to me, saying,
I will give thee thy wife; at which I was glad and comforted:
for I believed that it would be fulfilled ere long;
as it was accordingly--she being soon after convinced, blessed be the Lord.

At the next meeting one William Yardley came;
and after the meeting she discoursed with him long, but at last Truth sprung up in her,
and in him also, that he went to her and said, "`Ann,
God`'s love is to thee,`" which she feeling, was given up to obey it, and was glad.
Then our days were made more joyous,
and we lived together after this about thirty-five years,
and many friends came to see us, of whom we were glad.
We had an open house, and open hearts to entertain the Lord`'s people,
and were glad he had in mercy fitted and enabled us to be serviceable to his people;
and my trade increased, for we had favour with God and men.

I was much concerned in preaching the gospel of our Lord,
and went to and fro to meetings, and many people were convinced in divers places;
as in Darbydale, Matlockside, Ashover parish, Brampton, Harsdale, and in the High Peak;
many and precious meetings we had, as we got liberty at houses,
and meetings were settled, and many of my own kindred were convinced,
and died in the Truth.
I have ground to hope my aged grandfather, who was about ninety years old,
was convinced and glad of the Truth in his old age, telling my mother,
"`This is that I have been seeking for all my days,`" meaning the Truth.
After some time, I went to Derby, and got some meetings there, and at Little Chester,
and many Baptists were convinced in Cheshire.

Afterwards it was required of me to go and visit the churches in Nottinghamshire;
so I went to Nottingham, and found William Smith lying sick, a fine living, faithful man,
and brave minister of Christ;
and it was revealed to me that he would be taken away at that time,
as I told Thomas Highfield over night; and next day, after the meeting was over,
I went to see him, and stayed with him some time.
Oh! he was in a sweet frame, full of love; life and peace were plentifully in him.
I left him in great unity, tenderness and love, and went to Mansfield,
and he died in a few days, and left a good savour behind him.
His memory is sweet to me, and those parts had a great loss of him.
From thence I went to Skegby, Hucknell, and then home.

After this,
the Lord was pleased to lay it upon me to go abroad again into Nottinghamshire and Leicestershire,
which I was very loath to do; but I durst not but go.
I went to Tupton meeting on the fifth-day, and to Boulsover on the sixth,
where we had some disturbance, and on the seventh-day to Chesterfield,
where we had a glorious meeting, and some convincement.
Oh! the Lord`'s power was over all.
From thence I would fain have gone home again, but must not, and I wept sore.
I went into Nottinghamshire, and on first-day had a meeting at Worksop, in a barn,
which William Bailey had hired.
His wife happened, as she rode near Worksop, to fall off her horse and break her leg,
and her husband came down from London to see her,
and finding that she was not fit to be removed, he hired a house for one year,
for Friends to meet in.
I went to see her, and had a meeting there on first-day; and as I was at prayer,
the officers, with many more, came railing and raging up into the meeting,
making a great noise, as if they would have affrighted us, till they came near me,
and just as they came to me, the power of the Lord increased, and my voice rose strongly,
and they all stopped, and turned back like men smitten, and went quite away,
not having power to do us any harm.
We had a precious meeting, and went away comforted.

Next day I was at a good meeting at Blyth, and another in the evening;
to which came John Seaton, one of the chief men of that town, who was convinced,
and proved a faithful man to the Truth till his dying day.
Many more in that town, and about it, were convinced of the Truth,
and stood nobly to it through suffering times, faithful to the end.
Next day I went to a meeting at a town called Etalstall, in the forest,
where I had a good meeting; many came to it, and some were convinced,
particularly one John Kent, who received the Truth.

I went to a meeting at Kersall, and the priest of the town came,
and made a great noise at my back for a while, to stop me; but I held on,
and was sorry he troubled the meeting, for it was in a precious frame.
But at last I felt I must stop, and turned to him;
but he offering to clear himself from preaching for hire,
said he need not to preach except he pleased, for he had an estate to live on,
if he did not preach.
So I bade the people take notice; This man is his own master, and need not preach,
unless he will; but the apostle Paul, and they that were sent of God, were not so:
for Paul said, "`Necessity is laid on me,
and woe is unto me if I preach not the gospel.`"
By this I showed the priest from his own words, that he was no minister of Christ;
Christ was not his Lord and Master, since he could do what he would,
either preach or not preach: so he was made manifest, and went away in a great rage,
and his company with him.
The Lord was mightily with us that day, and we had a good meeting,
and were sweetly comforted, and had no harm by man.

Then I went to Akring, and had a meeting, and one John Allin came to it,
and was convinced and shaken wonderfully; but though he trembled, yet he rejoiced,
and cried out, "`He is come!
He is come!
He is come!`"
After which, he went home, and met with high professors, and disputed them much;
then he took his Bible and went to and fro in the town, but he ran before he was sent,
and came to some loss: so his relations sent him to me,
and when he came to my house and talked with me, he was finely recovered;
so that in a few days he went home.
But the family and professors about him set on him again; and he was zealous,
and discoursed them till he hurt himself again: then I took my horse,
and went and fetched him away to his uncle`'s at Blyth, where I left him.
He did well, and proved an honest Friend, and after some time went to London,
and was taken at a meeting with his wife; she went with him before the mayor, who,
in pity to his wife, would not send him to prison with the other Friends,
which he was freely given up to, and grieved that his wife came in the mayor`'s sight,
and was very sincere, I hope, as long as he lived.

The next day I went to a meeting at Ogston, which was very large.
I had never seen the like appearance before--the living Truth went through the meeting.
Many were reached, and the power of the Lord came over all to the joy and comfort of many.

I was also at a meeting at Long Clauson, in the vale of Beavor,
and there was a young man, called William Marriott, who was full of life;
and Sarah Brown, Elizabeth Doubleday and Edward Hallam,
and Friends were comforted together.

The next day I went to a meeting at Harby; and the day following being first-day,
I went to a meeting at Crowston, there the lord Ross, so called,
came to the steeple-house, and our meeting was near it:
the officers and others came to break up the meeting, with a great noise,
as if they meant to frighten us all;
and as they came up the entry I turned my face upon them, as I was declaring the Truth;
the Lord enabled me to speak boldly, and his power came over them;
but before they came to me they were silent, and turned back,
like men smitten in their hearts.
In a little time they went away and left us, and we had a good meeting,
praised be the Lord forever, whose power was over all.

Next day I went to a meeting at Broughton, at John Wilsford`'s,
where a Baptist got privately to hear, who was reached,
and confessed to the Truth of what I spoke, as John told me afterwards.

The next day I came to Nottingham, and had a good meeting there on the third-day,
and Friends were glad of me, and we were comforted together.
But a Friend came to fetch me home from thence; for my wife was very weak,
and more likely to die than live, thinking she should scarcely live to see me.
I hastened home on fourth-day, and found my wife very weak, and myself much spent:
but thanks be to God, he raised her up again.
My mother was with her, but my father was not convinced; he hearing that I was abroad,
and how things were at home,
thought to come and chide me for leaving my wife in her condition.
But the meeting happening to be at my house the next first-day, thither my father came,
not till that morning: but some Friends were got in before him;
so he intending to stay all night, deferred it, rather than fall on me before them.
When the meeting was gathered, after some time I spoke;
and there were some of the chief of the town, whose tears I saw run down their cheeks,
and my dear father was so broken, that he cried aloud, in great joy of heart,
whilst he trembled.
At which I was silent a little, and my father came to me, before all the people, weeping,
and took me in his arms and kissed me.
The next day we walked alone, and had much discourse, till he fell to weeping again,
and desired me to forbear, and say no more; after which we parted--he loved me much,
yet he never came into open obedience to the Truth.

I stayed at home some time.
And Oh the peace that flowed in my heart! as Christ promised, not as the world giveth,
who cry peace, peace, when there is no peace at all experienced.
But, praises to the God of my life,
his peace hath he given to me and many thousands in this day;
that peace the world does not know, neither can they take it away from us,
glory to the Highest forever.
Oh! the love and life that flows here, and springs from the Fountain of living waters,
in whom all our fresh springs are.
Feel it reader, in thyself, hast thou not seen it gush out of thy rocky heart?
When Christ, the spiritual Moses, hath smitten upon it, with the rod of God in his hand.

An Epistle to Friends.

My dear Friends, It is in my heart to write a few lines to you ere I proceed.
Have you not found in your measures, this Christ of God, to be what I say of him?
Oh! prize this immortal life that now stirs in you, and praise the Lord for his mercy.
Live in this life that frees from death; abide in it, and your joy will be full.
The world little knows your joy, little knows your peace; though ye sorrow,
yet always rejoice; though ye war daily, yet live in peace.
The peace of God, that passeth all understanding, keep your hearts and minds in one;
in that light of life, which now shines in your hearts, that you may never fall;
but always keep low in your measures, and see that none look out,
or mind any thing but the Lord, who alone is to be minded in all, by all, and above all,
and followed, obeyed and trusted in.
Dear friends, keep in the innocent life, and this will knit you together,
and enliven every member, and quicken you all, and make you savoury;
and seasonable fruit will be reaped, and a good savour will you be to one another;
and this will feed you, and your strength will be daily renewed,
and the increase of God experienced, and you will daily feel his love,
which is better than wine, to make glad your hearts, and to surpass the world`'s love:
this will rejoice your souls in times of adversity;
for this love many waters cannot quench.

Therefore, dear friends, all keep your minds stayed on the Lord,
and take heed ye lose not the things ye have received of him; but all wait,
in your measures, upon the Lord only, and expect nothing from man,
for he is not to be accounted of; nor think to live on the manna others have gathered,
but come you and be diligent also.
Take heed the Lord call not for you, when you are gone abroad with your minds,
about your own business.
Keep your habitation, and the Lord will keep you, even as the apple of his eye;
"`Nothing shall harm you, if ye be followers of that which is good.`"
All live in the true light, and abide in it,
by which all dangers whatsoever will be made naked and bare to you,
and all false spirits will be seen and tried in the true light,
and the mind of God you will clearly know; and if you all keep here and live in it,
you will find safety, and the enemy will not be able to touch you.

Therefore, dearly beloved friends, keep in the light, of which you were convinced,
and by which you were converted and turned to the Lord.
Keep in that, for that keeps truly humble, in sincerity and truth,
and so all feigned humility,
and all pretences and outside professors will be made manifest,
and your enemies`' strength will also be clearly seen, which is mere weakness.
Be not forward in answering questions put forth by the opposers of the Lord`'s Truth;
but stand singly in obedience to the Lord, and be as fools,
that the true wisdom may be preferred, and thus will the Lord`'s will be done,
whether their wills be answered or no; and your peace will be as a river,
as you hearken to the Lord,
and the Lord`'s cause will be pleaded with all flesh by himself,
and his arising will be the scattering of his enemies;
for Babel`'s destruction will come upon her;
by the brightness of his coming and the breath of his lips will she be utterly destroyed;
the mouth of the Lord hath spoken it.
So, my dear friends, all keep in your strength,
and feel the arm of his power stretched out, to carry you on;
that you may daily know victory, and praise the Lord in his own sanctuary,
and declare of his wondrous works;
for with a strong hand hath he brought us out of anguish and bitterness of spirit,
which we once were in, by reason of our cruel bondage in sin.
Had not the Lord come to visit us, we had been in slavery even till now,
for none else was able to deliver us, neither was there any to intercede for us.
Therefore, his own arm brought salvation to us.
All keep in that grace which saves, that breaks the rocks, and hath often broken you,
even to pieces, and hath made your earthly house to tremble,
and hath filled you with dread.
O, remember his mighty works in the deep, and receive the law at his mouth--hear it,
and do it--behold, it is near you, in your heart, and in your mouth,
that ye may not depart from it.

Dear friends, watch diligently, for in this furnace you will be tried.
But though you are suffered to be tempted,
yet will not the Lord permit you to be tempted beyond your measures.
Therefore all keep in your measures--there is your safety;
"`My grace is sufficient,`" saith the Lord; therefore fear not your adversary,
for he cannot hurt you, if ye always fear the Lord your God, and live in his counsel,
whereby your hearts will be kept clean habitations for his holy Spirit to dwell in:
for stronger is he that is in you, than he that is in the world.

From your dear friend and fellow-labourer in the work of the gospel.

John Gratton.

3rd of the Eighth month, 1673.
