== Chapter V

After this, two men of the church of England, who wished me well, came to see me,
and sent for me into the jailer`'s hall; but before I came, another Papist,
that had been tried for clipping, +++[+++coin]
got into discourse with them, and vilified their church sadly, and was very high.
Then I asked a question,--If, said I,
it can be made to appear that the pope of Rome is not in the apostle Peter`'s spirit,
will you not then grant that he cannot be Peter`'s successor?
The Papist answered yes.
Then I asked him if Simon Magus was not out of Peter`'s spirit,
who thought that the gift of God could be bought and sold for money?
He replied yes.
Then, said I, the pope is in Simon Magus`'s spirit, and not in Peter`'s,
for he thinks so still; but he said nay, the pope did not think so.
Then, said I, he is worse than Simon Magus, because he makes people believe so; else,
why doth he take money for his bulls, pardons, and indulgences?
To this neither he nor the popish priest that stood by, said a word more, but went away;
and the churchmen were glad.

After this there came in a Jesuit and another priest, and two more Papists.
One day the Jesuit showed me a place in a book,
treating of a man being born of the Spirit and of water.
I asked him what he showed me that for?
He answered, to let me see that a man must be born of water as well as of the Spirit.
I asked him what water?
He said baptismal water.
What! said I, elementary water?
He said yes.
Then, said I, dost thou believe that elementary water hath that virtue in it,
as to help to make a man a new creature?
or to this effect.
He said yes: then I denied their baptism,
and told him he could not prove that ever our Saviour Christ baptized any with water,
or commanded any man to baptise with water; and bade him either prove or yield:
but he could not prove their baptism, and to yield he was not willing.
So I left him to search the Scriptures for a proof.

After this he fell on me sharply, about the eucharist or sacrament, as they call it,
of bread and wine.
He told me, that after the words of consecration, so called, by the priest,
(we read of no such words in Scripture) the bread was really, corporeally,
and substantially the very flesh of Christ, and the wine his very blood,
urging Christ`'s words, "`Take, eat, this is my body.`"

I told him, Christ also said, "`The flesh profiteth nothing,
it is the Spirit that quickeneth; the words that I speak unto you,
they are spirit and they are life; and he that hath the Son, hath life;
but he that hath not the Son, hath not life.
But the apostle speaking of the children of Israel, 1 Cor. 10. says,
they were all baptized unto Moses in the cloud and in the sea;
and they did all eat the same spiritual meat, and did all drink the same spiritual drink;
for they drank of that spiritual Rock which followed them, and that Rock was Christ.
Now, if it be the same, it is spiritual, and not, as thou sayest, corporeal;
and if it be not the same, the apostle saith not true.
This put him to silence, for he durst not say the apostle lied; and if so,
then it was the same, and if the same, then not the very flesh of Christ corporeally:
so he was silent a while; at last he said, "`Well, for my part,
I know nothing of spiritual eating or drinking.`"
Then, said I, it is no matter to talk more with thee.

Another time he began to discourse with me, asking me if I did not believe a purgatory,
whither all go before they can go to heaven.
He said there was a place of purging after this life,
and there were three sorts of people went into purgatory; one sort were so holy,
that they went strait through it into heaven, for their works did abide,
and they had reward of the same; another sort was so unholy,
that they went strait through purgatory into hell; and there was a third sort,
the most numerous, who were neither so holy, as to go strait to heaven,
nor so very unholy as to go strait to hell, and those stayed in purgatory fire,
till they were made clean, and suffered loss,
because their works did not abide when they were tried by fire,
yet they were saved but so as by fire; alluding to the apostle`'s words,
that every man`'s work should be tried by fire, of what sort it is, wood, hay,
or stubble; 1 Cor. 3:12-14. Then he queried,
Can any man`'s work be tried before it be done?
I said no.
Then, said he, Can a man`'s work be said to be done before he be dead?
I said no.
Well then, said he, if a man`'s work cannot be tried before it be done, as it cannot,
nor done before he be dead, it must needs be tried after he is dead,
and it must be tried by fire, therefore it must needs be purgatory fire.`"
I asked him what sort of fire it was, whether like that before us, which was a coal fire,
elementary fire; he said yes.
I never heard before, said I, that a coal fire could try men`'s works,
or that it would burn to all eternity.

Now the Lord was pleased to appear, for I felt him near me,
and he opened my understanding, and I laboured to show him from the holy Scriptures,
that men were to know a being baptized into Christ`'s death,
and to become dead to sin whilst here, and be buried with him by baptism into death;
that like as Christ was raised from the dead by the glory of the Father,
even so we also should walk in newness of life.
For if we have been planted together, said the apostle, in the likeness of his death,
we shall be also in the likeness of his resurrection; knowing this,
that our old man is crucified with him, that the body of sin might be destroyed,
that henceforth we should not serve sin: Rom. 6. The apostle saith,
"`How can you that are dead to sin, live any longer therein?`"
So the old man being crucified, death hath no more dominion over you;
and he that enters into Christ, the true rest, ceaseth from his own works,
as God did from his; Christ worketh in him, for he is all in all.
The baptism of Christ is with the Holy Ghost and fire;
and he will purge away the filth of the daughter
of Zion with the spirit of judgment and burning;
and the day of the Lord shall burn as an oven; and Jacob shall become a flame,
and the house of Esau stubble; and the Lord shall sit as a refiner`'s fire,
and like a fuller with soap, and take away the filth of the daughter of Zion,
and purely purge away her dross, and take away her tin.
The Lord said by his prophet, "`I will make a man more precious than gold,
than the golden wedge of Ophir;`" and that he would purify the sons of Levi.
The word of the Lord is as a fire and a hammer, to break the rocks asunder;
and our God is a consuming fire to all the workers of iniquity,
and reveals himself in flames of fire, to render vengeance upon all that know not God,
and that obey not the gospel of our Lord Jesus Christ.
The Lord makes all things new; and if any man be in Christ he is a new creature;
old things are done away, and become as dross and dung in comparison of Christ.
So that man loseth all his own works, for they cannot abide the trial; but Christ is,
of God, made unto us wisdom, righteousness, sanctification and redemption;
and if any man glory, he must glory in the Lord, for out of him there is none.
This must be done or known in this life, in the day time, for the day shall declare it,
and the fire try every man`'s work, of what sort it is.
Therefore, said Christ, "`Work while it is day,
for the night cometh wherein no man can work.`"
There are twelve hours in the day, in which a man may work, but there is neither work,
nor device, nor knowledge, nor wisdom in the grave, whither thou goest; therefore,
whatsoever thy hand findeth to do, do it with thy might,
for as the tree falls so it shall be, and as death leaves judgment finds,
and in the grave there is no repentance.
The grave cannot praise the Lord, death cannot celebrate him,
they that go down into the pit cannot hope for his Truth,
but they that die in the Lord are blessed;
and they that are in Christ need no purgatory after death, having washed their garments,
and made them white in his own blood.
Nothing else can cleanse people, or save them from their sins,
for there is no other way to God but by him, neither is there any can save from death,
and give life eternal, but Jesus Christ.

Much more was said than I can now remember:
but he was ignorant and not acquainted with these things,
that he had not wherewith to oppose, nor did he deny what I said;
so his purgatory was all thrown aside as an invention of men,
and their pretending to pray men out of purgatory is all a cheat to get money by,
and all their pardons nothing but deceit, for the Lord only hath power to forgive sin.
Much opened in my mind, and all he could say came to nothing; so we parted friendly.

Oh! blessed be the Lord, who hath discovered the great deceiver,
and all her abominations; and the false prophet, with all his transformings are seen,
and both thrown down to the earth together.
She is full of the blood of the saints and martyrs of Jesus, and she thirsts for more;
but the Lord hath a remnant that have come out of her,
and refuse to partake with her of her sins,
lest they should partake with her of her plagues; for strong is the Lord God Almighty,
that judgeth her.

I also had good service with many other people,
and sometimes got to some meetings at Little-Eaton and other places,
but I did not write down what passed in all places, only some things of note.

I wrote to the priests of Derby, about the rude,
wicked practices which the people of that town lived in, for they made bon-fires;
and one year they carried about a thing they called the pope,
and then burnt it in the fire,
and the next year they carried about a thing they called Presbyter John,
and burnt that also; and these things, with many others I beheld in the town,
grieved me very much.

About this time the priests in their pulpits preached aloud,
that active obedience must be practised by all the king`'s subjects.
And one Henry Ward having been one day with the mayor, came to me in the evening,
and told me that the mayor said, we must obey the king actively;
so that if the king did command us to worship Mahomet, we ought to do it;
and if it was amiss, it would be the king`'s fault, and not ours.

At this time the Act for twenty pounds per month was put in execution,
against those who were rich, or such whom the prosecutors were minded to afflict;
upon which one Burrows of Derby, to avoid suffering, conformed;
and there was scarcely a man in that town,
according to the remarks I then made upon them,
who was willing to be reputed a Presbyterian,
for they had no meeting in or about that town, unless it were in private.

Such is the cowardice of men,
whose religion is built upon the tradition and inventions of men, and not upon Christ;
for from hence it is plain,
how needful it is for men to lay their building upon that Rock,
which neither the windy doctrines of men,
nor the swelling waves of persecution are able to move.

In this time of my confinement, several people resorted to me in prison on first-days,
and we had good meetings there;
for though the ministers of the gospel may be shut up in jails for the testimony`'s sake,
yet the word of God cannot be bound, for it had free course, and was glorified.

This prison was made easy to me,
and things were well at home with my dear wife and family;
and though she was a tender woman, yet she was enabled, through mercy, to keep markets,
to carry on our business for a livelihood; she also came sometimes to see me in prison,
though it was sixteen miles, which was hard for her in the winter season.

Whilst I was a prisoner I wrote a little book,
which I entitled "`The Prisoner`'s Vindication,`"
also some epistles and letters to Friends,
and meditations in verse, for my children.
The reason why I wrote some remarkable passages of my sufferings for Truth,
and also the great things which the Lord hath wrought for me,
both in supporting me therein, and delivering me out of,
is that my children and others may be encouraged to be faithful to the Lord,
and valiant for the Truth upon the earth; for this cause it came into my mind,
to tell to others how good the Lord hath been to me,
for which I am deeply engaged to praise his great name.

+++[+++The following extract is taken from the work above alluded to.]

To all Persecutors, Both by Words and Actions.

Upon the 16th day of the Sixth month, called August, 1680;
I being at Bakewell about my trading, it being a fair,
was arrested by two or three bailiffs, by virtue of a writ of Excommunicato Capiendo,
for not coming to the parish church, so called, and not appearing at the Spiritual court.
I had appeared there several times, and offered to the parish priest,
that if he could make it appear I was in an error, by clear Scripture,
I would take him for my friend.
And further, that if he could make it appear from clear Scripture,
that it was my duty in the sight of God,
to come to the parish church and conform to them, I would do it.
But he did not find it his business to seek to inform me at that time, or any other,
being not so charitable as to bid me come another
time and then he would discourse with me.
Although after this I was never cited to the court again,
yet upon the day aforesaid I was sent to Derby jail, where I remain a prisoner.

After I was sent to prison, many false charges were flung after me,
to render me and Truth odious to the country people,
who were ready to wonder why they should send such a peaceable man to prison.
I was by my persecutors highly accused to be an heretic, a factious fellow,
the ringleader of a factious people; yea, a blasphemer, an enemy to Caesar,
a dangerous fellow, and a spreader of dangerous principles, and what not.
And all to make the people think hardly of me, and believe if they could,
against their belief, that I was some dangerous man; insomuch, that they said,
I was not fit to live, especially not fit to be loose in a country;
for by keeping me in prison, they had hopes to scatter the rest.
At the hearing of these malicious and false calumnies, I was grieved, not for myself,
but others, who I heard were ready to think hardly of me,
because such reports had gained some credit with some,
who were thought both wise and sober, and they believed them,
because others believed them; those others believed them, because my persecutors,
who are looked upon by most to be spiritual men,
reported them amongst these uncharitable men.

Not one came to show me my reported sad condition, but in prison I must lie,
come what will come of wife and children.
My wife went, with two friends more, to the Arch-Deacon, so called,
and showed him the unreasonableness of my suffering, and the need of my liberty;
but his words were great charges as aforesaid,
though he never discoursed me about religion in his life.
It is true, he also said, that he would come to me and discourse me,
and if I was in the right, and he in the wrong, I should come out of prison,
and he would go in for me; but he yet fails to make his words good.
I do declare to all that may see these lines, that if I cannot make it appear,
that he is wrong, and I right, I then will be content to stay where I am;
only I would be judged by men unprejudiced against the Truth, such as are not partial,
and make no outward gain of the Scriptures.

Many others have desired my enlargement, some by letters, and some have gone in person,
but all fails, except I will conform,
and pay the charges they have been at in laying me in prison; which thing I cannot,
and dare not do.
For, first,
I believe I ought not to conform to the worship that is now maintained
by the priests of this nation by their preaching and practice;
I do not mean by their purses; for both they and it cost the people dear.
Secondly, I believe, that though it be after the way which they call heresy,
yet the worship which I now own, is the true worship of God;
and I do find by good and great experience, that the Lord God of heaven and earth,
who is a Spirit, doth approve and own it so to be.
For the worship I own and believe, is the true worship of God,
that is spoken of in John 4:23-24. They that worship
God must worship him in spirit and in truth;
and saith our Saviour, the Father seeketh such to worship him.
Thirdly, seeing our Lord, Christ Jesus, did set up, appoint and command this worship,
therefore I believe I ought not to leave it, and run to another worship,
that is no where commanded, either by Christ or any of his apostles,
thinking thereby to save my estate, and to live at liberty in the world,
and enjoy those natural rights and privileges I am a free-born heir to,
which I see the drunkard, swearer, curser and proud wicked person is not deprived of,
though he be so wicked, Lastly, seeing I do those things I believe I ought to do,
and have not given any just occasion of offence, or done wrong to any man,
therefore I cannot own myself in a fault, and give monies for a pardon to those,
who while they are pardoning others,
are therein committing the highest sins they can approach unto.
If I have sinned, it is against God, and to him I look for mercy;
but in this I am not by him accused or judged as a sinner,
but owned and justified by him, and can say, it is God that justifies me,
who shall condemn me?
Now should I come to my persecutors, and own myself an offender,
and buy their absolution, and conform to their invented ceremonies,
then should I by so doing give God`'s spirit and my own heart and conscience the lie;
from which, I hope, without offence I may take the liberty to say, good Lord preserve me.

But seeing I must have no better treatment from my persecutors than a prison,
which indeed is the way of argument that the false prophets in all ages have taken,
with things of the like nature, as fines, whips, lions`' dens, fiery furnaces, faggots,
and such like;
I desire they will be pleased to suffer me to treat them with a few arguments,
which are in my mind, and when I have done, I shall leave them to do,
as it shall please God to suffer them, as to me,
and desire they may consider and consult their own profit eternally, and not forget,
that ere long, both they and I must appear before the judgment seat of Christ,
to give an account of the deeds done in the body, whether they be good or evil.

And first, I enquire of you that persecute me and others, whether if it was so,
as you say falsely it is, that I was a heretic, a factious fellow, etc.,
what precept or example you have from Christ or his apostles, to lay me in prison,
seeing I am a peaceable man and just in my dealing, and pay to Caesar his due,
as many that know me will witness?
But instead of a command for persecution,
doth not our Lord Christ prohibit it several times?
It may be you will say,
it is no persecution that is done in this kind to an erroneous person, etc.,
though it may be, for all he is so called by you,
who call light darkness and darkness light, he is a true Christian,
and servant of Jesus Christ.
Doth not Christ prohibit all manner of violence, cruelty, imposition and the like,
when he bids his followers to love their enemies, not to persecute their friends;
and whatsoever they would that men should do unto them, to do so unto men, saying,
this is the law and the prophets: and also said, with what measure you mete,
it shall be measured to you again?
Is it obeying Christ`'s command to lay men in prison?
You would not be so done unto for your faithless faith, and worthless worship.
Though you profess to love God, yet while you in works deny him,
I shall not much heed your profession;
for he is a true lover of him that keeps his commandments, as will be found one day,
when those that pretended to preach and prophesy in his name,
and in his name to cast out devils, shall be bidden to depart from him,
as workers of iniquity.
And if those that preach and prophesy in his name, and in his name cast out devils,
be sent away from him, because they, for all that, were workers of iniquity,
what do you think will be the portion of those that preach and prophesy in man`'s name,
and by man`'s authority only are held up; and instead of casting devils out, tell people,
they must live in sin all their lives,
and make the people content to let the devil keep the house, hurry them on into iniquity,
transgression and sin all the days of their lives; and for all this,
tell those very people that they are Christians,
and though they do those things they ought not,
and leave undone those things they ought to do, and are miserable offenders,
in whom there is no health, yet while they put into the priest`'s mouth,
are owned as a dear brother and sister, and so called when they are buried by him,
though it may be they have killed themselves by a drunken bout.
O! how dreadful will the end of these things be!
It is a grief to my spirit to think of it.

But further, did not Christ command that both tares and wheat should grow together?
And do not these two words, wheat and tares comprehend all mankind?
What can you make for your practices here?
If I be a tare, you should let me alone till the day of the harvest;
for what hast thou to do with another man`'s servant;
to his own master he stands or falls.
Christ Jesus showed a reason also, why he would have men to let them alone,
and both grow together; for, saith he, lest while you pluck up the tares,
ye root out the wheat also.
This clearly shows that men may be mistaken,
especially those that have not an infallible spirit;
for it is the spirit of God that is infallible,
which searcheth and makes all things manifest, even the deep things of God.
We have had sufficient experience, that under pretence of plucking up the tares,
which is contrary to Christ`'s command, the devil hath laboured with all his might,
to root the wheat out of the world; and though Christ saith,
he came not to destroy men`'s lives, but to save them,
yet the devil came to kill and destroy men`'s lives, not to save them.
Christ rebuked his disciples, when they would have called fire from heaven,
and told them, they knew not what spirit they were of.
My kingdom, said he, is not of this world.
He did not come to be Lord and King in an outward manner,
and make men yield to him by outward force, for if so, then would his servants fight;
but he came to set up his kingdom in the hearts of men.
It was promised by the Lord, that he would give him for a covenant to the people,
and would create new hearts in them, and write his laws in them,
and put his fear in their inward parts, and be their God.
So when Christ came, he said to them, the kingdom of heaven is within you;
and said the prophet, he shall sit as a refiner`'s fire, and fuller`'s soap;
what for but to purify the heart, that it may offer an offering in righteousness?

It is true, the apostles in their weakness,
forbade those that they found casting out devils in his name,
because they did not follow him; but did Christ approve of it?
Nay, he rebuked them, saying, he that is not against me, is for me.
Methinks this might be taken notice of by you priests, who persecute me and others;
since you have seen some of your drunken hearers become very sober men,
after they have come to hear the Quakers, as you call us, preach; some of your swearers,
cursing, proud, profane hearers become very careful livers, both in words and deeds;
and what! doth this grieve you?
Methinks you should think such men as these,
that prevail so upon people`'s hearts to be good men, men of your side,
if you be for God, and should, like Christ, whom you call your Lord and Master,
rather rebuke such as forbid us, than forbid us yourselves.
When, like Peter and John,
we dare not but speak the things we hear and see and are commanded,
not then to take us and put us in prison; and so stop the mouths of them God hath opened,
and be angry with them, though they do what they do freely,
and look for no part of your great revenues.
Remember, you do not desire to be so done by; and also it is worth your taking notice,
that those our Saviour Christ whipped out of the temple, were buyers and sellers;
what would you think, if such must be whipped out of your steeple-houses now,
and such only be admitted to preach as would do it freely!

But though he did whip such out, as aforesaid, yet we never read that he whipped any in;
or that if any would not come to that place, he imprisoned them, or fined them,
or the like.
No, he was a Shepherd, tender and loving to them; if any go astray,
his way to fetch them in, is ever by his gentle calls unto them, in reproving,
rebuking and checking them in their hearts by his spirit,
and following them with his righteous judgments in their inward man.
So that for want of true peace with God, many have returned again to him,
who shows them wherein they offend; and when they return,
there is more joy in heaven over one sinner that repents,
than over ninety-nine just persons which need no repentance.
Just persons; mark that! these are none of your church of miserable offenders.
But let me ask you, is not faith the gift of God?
And that which is not of faith is sin; is it not?
If so, then I ask,
what you would gain if you could make a man choose to conform to your worship;
yours I call it, contrary to his faith and conscience,
rather than lose his enjoyments of wife, children, liberty and estate,
any more than a hypocrite, one that seemed to be what he is not?
Nay, may I not say any better than a heretic;
for I take him to be a heretic that is condemned of himself,
that allows himself to do that which he condemns himself for.

This way of persecuting men for their faith and conscience,
is the way to bring some to become hypocrites and heretics,
and this is the way such men have gone in,
to hold up their idolatry and superstition in all ages; witness Baal`'s prophets.
The old serpent knows this well enough; therefore it was said in the revelation,
the devil shall cast some of you into prison.
Some of whom?
Some of the servants and faithful witnesses of Jesus, who would not,
and could not worship the beast.
But further,
suppose I wanted faith and a right understanding
of the things that belong to my everlasting peace,
do you think that a prison will be a means to bring me into the true faith?
Can the prison walls rectify my understanding, or give me faith and wisdom?
Did ever Christ command the use of a prison or fine, or any thing of that nature,
to men that would not hear him, or believe him?
What ground have you for this?
Show us your foundation for these actions, and bring command,
precept or example for them from Christ or his servants,
and then I shall think better of you; but if not, let me tell you,
one day you may find your portion to be what the prophet said, Woe to him that spoils,
and is not spoiled.
Therefore I could gladly desire, even in pity to your own souls,
that you would consider your doings;
not that I am so much grieved for my own sufferings for truth`'s sake; no,
though my poor wife and children are near and dear to me, yet blessed be the Lord,
I have faith in God concerning them, and believe he will take care for them and me too,
and can trust the Lord upon all accounts, blessed be his name forever!
Though it is hard, and will be so found one day to you that part me from them,
to be stripped from them for my obedience to God, and laid in prison,
and by you reported to be one of the worst of men.
O! this is the way and manner which the serpent and his
instruments of old took with the servants of Jesus Christ,
witness Paul`'s accusers, and persecutors.
We, said they, have found this man a pestilent fellow, a mover of sedition,
a ringleader of the sect of the Nazarenes, etc.
And the great rabbies of those days, the Scribes, Pharisees, high priests and rulers,
that persecuted our great Lord and Master Jesus Christ,
accused him to be an enemy to Caesar, a blasphemer, and a deceiver, etc.

And you that are my persecutors, are not you much like these men aforesaid,
who persecuted Christ and his apostles, and cried to the rulers for help,
in your proceedings against me?
And though some of you never saw me as I know of,
and none of you ever came to discourse me,
or see wherein I was mistaken as to my faith and principles; yet you can fling it out,
that I am a dangerous person, a deceiver,
and run up and down the country to delude people.
These your false charges will one day be remembered, except you repent,
which I desire you may.

Consider your doings, and see who you run parallel with; you are but men,
you may be mistaken, seeing you are not led by an infallible spirit,
and therefore cannot be sure you are in the right; but you go by conjectures,
and rest upon the judgment of ancient fathers, reverend divines, as some call them,
heathen authors, or else your own conceivings, or the like, and yet are uncertain,
and leave the people unsatisfied,
and so manifest yourselves to be such as are not sent with the Lord`'s message,
received from God himself,
as by your uncertain beating the air is manifest
to every one whose eyes the Lord hath opened.
So that there is great danger,
if I should leave Christ the true light and teacher of men,
who now appears by his pure spirit in my heart,
and shows me the things that belong to my peace, and follow you, I should then be led,
both in principle and practice, to do those things I ought not,
and leave undone those things I ought to do;
and then I could not escape being a miserable sinner and offender,
in whom there is no health.

Suppose I should, contrary to my faith and knowledge, come to you,
and live and die in error, for fear of being kept here in prison,
and brought to poverty in the world, which, blessed be the Lord,
I value not in comparison of my peace with him, the God of peace,
and think to plead with God, and say, I did what I did in submission to men`'s will,
who said, they were the ministers of Christ,
and was forced to it by the chief priests of our country,
and must either submit to their wills, or lie in prison, have my goods spoiled,
and my wife and children impoverished; so that I did what I did only to save my estate,
and have my liberty, etc., or else I would not have done it,
for it was against my faith and conscience, and because of the fear of man.
Will this excuse me?
If not, then I ask you, can you excuse me to God, and assure me of it,
if I will conform to your worship,
and give you monies for a pardon of my true obedience to God in disobedience to you?
For so indeed the case lieth; if you cannot excuse me,
if you should or could force me to sin against God, then why should not I,
who am a peaceable man, and wrong no man, but love all men,
have my liberty to live as I dare to die?
Seeing I must answer for myself, and stand or fall to my own master,
what have you to do to judge me, who am the Lord`'s servant?
I must stand or fall to him I serve; how dare you smite your fellow servants,
and cast them into prison who have done you no wrong, nor owe you any thing but love,
when he that put his fellow servant in prison, who owed him an hundred pence,
was so severely judged of his Lord, who had forgiven him a greater debt?
And He has taught us to use those words in prayer, forgive us our trespasses,
as we forgive them that trespass against us.
And would you not have God answer your own desire?

Consider these things, and learn to do as you would be done unto;
for with the same measure you mete, it shall be measured to you again.
Remember what your Saviour layeth down as great offences at the last day,
to those on the left hand.
Go you cursed into everlasting torment with the devil and his angels; or, depart from me,
ye workers of iniquity, I know you not; for I was an hungered, and you gave me no meal;
thirsty, and you gave me no drink; naked, and you clothed me not; sick, and in prison,
and you visited me not.
And when they answered, when saw we thee an hungered, thirsty, naked, etc.,
and did not minister unto thee?
He told them, inasmuch as you did it not to one of the least of these my brethren,
you did it not to me.
By which it is clear, he takes that which is done to his followers as done to himself;
for indeed it is for his sake, who teaches us to live righteously,
soberly and godly in this present evil world; and because we obey him,
and keep his command, therefore are we hated of all men for his name`'s sake.
But the wicked are not thus treated by you; the swearer, liar, drunkard, proud person,
etc., are left at liberty, and in these days are the men in fashion.
But if it be so great an offence not to visit the servants of Christ, when in distress;
what will it be to those that lay them in prison, and keep them there,
which is a means to bring them into nakedness, hunger, thirst and sickness?
Was it not said, that it were better a millstone were hanged about his neck,
and he cast into the sea,
than to offend one of those little ones that believed in Christ.
What then will his portion be that not only offends them, but persecutes them,
imprisons them, spoils their goods, belies and slanders their person,
and misrepresents them to the world, takes the righteousness of the righteous from him,
and takes him from his dear wife and children, and causeth them to suffer also;
though it is said.
Cursed is he that parts man and wife.
What excuse can you make at the last day for these things!
How unlike are you to him who is good to all men,
and laid down his life a ransom for all,
and doth cause his sun to shine upon all, and his rain to descend upon all,
and his grace that brings salvation appears in all, and strives with all.
