== Concerning the Death and Sufferings of Christ.

But some are ready to object, and say,
You Quakers do mightily preach up the light within,
but you say little of the death and sufferings of Christ without the gates of Jerusalem.

[.discourse-part]
_Answer;_ we have many accusers that say all manner of evil against us,
which we patiently bear, knowing it is for his sake that suffered for us,
who is become not only our light, but also our salvation as we abide in him,
as he hath commanded us.
And we declare, that as he by the grace of God tasted death for every man;
so every man hath this benefit by it, that he may now come to him, receive him,
and in him receive power to become a child of God.
Therefore, when he came into the world there was great joy,
for the angel that appeared unto the shepherds said unto them, "`Fear not,
for behold I bring you good tidings of great joy, which shall be to all people:
and there was with the angel a multitude of the heavenly host, praising God, saying,
Glory to God in the highest, and on earth peace, good will to men.`"

Here is universal love; "`For God so loved the world, that he gave his only begotten Son,
that whosoever believeth in him, should not perish,
but have everlasting life.`"!So all the world are put into a capacity,
by the death and sufferings of Christ, to come to him, and he that comes to Christ,
he will in no wise cast out; "`For God is no respecter of persons,
but in every nation he that fears him, and works righteousness, is accepted of him.`"
So we say, it is Christ that suffered for us, "`The just for the unjust,
that he might bring us to God; being put to death in the flesh,
but quickened by the Spirit.`"
Yea, "`He laid down his life a ransom for all;
who himself bare our sins in his own body on the tree, that we being dead unto sin,
should live unto righteousness; by whose stripes we are healed.
Whilst we were sinners, Christ died for us, and by himself purged our sins.
Forasmuch then as the children are partakers of flesh and blood,
he also himself likewise took part of the same,
that through death he might destroy him that had the power of death, that is the devil,
and deliver them who, through fear of death,
were all their life time subject to bondage.`"

This now I declare,
we own the death and sufferings of Christ according to the holy Scriptures; and he, only,
that suffered without the gates of Jerusalem, hath been our peace-maker,
and is now come by his light and Spirit, to give us the knowledge of God,
and what he hath done for us; so that in his light we see him,
who is our light and our salvation.
Isaiah said, "`He hath borne our sorrows,
and carried our griefs;`" which were the sad effects of our sins,
so that now remission of sins that are passed is
freely preached unto all men through him,
and all mankind are invited to come to him,
and all the ends of the earth to look unto him and be saved.

After the prophet Isaiah had largely spoken of his death and sufferings,
and the great love and mercy of God which flows forth through Christ unto all,
and how he is enlarging his habitation, he shows that the Gentiles,
who had been as barren and desolate,
should come to bring forth more children than the married wife;
and that they would break out on the right hand and on the left,
and that her Maker should be her husband and redeemer.
Read Isaiah 54, which is full of precious promises, viz:
"`All thy children shall be taught of the Lord,
and great shall be the peace of thy children: in righteousness shalt thou be established:
thou shalt be far from oppression.`"
And Isaiah 55, "`Ho every one that thirsteth, come ye to the waters, etc.
Behold thou shalt call a nation that thou knewest not,
and nations that knew not thee shall run unto thee, because of the Lord thy God.`"

[.offset]
Thus it is clear from the prophet in these three chapters,

[.numbered-group]
====

[.numbered]
_First;_ That we are all like lost sheep gone astray.

[.numbered]
_Secondly;_ What Christ hath suffered for us, and how he appeared in the world,
and was rejected and despised of men.

[.numbered]
_Thirdly;_ How after his death and sufferings,
the good will of God is plentifully seen to flow forth to all people,
and an invitation is given to all who are thirsty, to come to the waters,
as it is also in John 7:37; "`If any man thirst, let him come unto me and drink;
he that believeth on me, out of his belly shall flow rivers of living water;
but this spake he of the Spirit, which they that believed on him should receive;
for the Holy Ghost was not yet given, because that Jesus was not yet glorified.`"

But after our Lord Jesus Christ had suffered and risen from the dead,
and ascended far above all heavens, that he might fill all things, as the apostle says,
he sent the Holy Ghost.
Then the fountain opened more plentifully, and men out of all nations were spoken to,
and heard in their own language the wonderful works of God declared.
Now the day of deliverance dawned,
and the day spring from on high did visit the children of men;
the Son of Righteousness was risen with healing in his wings,
and his light broke forth in obscurity; they that sat in darkness saw the light of life,
and life eternal was risen over death, hell and the grave,
shining in the hearts and souls of men; and the Spirit was poured out upon all flesh,
according to the Lord`'s promise, Joel 2. And whosoever will, is now,
by the death and sufferings of Christ, put into a capacity of salvation;
and this benefit comes unto all, whether they will accept it or no;
the Spirit of God is poured forth upon all; the Fountain of living water is open to all;
the grace of God that brings salvation appears to all. Tit. 2:11.
And the day of salvation is broken forth,
and the true light now shines unto all,
even to them that sat in darkness and saw no light,
and in the region and shadow of death.
"`The Spirit and the bride say, Come; and let him that heareth say.
Come; and let him that is athirst come; and whosoever will,
let him take the water of life freely.`"

====

Thus the invitation goeth out to all,
and whosoever will may receive or take of the Fountain of living water freely,
without money or price, or any thing to merit or purchase it,
for the pardon and remission of sins that are past is freely preached to all in Christ,
and for his sake that died for them, and bought them with his precious blood.

But this is not all the benefit that comes to poor souls by his death and sufferings,
for now, the true light shines, the hidden things of darkness are manifested, reproved,
judged and condemned; for he is also given for a witness to the people,
and he doth bear witness for them, if they follow him, and live to him who died for them.
But if they still live to themselves,
and follow the devices and desires of their own hearts,
and do those things they ought not, and leave undone those things they ought to do,
then he doth witness against them, judge and condemn them, for their evil ways, words, etc.

Let me speak freely, and say, while we were enemies, we were +++[+++by the death of Christ]
put into a capacity to turn from that which made us so, viz: sin,
and be joined to the Lord, who stood ready to receive us in him who died for us,
and would not impute our trespasses unto us, because he had suffered for us,
who now unites and reconciles us to God,
and by his life we come to be quickened and raised from death to life.
And we see in his light, that as we come to him, receive and follow him,
we feel his life and power more and more unite us to God,
the giver of this unspeakable gift, and he manifests his love unto us,
who is in Christ reconciling us unto himself;
and the more we are gathered into the life of him, the more God is with us,
and his peace witnessed by us, to his praise and glory, forever more, amen.

So in Christ we reap all the benefits of his death, sufferings, rising again,
ascending and mediatorship, who gives peace to our souls, and is our light, leader,
teacher, commander, king, law-giver, wisdom, righteousness,
sanctification and redemption.
Come then to Christ, believe in him, follow him, and thou shalt not abide in darkness,
but shalt have the light of life.
The Lord complained of the Jews of old, that though they searched the Scriptures,
and thought in them to have eternal life, yet they would not come to him,
that they might have life.
This is still the cause of all that death and darkness that people lie in;
they will not come to him, nor do they love him or his appearance, or light,
which makes all things manifest that are reproved.
"`How oft,`" said Christ, "`would I have gathered thee, but thou wouldst not.`"
Here it is plain, God would have all to be saved, but they will not come unto him,
nor be gathered by him.
Oh! therefore come and let us walk in the light of the Lord;
let us walk honestly as in the daytime, that our sanctification may be throughout,
for it is Christ that sanctifies,
washes and purifies with the washing of regeneration and renewing of the Holy Ghost;
for if he wash us not we have no part with him, but if we walk in the light,
as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ his Son cleanseth us from all sin; 1 John 1:7.

Thus it is clear we had need to come to the Lord Jesus Christ,
and give up to be saved by him, and in a word,
to receive him who hath done all this for us, to be all to us,
and we to be what we are in Him, who is the way, the truth and the life,
and no man cometh unto the Father but by him.
This is the one thing needful, the good part which Mary chose, the pearl of price,
that is better than the whole world.

Therefore let none rest in notions and empty profession, dead forms, dry opinions,
and beggarly elements, but come and kiss the Son, lest he be angry,
and ye perish from the way.
For in him we have peace; in the world is trouble,
and no true peace to be met with but in him; he is the way of peace:
blessed are they who know him, and abide in him unto the end;
they will lay down their heads in peace, when time with them here shall be no more.

[.signed-section-signature]
John Gratton.
