== An Epistle to Friends in Pennsylvania.

Truly beloved Friends,

Mahlon Stacy, John Wilford, George Wood, John Blunstone, Francis Davenport,
Samuel Jennings, Job Bunting, and all other dear friends as if named,
that live near you inwardly or outwardly,
my sincere love in the blessed Truth tenderly salutes you all,
with your tender loving wives and families, earnestly breathing to the Lord,
the fountain of living waters for you, that you may be kept and preserved living,
faithful and fruitful in the blessed Truth,
in which alone our souls are made capable to rest with God in all times of trouble;
praises to him forever.

Dear friends, the weighty sense of how things have been for some time,
and still are amongst you, hath bowed me much before the Lord in spirit secretly,
having none to ease my mourning soul unto but him alone,
who takes notice of all our unutterable sighs and groans; and I hope in his great mercy,
love and pity, as he hath hitherto helped us, so he will still appear for our help,
preservation, comfort and consolation, if we carefully keep low and inward,
being bowed humbly before him, waiting for his pure appearance in our inward man.
Emmanuel, God with us, is known to be wonderful, counsellor, the mighty God,
and Prince of peace, able to dispossess the man of sin, who opposeth,
and would exalt himself above all that is called God; but,
blessed be the Lord our God! he hath enabled us to say in truth,
"`Greater is he that is in us,
than he that is in the world;`" so that we witness the apostle`'s testimony true, viz:
"`That which is to be known of God is manifest in men, for God makes it known to them.`"

Therefore, dear friends, keep your minds to the appearance of God, who is our Saviour,
and there is none else besides him; and rejoice and praise him for his great mercy to us,
in making known himself in us;
and for those that boast of what they know of God without them, pity them, pray for them,
and take heed of being entangled or snared by them.
For, according to the tenor of holy Writ,
we ought to be thankful for what we know of God in us,
if what is to be known of God is manifest in us.
Then we ought also to consider the Almighty is free,
and dispenses knowledge as it pleases him,
and doth manifest what and how much he pleases to the children of men;
and if he please to manifest more to another than to me, I ought to be content,
and make a right use of what I have; and not envy my brother for having more,
nor exalt him; nor despise my brother that hath less than I,
but consider that no man hath any thing but what he receives from above;
and that it is God makes men to differ.
And he that improves what is freely given, shall have an increase;
"`For to him that hath, it shall be given,`" said Christ,
"`and he shall have abundance.`"

My dear friends, let us look inward, and wait for what the Lord pleases to manifest,
and take counsel of him, and abide in him and in his counsel,
and strive not at all without him;
but see that we do all in the meek and peaceable spirit of the Lamb,
for the Lamb shall have the victory, yea, hath it and reigns, glory to God forever.
So fallen Adam, corrupt self, with all their knowledge, arts, tongues, studies,
faith and trade must all come down and come to naught,
for the Lord alone is and shall be exalted over all.

Dear friends, as it is said, the Lamb shall have the victory,
so it is observed and plainly seen in all places, where his life, light, love, meekness,
patience, gentleness, long suffering, purity, wisdom and truth are manifest, and kept in,
victory is obtained by the Lamb of God, that takes away the sin of the world,
and saves out of it, all that truly receive him,
and gives them power to become the sons of God,
and to obtain conquest and victory over the evil one.
O, therefore, friends and brethren, abide in him,
and be sure to live in a sensible knowledge that he abides in you,
as you may remember he prayed to his Father, that we might be in him and he in us;
this is precious, Christ in us the hope of glory, the great mystery of God.
Hold this fast, hide him in your hearts, let him be head in you,
secretly ruling in your souls, yield obedience unto him,
and live in a sensible feeling of his life, light, joy, comfort.

Friends, keep here and you will know enough, you cannot want any thing if you enjoy this;
but if you had all knowledge without this, all languages, mysteries, yea,
faith to remove mountains, and have not this love, all is worth nothing.
This is he whose lips preserve true knowledge, he teaches the way of God; truly,
never could any man speak like him.
In hearing him, dear friends, he keeps us in communion,
unity and fellowship with God and one with another,
and in peace that passes the understanding of the wise knowing men of this world.
This is the best knowledge, to know God to be our God,
Christ Jesus to be our Lord and Master, our head and law-giver, and wonderful counsellor:
Oh! let us see this to be our knowledge, and wait, watch and pray to grow in it;
and flee contention, strife, vain disputations and janglings,
for the victory is to the Lamb, and all they shall overcome, that abide therein;
therefore watch and pray in his name, and suffer with him.
His sufferings are very great, yea, wonderful at this day, and many suffer with him, yea,
and also shall reign with him forever;
such know their overcoming to be through sufferings.
Behold the Lamb of God, feel his divine nature in your inward man,
and be gathered thereinto and put him on, and be clothed with him,
that he may make you comely with his own comeliness;
thus shall you know the armour of light, yea the whole armour,
though many a sharp arrow and keen dart have been shot at you,
yet it still remains armour of proof.
Keep it on, dear friends; neither say, nor do,
nor think any thing contrary to the divine will, but learn in silence and stillness;
watch to know what the Lord speaks, for he works the work no other can do,
nor can any of the sons of men do what he doth;
let him therefore have that preeminence that is due to him,
and be all in all and then there will be an end of strife, and peace on earth,
good will to all men will ensue, and glory to God on high.

As we experience this we are by him redeemed out of the earth,
and out of the evils thereof, being followers of the Lamb wheresoever he goes,
and whatever riseth up against these shall not prevail,
for no weapon formed against such shall prosper,
neither shall the gates of hell prevail against them.
The Lord is known at this day by a remnant, blessed be his name,
to be both Lord and Christ, yea, our sure Rock of safety, strength, power, life,
righteousness, sanctification and salvation; yea, all we are to God we are in him,
and him only.

Dear friends, keep close with him in spirit; his tabernacle is here with us,
and we find he delights in the sons of men,
and to make his abode in the habitable parts of the earth.
Therefore, dear friends, come into the temple, and tarry there with him,
and look unto him, and if another saith he sees more of him than you do,
be still and look not at man, but take heed; for Christ said, "`Many shall say unto you,
Lo, here is Christ! or, Lo, he is there! believe them not.`"
But watch and pray, and let nothing separate you from him;
and what he shows you plainly of the Father, be thankful for;
enjoyment is the best knowledge, and keeps the soul low, humble, meek, patient, gentle,
holy, harmless, quiet and peaceable,
when the knowledge that is without enjoyment puffs up, exalts, is not gentle, nor holy,
nor harmless, but hurtful and dangerous, carrying the mind quite away from God,
like the raven that flew from Noah`'s ark, which returned not again.

What is man out of Christ Jesus the way, the truth and the life, the power of God?
Truly nothing, worse than nothing;
but in him man comes again to stand up in the image of God.
He is the unspeakable gift, stand fast in him, quit yourselves like men,
be strong in the Lord and in the power of his might; remember his noble acts,
he made the weak strong who had faith in him, though they were weak,
he quenched the violence of fire, stopped lions`' mouths, made armies of aliens flee,
yea, death and the grave were conquered by him who is the conqueror,
and gives victory to all his true disciples and followers, and enables them to overcome,
and his promises to such are great and precious.
Read them with the Spirit, as follows; "`To him that overcomes,`" saith he,
"`will I give to eat of the tree of Life, which is in the midst of the paradise of God;
he shall not be hurt of the second death; to him will I give to eat of the hidden manna,
and will give him a white stone, and in that stone a new name written,
which no man knoweth, save him that receives it; he shall have power over the nations,
and he shall have the Morning Star, he shall be clothed in white raiment,
and I will not blot out his name out of the book of life,
but I will confess his name before my Father, and before his angels:
him will I make a pillar in the temple of my God, and he shall go no more out,
and I will write upon him the name of my God, and the name of the city of my God,
and I will write upon him my new name.
I will grant him to sit with me in my throne, he shall inherit all things,
and I will be his God, and he shall be my son,`" saith the Lord.

They that overcame, overcame by the blood of the Lamb,
and by the word of their testimony; they loved not their lives unto death,
they came through great tribulations, they washed their robes,
and made them white in the blood of the Lamb, they kept before the throne of God,
and served him night and day in his temple,
and he that sitteth on the throne dwells amongst them,
they shall hunger nor thirst no more,
the Lamb which is in the midst of the throne shall feed them,
and lead them to living waters,
they have their Father`'s name written in their foreheads,
they sing a new song before the throne, they are redeemed from the earth,
and are not defiled with sin, but follow the Lamb whithersoever he goeth,
they are redeemed from amongst men, being the first fruits unto God;
in their mouth is found no guile, for they are without fault before the throne of God.
They have patience, keep the commandments of God and the faith of Jesus, and he overcame;
for he is Lord of lords, and King of kings, and they that are with him are called,
chosen and faithful.
Blessed are they that do his commandments, that they may have right to the tree of Life,
and may enter in through the gates into the city.

My dear friends, what sweet encouragement is here.
Let us make it our business to know these things experimentally,
according to our measures, and keep in the love of God,
and in it live and love one another;
this will cause us earnestly to desire and travel for the good and welfare one of another,
and of all mankind.
We cannot be truly religious out of this love; in this it is we feel one another,
as true members of the body, of which Christ is head; herein we love as brethren,
and are ready to wash one another`'s feet.
But if a man say, he loves God, and hates his brother, he is a liar.
This commandment have we from him, that he that loves God, loves his brother also.
"`A new commandment I give unto you, that you love one another,`" said Christ our Lord;
"`by this shall all men know that ye are my disciples, if ye love one another.`"
This is a certain mark of a true disciple.
But false apostles cannot love true ones.

Friends, keep your habitation that God has gathered you into, viz:
the spirit of meekness, love, gentleness, patience, purity, truth;
suffer quietly in this, and with it, for it will overcome all, and then you,
as you abide in it, will overcome by it.
I am glad you have not appeared in print, and very sorry G. K. and G. H.,
with others have,
by which occasion hath been greatly given to the enemies of the blessed Truth,
to speak evil of it.
I desire you do not meddle in that matter,
except the Lord constrain you to it by his holy Spirit, but leave your cause to God,
he will plead it.
And if in any word, or otherwise, you have done amiss, own your fault,
and seek to preserve the honour of Him, his truth and name, and seek none to yourselves,
nor strive together, for you are brethren, if you be as you profess; but be gentle,
long-suffering, and wait upon God, and whatever he bids you do,
do it and keep in a sense of the love of God,
and this will make you fruitful before him and men, and keep in the living faith,
which is not without good works,
but it works by love to the praise of the Author and Finisher of it,
and your Teacher will be with you, and fill you with his merciful goodness,
wisdom and strength.
If God be with us, who can be against us?
Surely none.
Therefore, look not out, dear friends, at the tree of knowledge,
though it seems pleasant to the eye that is not single,
but covets to be something more than God makes it,
and seeks its own exaltation and honour.
But let it be your care to know a being truly kept in covenant with the Lord.

Dear friends, let those alone that fly into the third heavens, as they may think,
and run into high things, great sights, and deep mysteries, yet love them,
and seek peace as much as in you lieth, and if any be offended at you,
because you see not what they pretend to, bear it patiently, for they ought not so to be;
the apostle Paul did not so, but became all things to all,
seeking to gain all to Christ Jesus;
even so do all that abide in the same spirit to this day.
They gather to him, viz: Christ the gift of God to all mankind, and in all,
according to their measure; the Lord fill many with it, and double our portions of it,
if it be his blessed will.
This is our treasure indeed, and by it we are led and guided into all truth,
and enabled to believe all things that are written in the holy Scriptures of truth,
concerning our Lord Jesus Christ, and do know him to be the author of our faith,
and not man.

No man can give any faith that is true and living;
there is no man hath any power over it;
yet men may be free to give an answer of their faith, if the Lord require it;
but take heed of men that run into needless questions, and doubtful disputations,
and vain janglings, in their own will and wisdom.
Remember our Lord Christ was sometimes silent to those: therefore,
if any friend of God be drawn forth to give a relation of what
the Lord of his own free grace hath brought them to believe;
let him do it in obedience to the Lord, and it is well;
but if any friend or friends be not yet come so far
as to believe in all respects what he doth,
let him not be offended with them, because they are weak,
but exhort them as Paul did some of old, that unto what they have attained,
walk by the same rule, mind the same thing,
and wait upon God to be carried on from faith to faith, and from grace to grace, etc.,
in and by the spirit of the Lord, not by man;
"`For he cannot add one cubit to his stature,`" by all he can do,
neither is it Christian for any to be offended at his brethren,
if they believe not in all respects just as he doth;
for children must be admitted to have milk,
and not be forced upon strong meat till they be able to digest it.
And tender fathers are careful to administer such
necessary food to their children as is nourishing,
and tends to their growth and strengthening,
and it is their joy to see them in a thriving condition, and come up to be young men,
to have the word of God abiding in them, and dwelling plentifully and richly in them.
Oh! that we may all truly travail for this, but to be offended with them,
because they see not, know not, or believe not all a father doth,
and disown them for this; O, this is unnatural, unkind, inhuman, therefore,
surely it is not Christian.

Therefore, my dear friends, keep low and dwell in the meek spirit of the Lamb,
that hath suffered deeply for us, and passed by many a weakness,
and helped us to eye salve, and given us to see the things that belong to our peace,
opening parables to us.
Let us keep close with him,
and then by him we shall be fitted and furnished to every good word and work,
to his glory, praise and renown forever, amen.

How doth my love flow secretly unto you, from the exercise that my soul hath had for you;
you are dear and near to me.
I should be glad to see you, and be with you a little season, in the will of God;
but I think I must never see your faces more, that is to say in the body.
But I have hope in the Lord, to meet you in our Father`'s kingdom of glory,
and abide with you forever.
This helps to comfort me many a time, when I think of you, though I could wish,
if it so pleased the Lord, to see you either here or there.
Dear friends, pray for me, and for all the flock of God, everywhere,
for we know not what we have yet to meet with; tried we must be, and proved many ways,
and those that are approved shall be made manifest,
and those that are otherwise will be known.
Oh! that we may be approved ones forever.

To the Lord I dearly commit you all, knowing he is able to keep you from falling;
and I dearly salute you all, both those whom I know by face, and those I do not,
who are true Friends, and abide in that in which they cannot be otherwise.
I pray God to be with you all, and all his, everywhere,
and keep us all by his own power, fitted and prepared for himself,
and in everything enable us to be fruitful, every way to his praise, glory,
honour and renown, and our souls`' everlasting joy, comfort and consolation; even so,
let it be, O Lord! for thou only art able to say, Amen to it in truth.
So prays your dear friend and brother in the service and sufferings of the blessed Truth,
that lives and abides forever.

John Gratton.

Written at Monyash, in the Seventh month, 1693.
