== Testimonies of John Gratton

[.blurb]
=== John Whiting`'s Testimony Concerning Our Dear Friend John Gratton.

Love to the precious Truth which I received in my early days,
and embraced as my chiefest joy,
and which is dearer to me than all that this world can afford,
hath made me love the messengers and ministers of it, and their testimony for its sake;
of whom our dear friend, John Gratton, was not the least,
being one of the Lord`'s worthies, raised up in these latter days, after long travail,
and sent forth to publish the glad tidings of the gospel of Christ,
to his neighbours and countrymen, etc., as by the following relation will appear.
A true minister of the everlasting gospel of life and salvation
to the sons and daughters of men in life and power,
which is glad tidings indeed, to as many as receive it.
But he is now removed and taken from us, and is gone to his everlasting rest,
and his works follow him.

The removing so many of the Lord`'s worthies from among us of late years,
is matter of weighty consideration, with which my heart hath often been deeply affected;
but in this I am comforted, that we are not left destitute,
and that the work is the Lord`'s: and though they are taken away,
he can raise up others in their room; and that they died in the Lord,
and if we are faithful we shall go to them, seeing they cannot return to us,
where we shall forever live to laud and praise the name of the Lord.
And in the mean time let us pray the Lord of the harvest,
that he will send forth more faithful labourers into his vineyard,
to supply the places of those who are removed; for the harvest indeed is great,
and much work yet to be done before the nations are converted unto him,
and the true labourers, in comparison of the greatness of the work, are yet but few.

I should not have presumed to write any thing concerning this our deceased friend,
considering how many abler there are to speak of him,
had not I had a more than common respect to him, for his testimony`'s sake,
and intimate acquaintance with him for about twenty years,
and knew his temper and spirit well;
and were it not to give some account of the ensuing journal,
and my concern in it which is as follows:

Our friend John Gratton, whose service in the Truth, and labours in the work of the Lord,
are, I doubt not, fresh in the memories of many,
who will be glad to hear the relation of him, left an account, in several manuscripts,
of his life, labours, travels, and sufferings, which,
being sent up to London since his decease, were put into my hands,
with desire that I would peruse and compare them; which I carefully did,
and brought the substance of all into one, according to the order of time,
as near as I could in his own words, not omitting any thing that was material.

May the Lord make it serviceable to all that read it, that it may redound to his glory,
the advancement of his truth, and the comfort of his people.

He died in the first month,
1711-12. And precious in the sight of the Lord is the death of his saints:
to whose divine grace and guidance I recommend all, with my own soul.

[.signed-section-signature]
John Whiting.

[.signed-section-context-close]
London, the 20th of the Twelfth month, 1719.

[.blurb]
=== Joseph Smith`'s Testimony Concerning John Gratton.

Having known my dear friend, John Gratton thirty years or upwards,
and he being one whom I dearly loved,
as a minister of the gospel of our Lord and Saviour Jesus Christ,
it is upon my mind to write a short testimony concerning him.
He travelled much in the work of the ministry,
and was willing to spend and be spent for the Truth`'s sake.
His testimony was very powerful, and prevailed to the tendering of the hearts of many;
and I may say, for one, he was very helpful to me in my young years,
wherefore I had always an honourable esteem for him as an elder, and a father in Israel,
But within this fifteen or sixteen years I have had a more full knowledge of him;
for I sometimes travelled with him, and had private opportunities in his company:
and although he was endued with an excellent gift of the ministry,
yet he was very tender and courteous to those who
were but young in the work of the gospel,
whose care was to serve the Lord and not themselves,
and indeed he had a word of comfort to the weary travellers, whose faces were Zionward;
yet he was very sharp against deceit.
He dearly loved the Truth, and the prosperity of it.
May I not say, the righteous is taken away, and few consider it.
My desire and prayer to the Lord is,
that as he hath been pleased to remove many of the ancients,
he might raise up many more faithful labourers,
and give them a portion of the same Spirit, that the Truth might spread over the nation,
and nations remote;
that many might be turned from the evil of their ways unto the fear of the Lord,
and so lay down their heads in peace, as I believe this our dear friend hath done.
And though he is taken from us, to our great loss,
yet I doubt not but it is to his eternal gain;
for I being with him a little before he was taken away,
found him sensible and retaining his integrity,
which was much to my comfort and satisfaction; and now I may say, he being dead,
yet speaketh: and his memory is fresh in my remembrance,
I being sensible that he died in the love of Truth,
and in true love and unity with faithful brethren.

[.signed-section-signature]
Joseph Smith.

[.signed-section-context-close]
North Collingham, in Nottinghamshire, 22nd of the Third month, 1713.

[.blurb]
=== Josiah Langdale`'s Testimony Concerning Our Dear Friend, John Gratton.

He was one whom I dearly loved because of that spirit
that dwelt in him in a plentiful manner.
Indeed, the Lord wonderfully favoured him with his grace and spirit,
so that I have sat with great delight under his ministry in many places.
I was at London the last time he was there,
and he was very living and powerful in his testimony,
and many things dropt from him in his declarations,
which were very suitable to the congregations;
so that I admired the wisdom that the Lord had endued him with,
and the strength that his natural body had, for out of meetings he was very weak,
because of his distemper that was upon him.
He preached the gospel of life and salvation freely,
and suffered for the testimony the Lord gave him to bear,
and many were turned to the Lord through his ministry,
who became obedient and faithful to the manifestation
of God`'s spirit in their own hearts,
several of whom I was intimate with; so that it is a true relation I give of him.

I desire the Lord may raise up many such true labourers as he was in his day,
to labour in his vineyard, that many may be turned to righteousness,
and grow up in holiness, to the praise and glory of God,
who hath appeared by his light and grace in a wonderful manner in our day.
Surely the Lord is about to make his name and truth
famous amongst the inhabitants of the earth;
for this cause, and for the love that he bears to the workmanship of his hands,
is he working in the hearts of many by his Spirit,
and is raising up true-hearted men and women, that run not after filthy lucre,
but are seeking to gain souls to the Lord,
and turn men and women from their sins and transgressions,
that they may be heirs of eternal salvation;
for this end did our dear friend and brother labour.
I have met with him in divers counties in this nation,
where he laboured faithfully and truly in the work of the Lord;
endeavouring as much as in him lay to stir up the pure mind:
and I have seen his labours of love effectual,
so that many hearts and souls have been sweetly refreshed through that love that flowed,
and dwelt plentifully in him; and after a meeting he was solid and serious,
and his discourse tended much to edification,
and to build up the children of the Lord in the most holy faith.
He was one that sought not to be applauded by men,
but kept humble and low in the fear of God, and had an eye to his glory.
These qualifications that his Lord and Master had endued him with,
and his exemplary life,
did much beautify him in the eyes of those that loved and feared Almighty God.
Well this may be safely said, that he was a man of God, and did good service in his day,
and is entered into that rest,
that is prepared for all those that love the Lord Jesus Christ.

[.signed-section-signature]
Josiah Langdale.

[.signed-section-context-close]
Bridlington, the 3rd day of the Eighth month, 1712.

[.blurb]
=== A Testimony from Several Friends in Cheshire, Concerning Our Ancient Friend, John Gratton, Deceased.

We whose names are hereunto subscribed,
having had a pretty early and long acquaintance with that good man, thought it our duty,
in respect to his memory, to give forth this testimony concerning him.
In his early and several visits to this county in the service of Truth,
we observed the Lord attended him, and put him forth,
so that many times he was wonderfully opened and enlarged to speak of the things of God,
and to unfold the mysteries of his kingdom in a very convincing manner to the ignorant,
and to the comforting and strengthening of the faithful.
Times of refreshment did often sweetly attend the
meetings of Friends he paid his visits to,
which made him acceptable to us; and as he was lively and powerful in his testimony,
so many times he was sweetly drawn forth in praise and supplication to the Lord.
He spared not himself, wherein he could be serviceable to God, his truth and people,
and had still an eye to the glory of God therein,
and was zealously concerned to exalt the kingdom of his dear Son Christ Jesus our Lord,
which he did, not only in doctrine, but in conversation, for he was a good example,
both at home and abroad;
and his service both here and in other places cannot easily be forgotten by us.
His travels were considerable in this nation,
and many were convinced by him in this county, and in other parts,
and brought to the knowledge of the Truth.
He also made a visit to Friends in Ireland, where he was gladly received,
and often spoke of the satisfaction he had therein,
as also in his travels through Scotland.
Whilst he lived in Monyash, in the county of Derby, his house and heart were open,
and his entertainment free.
The company of honest Friends was very acceptable,
and many made respectful visits to him,
which he would say were times of comfort and consolation.

As years came on, infirmities increased, which weakened and brought him often very low.
His imprisonments and loss of goods, for his testimony of Truth,
he bore with a great deal of patience,
and waded through those sufferings with a Christian courage.
Some time after his removal to the county of Nottingham,
his dear wife was taken from him, which added still to his sorrows;
for she was a strength and comfort to him in the midst of his exercises,
and continued so to be to her end,
and after her death he had the help and assistance of an affectionate daughter,
who discharged her duty to him to his very last.

We shall only add, he was a man beloved of God and of his people, sound in his testimony,
courteous in his behaviour; he loved the Truth for the Truth`'s sake;
was patient in his suffering for it, faithful to God in discharging his duty to him,
helpful to his people wherein he could be serviceable to them,
either in their private or public concerns; he lived well, and so he died:
and after all the toils, exercises and buffetings he met with here in this world,
in a good old age he was gathered home unto a quiet habitation.

The Lord God Almighty raise up and send forth many
more such faithful labourers into his harvest,
that the scattered may be gathered, and the dispersed brought home to the fold of safety,
where they may be prepared with the redeemed of the Lord, to give unto him,
and unto the Lamb that sits upon the throne, the glory, honour,
and high praises that are his due, and our duty to render him, even world without end.
Amen.

[.signed-section-signature]
Joseph Endon, John Walker, Ralfe Brock, John Hough, William Harrison, John Hobson,
Benjamin Bangs, Martha Hobson, Mary Richardson, Martha Royle, Tabitha Ardern, Mary Bangs,
Martha Moss.

[.signed-section-context-close]
Stockport, the 2nd of the First month, 1712-13.

[.blurb]
==== The Testimony of Several Friends Belonging La Monyash Monthly Meeting, Concerning Our Deceased Friend, John Gratton.

We whose names are hereunto subscribed, being members of Monyash monthly meeting,
whereunto our well beloved friend, John Gratton, did many years belong,
in which time we were intimately acquainted with him;
enjoyed many comfortable and precious opportunities in conversing together,
and were often refreshed under his ministry; do find ourselves concerned,
as a duty we owe to his memory,
and for the recommending his Christian labours to succeeding ages,
to write this brief testimony concerning him.
He was a man of note in his country,
and one whose Christianity did show itself in the spirit of meekness and humility,
notwithstanding many troubles and exercises which he met with.
He was also an able minister of the everlasting gospel,
being made instrumental in the convincement of many.
He had great openings, was sound in doctrine, and skilful in hitting the mark.
His ministry was lively and powerful, plentifully opening the Scriptures.
He travelled much in the service of Truth, both in this nation,
and in other countries adjacent.
His residence was at Monyash, in the county of Derby, above forty years,
where we were often comforted in his company, and therefore loved him in the Truth,
and do believe that he lived and died a servant of the Lord.
He departed this life at Farnsfield, in Nottinghamshire,
in the sixty-ninth year of his age.

[.signed-section-signature]
Elihu Hall, Henry Bowman, Cornelius Bowman, George Potter, Rebecca Bowman, Ann Bowman,
Sarah Potter, Hester Bowman.

[.blurb]
=== Phebe Bateman`'s Testimony Concerning Her Dear Father and Mother.

It hath been much in my mind to give a short account
of the latter end of my dear and tender parents,
it pleasing the Lord so to order it,
that they both finished their days with me at Farnsfield, in Nottinghamshire.
They broke up house-keeping at Monyash, in the fourth month, 1707,
and went from thence to brother Joseph`'s, and after a short stay there, came hither.
My dear mother had been weakly about half-a-year before, but then was something better,
and went a journey with my dear father.
She had a tender care for us all, being a very affectionate, loving, tender mother;
and in our bringing up, had an eye to the Lord, that we might be trained up in his fear,
and was not backward in reproving us for any appearance of evil.
My father being about five years and a half in prison, when we were but young,
the tuition of us fell mostly upon her; and as we grew up,
she would often advise us to diligence and carefulness, not only to the Lord,
but in the outward affairs of the world, that none might be losers by us.
Her weakness of body increased fast on her,
so that she much desired her time here might not be long, if the Lord saw it good,
yet was freely given up to his holy will, and would say to me, "`Do not desire my life,
but give me up freely.
I know I might have been assisting to thee, if the Lord had been pleased to order it,
but my desires are more to be gone, if he see it good, than to live any longer here.`"
She had a tender regard in her mind for dear father, that he might not be neglected,
and I being pretty much taken up in attending her, she would often say,
"`Dost thou take care of thy father?`"
For as their love and sympathy had been great in all times of trial of what sort soever,
so it continued to the last.
I believe she never hindered or discouraged him once
from going out in the service of the blessed Truth,
but was an encourager of him,
and in his absence very diligent and careful that nothing
might go amiss to make him uneasy at his return,
so that he was much at liberty to serve the Lord
for many years before he gave up house-keeping.

She was preserved in much patience and resignation to the will of the Lord, often saying,
she had hope in him; was very sensible to the last,
and departed this life in much quietness and stillness,
as if she had been going to sleep, without either sigh or groan,
the 4th of the tenth month, 1707, and I believe,
is entered into the rest which is prepared for the righteous,
in the sixty-fifth year of her age, they having lived together nearly thirty-nine years.
She was buried the 7th of the tenth month, in the burying place of Friends,
by the meetinghouse in Farnsfield, many Friends accompanying her body to the grave.

My dear father was then very weakly,
and the loss of my dear mother was a near trial and exercise to him; she having been,
as he himself said, a sweet help to him in the Lord,
was deeply bowed in spirit for the loss of her, yet freely gave her up to the Lord.
He was now brought so low and weak, that few who saw him,
thought he would continue long after her:
but it pleased the Lord in his great love and infinite goodness,
to raise him up in some measure, though he continued weak all along,
but was enabled to go up to London the summer following, to see and visit Friends,
being out near half a year, in which time he had several fits of illness,
but the sorest time was at the house of R. Richardson,
he and his wife being very tender of him.
Yet his desire was great to get to my house, if the Lord saw it good;
and he was pleased to raise him up again,
so that he was enabled to get home the 29th of the seventh month, 1708.
He continued weakly, being attended with various exercises,
which often brought him very low,
though sometimes he was enabled to take a little journey to visit Friends.

The last winter he sensibly decayed, so that he would often say to me,
he could not continue long, his stomach being so weak,
he could take little food for several months before he died.
His desires were great to go hence, if the Lord saw it good;
and as his weakness increased, his desires, if could be,
grew stronger and more earnest with the Lord to remove him out of this troublesome world,
being well satisfied his day`'s work was over, yet desired to wait the Lord`'s time.
My eldest daughter being then very ill, he often gave good advice and counsel to her,
to fear the Lord, and be obedient to her parents, with more to that effect,
to all my children.

About a month before his decease, I was called on so suddenly,
that it was thought he could not live till I came to him.
I found my children and the maid weeping, thinking he would not have spoken again,
but when I came to him, he broke out into tears, saying,
he thought he should never have seen me more;
but soon got a little strength to sit up in his chair,
and called all the children to him, one by one, and kissed them, giving them good advice;
saying it was a great comfort to him to see we should
part in so much love and unity one with another;
and calling for the maid, spoke very tenderly and lovingly to her.
Being attended with sore sickness and pain, he said, "`Lord, I pray thee give me ease,
if it be thy holy will, and remove me soon out of this body.
Thou knowest it is through thy great mercy that we have hope in thee.
Lord, I pray thee, be with my children that I leave behind,
and with all friends and neighbours of what profession soever:
it is through Christ Jesus our Advocate, who is gone before us,
that we are enabled to come to thee.`"
His pain and exercise of body continuing, he said again, "`Lord, if it be thy holy will,
remove me out of this troublesome body.`"
Another time, some Friends being come to visit him, I told him,
here were Friends come to see him; he said, they might see he was a weak man;
and looking on them as they sat by him, he said, "`The Lord bless his people,
and prosper his Truth amongst them, and enable them to live in love one with another.`"
Not long after, weakening very fast, he said, "`Lord,
I freely commit my soul and spirit unto thee;`" desiring
to have his dear love given to Friends,
naming several in particular.
A little before he died, he told me, he thought he should be gone in half an hour,
being very sensible to the last.

He departed this life on the 9th of the first month, 1711-12, and is, I hope,
at rest with the Lord, where the wicked cease from troubling, and where,
the weary are at rest.
He was buried beside my dear mother the 11th of the same,
in the sixty-ninth year of his age,
having been convinced of the Truth about forty years.

[.signed-section-signature]
Phebe Bateman.

[.signed-section-context-close]
Farnsfieid, 1712.
